### ISSUE TITLE
Loading YOLO error since update

### ISSUE THREAD

**Issue by fire17** [MVIG-SJTU/AlphaPose#100]
I reinstalled AlphaPose Pytorch since the last time, I installed it, it was the 5fps version...
and apparently things have changed...
Im running the webcam demo:

> python3 webcam_demo.py --webcam 0 --outdir examples/res --vis

At the beginning, when it loads yolo I get an error
```
Loading YOLO model..
Traceback (most recent call last):
  File "webcam_demo.py", line 46, in <module>
    det_model.load_weights('models/yolo/yolov3.weights')
  File "/home/magic/AlphaPose/yolo/darknet.py", line 474, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: invalid argument 2: size '[512 x 256 x 3 x 3]' is invalid for input with 704923 elements at /pytorch/aten/src/TH/THStorage.cpp:84
```

Please help
Thank you!
( @Fang-Haoshu )

**Comment by Fang-Haoshu** [comment]
This part should not be influenced as far as I can see. It seems that the weightfile is corrupted. May you check for that?

**Comment by fire17** [comment]
Hopefully you're right, it doesn't make sense... I'll redownload it and get back to you...

**Comment by fire17** [comment]
Awesome brother!
yes it was corrupted... Thank you very much!
