### ISSUE TITLE
关于idx的顺序不连续问题

### ISSUE THREAD

**Issue by pangwenfeng** [MVIG-SJTU/AlphaPose#1000]
你好，首先感谢你们的工作。我在使用reid做轨迹跟踪时发现，输出的idx不是连续的，会出现缺失，比如检测某个视频后输出的结果会出现 idx1，idx3，idx4，idx7，而不存在idx2，idx5，idx6，请问这个是正常现象吗？还是我的操作有误所致的呢？再次感谢，非常期待你的解答。

**Comment by tang-hy** [comment]
您运行的命令是什么呀

**Comment by pangwenfeng** [comment]
您好，感谢您的回复。我在 demo_inference.py 的基础上添加了一个循环和一个额外的路径参数，使其可以运行一次处理多个视频，另外使用了--pose_track参数。形式大概就是： python demo_inference.py --cfg xxx.yaml --checkpoint xxxx.pth --img_folder xxx --outdir xx --pose_track

**Comment by tang-hy** [comment]
抱歉，这边目前也不知道什么原因，正常来说不应该出现这种情况。您或许可以提供更多的信息，如运行截图、结果示意图等~

**Comment by Fang-Haoshu** [comment]
close due to no response
