### ISSUE TITLE
关于人体手指节点

### ISSUE THREAD

**Issue by Ramblestsad** [MVIG-SJTU/AlphaPose#1009]
诚心的提问：请问想要识别人体手指节点应该如何做？或者说该框架可以做到吗？
前置知识有限，如果有清晰步骤更好！
万分感谢

**Comment by jianghanling** [comment]
朋友你找到答案了吗 最近也在做手指节点检测 我们可以邮箱联系 1025831198@qq.com

**Comment by HaoyiZhu** [comment]
你好！可以的，我们的136点的wholebody版本包括了两只手共42个点。我们也提供了single hand 的版本，详见[Model Zoo](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md)
