### ISSUE TITLE
你好，在运行pytorch版本的AlphaPose　video_demo.py出现“TypeError: can't pickle cv2.VideoCapture objects”

### ISSUE THREAD

**Issue by bravestpeng** [MVIG-SJTU/AlphaPose#101]
其他的环境都配置好了，在第video_demo.py 40行 data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()；出现了这个问题，能帮忙解决吗，谢谢

**Comment by Fang-Haoshu** [comment]
你的环境是？跑的命令是？

**Comment by Fang-Haoshu** [comment]
no response, close

**Comment by shayxurui** [comment]
你好，我也遇到跟他相同的问题。环境是ubuntu16.04,cuda8。命令是python3 video_demo.py --video  ./1.wmv --outdir examples/res --save_video。

**Comment by Fang-Haoshu** [comment]
你好，试试更新opencv版本有没有帮助
```
pip3 uninstall opencv_python
pip3 install opencv_python --user
```

**Comment by shayxurui** [comment]
你好，感觉你的回复。我卸载又重装opencv，但是还是原来的环境，我的python用的是annaconda的python3.6.0    请问你们的环境是什么?

**Comment by Anymake** [comment]
我这试的这个问题和多线程有关，关闭多线程，命令后面加上 “--sp”，使用单线程暂时不会有问题，具体原因还在看

**Comment by Fang-Haoshu** [comment]
@Anymake 谢谢你的解决方案
看起来是多线程问题，但我还没找到解决方法

**Comment by TommeyChang** [comment]
我用多线程还出现了另外一个错误：/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by Fang-Haoshu** [comment]
@TommeyChang Not an error, just a warning message

**Comment by liuruijin17** [comment]
@Anymake Thanks a lot! This helped me!

**Comment by ZhongXiaoFang** [comment]
> 我用多线程还出现了另外一个错误：/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
> len(cache))。关掉多线程就不报错。

遇到了同样的问题，还没有解决

**Comment by Fang-Haoshu** [comment]
@ZhongXiaoFang 这个问题我已经回复过了...

**Comment by FoolishMao** [comment]
@Anymake video的多线程问题解决了吗？

**Comment by guancheng817** [comment]
> @Anymake video的多线程问题解决了吗？
我今天跑了程序，多线程还是会报错。依然用的是单线程...

**Comment by sxl1995** [comment]
> Add "del self.stream" at line 194 in "dataloader.py".



> > @Anymake video的多线程问题解决了吗？
> > 我今天跑了程序，多线程还是会报错。依然用的是单线程...

Add "del self.stream" at line 194 in "dataloader.py".

**Comment by HoldYourFire** [comment]
@Fang-Haoshu，你好。请问有相关的群么？相互交流学习下

**Comment by DragonAndSky** [comment]
@HoldYourFire @sxl1995  问个问题,我加载/duc_se.pth模型到半路，内存就溢出了，模型有十几个g这么大吗

**Comment by zacario-li** [comment]
@DragonAndSky 我这里只占用了2.8G显存

**Comment by GuoHaiYang123** [comment]
请问你们demo时，是CPU利用率高，还是GPU利用率高啊，我装的GPU版本的pytorch框架，但运行时CPU利用率100%，我不知道如何使用GPU来demo

**Comment by 2429581027** [comment]
> 其他的环境都配置好了，在第video_demo.py 40行 data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()；出现了这个问题，能帮忙解决吗，谢谢

你好 我想问下配置环境的时候 pip install ntpath 你的可以运行么，我的一直在报错

**Comment by Fang-Haoshu** [comment]
Bug fixed in the latest version! Thanks, guys!

**Comment by gaoyao123** [comment]
> ntpath

I also meet this problem,how to deal with it?

**Comment by liangmuxue** [comment]
多线程序列化的问题，解决方法参见 http://xiaorui.cc/archives/2665
