### ISSUE TITLE
CUDA out of memory when executing demo_inference.py

### ISSUE THREAD

**Issue by jsaray** [MVIG-SJTU/AlphaPose#1011]
Hello,

After executing : 
python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/

I get 
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 3.82 GiB total capacity; 2.37 GiB already allocated; 34.56 MiB free; 59.31 MiB cached)

As mentioned in your iisue https://github.com/MVIG-SJTU/AlphaPose/issues/123, I added parameters --posebatch 10 --detbatch 10
With the same result.

I also went to the configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml  and explicitely set : BATCH_SIZE to a lower value with the same problem.

What could the problem be ? any ideas to fix it ?

**Comment by jsaray** [comment]
thank you very much !, now it seems to work as a charm :

(alphapose) [root@adelie AlphaPose]# python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --posebatch 2 --detbatch 1
Loading YOLO model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.14it/s]
===========================> Finish Model Running.
===========================> Rendering remaining 0 images in the queue...
Results have been written to json.


However it seems that the output is a json.
Do I have to manually use cv to draw the skeleton ? and validate that things went well ?

**Comment by jsaray** [comment]
Hi, checking the doc you can automatically export pictures with skeleton drawing by using flags --vis --save_img

**Comment by dekathomas** [comment]
flag `--save_img` can save the image to the output directory

**Comment by Fang-Haoshu** [comment]
Cool! Will close it.
