### ISSUE TITLE
跑图片list，CPU跑满，GPU利用率低，以及爆内存killed

### ISSUE THREAD

**Issue by juneleung** [MVIG-SJTU/AlphaPose#1019]
你好，我使用gpu选项，但是看起来似乎一直在使用cpu进行处理，如何提高GPU利用率加速？
![image](https://user-images.githubusercontent.com/32699460/163015363-ed2c31e1-7b9c-451d-92a9-4e8dcbc9b9c7.png)

```python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --list ./list2Apose.txt --indir ./tmp --outdir ./output/res --gpus 0 --pose_track --vis_fast --sp```

，同时 如果list比较多文件，会killed，尝试过 使用--detbatch 3 --posebatch 32等，但是依然会在运行一半killed，有没办法解决killed的问题呢？

``` 33%|██████▌             | 2140/6576 [08:15<15:38,  4.73it/s]Killed```

**Comment by Markshilong** [comment]
> 可能pytorch安装成了cpu版本？

我也是在运行demo_inference.py时 会沾满CPU而GPU占用率很低，新的代码在这方面有什么优化吗？
