### ISSUE TITLE
Select GPU to use

### ISSUE THREAD

**Issue by RomeroBarata** [MVIG-SJTU/AlphaPose#102]
Hi,

Would that be possible to add an option to select which GPU to use with AlphaPose? I'm using the Pytorch version and I have 4 GPUs on my system. I've tried editing the CUDA_VISIBLE_DEVICES environment variable but AlphaPose always grabs the GPU 0. Thank you!

Kind regards,
Romero

**Comment by Fang-Haoshu** [comment]
Hi, can you try
CUDA_VISIBLE_DEVICES=3 python3 demo.py xxxxx
It works in my side.

Hope that it can help

**Comment by RomeroBarata** [comment]
Sorry, editing the CUDA_VISIBLE_DEVICES works fine, that was my mistake. I think I wasn't exporting it before. Thank you for your help.

**Comment by Fang-Haoshu** [comment]
cool
