### ISSUE TITLE
Keypoints number doesn't match the frame

### ISSUE THREAD

**Issue by 4lparslan** [MVIG-SJTU/AlphaPose#1024]
Hello, when I ran my own data with Fast Pose (DUC) model trained in COCO, I found that all poses saved in .json are complete (all 17 keypoints detected). However, when I checked the saved images, the detected poses were not always complete.
**For example in a frame of my input video person's arm not visible. I don't understand that JSON file have still 17 keypoints. I will be happy if you give me information.**

**Comment by Fang-Haoshu** [comment]
The visualization is thresholded by the joint confidence.
