### ISSUE TITLE
Error Running AlphaPose on a video

### ISSUE THREAD

**Issue by nishata24** [MVIG-SJTU/AlphaPose#1027]
Hello,
While trying to run AlphaPose on videos using the following command: ./scripts/inference.sh configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml pretrained_models/fast_res50_256x192.pth trimmed2_wo_exo.mp4, I ran into the following error: OSError: [Errno 28] No space left on device. I am running AlphaPose in a container, so the first time I had this issue I created a new container with 5G of shared memory and that seemed to resolve the issue for a bit because I was able to run alpha pose on a 1 minute video. However, I tried running AlphaPose on a second video that was 2 minutes long in that same container and received the error regarding space. Below is a screenshot of the entire error message that appeared when I tried running AlphaPose on the 2 minute video. Has anyone had a similar issue or does anyone have any suggestions for solving this issue? Thank you very much. 
<img width="997" alt="Screen Shot 2022-05-07 at 1 52 52 PM" src="https://user-images.githubusercontent.com/94148211/167266960-52965c8e-f1bc-4187-a5aa-3d60388fb45a.png">

**Comment by Fang-Haoshu** [comment]
No space left on device
Just simply enlarge the space, 5G is too small, perhaps try a 50GB
