### ISSUE TITLE
Where's the train folder? Please make a tutorial on how to train with COCO, MPII, or custom dataset

### ISSUE THREAD

**Issue by fengmaozheng** [MVIG-SJTU/AlphaPose#1028]
Why are all the training related questions open or not properly answered? I can't find tutorial on how to train models within this repo.

**Comment by dekathomas** [comment]
Hello, just download COCO trans2017, val2017 and annovation2017 from [COCO website](https://cocodataset.org/#download)2. After you have all the files. just put it in the root folder `./data/coco/` (you can check this one if you open one of the training config inside `./configs/coco/` there are so many configs there.

After you set all of them you can go to `./scripts/train.py` and run `python ./scripts/train.py --exp-id {yourFolderDataTraningName} --cfg {yourSelectedConfigFilePath}` 
Or you can run from its `.sh` in `./scripts/train.sh`

Hope I help you to address your problem.

**Comment by karlwen809** [comment]
why i dont have the folder data

**Comment by Fang-Haoshu** [comment]
You need to create that folder
