### ISSUE TITLE
Where is SSD VGG-512

### ISSUE THREAD

**Issue by dekathomas** [MVIG-SJTU/AlphaPose#1029]
Hello, is anyone here know where is VGG-512 in this project? Because in the paper @Fang-Haoshu  state that alphapose use SSD VGG-215 to do the object detection, and not ResNet.

**Comment by dekathomas** [comment]
OMG! 😂 All this time I was referring to your RMPE paper and use this code as my code base. Do you have a simple explanation or graph that can describe the whole process of this Alphapose repository?

**Comment by Fang-Haoshu** [comment]
Hi, the paper is public at http://arxiv.org/abs/2211.03375
Thanks for your interest! @dekathomas
