### ISSUE TITLE
算法复现咨询

### ISSUE THREAD

**Issue by yjfncu** [MVIG-SJTU/AlphaPose#103]
您好，请问有没有tensorflow 版本的AlphaPose实现，或者我想用tensorflow从训练到测试复现一遍，不知道有没有AlphaPose的整个网络结构可以参考一下，谢谢

**Comment by Fang-Haoshu** [comment]
你好，实现的话 你可以先从pose网络之外的部分开始，我们近期也会放pose网络的训练代码

**Comment by Fang-Haoshu** [comment]
你好，刚刚发布训练代码，你可以参考一下哈
