### ISSUE TITLE
Update YOLO Detector

### ISSUE THREAD

**Issue by pranavgundewar** [MVIG-SJTU/AlphaPose#1037]
Hi! Thank you for sharing the codebase. 

I have seen that YOLO V3 SPP is not very robust when detecting small, fast-moving objects in the videos.

I wanted to update the YOLO backbone to either Yolo v5 or YoloX. Can you share steps to update the detection backbone?

Thank you!

**Comment by pranavgundewar** [comment]
I will check the code today and will let you know.

**Comment by Fang-Haoshu** [comment]
Great! In fact, we have tested EfficientDet and Yolov5 series, and they perform worse than yolov3 for pose estimation. Yolox is the only one that surpass yolov3 so far in our case.

**Comment by foocker** [comment]
> 

unexpected.

**Comment by VisImage** [comment]
I tried and did not go through. In colab:

! python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth \
--detector yolox --video /content/alphaPose_sample3.avi --outdir /content/out_yolox --save_img --save_video --sp --vis_fast

output: 
Loading YOLOX-X model..
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/AlphaPose/alphapose/utils/detector.py", line 223, in image_detection
    dets = self.detector.images_detection(imgs, im_dim_list)
  File "/content/AlphaPose/detector/yolox_api.py", line 89, in images_detection
    self.load_model()
  File "/content/AlphaPose/detector/yolox_api.py", line 46, in load_model
    torch.load(self.model_weights, map_location="cpu")["model"]
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Loading pose model from pretrained_models/fast_res50_256x192.pth...
===========================> This video get 570 frames in total.
  0% 0/571 [00:00<?, ?it/s]

@pranavgundewar have you got any chance to try it out?

**Comment by HaoyiZhu** [comment]
Hi, thanks for your feedback @VisImage ! We actually have not updated colab yet. And I think your error might be due to the yolox weight is not downloaded.  You have to download the weights from https://github.com/Megvii-BaseDetection/YOLOX and put them into `detector/yolox/data/`. We will update this part later.

**Comment by Fang-Haoshu** [comment]
please use ``!wget -P ./detector/yolox/data/ https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.0/yolox_x.pth`` to download weight on colab

**Comment by VisImage** [comment]
@Fang-Haoshu, Thank you for the update.  I downloaded yolox_x.pth file and tried again.  Unfortunately, it does not goes through, as shown in the screen capture below.  Please advise.

![ColabCapture](https://user-images.githubusercontent.com/38402317/175782939-8202c981-574e-4f23-8210-f6e02c31e986.PNG)

**Comment by HaoyiZhu** [comment]
Seems there is no error? And the progress bar is 11/571, so why you interupt it?

**Comment by VisImage** [comment]
@Fang-Haoshu, Thank you for the feedback. Upon further investigation, we find that it is an issue on Colab memory.  After changing Colab runtime shape to High RAM, from standard, the expected result json file (alphapose_result.json) is generated. 

The following are the results of three models (-- pose_track; --detector yolox; and --detector tracker) on my video:

1) At the default configuration (threshold e.t.c)  "--detector yolox" produce more poses than "--pose_track", but not more reliable poses. 
2) The bounding boxes (the 'box' values in result.json file) are not accurate/reliable. When plotting such bounding box together with pose (keypoints), many boxes seems NOT related with the pose.  Is the 'box' values validated before writing into alphapose_result.json? 
3) we still can not make the model  "--detector tracker" work

**Comment by HaoyiZhu** [comment]
@VisImage To use pose tracker, you should use the flag `--pose_flow` or `--pose_track` (See https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/demo_inference.py#L82-L85). By the way, could you offer the vis result of the "unrelated" boxes and poses?

**Comment by VisImage** [comment]
Thank you for the update.  I'll check the --detector tracker fix in these couple of days.  To share the "unrelated" boxes and poses, I have sent you an email to fhaoshu@gmail.com, since our video is not proper to be shared in public. If you prefer other communication channel, please email me at yin.s@vis.ca..
