### ISSUE TITLE
 UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown   len(cache))

### ISSUE THREAD

**Issue by Vivianwxf** [MVIG-SJTU/AlphaPose#104]
hello and Thank you for your hard work.i have a bug,hope　your reply.
``/AlphaPose$ CUDA_VISIBLE_DEVICES=0 python demo.py --indir examples/demo/ --outdir examples/results/ --save_img
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
100%|█████████████████████████████████████████████| 3/3 [00:00<00:00,  3.87it/s]
===========================> Finish Model Running.
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
(helloworld) vivian@vivian-Super-Server:~/HelloWorld/helloworld/AlphaPose$ /home/vivian/anaconda3/lib/python3.5/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown
  len(cache))
``

best wishes!

**Comment by Fang-Haoshu** [comment]
duplicate issue
