### ISSUE TITLE
demo_inference error

### ISSUE THREAD

**Issue by ldincredible** [MVIG-SJTU/AlphaPose#1042]
Hi, I use this script "python3.7 scripts/demo_inference.py --cfg configs/halpe_136/resnet/256x192_res50_lr1e-3_2x-dcn-combined.yaml --checkpoint pretrained_models/multi_domain_fast50_dcn_combined_256x192.pth --outdir examples/res --vis --webcam 0"
then i got this error:
Loading YOLO model..
Starting webcam demo, press Ctrl + C to terminate...
1it [00:00,  1.11it/s]Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/AlphaPose/alphapose/utils/writer.py", line 108, in update
    pose_coord, pose_score = self.heatmap_to_coord(hm_data[i][self.eval_joints], bbox, hm_shape=hm_size, norm_type=norm_type)
TypeError: 'NoneType' object is not callable
2it [00:01,  2.09it/s]
I would be very grateful if you could help me solve this problem

**Comment by HaoyiZhu** [comment]
Are you using the latest version of codes?
