### ISSUE TITLE
Error in "setup.py build develop" in Google Colab

### ISSUE THREAD

**Issue by maarten0912** [MVIG-SJTU/AlphaPose#1044]
I have used the Google Colab given sample previously, and I know that it worked yesterday. When I tried to run the sample again today, I could not get it to work anymore.

I don't think it is related to the commit to the main branch from yesterday, since I get the same error when setting the repo back to before that commit (2330a3d7f56269c9186ce08a9c974ffec12fb2f5).

This is what I am running (it is just the unmodified given Google Colab sample):

```
! pip install pyyaml==5.2
! pip install scipy==1.1.0
! pip install torch==1.2.0 torchvision==0.4.0
! pip install pillow==6.2.2
import torch
print(torch.__version__)
import yaml, scipy
print(yaml.__version__)
print(scipy.__version__)
```

> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Requirement already satisfied: pyyaml==5.2 in /usr/local/lib/python3.7/dist-packages (5.2)
> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Requirement already satisfied: scipy==1.1.0 in /usr/local/lib/python3.7/dist-packages (1.1.0)
> Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python3.7/dist-packages (from scipy==1.1.0) (1.21.6)
> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Requirement already satisfied: torch==1.2.0 in /usr/local/lib/python3.7/dist-packages (1.2.0)
> Requirement already satisfied: torchvision==0.4.0 in /usr/local/lib/python3.7/dist-packages (0.4.0)
> Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from torch==1.2.0) (1.21.6)
> Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.7/dist-packages (from torchvision==0.4.0) (6.2.2)
> Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from torchvision==0.4.0) (1.15.0)
> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Requirement already satisfied: pillow==6.2.2 in /usr/local/lib/python3.7/dist-packages (6.2.2)
> 1.2.0
> 5.2
> 1.1.0

```
import os
!rm -rf /content/AlphaPose
os.chdir('/content/')
!git clone https://github.com/MVIG-SJTU/AlphaPose.git
os.chdir('/content/AlphaPose')
!git checkout **2330a3d7f56269c9186ce08a9c974ffec12fb2f5**
```
> Cloning into 'AlphaPose'...
> remote: Enumerating objects: 2325, done.
> remote: Counting objects: 100% (15/15), done.
> remote: Compressing objects: 100% (15/15), done.
> remote: Total 2325 (delta 1), reused 3 (delta 0), pack-reused 2310
> Receiving objects: 100% (2325/2325), 108.66 MiB | 32.31 MiB/s, done.
> Resolving deltas: 100% (1116/1116), done.
> Note: checking out '2330a3d7f56269c9186ce08a9c974ffec12fb2f5'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 2330a3d add support for PyTorch 1.11 and CUDA 11.3

```
!python -m pip install cython
!sudo apt-get install libyaml-dev
```

> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (0.29.30)
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libyaml-dev is already the newest version (0.1.7-2ubuntu3).
> The following package was automatically installed and is no longer required:
>   libnvidia-common-460
> Use 'sudo apt autoremove' to remove it.
> 0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.

**The important part:**

```
import os
os.chdir('/content/AlphaPose')
print(os.getcwd())
! python setup.py build develop
```

> /content/AlphaPose
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> creating build/lib.linux-x86_64-3.7/alphapose
> copying alphapose/__init__.py -> build/lib.linux-x86_64-3.7/alphapose
> copying alphapose/opt.py -> build/lib.linux-x86_64-3.7/alphapose
> copying alphapose/version.py -> build/lib.linux-x86_64-3.7/alphapose
> creating build/lib.linux-x86_64-3.7/trackers
> copying trackers/tracker_api.py -> build/lib.linux-x86_64-3.7/trackers
> copying trackers/tracker_cfg.py -> build/lib.linux-x86_64-3.7/trackers
> copying trackers/__init__.py -> build/lib.linux-x86_64-3.7/trackers
> creating build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/single_hand_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_136_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_coco_wholebody_136_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_coco_wholebody_26.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/coco_wholebody.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_68_noface.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/coco_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_68_noface_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_coco_wholebody_136.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_coco_wholebody_26_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/__init__.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/concat_dataset.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/coco_wholebody_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_136.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/mpii.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_26_det.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/single_hand.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/halpe_26.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/mscoco.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> copying alphapose/datasets/custom.py -> build/lib.linux-x86_64-3.7/alphapose/datasets
> creating build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/detector.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/transforms.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/bbox.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/logger.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/metrics.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/env.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/vis.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/__init__.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/webcam_detector.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/writer.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/registry.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/config.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/pPose_nms.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> copying alphapose/utils/file_detector.py -> build/lib.linux-x86_64-3.7/alphapose/utils
> creating build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/hardnet.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/criterion.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/fastpose_duc_dense.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/__init__.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/builder.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/hrnet.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/simplepose.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/fastpose.py -> build/lib.linux-x86_64-3.7/alphapose/models
> copying alphapose/models/fastpose_duc.py -> build/lib.linux-x86_64-3.7/alphapose/models
> creating build/lib.linux-x86_64-3.7/alphapose/utils/roi_align
> copying alphapose/utils/roi_align/__init__.py -> build/lib.linux-x86_64-3.7/alphapose/utils/roi_align
> copying alphapose/utils/roi_align/roi_align.py -> build/lib.linux-x86_64-3.7/alphapose/utils/roi_align
> creating build/lib.linux-x86_64-3.7/alphapose/utils/presets
> copying alphapose/utils/presets/simple_transform.py -> build/lib.linux-x86_64-3.7/alphapose/utils/presets
> copying alphapose/utils/presets/__init__.py -> build/lib.linux-x86_64-3.7/alphapose/utils/presets
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/osnet.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/resnet_fc.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/osnet_ain.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/net_utils.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/ResBnLin.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/ResNet.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> copying trackers/ReidModels/bn_linear.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels
> creating build/lib.linux-x86_64-3.7/trackers/tracking
> copying trackers/tracking/__init__.py -> build/lib.linux-x86_64-3.7/trackers/tracking
> copying trackers/tracking/matching.py -> build/lib.linux-x86_64-3.7/trackers/tracking
> copying trackers/tracking/basetrack.py -> build/lib.linux-x86_64-3.7/trackers/tracking
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling
> copying trackers/ReidModels/psroi_pooling/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling
> copying trackers/ReidModels/psroi_pooling/build.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/backbone
> copying trackers/ReidModels/backbone/googlenet.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/backbone
> copying trackers/ReidModels/backbone/sqeezenet.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/backbone
> copying trackers/ReidModels/backbone/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/backbone
> copying trackers/ReidModels/backbone/lrn.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/backbone
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/classification
> copying trackers/ReidModels/classification/rfcn_cls.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/classification
> copying trackers/ReidModels/classification/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/classification
> copying trackers/ReidModels/classification/classifier.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/classification
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/reid
> copying trackers/ReidModels/reid/image_part_aligned.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/reid
> copying trackers/ReidModels/reid/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/reid
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/modules
> copying trackers/ReidModels/psroi_pooling/modules/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/modules
> copying trackers/ReidModels/psroi_pooling/modules/psroi_pool.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/modules
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/functions
> copying trackers/ReidModels/psroi_pooling/functions/psroi_pooling.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/functions
> copying trackers/ReidModels/psroi_pooling/functions/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/functions
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/_ext
> copying trackers/ReidModels/psroi_pooling/_ext/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/_ext
> creating build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/_ext/psroi_pooling
> copying trackers/ReidModels/psroi_pooling/_ext/psroi_pooling/__init__.py -> build/lib.linux-x86_64-3.7/trackers/ReidModels/psroi_pooling/_ext/psroi_pooling
> creating build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/nms.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/utils.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/kalman_filter.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/timer.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/__init__.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/io.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> copying trackers/tracking/utils/parse_config.py -> build/lib.linux-x86_64-3.7/trackers/tracking/utils
> running build_ext
> building 'detector.nms.soft_nms_cpu' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/detector
> creating build/temp.linux-x86_64-3.7/detector/nms
> creating build/temp.linux-x86_64-3.7/detector/nms/src
> x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.7/dist-packages/numpy/core/include -I/usr/include/python3.7m -c detector/nms/src/soft_nms_cpu.cpp -o build/temp.linux-x86_64-3.7/detector/nms/src/soft_nms_cpu.o -Wno-unused-function -Wno-write-strings -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=soft_nms_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
> In file included from /usr/local/lib/python3.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1969:0,
>                  from /usr/local/lib/python3.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
>                  from /usr/local/lib/python3.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from detector/nms/src/soft_nms_cpu.cpp:638:
> /usr/local/lib/python3.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it with " \
>   ^~~~~~~
> creating build/lib.linux-x86_64-3.7/detector
> creating build/lib.linux-x86_64-3.7/detector/nms
> x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/detector/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/detector/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
> building 'detector.nms.nms_cpu' extension
> x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.7m -c detector/nms/src/nms_cpu.cpp -o build/temp.linux-x86_64-3.7/detector/nms/src/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
> detector/nms/src/nms_cpu.cpp: In function ‘at::Tensor nms_cpu_kernel(const at::Tensor&, float)’:
> detector/nms/src/nms_cpu.cpp:26:50: error: expected primary-expression before ‘>’ token
>    auto suppressed = suppressed_t.data_ptr<uint8_t>();
>                                                   ^
> detector/nms/src/nms_cpu.cpp:26:52: error: expected primary-expression before ‘)’ token
>    auto suppressed = suppressed_t.data_ptr<uint8_t>();
>                                                     ^
> detector/nms/src/nms_cpu.cpp:27:40: error: expected primary-expression before ‘>’ token
>    auto order = order_t.data_ptr<int64_t>();
>                                         ^
> detector/nms/src/nms_cpu.cpp:27:42: error: expected primary-expression before ‘)’ token
>    auto order = order_t.data_ptr<int64_t>();
>                                           ^
> detector/nms/src/nms_cpu.cpp:28:35: error: expected primary-expression before ‘>’ token
>    auto x1 = x1_t.data_ptr<scalar_t>();
>                                    ^
> detector/nms/src/nms_cpu.cpp:28:37: error: expected primary-expression before ‘)’ token
>    auto x1 = x1_t.data_ptr<scalar_t>();
>                                      ^
> detector/nms/src/nms_cpu.cpp:29:35: error: expected primary-expression before ‘>’ token
>    auto y1 = y1_t.data_ptr<scalar_t>();
>                                    ^
> detector/nms/src/nms_cpu.cpp:29:37: error: expected primary-expression before ‘)’ token
>    auto y1 = y1_t.data_ptr<scalar_t>();
>                                      ^
> detector/nms/src/nms_cpu.cpp:30:35: error: expected primary-expression before ‘>’ token
>    auto x2 = x2_t.data_ptr<scalar_t>();
>                                    ^
> detector/nms/src/nms_cpu.cpp:30:37: error: expected primary-expression before ‘)’ token
>    auto x2 = x2_t.data_ptr<scalar_t>();
>                                      ^
> detector/nms/src/nms_cpu.cpp:31:35: error: expected primary-expression before ‘>’ token
>    auto y2 = y2_t.data_ptr<scalar_t>();
>                                    ^
> detector/nms/src/nms_cpu.cpp:31:37: error: expected primary-expression before ‘)’ token
>    auto y2 = y2_t.data_ptr<scalar_t>();
>                                      ^
> detector/nms/src/nms_cpu.cpp:32:41: error: expected primary-expression before ‘>’ token
>    auto areas = areas_t.data_ptr<scalar_t>();
>                                          ^
> detector/nms/src/nms_cpu.cpp:32:43: error: expected primary-expression before ‘)’ token
>    auto areas = areas_t.data_ptr<scalar_t>();
>                                            ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

What could this issue be related to? And more importantly, how can I fix it?

**Comment by Fang-Haoshu** [comment]
Hi, I updated the colab to the latest version of AlphaPose, using pytorch 1.11. I can now run it successfully, can you try the latest colab on the master branch?

**Comment by Fang-Haoshu** [comment]
And I figure out why the checkout not working. You need to checkout to the commit **before**  2330a3. I think check out to d97ac should work. The 2330a3 is the PR that we merge yesterday, it update the codebase to pytorch 1.11
