### ISSUE TITLE
Previous version of AlphaPose

### ISSUE THREAD

**Issue by akamob** [MVIG-SJTU/AlphaPose#1047]
Hi, Thank you for the great work.

I use AlphaPose on [this](https://drive.google.com/file/d/1-fgKzips8Tl5mR52-V07_YIbMNxjwx-l/view?usp=sharing) jupyter notebook.
And I found I can't use it after updating, I met some problems like:
```
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'
ModuleNotFoundError: No module named 'detector'
```

I'm wondering if it is possible that you could provide the previous version of AlphaPose with me?
Thank you!

**Comment by Fang-Haoshu** [comment]
Hi, below this line ``!git clone https://github.com/MVIG-SJTU/AlphaPose.git``, please add a ``!git checkout "pytorch<1.5`` so that you can use the older version of alphapose

**Comment by akamob** [comment]
Ok, if I have some new problems then I would contact you again.
Thank you!
