### ISSUE TITLE
--detector tracker seems not working 

### ISSUE THREAD

**Issue by VisImage** [MVIG-SJTU/AlphaPose#1048]
Using the colab link provided in the repo, and went to the very end: works like a charm. :-)

"!python3 scripts/demo_inference.py  with flag --pose_track --" on my own video file works fine. My own video file and osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0 are uploaded to the colab folder.

"!python3 scripts/demo_inference.py  with flag --detector tracker" hangs (frozen). file jde.1088x608.uncertainty.pt has been uploaded to //content/AlphaPose/detector/tracker/data/jde.1088x608.uncertainty.pt.

Two colab cells for the above two program-executions are shown below for your reference. Thank you.

![Capture](https://user-images.githubusercontent.com/38402317/175453396-3b41773e-87a7-4a9a-ae22-686ffb3f0d3e.PNG)

**Comment by Fang-Haoshu** [comment]
Hi, it hints that the jde.1088x608.uncertainty.pt might be corrupted. Can you try redownload and reupload it to the google drive?

**Comment by VisImage** [comment]
Thank you for the suggestion.  I re-download and re-upload the file jde.1088x608.uncertainty.pt and tried again. The same issue appears.

Actually, I noticed that my first customized cell also uses this same file " jde.1088x608.uncertainty.pt" and it worked fine.  It might be another file corrupted. 

! python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml \
--checkpoint pretrained_models/fast_res50_256x192.pth  --outdir /content/output_track \
  --pose_track --sp  --save_img  --save_video  --vis_fast --video /content/alphaPose_sample3.avi

**Comment by HaoyiZhu** [comment]
Hi, we have fixed a bug of --detector tracker. You can try again now! @VisImage

**Comment by Fang-Haoshu** [comment]
And the file corruption of " jde.1088x608.uncertainty.pt" needs double check @VisImage, since the pytorch error message point to this file
