### ISSUE TITLE
UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown len(cache))

### ISSUE THREAD

**Issue by Vivianwxf** [MVIG-SJTU/AlphaPose#105]
hello and Thank you for your hard work.i have a bug,hope　your reply.
/AlphaPose$ CUDA_VISIBLE_DEVICES=0 python demo.py --indir examples/demo/ --outdir examples/results/ --save_img Loading YOLO model.. Loading pose model from ./models/sppe/duc_se.pth 100%|█████████████████████████████████████████████| 3/3 [00:00<00:00, 3.87it/s] ===========================> Finish Model Running. ===========================> Rendering remaining images in the queue... ===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time). (helloworld) vivian@vivian-Super-Server:~/HelloWorld/helloworld/AlphaPose$ /home/vivian/anaconda3/lib/python3.5/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown len(cache))

best wishes!

**Comment by Fang-Haoshu** [comment]
Hi, this is not a bug, just a warning. You can ignore it.

**Comment by Vivianwxf** [comment]
Thank you very much for your prompt reply.
But the program stops running here

**Comment by Vivianwxf** [comment]
@Fang-Haoshu WoW~Thank you very much for your prompt reply

But the program stops running here

**Comment by Vivianwxf** [comment]
@Fang-Haoshu  oh,i get it!!!! thanks~~~

**Comment by Fang-Haoshu** [comment]
Cool

**Comment by tiahflorens** [comment]
I am facing the same problem here..
demo.py does not giving me the result images...
How can I fix this ?

**Comment by zzw1123** [comment]
I met the same problem, have you solved it? @Vivianwxf

**Comment by banginpadr** [comment]
did anyone solved this problem? i have the same problem and the program stop working every time

**Comment by lucas-amin** [comment]
Is the problem solved?? How did you get it? @Vivianwxf

**Comment by YangJae96** [comment]
How did you solve the problem?
