### ISSUE TITLE
How to load the models only once ?

### ISSUE THREAD

**Issue by SachaCutillas** [MVIG-SJTU/AlphaPose#1050]
Hello !

First, thank you for your work, it's amazing.
I woud like to implement AlphaPose in a real time project and I would like to load the SE Resnet, YOLO, pose and reid model only once and execute AlphaPose frame after frame. For now, I can just run the command `python demo_inference.py` and it loads the model each time I call it.
How can I achieve that ?

Thank you vor your time !

**Comment by Fang-Haoshu** [comment]
Hi, for real-time stream, you can use the flag --webcam $webcam_id(for example, 0) You can refer to our document mentioned in the readme. We have provided many document.

**Comment by Fang-Haoshu** [comment]
Hi, for real-time stream, you can use the flag --webcam $webcam_id(for example, 0) You can refer to our document mentioned in the readme. We have provided many document.

**Comment by Fang-Haoshu** [comment]
More detailed inference options and examples, please refer to [GETTING_STARTED.md](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/GETTING_STARTED.md)
