### ISSUE TITLE
Human-ReID based tracking

### ISSUE THREAD

**Issue by maarten0912** [MVIG-SJTU/AlphaPose#1051]
When is the paper coming? I cannot find it anywhere. Could you share the MOTA and MOTP of the Human-ReID based tracking module?

**Comment by Fang-Haoshu** [comment]
Hi, the paper is still under review and we haven't post it on arxiv. The mAP and MOTA are 74.7/64.7 on PoseTrack 2018 val set when the reid model is trained on PoseTrack. The current repo contain a more general re-id model that performs better for in-the-wild videos.
