### ISSUE TITLE
Benchmark for the detection

### ISSUE THREAD

**Issue by cheesezoella** [MVIG-SJTU/AlphaPose#1053]
Hi, may i know what commands to run to get the benchmark like fps or inference time? May I also what is iter/s stated below? Is it related to fps? Thank You :)
![Screenshot from 2022-07-14 12-25-01](https://user-images.githubusercontent.com/108833079/178898325-edf0a852-6984-44a8-a11b-61897d170c8b.png)

**Comment by Fang-Haoshu** [comment]
Hi, we run the demo inference program and calculate the fps and speed manually. The iter/s is obtained for batch_size=64.  Thus, 1 iter/s means 64 people per second. The fps is related to the number of people per frame.

**Comment by zxcamazing** [comment]
Loading pose model from pretrained_models/fast_res50_256x192.pth.. .
det time : 0.0462 | pose time : 0.0398 | post processing : 0.0598:100% 5032/5032 [09:19<00:00， 9.00it/s]
结尾的“9.00it/s”就是表格里的speed么？@ Fang-Haoshu  提前感谢
