### ISSUE TITLE
Bugs in Bounding Box data in the result

### ISSUE THREAD

**Issue by VisImage** [MVIG-SJTU/AlphaPose#1054]
issue generate:
1) add an image into example/demo/visimage.jpg
2) run colab example and get the following result:
![colab_detection_result](https://user-images.githubusercontent.com/38402317/179419136-df42c082-439f-4906-93df-ff71d2646d61.JPG)
3) add the following code segment in colab after the pose detection:
[DrawBBOX.txt](https://github.com/MVIG-SJTU/AlphaPose/files/9128303/DrawBBOX.txt)
4) the original added image and result bbox image are shown here.
![visimage](https://user-images.githubusercontent.com/38402317/179419637-f0b01cc7-9f85-481e-ab43-2ea82188f085.jpg)
![visimage_box](https://user-images.githubusercontent.com/38402317/179419641-1a9b3c6c-baac-4f79-8232-b987447a369c.jpg)
5) the flat Bboxes (in blue) cross the whole image (almost from left tot he right of the image in the visimage_box.jpg are bugs.

**Comment by VisImage** [comment]
Thank you for the reply.  Would you please advise how to set a higher confidence score? I checked the file alphapose -> detector-> yolo -> cfg -> yolo.cfg and the file  alphaPose -> detector-> yolo -> cfg -> yolov3.cfg, but cannot find the  confidence score.

Also, there is a key :score" in the alphapose-result.json file.  Is it the confidence score for the pose detected? ( "score": 2.8948452472686768) If it is, what is its range? it seems not (0, 1). what is its accuracy? It cannot be accurate up to 16 digits.

**Comment by Fang-Haoshu** [comment]
alphapose -> detector-> yolo.cfg
you can set the cfg.CONFIDENCE to a higher value, say 0.3 or 0.5

**Comment by VisImage** [comment]
Where should I find  definition for the key : "score" in the file of alphapose-result.json ( "score": 2.8948452472686768 in my case) What is its range?
