### ISSUE TITLE
the program stops running here, Is it a bug?

### ISSUE THREAD

**Issue by my-hello-world** [MVIG-SJTU/AlphaPose#106]
hi and Thank you for your hard work.i maybe reencounter a bug,hope your reply.
``/python3.5/site-packages/torch/cuda/__init__.py:116: UserWarning: 
    Found GPU1 Quadro K4000 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Loading pose model from ./models/sppe/duc_se.pth
 94%|██████████████████████████████████████▋  | 906/960 [03:46<00:13,  4.00it/s]Video ended abnormally! Check if the video is standard format.
 99%|████████████████████████████████████████▊| 955/960 [04:00<00:01,  3.98it/s]

best wishes!！

**Comment by shizhenjun** [comment]
你的GPU太老了，他们的程序用的是比较新的pytorch版本，不支持你的GPU；如果对pytorch进行降级的话，估计很多函数都不能用，所以建议换块卡吧，1080应该就可以

**Comment by my-hello-world** [comment]
@shizhenjun 谢谢你。这样啊~我这个电脑是服务器，quadro k4000+tesla k40，计算能力分别是3.0和3.5。我是小白，可能是我操作的不对？设置了CUDA_VISIBLE_DEVICES=0或1或者0,1，都会提示计算能力只有3.0，过低。 我运行代码如：CUDA_VISIBLE_DEVICES=0 python3 video_demo.py --video examples/input.mp4 --outdir examples/results-v/ --save_video  --vis_fast。
再次谢谢~

**Comment by my-hello-world** [comment]
@shizhenjun
 谢谢你。这样啊我这个电脑是服务器，quadro k4000+tesla k40，计算能力分别是3.0和3.5。我是小白，可能是我操作的不对？设置了CUDA_VISIBLE_DEVICES=0或1或者0,1，都会提示计算能力只有3.0，过低。 我运行代码如：
CUDA_VISIBLE_DEVICES=0 python3 video_demo.py --video examples/input.mp4 --outdir examples/results-v/ --save_video --vis_fast
再次谢谢

**Comment by Jeff-sjtu** [comment]
你程序报错
```
Video ended abnormally! Check if the video is standard format.
```
可以排查一下，你的视频是否有问题，可以换个视频测试一下？

**Comment by Jtoo** [comment]
I got stuck at this problem weeks ago and I believe it is a bug.
The problem is the total frames length read from "stream.get(cv2.CAP_PROP_FRAME_COUNT)" is not accurate for videos without "nb_frames" field in stream header.
The actual frames number read from stream might be less, but main process insists on reading exact "data_len" frames from the queue filled by dataloader.
So main process may stop near the end because the dataloader actually cannot put "enough" item into queue.

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your info! @my-hello-world @Jtoo, I just fix this bug in the latest commit. Please update your code and check if the problem still exists

**Comment by Anymake** [comment]
python3 demo.py --list ……  still has this bug, and the image has no problem

Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
 97%|█████████████████████████████████████▉ | 1072/1102 [01:07<00:01, 15.81it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/con/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/con/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/con/work/alphaPose_pytorch/dataloader.py", line 150, in getitem_yolo
    img_k, orig_img_k, im_dim_list_k = prep_image(im_name_k, inp_dim)
  File "/home/con/work/alphaPose_pytorch/yolo/preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

100%|██████████████████████████████████████▉| 1099/1102 [01:20<00:00, 13.74it/s]

**Comment by Jeff-sjtu** [comment]
It seems one of your image cannot open. Maybe you give a wrong image name.
