### ISSUE TITLE
fatal error when running python setup.py build develop

### ISSUE THREAD

**Issue by LeeChunHei** [MVIG-SJTU/AlphaPose#1063]
Hi,
I'm trying to install the latest AlphaPose in Linux.
The distribution I use is Pop!_OS 22.04 LTS.
The GPU I'm using is GTX1080.
When I ran python setup.py build develop, the following error message was shown.

detector/nms/src/nms_kernel.cu:5:10: fatal error: ATen/ceil_div.h: No such file or directory
    5 | #include <ATen/ceil_div.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/lib/cuda/bin/nvcc' failed with exit status 1

May I ask how to fix this problem?

**Comment by Fang-Haoshu** [comment]
what pytorch version are you using?

**Comment by LeeChunHei** [comment]
> what pytorch version are you using?

Oh, I'm using 1.10.2
I should use 1.11 right?

**Comment by LeeChunHei** [comment]
But in the install.md.
We are asked to create conda env with python 3.6
And it looks like conda install pytorch will install 1.10.2 in python 3.6

**Comment by Fang-Haoshu** [comment]
Yes, you should use pytorch>=1.11. You can either checkout to the branch pytorch<1.11, or you can try to install the pytorch 1.11 by: conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
Try if this installation works

**Comment by LeeChunHei** [comment]
> conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch

Package pytorch conflicts for:
torchvision==0.12.0 -> pytorch==1.11.0
torchaudio==0.11.0 -> pytorch==1.11.0The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - python=3.6 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35

The problem here is python 3.6 is installed.
I think the INSTALL.md should update to correct install instruction, for example "conda create -n alphapose python=3.7 -y" ?

**Comment by Fang-Haoshu** [comment]
Oh I see. Thanks for reporting this issue!
