### ISSUE TITLE
some troubles when setup in colab about opendr

### ISSUE THREAD

**Issue by timbsb** [MVIG-SJTU/AlphaPose#1073]
I have trouble using [colab](https://colab.research.google.com/drive/1c7xb_7U61HmeJp55xjXs24hf1GUtHmPs?usp=sharing#scrollTo=p-Gw3k4coyFD) alphapose provide. It was OK before. There are troubles when running "**! python setup.py build develop**":
```
...
Installed /content/AlphaPose
Processing dependencies for alphapose==0.5.0+308cc9a
Searching for opendr
Reading https://pypi.tuna.tsinghua.edu.cn/simple/opendr/
Download error on https://pypi.tuna.tsinghua.edu.cn/simple/opendr/: The read operation timed out -- Some packages may not be found!
Couldn't find index page for 'opendr' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.tuna.tsinghua.edu.cn/simple/
Download error on https://pypi.tuna.tsinghua.edu.cn/simple/: _ssl.c:1074: The handshake operation timed out -- Some packages may not be found!
No local packages or working download links found for opendr
error: Could not find suitable distribution for Requirement.parse('opendr')
```
It seems to have trouble in opendr.

**Comment by kesaroid** [comment]
I ran into the same problem while setting it up on my local machine. It seems like a download timeout from that website.

**Comment by yxz-git** [comment]
Excuse me, have you solved the problem?

**Comment by Fang-Haoshu** [comment]
Hi, we update the codebase and use pytorch3d for visualization. This problem should be fixed.
