### ISSUE TITLE
Any implementation with yolov5?

### ISSUE THREAD

**Issue by iamdami** [MVIG-SJTU/AlphaPose#1081]
Hi. Thank you for your amazing work!

I know there are some implementation with yoloX.
I saw the comment saying that EfficientDet and yolov5 series have worse performance than yolov3 for pose estimation and yoloX is the only one that surpass yolov5 so far.
So I'm gonna try it out first, but is there any news regarding the implementation with yolov5?

**Comment by HaoyiZhu** [comment]
Hi, we do not add yolov5 in AlphaPose due to the license issue. However, you can refer to `https://github.com/MVIG-SJTU/AlphaPose/tree/master/detector` and add yolov5 here by yourself.

**Comment by Fang-Haoshu** [comment]
the official yolov5 implementation is at https://github.com/ultralytics/yolov5
