### ISSUE TITLE
singlehand 在debug模式下报错

### ISSUE THREAD

**Issue by humorbei** [MVIG-SJTU/AlphaPose#1084]
你好，在训练singlehand时加上--debug报下面错误，不加可以正常训练：
******************************
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Create new model
=> init weights
Adjusting learning rate of group 0 to 1.0000e-03.
loading annotations into memory...
Done (t=1.28s)
creating index...
index created!
############# Starting Epoch 0 | LR: 0.001 #############
  0%|                                                                      | 0/525 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "./train.py", line 348, in <module>
    main()
  File "./train.py", line 295, in main
    loss, miou = train(opt, train_loader, m, criterion, optimizer, writer)
  File "./train.py", line 106, in train
    debug_writing(writer, output, labels, inps, opt.trainIters)
  File "/tmp/alphapose/utils/logger.py", line 26, in debug_writing
    tmp_inp[0] += torch.sum(F.interpolate(tmp_tar, scale_factor=4, mode='bilinear'), dim=0)[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 3961, in interpolate
    raise NotImplementedError(
NotImplementedError: Input Error: Only 3D, 4D and 5D input Tensors supported (got 2D) for the modes: nearest | linear | bilinear | bicubic | trilinear | area | nearest-exact (got bilinear)

**Comment by HaoyiZhu** [comment]
感谢指出！目前single hand不支持debug模式，后续我们会试图加上。
