### ISSUE TITLE
测试SMPL + tracking报错

### ISSUE THREAD

**Issue by humorbei** [MVIG-SJTU/AlphaPose#1086]
你好，执行python demo_inference.py --cfg configs/smpl/256x192_adam_lr1e-3-res34_smpl_24_3d_base_2x_mix.yaml --checkpoint pretrained_models/pretrained_w_cam.pth  --webcam=0 --save_video --vis --pose_flow
报以下错误：
Traceback (most recent call last):
  File "demo_inference.py", line 170, in <module>
    det_loader = WebCamDetectionLoader(input_source, get_detector(args), cfg, args)
  File "/tmp/alphapose/utils/webcam_detector.py", line 60, in __init__
    train=False, add_dpg=False, gpu_device=self.device,
AttributeError: 'WebCamDetectionLoader' object has no attribute 'device'

**Comment by alessmolt** [comment]
how did you solved the issue? did you just hardcoded 'cuda'?

**Comment by Ivana-H16** [comment]
您好！请问您后续是如何解决的呢？
