### ISSUE TITLE
We can't use the Colab Program for Quick Start

### ISSUE THREAD

**Issue by thoth000** [MVIG-SJTU/AlphaPose#1087]
Thank you for developing AlphaPose!
In ReadMe.md, you provide a colab example for our quick start.
# ISSUE
I faced a problem.
However, I can't run the program completely.
I stopped at `! python setup.py build develop` command.
Would you teach me how to run this program completely?
Where are problems?

**Comment by HaoyiZhu** [comment]
Are there any more detailed bugs?

**Comment by thoth000** [comment]
Thank you for your kind reply.
I was able to solve this problem myself.

First, we removed the installation part of Pillow,
```
! pip install pillow==6.2.2
```
because the error in the first block is as follows
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask 2022.2.1 requires pyyaml>=5.3.1, but you have pyyaml 5.2 which is incompatible.
```

And I was able to run the program perfectly!
