### ISSUE TITLE
demo_3d_inference.py可视化问题

### ISSUE THREAD

**Issue by swsong89** [MVIG-SJTU/AlphaPose#1090]
您好，我利用scipt/demo_3d_inference.py对examples/demo/1.jpg进行测试，结果和原图一样没有生成人体网格，然后发现alphapose/utils/vis.py # 617行前后渲染结果没有生效，您这边输出图片正确吗？
![1](https://user-images.githubusercontent.com/41881939/201088617-6d613b23-85f0-4a6a-98d0-62d56a5cc947.png)

**Comment by Fang-Haoshu** [comment]
Hi, we update the render process by using pytorch3d instead of opendr. you can try our new codebase to see if the visualization is correct.

**Comment by swsong89** [comment]
> Hi, we update the render process by using pytorch3d instead of opendr. you can try our new codebase to see if the visualization is correct.

Thank you for your work，the visualization is correct.
