### ISSUE TITLE
human reid model not available on google drive

### ISSUE THREAD

**Issue by sankamohotttala** [MVIG-SJTU/AlphaPose#1096]
Hi, congratulations on the recent paper publication and appreciate making the code openly available.
I noticed when i tried to implement the tracking methods that the needed model weights for Reid model is not available on the google drive link. I may be available on the Baidu link but unfortunately I'm from outside china so it is not possible it seems to access it. Specifically I am referring to the model weights mentioned in the trackers/tracker_cfg.py file. ("trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth").

I would really appreciate if you can reupload it into the google drive. Thank you.

**Comment by Fang-Haoshu** [comment]
Hi thanks for the remind. Add the link to google drive in the readme
