### ISSUE TITLE
where can i get pretrain weight?

### ISSUE THREAD

**Issue by Sonic8657** [MVIG-SJTU/AlphaPose#1105]
Hi,I'm new here.
I notice "pretrained_models" is empty.
where can i get weight to run "demo_inference.py"
I want test base on webcam.
Thanks.

**Comment by nistring** [comment]
Hi. You can download weights from [here](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md) and store it in the pretrained_models folder. Then add the path to the weights to --checkpoint argument.
Don't forget to complete setups before your first run.

**Comment by Sonic8657** [comment]
How silly of me! Thank you so mach.
If you mean "setup.py", i will try it.
