### ISSUE TITLE
About the results accuracy by two version of Alphapose

### ISSUE THREAD

**Issue by zhFuECL** [MVIG-SJTU/AlphaPose#113]
I have run both two version of Alphapose on examples and found the original version has a better result although it is very slow.
The result of the original version
![3](https://user-images.githubusercontent.com/16152279/45302943-e160f000-b514-11e8-9bb6-86625219e4fd.jpg)
The result of pytorch version
![3](https://user-images.githubusercontent.com/16152279/45302954-efaf0c00-b514-11e8-86e1-acf7fe31ed84.jpg)

It can be seen that the original version can detect more persons.
So could someone tell me how can I get the same result from the pytorch version?

**Comment by Fang-Haoshu** [comment]
Hi, to detect more people, you can simply lower the conf threshold by adding a flag like --conf 0.05
You can also increase the nms thres, check the run.md and speed_up.md for more details
