### ISSUE TITLE
undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

### ISSUE THREAD

**Issue by jersonal** [MVIG-SJTU/AlphaPose#1132]
i have a problem. look title
my environment：
ubuntu18.04
python 3.8
cuda 11.3
cudnn 8.2.1
pytorch 1.12.0
i use :`python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x-dcn.yaml --checkpoint pretrained_models/fast_dcn_res50_256x192.pth --indir examples/demo/ --save_img`
and have an error message:
ImportError: /home/xxx/workspace/AlphaPose-master/detector/nms/nms_cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

how can i solve it?

**Comment by jersonal** [comment]
The reason for this error is a project compilation issue, which I resolved by recompiling.

**Comment by zdl12345678** [comment]
Hello, could you please provide more details on how you resolved this issue? I have also encountered this issue.

**Comment by jersonal** [comment]
> Hello, could you please provide more details on how you resolved this issue? I have also encountered this issue.

[The reason for this error is a project compilation issue, which I resolved by recompiling.](https://github.com/MVIG-SJTU/AlphaPose/issues/1132#issuecomment-1507828879)
