### ISSUE TITLE
Cuda root directory on University managed HPC cluster system

### ISSUE THREAD

**Issue by mtaimooradil** [MVIG-SJTU/AlphaPose#1133]
Hi Everyone,

I am trying to set up alphapose on a university managed HPC system. As the system is university managed, I do not have access to sudo and I do not have paths to cuda library. I can only access cuda as a library or a module to run my scripts. But to set up alphapose I need to make a PATH variable for CUDA root directory. It does not work if I give this path to CUDA library or if I just load the module. If someone can provide any help with this, it would be amazing.

Thanks
Taimoor

![image](https://user-images.githubusercontent.com/126269610/231707300-ded502ad-9b4b-4bd8-9076-72bef40bf2da.png)
![image](https://user-images.githubusercontent.com/126269610/231708313-556fc08d-d9b4-409f-b245-755e5f69bacc.png)

**Comment by Rakesh-Paul01** [comment]
@mtaimooradil did you figure this out??

**Comment by mtaimooradil** [comment]
> @mtaimooradil did you figure this out??

Yes, loading the module does load the CUDA libraries. But sometimes, the names of environment variables are a bit different than what Alphapose is expecting so I had to manually check each environment variable for CUDA-related paths. I have not figured it out for the case of Openpose (there even the renaming of environment variables doesn't work), but that is not an issue for this repository.
