### ISSUE TITLE
[BUG]  the bug of function : transformBoxInvert_batch

### ISSUE THREAD

**Issue by lianghongkey** [MVIG-SJTU/AlphaPose#115]
Line 204 :lenW = lenH * inpW / inpH
Line 206 : _pt = (pt * lenH) / resH
in file:AlphaPose/SPPE/src/utils/img.py

issue: if the type of "inpW" and "inpH" is int, then the result will be wrong.
so  we can  set  two variable to float in  opt config file
or   force the type in code

**Comment by Jeff-sjtu** [comment]
Can you please tell me in what situation, will the type of "inpW" and "inpH" be int?
This doesn't happen in our demo code.

**Comment by lianghongkey** [comment]
"----------------------------- Data options -----------------------------"
parser.add_argument('--inputResH', default=320, type=int,help='Input image height')
parser.add_argument('--inputResW', default=256, type=int,help='Input image width')
**In file opt.py**

The config file  set them to be int.

**dataloader.py**  663:   preds_hm, preds_img, preds_scores =
      getPrediction(hm_data, pt1, pt2,   opt.inputResH, opt.inputResW, opt.outputResH, opt.outputResW)
**eval.py**  144:  preds_tf = transformBoxInvert_batch(preds, pt1, pt2, inpH, inpW, resH, resW)

**Comment by Jeff-sjtu** [comment]
In python3, this operation is correct.
