### ISSUE TITLE
有关训练集处理

### ISSUE THREAD

**Issue by accountcwd** [MVIG-SJTU/AlphaPose#118]
你好，请问做姿态估计网络训练的时候，数据集是使用原图还是根据bbox裁剪成相应的大小模拟检测出的框进行训练的呢?我试过裁出bbox区域送入stacked hourglass 网络训练出来的效果并不太好。

**Comment by Jeff-sjtu** [comment]
根据bbox裁剪进行训练。
我们的模型框架是基于ICCV2017的论文 [RMPE](http://openaccess.thecvf.com/content_ICCV_2017/papers/Fang_RMPE_Regional_Multi-Person_ICCV_2017_paper.pdf)，具体的训练细节你可以参考论文。

**Comment by accountcwd** [comment]
谢谢～
