### ISSUE TITLE
遇到Segmentation fault

### ISSUE THREAD

**Issue by YogaHe** [MVIG-SJTU/AlphaPose#119]
执行视频命令时，Segmentation fault

**Comment by Jeff-sjtu** [comment]
请使用此仓库安装[torchsample](https://github.com/Jeff-sjtu/torchsample)

**Comment by aashishsoni05** [comment]
Hello,
"No module named 'torchsample'" is this error fixed ? please provide the fix.

**Comment by Jeff-sjtu** [comment]
Please use this repo [torchsample](https://github.com/Jeff-sjtu/torchsample).
`python setup --install`

**Comment by Jeff-sjtu** [comment]
Please give me the whole error info. @guancheng817

**Comment by guancheng817** [comment]
(torch0.4) ouc@ouc-titanx:/media/ouc/4T_B/gc/AlphaPose$ python3 video_demo.py --video ./video/Panama.mp4 --outdir examples/res --save_video
Segmentation fault (core dumped)
(torch0.4) ouc@ouc-titanx:/media/ouc/4T_B/gc/AlphaPose$ 

it's the whole error info. Thanks..

**Comment by guancheng817** [comment]
(torch0.4) ouc@ouc-titanx:/media/ouc/4T_B/gc/AlphaPose$ python3 video_demo.py --video ./video/Panama.mp4 --outdir examples/res --save_video
Segmentation fault (core dumped)
(torch0.4) ouc@ouc-titanx:/media/ouc/4T_B/gc/AlphaPose$

it's the whole error info. Thanks.. @Jeff-sjtu

**Comment by guancheng817** [comment]
> Please give me the whole error info. @guancheng817

The whole error info only one line ..

**Comment by guancheng817** [comment]
I  recreate a conda enviroment, and everything is ok...

**Comment by dmg206** [comment]
I have met this problem too. It didn't OK for the torchsampe. can u help me.the log is below:
==================================================================
 % /home/em/anaconda3/envs/alphapose_pytorch/bin/python3  demo.py  --indir examples/demo  --outdir examples/res/  --vis --save_img
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.43it/s]
===========================> Finish Model Running.
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
zsh: segmentation fault (core dumped)  /home/em/anaconda3/envs/alphapose_pytorch/bin/python3 demo.py --indir    --vi

**Comment by wine3603** [comment]
我安装的是pytorch-0.4 版本，也是同样的问题。。。
`~/AlphaPose$ python3 demo.py  --indir examples/demo  --outdir examples/res --save_img --vis_fast
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  7.09it/s]
===========================> Finish Model Running.
Segmentation fault (core dumped)
`
or 
'python3 demo.py  --indir examples/demo/  --outdir examples/res --save_img --vis_fast
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  7.67it/s]
===========================> Finish Model Running.
Segmentation fault (core dumped)'

**Comment by wine3603** [comment]
I solved this bug by down grade the pytorch = 0.4.0!
it must be pytorch=0.4.0, other version meet 
Segmentation fault (core dumped)'

**Comment by carolynenewman** [comment]
I have downgraded to pytorch=0.4.0, and have torchsample installed. I also have one .jpg image in a directory which is accurately called upon in the command line. Yet, I am still getting a segmentation fault. Has anyone found another solution to this problem?

**Comment by allenday** [comment]
pip install torch==0.4.0 torchvision==0.2.1 Pillow==6.1
