### ISSUE TITLE
how to train the model

### ISSUE THREAD

**Issue by tanghui2017108** [MVIG-SJTU/AlphaPose#120]
hi , i want to train my dataset .how i can do ?

**Comment by Molength** [comment]
我也遇到了同样的问题，咋训练模型呢？

**Comment by Fang-Haoshu** [comment]
Hi, we are organizing our code and will release them soon.

**Comment by Fang-Haoshu** [comment]
Hi, we just released the training code. Have fun! @tanghui2017108 @baicaigithub @Molength
