### ISSUE TITLE
Suggestion: support '\', the windows path sytle in video_demo.py

### ISSUE THREAD

**Issue by baicaigithub** [MVIG-SJTU/AlphaPose#121]
https://github.com/MVIG-SJTU/AlphaPose/blob/17d072a842102b9e1a28d64a9d54ec723839257c/video_demo.py#L65

On windows, path is by default using '\\', e.g. copying from explorer. If passing in video file path in windows style, user will get an error from opencv about failing to open video. The fix is either support '\\' or print out the file path being read so that user is able to detect the issue.

Let me know what you think and I'd be happy to provide a fix if needed.

**Comment by Fang-Haoshu** [comment]
Oh, thanks for the suggestion! You are right. Would you please make a PR? Thanks a lot!
