### ISSUE TITLE
pose skeleton (PoseTrack)

### ISSUE THREAD

**Issue by sanjeevini178** [MVIG-SJTU/AlphaPose#1221]
How do I extract pose skeletons alone as graphs, preferably? From videos, though I'm able to save them with annotated boxes and skeletons, how do I extract just those skeletons? 

this is the command I currently use:
`!python scripts/demo_inference.py --cfg configs/halpe_136/resnet/256x192_res50_lr1e-3_2x-regression.yaml --checkpoint pretrained_models/halpe136_fast50_regression_256x192.pth --showbox  --video /content/drive/MyDrive/fingertap21_.MOV --outdir /content/drive/MyDrive/outputvideos/ --save_video --sp --pose_track`

**Comment by zhou-jered** [comment]
Currenyly there is no way to reach your goal by a single commandline, you need to write code, after get the keypoints, you draw it yourself, that's it.

**Comment by sanjeevini178** [comment]
> Currenyly there is no way to reach your goal by a single commandline, you need to write code, after get the keypoints, you draw it yourself, that's it.

yep, did that but just wanted to know if this repo had a way. thanks!
