### ISSUE TITLE
PoseFlow/tracker.py  内部变量anno_dir未找到

### ISSUE THREAD

**Issue by gnnbest** [MVIG-SJTU/AlphaPose#125]
您好，在运行 python tracker.py --dataset=val 时：

问题：tracker.py内部语句：anno_dir = "./posetrack_data/annotations/{}".format(dataset)这个目录找不到呢？里面放置的是什么格式文件？如果用自己的图像，这个是自己生成的吗？怎么生成呢？谢谢🙏，
看名字好像是标注文件呢，但是预测的时候还需要标注文件吗？

前提：已经可以得到一系列图像的姿态估计结果alpha-pose-results.json文件，python deepmatching.py也可成功运行得到.txt文件

**Comment by Fang-Haoshu** [comment]
@YuliangXiu

**Comment by YuliangXiu** [comment]
This folder is for annotation files of the PoseTrack dataset, you can download from [posetrack](https://posetrack.net/users/download.php)

**Comment by my-hello-world** [comment]
@YuliangXiu   你好，不好意思又来打扰您。我已经下载了PoseTrack dataset。
格式如：
`.
├── test
│   ├── 000001_mpiinew_test.json
│   ├── 000002_mpiinew_test.json
│   ├── 000002_mpii_test.json
│   └── 024906_mpii_test.json
├── train
│   ├── 000001_bonn_train.json
│   ├── 024893_mpii_train.json
│   └── 024985_mpii_train.json
└── val
    ├── 000342_mpii_test.json
    └── 024621_mpii_test.json
但是我也出现了类似的错误：`
`./posetrack_data/images/test/000753_mpii_test/000083.jpg
./posetrack_data/images/test/000753_mpii_test/000084.jpg
100%|██████████████████████████████████████████████████████████████████████████████| 1/1 [03:35<00:00, 216.00s/it]
100%|███████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.44it/s]
  0%|                                                                                       | 0/1 [00:00<?, ?it/s]Exception KeyError: KeyError(<weakref at 0x7f342d8b93c0; to 'tqdm' at 0x7f342b0a72d0>,) in <bound method tqdm.__del__ of   0%|                                                                                       | 0/1 [00:00<?, ?it/s]> ignored
Traceback (most recent call last):
  File "tracker.py", line 268, in <module>
    imgs = []
KeyError: 'annolist'
`
我还没把我的视频分成单帧存储，所以是用alphapose处理imges/test/内的图片，alpha-pose-results.json文件后，执行track.py c出现的问题。

**Comment by my-hello-world** [comment]
@gnnbest  请问您跑通了吗？能分享下这个问题怎么解决的嘛？谢谢！

**Comment by YuliangXiu** [comment]
@my-hello-world alphapose 出来的 json是需要做一点调整的，具体sample.json 格式，参见[README](https://github.com/MVIG-SJTU/AlphaPose/tree/master/PoseFlow#quick-start)

**Comment by my-hello-world** [comment]
我有做调整，格式是一样的。
迷惑的是:
1."keypoint”里存的是和alphapose的输出(位置+检测得分）一样的吗？51个数字，17个关键点*3。
2.需不需要再运行什么了？annotations里相应的.json文件，没有"annolist"这个键。
3.tracker.py 生成了track.npy，如何查看运行的到的结果图呢？


实在是不好意思，因为刚接触这个方向和这方面的知识。很多东西不懂，麻烦您了~🌞🌞🌞🌞

**Comment by YuliangXiu** [comment]
“annolist” 是最终结果json 里面的一个key，track.npy 只是一个中间结果，我这套 code 现在只是用在PoseTrack Dataset 上，所以有很多地方写的不是很通用，因此如果是你自己的数据集，可能有没法从头执行到尾，我们正在做一个更通用的接口，不过需要一点时间，最近在准备 deadline，所以会稍微晚一点放出来，我建议你可以看一下tracker.py的代码然后自己改一下，或者等我们把通用接口写好，到时候我会告诉你的。

**Comment by YuliangXiu** [comment]
现有的是在全数据集上跑的，最终结果就是tracker.py 最终的生成结果，是许多个json 文件，每一个对应posetrack dataset 中一个视频，annolist 是需要生成的，所以既不在alpha-pose-test.json 也不再annotation 里面，我还是建议你看一下原code，我都有写注释的

**Comment by my-hello-world** [comment]
嗯嗯，我正在看源码的，就是很迷惑annolist如何生成的。现在在看poseval文件。

**Comment by lianuo** [comment]
@my-hello-world 我也在搞这个，想把alphapose和poseflow跑通，不过这俩数据格式有差别，还是有点头疼、

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.

**Comment by my-hello-world** [comment]
非常感谢 @YuliangXiu
