### ISSUE TITLE
error on running 'python demo.py'!RuntimeError: torch.cuda.FloatTensor is not enabled.

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [MVIG-SJTU/AlphaPose#126]
When I run 'python demo.py with the input dir and output dir ,such error occur:

RuntimeError: torch.cuda.FloatTensor is not enabled.
/home/wangxu/miniconda3/envs/pt/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
 @YuliangXiu

**Comment by Fang-Haoshu** [comment]
the wrong installation of Pytorch, need installation with Cuda.
