### ISSUE TITLE
GOD your installation instructions are so bad

### ISSUE THREAD

**Issue by danagain** [MVIG-SJTU/AlphaPose#127]

**Comment by danagain** [comment]
Can you not automate this entire process within docker containers or something ? It's absolutely ridiculous to try and run any of your code

**Comment by Fang-Haoshu** [comment]
Hi thanks. Since the developers are all students and we are not familiar with docker. It would be great if you can help to make a PR and provide a docker file. We appreciate the help from the community,

**Comment by danagain** [comment]
matplotlib, python-tk
