### ISSUE TITLE
pytorch版本的训练代码什么时候发布呢？

### ISSUE THREAD

**Issue by hcsearch** [MVIG-SJTU/AlphaPose#129]
你好，我看到之前也有人问pytorch版本的训练代码在哪里？官方说在整理中近期会发布。想问一下有具体的时间吗？如一周内？一个月内？或者什么时候？谢谢。

**Comment by Fang-Haoshu** [comment]
你好，刚刚发布了哈

**Comment by Zhangxiaof001** [comment]
> 你好，刚刚发布了哈

你好，请问在哪里可以找到训练代码？

**Comment by Jeff-sjtu** [comment]
@Zhangxiaof001 
PyTorch 分支上的[Train](https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/train_sppe)文件夹。

**Comment by Zhangxiaof001** [comment]
@Jeff-sjtu  谢谢

**Comment by hcsearch** [comment]
It's very cool.thank you.

**Comment by hcsearch** [comment]
> 你好，刚刚发布了哈
It's very cool.thank you.

**Comment by hcsearch** [comment]
@Fang-Haoshu 
It's very cool.thank you.
