### ISSUE TITLE
A little bug with np.loadtxt

### ISSUE THREAD

**Issue by ChangQF** [MVIG-SJTU/AlphaPose#13]
There are `proposal_scores = np.loadtxt("scores-proposals.txt")` in parametric-pose-nms-MPII.py and parametric-pose-nms-COCO.py.
But when there is only one number in scores-proposals.txt - it means there is only one person in pic, 
`proposal_scores[i]` may be wrong, because `proposal_scores.shape` will be ().
So I change the code to

 `proposal_scores = np.loadtxt("scores-proposals.txt", ndmin=1)`

I test it in centos6, python2.7, numpy 1.14

**Comment by zhijian-liu** [comment]
Would it be possible to submit a pull request instead? Thank you.
