### ISSUE TITLE
load YOLO model error

### ISSUE THREAD

**Issue by cswwp** [MVIG-SJTU/AlphaPose#131]
i have download the yolo mode file in baidu yun, and it recieved and error then run demo, it seems the model shape invalid, anyone help me?

This is the error info:
conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: invalid argument 2: size '[128 x 384 x 1 x 1]' is invalid for input with 18431 elements at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/TH/THStorage.cpp:84

**Comment by Jeff-sjtu** [comment]
Sorry for the wrong download link in Baidu Pan. It's for the old yolo version, we will update the link. Thanks.

**Comment by belloworld** [comment]
File "D:\YOLOv3\yolov3-master\models.py", line 342, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr:ptr + num_w]).view_as(conv_layer.weight)

RuntimeError: shape '[128, 384, 1, 1]' is invalid for input of size 18431

Can anyone please suggest me a solution? Using cfg/yolov3-spp.cfg
