### ISSUE TITLE
have you test some other layers to upsample such as deconvolution instead of pixelshuffle? 

### ISSUE THREAD

**Issue by FoolishMao** [MVIG-SJTU/AlphaPose#133]

**Comment by Jeff-sjtu** [comment]
In our experiments, pixelshuffle has better performance than deconv.

**Comment by FoolishMao** [comment]
@Jeff-sjtu  Thanks for what you have done! May I ask more details? If I use deconvolution instead of pixelshuffle, how many speed and accuracy would decrease? Thanks again!

**Comment by Jeff-sjtu** [comment]
Pixelshuffle is about 1~2 mAP higher than deconv, speed is almost the same.

**Comment by FoolishMao** [comment]
@Jeff-sjtu Thanks for your sharing!
