### ISSUE TITLE
Create annot.h5 for other dataset

### ISSUE THREAD

**Issue by hzhang57** [MVIG-SJTU/AlphaPose#134]
Thanks for sharing the impressive work. Can you elaborate the format of annot_coco.h5, so I could create one for my own dataset and fine-tune the model?

**Comment by hcsearch** [comment]
I have same problem，what's the annot_coco.h5 format?

**Comment by hzhang57** [comment]
Thank you :)

**Comment by Yuy1024** [comment]
@hzhang57 @hcsearch 
Hi,
1.Have you solve the problem of creating annot.h5 for other dataset ?
2.Have you successfully train on your own dataset?
Thank you!
