### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by zsano1** [MVIG-SJTU/AlphaPose#135]
您好，我想问一下train_sppe里面为什么没有像sppe用到hourglass网络和金字塔特征网络？还有是怎么运用stn的呢？怎么将yolo和它结合起来呢？谢谢

**Comment by Jeff-sjtu** [comment]
你好，新版的AlphaPose已经不使用hourglass网络了。网络结构是我们新提出的。

**Comment by zsano1** [comment]
那有没有什么新的论文可以读呢?不太明白为什么要这么用。还有stn结构也不用了吗?

**Comment by Jeff-sjtu** [comment]
你好，
Hourglass网络的计算量太大，不适合应用在realtime系统中。新的结构是速度与精度之间一个较好的权衡，没有使用stn。
技术论文目前还没有发表，具体细节可查看代码实现[FastPose](https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/src/models/FastPose.py).

**Comment by Yuy1024** [comment]
@Jeff-sjtu 请问新模型的论文现在发表了吗？新模型名字是？
