### ISSUE TITLE
您好，PoseFlow跟踪算法人数较多时耗时较长....

### ISSUE THREAD

**Issue by gnnbest** [MVIG-SJTU/AlphaPose#138]
问题一：
图片大小1280 * 720:
若图片中只有4个人时：best_matching_hungarian()算法耗时 12ms 左右
若图片中有33个人时：best_matching_hungarian()算法耗时接近 900ms，时间耗时较长

问题二：
我用deepmatching-static获取2张图片的信息生成0001_0002.txt耗时是700ms左右是这样吗？

我们的应用目标是实时跟踪，因为如上问题耗时太长，无法做到实时跟踪，不知道有没有什么办法呢？

有什么可以调整的参数吗？能让时间降下来？
图片场景是小学生上课的图片，人的走动比较小。
谢谢🙏

**Comment by YuliangXiu** [comment]
still working on a faster version, I will tell you when finished. @gnnbest

**Comment by YuliangXiu** [comment]
Fast ORB version is done, you can follow the latest [README](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/README.md) to generate matching files without DeepMatching.

As for the second problem, maybe you can try some more advanced implementation of Hungarian Algorithm to deal with this speed bottleneck, this Munkres package used by me is a naive implementation. 

Or maybe you can try other traditional tracking algorithms based on human body or human head.

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
