### ISSUE TITLE
大神，你好，训练出现维度不合问题

### ISSUE THREAD

**Issue by ZhongXiaoFang** [MVIG-SJTU/AlphaPose#139]
我按照配置教程搭建好了训练环境，运行python3 train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4命令进行训练时出现一下错误，求指导：

Create new model
############# Starting Epoch 0 #############
  0%|                                                  | 0/8646 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    main()
  File "train.py", line 169, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "train.py", line 33, in train
    loss = criterion(out.mul(setMask), labels)
RuntimeError: The size of tensor a (17) must match the size of tensor b (33) at non-singleton dimension 1

**Comment by Jeff-sjtu** [comment]
你好，代码已修复 f26bff17f2c3b087b329a07a827b9541722bfb0e
