### ISSUE TITLE
Error:UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown   len(cache))

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [MVIG-SJTU/AlphaPose#140]
When running demo.py,such error occure:

UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
And no result got.
@YuliangXiu

**Comment by Fang-Haoshu** [comment]
Not an error.
