### ISSUE TITLE
训练数据集问题

### ISSUE THREAD

**Issue by hcsearch** [MVIG-SJTU/AlphaPose#148]
h5格式里面的part部分，要求是17*2，我的理解是骨骼点需要完整的17个，所以我在把person_keypoints_train2017.json转成h5格式时进行了筛选，也就是只使用有17个keypoint的数据，那么这样筛选下来，只有8475个数据符合要求。跟官方的annot_coco.h5里面的144213个数据差别很大，请问官方是怎么转换的呢？或者我哪里做错了？谢谢。

**Comment by Jeff-sjtu** [comment]
你好，不需要完整的17个骨骼点。对于没有标记的点，请使用(0, 0)代替。

**Comment by hcsearch** [comment]
嗯，好的，谢谢，还有一个问题。骨骼点有一个状态标志，0，1，2，对于这部分有没有什么特殊的要求，如只选择状态标志为2的？

**Comment by Jeff-sjtu** [comment]
我们只区分了有标记和无标记两种类型，对于coco里面的visible以及invisible我们不区分。

**Comment by hcsearch** [comment]
明白，谢谢。
