### ISSUE TITLE
訓練方式的請教

### ISSUE THREAD

**Issue by chenloveheimei** [MVIG-SJTU/AlphaPose#157]
我想請問下，你之前非實時那個用的是tensorflow，這個可以實時的版本用的是pytorch，能夠把pytorch這個版本的模型轉換成tensorflow的嗎？效果一樣的嗎？剛接觸深度學習，虛心請教
謝謝

**Comment by Jeff-sjtu** [comment]
你好，我們非實時的版本不全是tensorflow實現。tensorflow框架實現human detector，lua的torch框架實現sppe。現在的新版本是使用pytorch把整個系統整合到一起，目前還沒有轉換到tensorflow的打算，請見諒。

**Comment by chenloveheimei** [comment]
我想移植到android上，但是Android看了好像没有pytorch的，Android能使用TensorFlow.所以我想就问下如果pytorch转TensorFlow是否可行而已？是否会效果一样，因为我还没接触过转换训练方法这一块，看看以你们接触这么久的经验，问下可不可行。
谢谢

**Comment by chenloveheimei** [comment]
好的謝謝。

**Comment by chenloveheimei** [comment]
請教下，duc_se.pth和yolov3-spp.weights分別是用來做什麼的？
謝謝
