### ISSUE TITLE
Pytorch version MPII format

### ISSUE THREAD

**Issue by LTH14** [MVIG-SJTU/AlphaPose#158]
Hi, it seems that I cannot get output in MPII format in the pytorch version. My command is 
python3 demo.py --indir xxx --outdir xxxx --dataset mpii.
Maybe there is something I miss? Thanks a lot!

**Comment by Jeff-sjtu** [comment]
You should fix the code in `SPPE/src/main_fast_inference.py`, Line42. The first 17 channels is for coco while last 16 is mpii.

**Comment by HaoWangXiDian** [comment]
It seems all other files need to modified also, because there are '17' fixed in them. Has anyone modified them for mpii format successfully?

**Comment by murdockhou** [comment]
> It seems all other files need to modified also, because there are '17' fixed in them. Has anyone modified them for mpii format successfully?

hi, have you get the MPII format successfully? Can you tell me where to changed? thx~

**Comment by HaoWangXiDian** [comment]
@murdockhou I forget exactly where I modified, you can modify relevant function by searching 17

**Comment by murdockhou** [comment]
> @murdockhou I forget exactly where I modified, you can modify relevant function by searching 17

thx~ I actually got the final 17 channels output simply and then remove some non-related output. What a stupid way ^.^

**Comment by SeanSyue** [comment]
@murdockhou Could you explain what have you done?

**Comment by SeanSyue** [comment]
@murdockhou Ok, let me make it clear. Did you modified the [line 42 of `SPPE/src/main_fast_inference.py`](https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/SPPE/src/main_fast_inference.py#L42)? Did you modifed other parts of the code?

**Comment by murdockhou** [comment]
@SeanSyue  Yes, i only modified the forward function, and replace `out.narrow(1, 0, 17)` into `out.narrow(1, 16, 17`) all of this. Nothing more has been changed. You can trying this and to see what has output for one image, then you can make sure which channel is useful and which is not. Just remove non-useful channels and make the order of the last channels changed then you can see the points in ** MPII version. **

**Comment by QuYJLeo** [comment]
> 似乎所有其他文件也需要修改，因为其中固定有“ 17”。是否有人成功将其修改为mpii格式？

yes

**Comment by Ehsan-Yaghoubi** [comment]
@murdockhou @Jeff-sjtu @

To get the results in MPII format:

When I change `out.narrow(1, 0, 17)` to `out.narrow(dim=1, start=17, length=16)` and use the `InferenNet_fast` it runs to this error:
```
>>> Loading YOLO model..
>> Loading pose model from ./models/sppe/duc_se.pth
  0%|          | 0/3 [00:00<?, ?it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/dataloader.py", line 666, in update
    hm_data, pt1, pt2, opt.inputResH, opt.inputResW, opt.outputResH, opt.outputResW)
  File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/utils/eval.py", line 145, in getPrediction
    preds_tf = transformBoxInvert_batch(preds, pt1, pt2, inpH, inpW, resH, resW)
  File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/utils/img.py", line 236, in transformBoxInvert_batch
    2 - center[:, 0].unsqueeze(-1).repeat(1, 17)).clamp(min=0)
RuntimeError: The size of tensor a (16) must match the size of tensor b (17) at non-singleton dimension 1

===========================> Finish Model Running.
100%|██████████| 3/3 [00:00<00:00, 17.63it/s]

```

And when I use `InferenNet` it runs to this error:
```
>>> Loading YOLO model..
> Loading pose model from ./models/sppe/duc_se.pth
  0%|          | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/demo.py", line 96, in <module>
    hm_j = pose_model(inps_j)
  File "/media/ehsan/HDD2TB/myvenvs/alphaposevenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/main_fast_inference.py", line 49, in forward
    flip_out, self.dataset))
  File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/utils/img.py", line 349, in shuffleLR
    tmp = x[:, dim1].clone()
IndexError: index 16 is out of bounds for dimension 1 with size 16
  0%|          | 0/3 [00:00<?, ?it/s]

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Has anybody fixed this bug already?

**Comment by hutslib** [comment]
> @murdockhou @Jeff-sjtu @
> 
> To get the results in MPII format:
> 
> When I change `out.narrow(1, 0, 17)` to `out.narrow(dim=1, start=17, length=16)` and use the `InferenNet_fast` it runs to this error:
> 
> ```
> >>> Loading YOLO model..
> >> Loading pose model from ./models/sppe/duc_se.pth
>   0%|          | 0/3 [00:00<?, ?it/s]Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/dataloader.py", line 666, in update
>     hm_data, pt1, pt2, opt.inputResH, opt.inputResW, opt.outputResH, opt.outputResW)
>   File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/utils/eval.py", line 145, in getPrediction
>     preds_tf = transformBoxInvert_batch(preds, pt1, pt2, inpH, inpW, resH, resW)
>   File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/utils/img.py", line 236, in transformBoxInvert_batch
>     2 - center[:, 0].unsqueeze(-1).repeat(1, 17)).clamp(min=0)
> RuntimeError: The size of tensor a (16) must match the size of tensor b (17) at non-singleton dimension 1
> 
> ===========================> Finish Model Running.
> 100%|██████████| 3/3 [00:00<00:00, 17.63it/s]
> ```
> 
> And when I use `InferenNet` it runs to this error:
> 
> ```
> >>> Loading YOLO model..
> > Loading pose model from ./models/sppe/duc_se.pth
>   0%|          | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/demo.py", line 96, in <module>
>     hm_j = pose_model(inps_j)
>   File "/media/ehsan/HDD2TB/myvenvs/alphaposevenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/main_fast_inference.py", line 49, in forward
>     flip_out, self.dataset))
>   File "/media/ehsan/HDD2TB/AlphaPose/AlphaPose/SPPE/src/utils/img.py", line 349, in shuffleLR
>     tmp = x[:, dim1].clone()
> IndexError: index 16 is out of bounds for dimension 1 with size 16
>   0%|          | 0/3 [00:00<?, ?it/s]
> 
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
> ```
> 
> Has anybody fixed this bug already?

have you fixed this problem?

**Comment by vinayvp** [comment]
Did anyone was able to get mpii format??
