### ISSUE TITLE
failed to build nms

### ISSUE THREAD

**Issue by codemarsyu** [MVIG-SJTU/AlphaPose#16]
Error message when do make under /AlphaPose/human-detection/lib/newnms

```
python setup_linux.py build_ext --inplace
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 51, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

Is it because cuda is not installed correctly?  Any suggestion ?

**Comment by codemarsyu** [comment]
OK. Looks it is because I am using Python 3.X which is not supported here ..... when can it support Python 3 ??

**Comment by Fang-Haoshu** [comment]
Hi, sorry about that. The NMS implementation is from another repo and is beyond our scope...  But any pull requests are welcomed!
