### ISSUE TITLE
算法在COCO上评估

### ISSUE THREAD

**Issue by FoolishMao** [MVIG-SJTU/AlphaPose#161]
谢谢你们的工作，我想咨询下，你们的评估是用哪些文件做的？是这个list-coco-minival500.txt文件包含的文件名吗？在demo.py输出的json转换成可以用COCOAPI评估的json格式的过程中需要注意什么吗？例如关键点score等阈值？

**Comment by FoolishMao** [comment]
只使用COCO数据集，学习率 1e-4，batch_size 64， 优化器 adam，迭代50epoch后，AP只有0.64，离你们po出来的模型AP=0.702还有很大距离。请问可以共享能重复你们结果的超参吗？

**Comment by Jeff-sjtu** [comment]
你好，训练学习率可以进一步下降到1e-5，以及稳定后使用dpg设置进行进一步训练。

**Comment by FoolishMao** [comment]
@Jeff-sjtu 谢谢，需要分成readme里面的三步进行训练是吗？

**Comment by ZhongXiaoFang** [comment]
你好，你是和作者一样在COCO的test-dev上进行测试吗？可是test-dev的标注json文件中只有图片名字，并没有图片中人体的关键点(比如训练数据的JSON文件就有人体关键点的位置坐标)。用COCO中的PythonAPI进行计算AP和AR的时候，类似于目标检测一样，需要用到test-dev的标注json文件（ground truth）和模型在test-dev上检测后生成的结果JSON文件。但是test-dev 的标注json文件没有关键点的信息，该如何计算得到AP和AR呢？求指点

**Comment by ZhongXiaoFang** [comment]
你好，你是和作者一样在COCO的test-dev上进行测试吗？可是test-dev的标注json文件中只有图片名字，并没有图片中人体的关键点(比如训练数据的JSON文件就有人体关键点的位置坐标)。用COCO中的PythonAPI进行计算AP和AR的时候，类似于目标检测一样，需要用到test-dev的标注json文件（ground truth）和模型在test-dev上检测后生成的结果JSON文件。但是test-dev 的标注json文件没有关键点的信息，该如何计算得到AP和AR呢？求指点 @Jeff-sjtu @FoolishMao @hjhhh3000 @zhijian-liu

**Comment by Jeff-sjtu** [comment]
你好，test集需要到COCO官网提交检测的json文件，网站会返回结果。

**Comment by FoolishMao** [comment]
@ZhongXiaoFang 我是用list-coco-minival500.txt这个文件里的验证集文件跑得评测

**Comment by FoolishMao** [comment]
@Jeff-sjtu 你好，请问你们在训练sppe结构的时候有尝试加上101resnet在imagenet上的权重作为pretrain吗？我尝试了下，效果不是很好，不知道是不是我权重加载的有问题。

**Comment by tianjiahao** [comment]
@FoolishMao 您好，请问annot_coco.h5文件是将train_2017和val_2017的json文件转换得到的吗？能发一下创建h5文件的代码吗？

**Comment by FoolishMao** [comment]
@tianjiahao 作者train spp中read me有提供

**Comment by Erikfather** [comment]
您好，我sppe训练后生成的是pkl文件，但是测试的时候需要的是duc_se.pth文件，这个.pth文件是怎么生成的呢

**Comment by Jeff-sjtu** [comment]
@Jeff-sjtu 你好，加上imagenet作为pretrain的作用不太大。

**Comment by Jeff-sjtu** [comment]
@FoolishMao 你好，使用imagenet pretrain模型的作用不太大

**Comment by pingqi** [comment]
@FoolishMao 你好，用list-coco-minival500.txt这个文件里的验证集文件跑得评测，这个是怎么跑的？使用哪个python脚本文件？怎么执行的啊？应该是得到的pkl模型文件跑这些图片，最终将得到json文件与原始文件的标注进行对比吧，那原始文件的json标注是从哪里得到的？Jeff-sjtu 说test集需要到COCO官网提交检测的json文件，网站会返回结果。如果是这样的话，能否发我一个，你得到的json，我貌似连不上coco官网，我的邮箱是pingqi_123@163.com,谢谢了。

**Comment by pingqi** [comment]
> 你好，你是和作者一样在COCO的test-dev上进行测试吗？可是test-dev的标注json文件中只有图片名字，并没有图片中人体的关键点(比如训练数据的JSON文件就有人体关键点的位置坐标)。用COCO中的PythonAPI进行计算AP和AR的时候，类似于目标检测一样，需要用到test-dev的标注json文件（ground truth）和模型在test-dev上检测后生成的结果JSON文件。但是test-dev 的标注json文件没有关键点的信息，该如何计算得到AP和AR呢？求指点 @Jeff-sjtu @FoolishMao @hjhhh3000 @zhijian-liu

@ZhongXiaoFang 这个是怎么弄的啊？能否说的详细点呢？@Jeff-sjtu @FoolishMao @hjhhh3000 @zhijian-liu

**Comment by Cronusf** [comment]
你好，你最后怎么跑的结果？求指导 @pingqi

**Comment by wduo** [comment]
> @ZhongXiaoFang 我是用list-coco-minival500.txt这个文件里的验证集文件跑得评测

Hi 请问下 list-coco-minival500.txt 这个文件里面的图片是属于COCO的哪个数据集呢？我测试了一下，好像不属于这四个：train2014,val2014,train2017,val2017。

是不是从train2017+val2017中随机选择500个，有可能属于前者，也有可能属于后者？

**Comment by wduo** [comment]
> @ZhongXiaoFang 我是用list-coco-minival500.txt这个文件里的验证集文件跑得评测

@Jeff-sjtu @ZhongXiaoFang 还有就是 训练集文件'annot_coco.h5'中包含144213 instances，也是从train2017+val2017中随机选择144213个吗？我看COCO2017的关键点数据集包括train(262465)+val(11004)个instances。

请问是随机选择的吗？还是按照规则进行了过滤，然后得到144213个呢？
多谢啦交大同学 多谢ZhongXiaoFang

**Comment by wduo** [comment]
> > @ZhongXiaoFang 我是用list-coco-minival500.txt这个文件里的验证集文件跑得评测
> 
> Hi 请问下 list-coco-minival500.txt 这个文件里面的图片是属于COCO的哪个数据集呢？我测试了一下，好像不属于这四个：train2014,val2014,train2017,val2017。
> 
> 是不是从train2017+val2017中随机选择500个，有可能属于前者，也有可能属于后者？

@ZhongXiaoFang 已解决

**Comment by wduo** [comment]
> > @ZhongXiaoFang 我是用list-coco-minival500.txt这个文件里的验证集文件跑得评测
> 
> @Jeff-sjtu @ZhongXiaoFang 还有就是 训练集文件'annot_coco.h5'中包含144213 instances，也是从train2017+val2017中随机选择144213个吗？我看COCO2017的关键点数据集包括train(262465)+val(11004)个instances。
> 
> 请问是随机选择的吗？还是按照规则进行了过滤，然后得到144213个呢？
> 多谢啦交大同学 多谢ZhongXiaoFang

@Jeff-sjtu @ZhongXiaoFang 期待您回答这个问题 抱拳抱拳

**Comment by tim20120526** [comment]
> > > @ZhongXiaoFang 我是用list-coco-minival500.txt这个文件里的验证集文件跑得评测
> > 
> > 
> > @Jeff-sjtu @ZhongXiaoFang 还有就是 训练集文件'annot_coco.h5'中包含144213 instances，也是从train2017+val2017中随机选择144213个吗？我看COCO2017的关键点数据集包括train(262465)+val(11004)个instances。
> > 请问是随机选择的吗？还是按照规则进行了过滤，然后得到144213个呢？
> > 多谢啦交大同学 多谢ZhongXiaoFang
> 
> @Jeff-sjtu @ZhongXiaoFang 期待您回答这个问题 抱拳抱拳

同学你好，请问这个问题你解决了吗？
