### ISSUE TITLE
Python3.6 can't pickle cv2.VideoCapture objects

### ISSUE THREAD

**Issue by jinfagang** [MVIG-SJTU/AlphaPose#164]
Running on python3.6 got this error:

```
  File "video_demo.py", line 41, in <module>
    data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()
  File "/~/AlphaPose/dataloader.py", line 214, in start
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle cv2.VideoCapture objects

```

**Comment by Fang-Haoshu** [comment]
The current solution is adding "--sp" flag. I haven't found a true workaround.

**Comment by jinfagang** [comment]
@Fang-Haoshu That's really work, but why anyway?

**Comment by Fang-Haoshu** [comment]
This bug is due to multi-processing in opencv. --sp disable multi-processing. BTW, can you tell me the version of opencv that you are using?

**Comment by FoolishMao** [comment]
@Fang-Haoshu   the version of opencv that I‘m using is 3.4.3 。And I have this error。

**Comment by jinfagang** [comment]
@Fang-Haoshu I install from pip, I think it's 3.2 or 3.4

**Comment by cclauss** [comment]
__--sp__ works because it turns off multiprocessing and the error dump says the problem above is in the _multiprocessing__ module.

**Comment by Tylerjoe** [comment]
the speed of single process is too slow, which version of opencv have you used for  multi-process successfully,Thanks! @Fang-Haoshu

**Comment by Pi-Rasp** [comment]
Can anyone give an example of using the '--sp' flag?

**Comment by cclauss** [comment]
Does this problem occur with the current version of https://pypi.org/project/opencv-python ?

**Comment by Pi-Rasp** [comment]
I am using opencv version 3.4.4. Can you please advice how to use --sp flag in code?

**Comment by cclauss** [comment]
Are you on Linux or on Windoze?

See: https://github.com/MVIG-SJTU/AlphaPose/issues/185#issuecomment-435843847

**Comment by yunfei-shi** [comment]
> I am using opencv version 3.4.4. Can you please advice how to use --sp flag in code?

video_demo.py --video ${path to video} --outdir examples/res --save_video --sp

**Comment by Fight-hawk** [comment]
i have encounter the same bug, and i just fix this bug refer [https://stackoverflow.com/questions/10862532/python-opencv-and-multiprocessing/17054961](https://stackoverflow.com/questions/10862532/python-opencv-and-multiprocessing/17054961)

**Comment by JoeyChuuichi** [comment]
@Fang-Haoshu I have the same error. My opencv version is 4.1. Hower, I can run the code by add --sp

**Comment by JoeyChuuichi** [comment]
> i have encounter the same bug, and i just fix this bug refer https://stackoverflow.com/questions/10862532/python-opencv-and-multiprocessing/17054961

Can you be more specific on how you fix it? I face the same problem

**Comment by alexgoft** [comment]
> i have encounter the same bug, and i just fix this bug refer https://stackoverflow.com/questions/10862532/python-opencv-and-multiprocessing/17054961



> > i have encounter the same bug, and i just fix this bug refer https://stackoverflow.com/questions/10862532/python-opencv-and-multiprocessing/17054961
> 
> Can you be more specific on how you fix it? I face the same problem

+1

**Comment by Fight-hawk** [comment]
can you speak chinese? i can not speak enlish well . if you can speak chinese, i can tell more detail. @JoeyChuuichi

**Comment by cclauss** [comment]
Write in Chinese and we can https://translate.google.com

**Comment by alexgoft** [comment]
> can you speak chinese? i can not speak enlish well . if you can speak chinese, i can tell more detail. @JoeyChuuichi

Can you simply post code snippet of the fix? Thank you very much in advance!

**Comment by JoeyChuuichi** [comment]
> can you speak chinese? i can not speak enlish well . if you can speak chinese, i can tell more detail. @JoeyChuuichi

Sure. Actually, I graduated from SJTU. 
我是18届交大毕业生哈哈哈（不过不是机动的）！
求教！我现在硕士项目正好需要用一下前辈们的项目~

**Comment by Fight-hawk** [comment]
不好意思啊，刚看见你的回复。根据我的调试发现只要self.cv2.VideoCapeture()这种写法就会出问题，so，你只需要找到代码中所有上述写法，并将其改为cv2.VideoCapeture()，并且需要作出相应其他修改，修改的地方不多，应该都在一个py文件里。个人觉得个中原因可能是因为在原始版本中出现了上述两种写法，而其读写的同一个文件，所以会有读写异常？ 以上原因纯属个人瞎分析，没有经过实验验证的，如果你找到原因，请贴出来告诉我一下哈

**Comment by JoeyChuuichi** [comment]
> 不好意思啊，刚看见你的回复。根据我的调试发现只要self.cv2.VideoCapeture()这种写法就会出问题，so，你只需要找到代码中所有上述写法，并将其改为cv2.VideoCapeture()，并且需要作出相应其他修改，修改的地方不多，应该都在一个py文件里。个人觉得个中原因可能是因为在原始版本中出现了上述两种写法，而其读写的同一个文件，所以会有读写异常？ 以上原因纯属个人瞎分析，没有经过实验验证的，如果你找到原因，请贴出来告诉我一下哈

我没有找到self.cv2.VideoCapture这个函数诶
你是指cv2.VideoCapture这个函数的输入或者输出有类似self.的东西吗?
比如这几个:
https://github.com/MVIG-SJTU/AlphaPose/blob/ab529c35904bf981b31ac5a60c3a4c98398fba31/dataloader.py#L219

https://github.com/MVIG-SJTU/AlphaPose/blob/ab529c35904bf981b31ac5a60c3a4c98398fba31/dataloader.py#L184

**Comment by Fight-hawk** [comment]
self.stream = cv2.VideoCapture(path) 是这种代码，不好意思是我记错了，就是说不能加self，也就是说stream变量不能作为类的成员变量 @JoeyChuuichi

**Comment by JoeyChuuichi** [comment]
@Fight-hawk 


> self.stream = cv2.VideoCapture(path) 是这种代码，不好意思是我记错了，就是说不能加self，也就是说stream变量不能作为类的成员变量 @JoeyChuuichi

我自己做了一个差不多的例子,感觉好像复现不出来bug
你这边是怎么样的?
这个是我的code,把path 路径改成任意可以用的视频文件

```python
import cv2


class test():
    def __init__(self, path):
        self.stream = cv2.VideoCapture(path)

    def func(self):
        self.datalen = int(self.stream.get(cv2.CAP_PROP_FRAME_COUNT))
        print(self.datalen)


if __name__ == '__main__':
    path = '/path/to/video/xxxxxxx.mp4'
    myclass = test(path)
    myclass.func()

```

**Comment by Fight-hawk** [comment]
我也没法复现这个bug，感觉不单单是成员变量的原因，从上面的问题描述来看，问题的出现跟python多进程有关，所以你的代码应该是不能复现这个bug，我试着加入了多进程代码，也没能复现，你如果找到了问题原因，麻烦分享下哈

**Comment by D-l-z** [comment]
> can you speak chinese? i can not speak enlish well . if you can speak chinese, i can tell more detail. @JoeyChuuichi

could you do me a favor. I am Chinese. I have the similar issue.
