### ISSUE TITLE
a question about deepmatching

### ISSUE THREAD

**Issue by my-hello-world** [MVIG-SJTU/AlphaPose#166]
Thanks for your works and sorry to bother you again.
shell ```python matching.py --orb=0 ```  
I got the error  `sh: 1: ./deepmatching/deepmatching: not found`
can you help me? 3q

**Comment by YuliangXiu** [comment]
I recommend you to use orb version, by this means there is no need to install DeepMatching.

**Comment by my-hello-world** [comment]
thanks for your reply.
 i have got  it use ORB version without installing DeepMatching lib. 
I think DeepMatching lib has failed to install.  emmmm....  i will try it again.
