### ISSUE TITLE
connection refused  mvig.sjtu.edu.cn 

### ISSUE THREAD

**Issue by worthlessFella** [MVIG-SJTU/AlphaPose#171]
I cannot download models:

(tensorflow-gpu) rick@ricks-pc:/media/rick/Rick/myprojects/AlphaPose$ ./fetch_models.sh 
--2018-10-19 16:01:52--  http://mvig.sjtu.edu.cn/publications/rmpe/output.zip
Resolving mvig.sjtu.edu.cn (mvig.sjtu.edu.cn)... 202.121.182.216
Connecting to mvig.sjtu.edu.cn (mvig.sjtu.edu.cn)|202.121.182.216|:80... failed: Connection refused.
unzip:  cannot find or open output.zip, output.zip.zip or output.zip.ZIP.
rm: cannot remove 'output.zip': No such file or directory
--2018-10-19 16:01:54--  http://mvig.sjtu.edu.cn/publications/rmpe/final_model.t7
Resolving mvig.sjtu.edu.cn (mvig.sjtu.edu.cn)... 202.121.182.216
Connecting to mvig.sjtu.edu.cn (mvig.sjtu.edu.cn)|202.121.182.216|:80... failed: Connection refused.

**Comment by YuliangXiu** [comment]
the server was down, you can download these models now.
