### ISSUE TITLE
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/generic/THCStorage.c:60

### ISSUE THREAD

**Issue by Huang9495** [MVIG-SJTU/AlphaPose#175]
A issue occurs at the `img = img.cuda()` and where should I modify to make it work?

system:
Ubuntu16.05;
GTX:1050ti

How to do?

![screenshot from 2018-10-22 10-49-57](https://user-images.githubusercontent.com/26674689/47277598-68b18100-d5f4-11e8-9cb2-a4c379ee92f6.png)

**Comment by xiaoweiChen** [comment]
ref:
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

```
cudaErrorInitializationError = 3
The API call failed because the CUDA driver and runtime could not be initialized.
```

May, you need use  nvidia-smi, make sure your GPU is being driven and working well.

**Comment by ChChwang** [comment]
have you solved it ? what should i do. pytorch model loading was set in __main __
