### ISSUE TITLE
Fail to build ntpath for python 3.6

### ISSUE THREAD

**Issue by vinjohn** [MVIG-SJTU/AlphaPose#176]
I failed to build the requirement ntpath on ubuntu 16.04 python 3.6. 
It seems it does not compatible with python 3.6. https://pypi.org/project/ntpath/
Is is a must for testing? How can I workaround?

**Comment by Fang-Haoshu** [comment]
Oh hi, it's for the video demo. But it's not necessary. It is introduced in this PR: https://github.com/MVIG-SJTU/AlphaPose/pull/153
You can revert it if needed.

**Comment by Fang-Haoshu** [comment]
BTW, go to bed earlier dude haha

**Comment by Tylerjoe** [comment]
> I failed to build the requirement ntpath on ubuntu 16.04 python 3.6.
> It seems it does not compatible with python 3.6. https://pypi.org/project/ntpath/
> Is is a must for testing? How can I workaround?

I also meet the same problem, have you solved this problem?

**Comment by David3310273** [comment]
So, what's the solution for this error?

**Comment by drwhitehouse** [comment]
sed -i s/ntpath// requirements.txt ?

**Comment by AaronWong** [comment]
ntpath is only used in video_demo.py
If you use linux, you can commit 'import ntpath' (line 15),
and  change 'ntpath' to 'os.path' (line 66) in video_demo.py.
