### ISSUE TITLE
关于减少需要检测的关键点

### ISSUE THREAD

**Issue by ZhongXiaoFang** [MVIG-SJTU/AlphaPose#177]
大神，早上好！
       基于COCO 数据集训练出来的模型能够检测出17个人体关键点。如果我现在只要检测下半身（除头部外）的12个关键点，我该如何修改代码？我的训练数据集是否也要把头部的关键点去掉呢？谢谢

**Comment by Fang-Haoshu** [comment]
not an issue. Close

**Comment by zcl912** [comment]
你改了关键点吗？我也要改关键点，不过改之后，有点问题，你解决了没？
