### ISSUE TITLE
OSError: Unable to open file (Unable to open file: name = '/home/ai/yali/alphapose/examples/results/pose/test-pose.h5'

### ISSUE THREAD

**Issue by NIEYALI** [MVIG-SJTU/AlphaPose#18]
Hi, I followed it as you mentioned, reinstall torch and go to lib to make . But now still have problems. Could u help me?
![qq 20180213181231](https://user-images.githubusercontent.com/17977751/36141952-fc44dd34-10e9-11e8-96dd-a3309980287a.png)

**Comment by Fang-Haoshu** [comment]
Hi, it seems the nms module is not installed correctly.
Try
```
cd AlphaPose/human-detection/lib/
make clean
make
cd newnms/
make
cd ../../../
```

**Comment by Fang-Haoshu** [comment]
Can you make it successfully?

**Comment by NIEYALI** [comment]
Hi, Which python version are u using? I use Anacanda 3, So I don't know if it's the problem

**Comment by NIEYALI** [comment]
![qq 20180214160015](https://user-images.githubusercontent.com/17977751/36191371-282e7b42-11a0-11e8-840c-d10acd76428e.png)
From this photo, I didn't meet error. So is it python version problem?

**Comment by Fang-Haoshu** [comment]
Hi, we are using python2. According to # 16, it seems that Python 3.x is not supported
