### ISSUE TITLE
关于训练步骤问题

### ISSUE THREAD

**Issue by ZhongXiaoFang** [MVIG-SJTU/AlphaPose#181]
你好，我之前配置好以后直接运行有数据增强的训练命令(python3 train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --addDPG) 进行训练，batch_size是16。当训练精度到达78%时，进行了测试，可是准确度却只有 20%左右，与你们给出的参考值71%相差甚远。主要有三个问题：（1）、否应该按照github上给出的训练步骤。先运行无数据增强的训练命令(python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4)。再运行有数据增强的训练命令（python3 train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --addDPG呢？  （2）、训练时的准确度应该达到多少才算训练得比较充分了呢？（3）、我该如何训练才能尽可能的达到与你们相近的结果呢？

**Comment by Jeff-sjtu** [comment]
请先使用无dpg的训练命令，稳定后降低lr，acc达到90%左右再加入dpg。

**Comment by ZhongXiaoFang** [comment]
恩呢，谢谢你，第二步（加入dpg）进行训练其实就是对第一步无dpg情况下训练出来的model模型继续进行训练吧。比如命令格式：python3 train.py --dataset coco --expID exp1 --nClasses 33 --LR 1e-4 --addDPG
  --loadModel  + 第一步无dpg得到的模型 @Jeff-sjtu

**Comment by FoolishMao** [comment]
@ZhongXiaoFang 有重复出好的结果吗？
