### ISSUE TITLE
Help to train own dataset

### ISSUE THREAD

**Issue by HaoWangXiDian** [MVIG-SJTU/AlphaPose#183]
1. How to get pre-trained model on mpii dataset and fine-tune it on my own dataset?

**Comment by Fang-Haoshu** [comment]
You can check the folder train_sppe for instructions of training. You can just use the trained model as initialize weights

**Comment by Yuy1024** [comment]
@HaoWangXiDian @Fang-Haoshu 
Hi, 
Have you solve the problem and successfully train on your own dataset? 
Thank you!
