### ISSUE TITLE
Some frames are missing in final_results in demo.py when estimate on conseutive frames

### ISSUE THREAD

**Issue by HaoWangXiDian** [MVIG-SJTU/AlphaPose#184]
I met a strange problem: when I used demo.py to estimate a sequence (samll difference between frames), some frames did not appear in final_results (It means len(image list) > len(final_result)). 

Why it happened and how do I solve it?

**Comment by Fang-Haoshu** [comment]
The people you want to detect must be very small. You can try using our master branch.

**Comment by HaoWangXiDian** [comment]
The people is not small at all, but they are doing sports. I guess the deformation that affect the detect. But the similar frame can be detected.

**Comment by Fang-Haoshu** [comment]
It would be good if you can upload some images. And I believe the master branch can do well since it detects human with 3 scale inputs.

**Comment by HaoWangXiDian** [comment]
I use pytorch (v0.4.1) branch, and the example are following:
![image](https://user-images.githubusercontent.com/34394741/47840662-f6118400-ddf1-11e8-8ad4-dea336e75577.png)

**Comment by HaoWangXiDian** [comment]
I change demo.py and some related file to mpii format, and did not change other code at all. 
I have one question: because torch's (v0.4.1) multiprocess have problem So I set sp flags in opt, may it result in the problem above?

**Comment by Fang-Haoshu** [comment]
Oh yeah, it is related to rendering.
Nope.
