### ISSUE TITLE
run demo.py error （about alphapose pytorch version in windows）

### ISSUE THREAD

**Issue by wangminda6** [MVIG-SJTU/AlphaPose#185]
Hello,I want to get a quick start this demo but I got such error when run:
 python demo.py --indir examples/demo/ --outdir examples/results/ --save_img --format cmu
(the python version is 3.6.5，pytorch version is 0.4.1 ,windows 10)

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 190, in get_context
    ctx = _concrete_contexts[method]
**KeyError: 'forkserver'**

During handling of the above exception, another exception occurred:

**Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    torch.multiprocessing.set_start_method('forkserver', force=True)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method)**
**ValueError: cannot find context for 'forkserver'**

how can I do with this error？
I really appreciate any kind of help!

**Comment by lrd8715923** [comment]
i meet same

**Comment by xiaoweiChen** [comment]
Maybe, this can help you 
https://stackoverflow.com/questions/46021456/configure-multiprocessing-in-python-to-use-forkserver

I meet the same issue, you can use --sp option just use one processor to run the demo.

**Comment by wangminda6** [comment]
the problem has been solved ,thank you very much!
