### ISSUE TITLE
Fine-tuning a pre-trained model: 33 output nodes vs 17

### ISSUE THREAD

**Issue by hoxi3** [MVIG-SJTU/AlphaPose#187]
I'm using the pytorch branch, and I'd like to fine-tune your pre-trained models on my data, but there appears to be an issue:

```
python train.py --loadModel ../../models/sppe/duc_se.pth --dataset mydata
```
...raises an error for mismatched geometry between the checkpoint and the codebase: 
```
RuntimeError: Error(s) in loading state_dict for FastPose_SE:
	While copying the parameter named "conv_out.weight", whose dimensions in the model are torch.Size([17, 128, 3, 3]) and whose dimensions in the checkpoint are torch.Size([33, 128, 3, 3]).
	While copying the parameter named "conv_out.bias", whose dimensions in the model are torch.Size([17]) and whose dimensions in the checkpoint are torch.Size([33]).
```

Can anyone help me understand why the demo uses 33 outputs? I'd like to mimic its behaviour. When I look at the [output doc](https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/doc/output.md), I get the impression that the number of outputs should be 17 for COCO-style keypoint sets and 16 for MSII-style keypoint sets.

**Comment by hoxi3** [comment]
Hm. I think I'm beginning to see. The demo uses 33 outputs, whereas the training module defaults to 17.

**Comment by hoxi3** [comment]
Can anyone help me understand why the demo uses 33 outputs? I'd like to mimic its behaviour. When I look at the [output doc](https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/doc/output.md), I get the impression that the number of outputs should be 17 for COCO-style keypoint sets and 16 for MSII-style keypoint sets.

**Comment by SivanKe** [comment]
I think the model was trained for COCO and MPII simultaneously. 
33 outputs since the first 17 outputs are COCO keypoints (COCO has 17 keypoints) and the other 16  are MPII keypoints (MPII has 16 keypoints). 
I think that you can simply train the first 17 outputs if you only want COCO type keypoints or the last 16 if your data is in MPII style.

**Comment by hoxi3** [comment]
Thanks!

**Comment by pingqi** [comment]
@hoxi3  Hi, does training 14 channels adding --nClasses 14 work ? when I add the param --nClasses 17, but it still return error as following ,

**Comment by lilichu** [comment]
me too. when load the model `duc_se.pth` such as:
`python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --trainBatch 8 --loadModel /home/user/backup/lichu/pytorch040/AlphaPose-pytorch/models/sppe/duc_se.pth`
I encounter the issue:
```
While copying the parameter named "conv_out.weight", whose dimensions in the model are torch.Size([17, 128, 3, 3]) and whose dimensions in the checkpoint are torch.Size([33, 128, 3, 3]).
	While copying the parameter named "conv_out.bias", whose dimensions in the model are torch.Size([17]) and whose dimensions in the checkpoint are torch.Size([33]).
```

**Comment by Yuy1024** [comment]
@hoxi3 @SivanKe @pingqi @lilichu

**Comment by Yuy1024** [comment]
@hoxi3 @SivanKe @pingqi @lilichu 
Hi，have you solve the problem and successfully train and  fine-tuning a pre-trained model?
