### ISSUE TITLE
Can this demo work directly when python3 is used?

### ISSUE THREAD

**Issue by zeroMrCc** [MVIG-SJTU/AlphaPose#189]
I just change the content int the .sh and makefile file. The 'python2' is changed by 'python3'. I just want to use this model in python3. But some problems occur.  The one is that`generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 22, in <module>
    from newnms.nms import  soft_nms
  File "/home/xc/XC/AlphaPose/human-detection/tools/../lib/newnms/nms.py", line 3, in <module>
    from cpu_nms import cpu_nms, cpu_soft_nms
ImportError: No module named 'cpu_nms'
`
Is this problem is caused by using the python3 not python2?

**Comment by Fang-Haoshu** [comment]
You are right. Currently master branch only supports py2
