### ISSUE TITLE
SPPE的两步训练策略？

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [MVIG-SJTU/AlphaPose#192]
在README中给出的两步训练策略如下：

Train without DPG first
python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4
Then, train with DPG
python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --addDPG

从代码中，并未发现这两步训练之间的关联性。在我的实验中，加入 -addDPG 后，训练貌似从头开始。两步训练在验证集上的准确率貌似也相差无几。

请问：我的理解是否存在偏差？我是否遗漏了什么重要部分没有看到？ @YuliangXiu

**Comment by YuliangXiu** [comment]
@Jeff-sjtu @Fang-Haoshu

**Comment by MoonBunnyZZZ** [comment]
> > 在README中给出的两步训练策略如下：
> > Train without DPG first
> > python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4
> > Then, train with DPG
> > python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --addDPG
> > 从代码中，并未发现这两步训练之间的关联性。在我的实验中，加入 -addDPG 后，训练貌似从头开始。两步训练在验证集上的准确率貌似也相差无几。
> > 请问：我的理解是否存在偏差？我是否遗漏了什么重要部分没有看到？ @YuliangXiu
> 
> 你好，我在执行train_sppe里面的train文件时候，总是报错：ValueError: embedded null byte
> 。请问这是什么原因呢？你在训练sppe结构时候，annot.h5对应的images文件夹下的coco数据集用的是2017还是2014的啊

我用的是2014.你下载的h5文件会不会有问题啊

**Comment by Erikfather** [comment]
您好，我sppe训练后生成的是pkl文件，但是测试的时候需要的是duc_se.pth文件，这个.pth文件是怎么生成的呢

**Comment by Jeff-sjtu** [comment]
你好，是先用1e-4训练，收敛之后，选择收敛的模型，使用loadModel参数，降低learning rate进行继续训练。之后，继续loadModel，加入 addDPG参数训练。 @MoonBunnyZZZ

**Comment by Jeff-sjtu** [comment]
这两个文件类型一样，只是保存时的名字不同。 @Erikfather
