### ISSUE TITLE
关于训练sppe结构的问题

### ISSUE THREAD

**Issue by Erikfather** [MVIG-SJTU/AlphaPose#193]
你好，我在执行train_sppe里面的train文件时候，总是报错：ValueError: embedded null byte
。请问这是什么原因呢？在训练sppe结构时候，annot.h5对应的images文件夹下的coco数据集用的是2017还是2014的啊

**Comment by tianjiahao** [comment]
@xiaoweiChen 请问annot_coco.h5文件是将train_2017和val_2017的json文件转换得到的吗？不知道您有没有json转HDF5这方面的代码，刚入门，代码能力有点弱。谢谢！

**Comment by xiaoweiChen** [comment]
@tianjiahao 因为annot_coco.h5这个文件不是我生成的，所以具体是怎么生成的，我不是很清楚。不过，从训练代码对这个文件的解析，里面存的主要是三个信息：文件名，bbox坐标，关键点坐标

AlphaPose\train_sppe\src\utils\dataset\coco.py 中的代码：
```
# create train/val split
        with h5py.File('../data/coco/annot_coco.h5', 'r') as annot:
            # train
            self.imgname_coco_train = annot['imgname'][:-5887]
            self.bndbox_coco_train = annot['bndbox'][:-5887]
            self.part_coco_train = annot['part'][:-5887]
            # val
            self.imgname_coco_val = annot['imgname'][-5887:]
            self.bndbox_coco_val = annot['bndbox'][-5887:]
            self.part_coco_val = annot['part'][-5887:]
```

HDF5其实我也不是很熟，不过我对JSON的处理还是蛮熟悉。coco原始的json比较难看一些，可以通过对原始的JSON文件进行处理，然后只保留上面的信息，在存回JSON文件中。下次再读取就好了，其实和HDF5在AlphaPose的用法差不多。

HDF5感觉应该和leveldb或lmdb一样用来存数据的内容，因为这样一大块二进制加载到主存中，通过指针的偏移的方式得到相应的数据，不论是在GPU还是在CPU上处理都会很快，就是比较吃内存。

所以，个人建议别舍本逐末，用JSON来处理就好。至少在这里，没必要花太多时间在HDF5上。 :)

**Comment by tianjiahao** [comment]
好的，谢谢你的指导，看了作者介绍的hdf5的资料，还是不怎么了解怎么写入，网上有关的代码也没找到，后面尝试一下您的方法。

**Comment by xiaoweiChen** [comment]
这个文件存在谷歌网盘上，需要你翻墙来下。我已经通过邮件发给你了。

因为还有其他事情，所以还没有用mpii的数据集训练过，这个需要你自己对数据和标签进行一下处理，网络输出部分也要改一下。
当然也可以在官方给出的模型上进行微调，然后用后14个输出来进行前向推测就好。

**Comment by pingqi** [comment]
收到了，谢谢。奇怪的是，作者的模型不是通过coco和mpii得到的吗？可是作者的代码怎么没有mpii的训练代码？

**Comment by xiaoweiChen** [comment]
这个你就要问作者了。从开源的代码来看，原来里面应该是有mpii相关的东西的。不过可能由于一些原因，mpii的代码都删除了，只保留了coco的部分。

**Comment by moyu916** [comment]
> @xiaoweiChen @tianjiahao 请问你们有annot_coco.h5文件吗？我下载不下来，能否发给我一份呢？我的邮箱是[pingqi_123@163.com](mailto:pingqi_123@163.com).另外你们用mpii的数据集训练过吗？
你好！能否发我一份annot_coco.h5文件，我的邮箱是972413091@qq.com

**Comment by moyu916** [comment]
> 这个文件存在谷歌网盘上，需要你翻墙来下。我已经通过邮件发给你了。
> 
> 因为还有其他事情，所以还没有用mpii的数据集训练过，这个需要你自己对数据和标签进行一下处理，网络输出部分也要改一下。
> 当然也可以在官方给出的模型上进行微调，然后用后14个输出来进行前向推测就好。

您好！能不能也发我一份annot_coco.h5，我的邮箱是972413091@qq.com,万分感谢！

**Comment by xiaoweiChen** [comment]
@moyu916 复制下面地址进行下载

https://gitee.com/loongchen/AlphaPose/raw/master/train/data/coco/annot.h5

**Comment by moyu916** [comment]
> @moyu916 复制下面地址进行下载
> 
> https://gitee.com/loongchen/AlphaPose/raw/master/train/data/coco/annot.h5

我下载下来了，但是还有几个问题，之前您说是用2017的数据集训练的，但是readme里边写的是person_keypoints_val2014.json请问是书写有误吗？还有您给的下载地址下下来的跟谷歌云盘上下载的h5文件命名和大小都不一样，哪个才是对的呢

**Comment by xiaoweiChen** [comment]
如果和官版提供的h5文件不一样，以官版的为准。

person_keypoints_val2014.json 这个文件在训练代码里面就没有用到，你可以自己找找看。

**Comment by moyu916** [comment]
> 如果和官版提供的h5文件不一样，以官版的为准。
> 
> person_keypoints_val2014.json 这个文件在训练代码里面就没有用到，你可以自己找找看。

确实没用到，谢谢！我还有一个问题是，运行你们的代码结果只能识别单人姿态，可能的原因是什么呢

**Comment by xiaoweiChen** [comment]
首先呢，我不是该库的维护人员。
其次呢，这个算法就是识别单人姿态，只不过前端使用了yolo或ssd进行了人体检测而已，所以这个算法，检测到的人越多，理论上就会处理的越慢。

**Comment by Yuy1024** [comment]
@xiaoweiChen @tianjiahao @pingqi @moyu916

**Comment by Yuy1024** [comment]
@xiaoweiChen @tianjiahao @pingqi @moyu916

**Comment by Yuy1024** [comment]
@xiaoweiChen @tianjiahao @pingqi @moyu916
Hi,
1.能不能也发我一份annot_coco.h5，邮箱是691554336@qq.com，gitee的网址打开提示访问受限？
2.请问你们用下载下来的annot_coco.h5文件训练成功了吗？
3.请问你们有用自己的数据进行finetune了吗？

**Comment by QuYJLeo** [comment]
你好，你有关于重写mpii训练的代码吗？

**Comment by yutian2333** [comment]
@xiaoweiChen @Fang-Haoshu @moyu916 @pingqi @Erikfather 你好！能不能也发我一份annot_coco.h5，邮箱是1105685914@qq.com，谢谢！

**Comment by shelly-xue** [comment]
> @xiaoweiChen @tianjiahao @pingqi @moyu916
> Hi,
> 1.能不能也发我一份annot_coco.h5，邮箱是[691554336@qq.com](mailto:691554336@qq.com)，gitee的网址打开提示访问受限？
> 2.请问你们用下载下来的annot_coco.h5文件训练成功了吗？
> 3.请问你们有用自己的数据进行finetune了吗？

你好 请问你用自己的数据finetune成功了吗
