### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'cv2.VideoCapture'>: it's not the same object as cv2.VideoCapture

### ISSUE THREAD

**Issue by oujieww** [MVIG-SJTU/AlphaPose#197]
use pip opencv 3.4.3 give me "TypeError: can't pickle cv2.VideoCapture object"
use source code opencv 3.3 give me "_pickle.PicklingError: Can't pickle <class 'cv2.VideoCapture'>: it's not the same object as cv2.VideoCapture"

there are three issues disscuss about this problem,with result "--sp".but the speed will be very slow.
which version of opencv should i use? ^_^ ,i want to try auther's opencv version

**Comment by Tylerjoe** [comment]
have find the suitable opencv version？ @oujieww
