### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by chengxmeng** [MVIG-SJTU/AlphaPose#198]
~/AlphaPose$ python3 demo.py --indir /home/AlphaPose/examples/demo --outdir examples/res 
Traceback (most recent call last):
  File "demo.py", line 45, in <module>
    data_loader = ImageLoader(im_names, batchSize=args.detbatch, format='yolo').start()
NameError: name 'im_names' is not defined

**Comment by aashishsoni05** [comment]
this is a problem of pytorch version. install pyroch==0.4.0.

**Comment by FuNian788** [comment]
Thanks for Jeff-sktu's comment. I have met the same question, and finally I see the demo means "Run AlphaPose for all images in a folder". When I change the command line from "python3 demo.py --indir /home/AlphaPose/examples/demo/1.jpg --outdir examples/res" to "python3 demo.py --indir /home/AlphaPose/examples/demo --outdir examples/res", the ERROR disappears.

**Comment by jhfollowgd** [comment]
我也是这个错误，我的pytorch版本是0.4.0（pytorch == 0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch）
然后路径（改用了绝对路径）也没问题，不知道问题是什么。
(py35) D:\python_all_kinds\HJM\Pose\Alphapose\AlphaPose>python demo.py --indir/D:\\python_all_kinds\\HJM\\Pose\\Alphapose\\AlphaPose\\examples\\yanshi --outdir examples/res --sp
usage: demo.py [-h] [--expID EXPID] [--dataset DATASET] [--nThreads NTHREADS]
               [--debug DEBUG] [--snapshot SNAPSHOT] [--addDPG ADDDPG] [--sp]
               [--profile] [--netType NETTYPE] [--loadModel LOADMODEL]
               [--Continue CONTINUE] [--nFeats NFEATS] [--nClasses NCLASSES]
               [--nStack NSTACK] [--fast_inference FAST_INFERENCE]
               [--use_pyranet USE_PYRANET] [--LR LR] [--momentum MOMENTUM]
               [--weightDecay WEIGHTDECAY] [--crit CRIT]
               [--optMethod OPTMETHOD] [--nEpochs NEPOCHS] [--epoch EPOCH]
               [--trainBatch TRAINBATCH] [--validBatch VALIDBATCH]
               [--trainIters TRAINITERS] [--valIters VALITERS] [--init INIT]
               [--inputResH INPUTRESH] [--inputResW INPUTRESW]
               [--outputResH OUTPUTRESH] [--outputResW OUTPUTRESW]
               [--scale SCALE] [--rotate ROTATE] [--hmGauss HMGAUSS]
               [--baseWidth BASEWIDTH] [--cardinality CARDINALITY]
               [--nResidual NRESIDUAL] [--dist DIST] [--backend BACKEND]
               [--port PORT] [--net DEMO_NET] [--indir INPUTPATH]
               [--list INPUTLIST] [--mode MODE] [--outdir OUTPUTPATH]
               [--inp_dim INP_DIM] [--conf CONFIDENCE] [--nms NMS_THESH]
               [--save_img] [--vis] [--matching] [--format FORMAT]
               [--detbatch DETBATCH] [--posebatch POSEBATCH] [--video VIDEO]
               [--webcam WEBCAM] [--save_video] [--vis_fast]
demo.py: error: unrecognized arguments: --indir/D:\\python_all_kinds\\HJM\\Pose\\Alphapose\\AlphaPose\\examples\\yanshi
