### ISSUE TITLE
'--sep' doesn't work

### ISSUE THREAD

**Issue by sunsinejust** [MVIG-SJTU/AlphaPose#20]
Hello, when I turn on the `--sep` flag, all results are still saved in one file `alpha-pose-results.json`.  
There only exists a single  .json file in folder `sep-json` .

`./run.sh --indir ../data --outdir ../alphapose --vis --sep --gpu 0,1 --batch 5`

Can U help me to separate the results? Thank you ahead~

**Comment by crh19970307** [comment]
Hi, the separate code is in predict/json/parametric-pose-nms-COCO.py It begins from line 73. The code will create a new directory sep-json. Check if the directory was created successfully.
