### ISSUE TITLE
can only process a few pictures

### ISSUE THREAD

**Issue by yi-jianfenghou** [MVIG-SJTU/AlphaPose#201]
root@d10c7c3ef981:/home/ruiyang/mnist/AlphaPose-pytorch# python3 demo.py --indir examples/video --outdir examples/res --posebatch 30
Loading YOLO model..
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 112, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: unable to write to file </torch_5211_1803063766> at /pytorch/aten/src/TH/THAllocator.c:383
Loading pose model from ./models/sppe/duc_se.pth
 23%|##################################2                                                                                                              | 49/209 [00:19<00:03, 48

then cannot go on...

**Comment by yi-jianfenghou** [comment]
多线程问题，后面加上--sp可运行。

**Comment by ariel415el** [comment]
HI, 
did you manage to fix this?
I have the same problem.. able to process only directories with very few images


Thanks
