### ISSUE TITLE
No error Message displayed

### ISSUE THREAD

**Issue by aashishsoni05** [MVIG-SJTU/AlphaPose#202]
Hello,
I have tried to implement the CPU version of AlphaPose (Pytorch). I am using Windows 10 as the OS and Anaconda environment. I did pretty much everything.
Changed "cuda() to cpu()" in all the directories as well as "CUDA=TRUE to CUDA=FALSE" in all the necessary files (generally, .py files). 

I have also installed all the necessary dependencies. Now when I try to run the model, I neither have an output nor an error message. 

what could be the possible solution to this?

**Comment by chetankm1992** [comment]
> Hello,
> I have tried to implement the CPU version of AlphaPose (Pytorch). I am using Windows 10 as the OS and Anaconda environment. I did pretty much everything.
> Changed "cuda() to cpu()" in all the directories as well as "CUDA=TRUE to CUDA=FALSE" in all the necessary files (generally, .py files).
> 
> I have also installed all the necessary dependencies. Now when I try to run the model, I neither have an output nor an error message.
> 
> what could be the possible solution to this?

I have the same issue.

**Comment by xiaoweiChen** [comment]
emmm... I think you can use python debugger check your script, first. And show something detail here. Or show your implemented script.

I haven't meet this. When I change all `cuda`  to `cpu`, and change the bool variable, the demo running very slow on my PC. My OS is Win10 and Pytorch 0.4.1.

**Comment by Fang-Haoshu** [comment]
@xiaoweiChen Thanks a lot! Could you please make a PR of cpu version? I think it can really help a lot.

**Comment by xiaoweiChen** [comment]
Well, I can do this. I will create the Pull Request at later time.
