### ISSUE TITLE
如何指定显卡运行

### ISSUE THREAD

**Issue by DeepBrainsMe** [MVIG-SJTU/AlphaPose#203]
你好，我有两张显卡，请问如何指定某一张显卡来运行程序呢？

**Comment by xiaoweiChen** [comment]
官方推荐用CUDA_VISIBLE_DEVICES这个环境变量来指定

可以参考下面地址中的内容：
https://discuss.pytorch.org/t/how-to-change-the-default-device-of-gpu-device-ids-0/1041

**Comment by chunklarry** [comment]
Add following code in demo.py, take GPU 1 as example.
```
import torch
torch.cuda.set_device(1)
```
or
```
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```

**Comment by IceTTTb** [comment]
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ‘0’  # ‘0，1’
