### ISSUE TITLE
python webcam_demo.py --vis failed. how can i avoid this ?

### ISSUE THREAD

**Issue by iwroldtan** [MVIG-SJTU/AlphaPose#205]
Traceback (most recent call last):
  File "webcam_demo.py", line 11, in <module>
    from dataloader_webcam import WebcamLoader, DetectionLoader, DetectionProcessor, DataWriter, crop_from_dets, Mscoco
  File "D:\AlphaPose\dataloader_webcam.py", line 7, in <module>
    from SPPE.src.utils.img import load_image, cropBox, im_to_torch
  File "D:\AlphaPose\SPPE\src\utils\img.py", line 269
    x = x.cuda(async=True)
                   ^
SyntaxError: invalid syntax

**Comment by ZeR0ll** [comment]
also run into this problem,I can install pytorch 0.4.0,so install pytorch 0.4.1, that may be the reason?

**Comment by iwroldtan** [comment]
> @ZeR0ll The error message is clear, this is a syntax error, have no relation with the pytorch version.
> 
> @iwroldtan Maybe, you do some modify leading this error.

I install AlphaPose follow the README.md. Did not modify anything! The Pytorch is ready for gpu.

**Comment by iwroldtan** [comment]
> also run into this problem,I can not install pytorch 0.4.0,so install pytorch 0.4.1, that may be the reason?

Have you run AlphaPose in your OS ? If you run well.  Share with me, please.

**Comment by xiaoweiChen** [comment]
`python3 demo.py --indir ${img_directory} --outdir examples/res ` this command will lead this error?

My environment is Win10 and Pytorch 0.4.1, demo running well.

**Comment by iwroldtan** [comment]
> `python3 demo.py --indir ${img_directory} --outdir examples/res ` this command will lead this error?
> 
> Make sure your python version.
> 
> My environment is Win10 and Pytorch 0.4.1, demo running well.

D:\AlphaPose>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from __future__ import print_function
>>> import torch
>>> x = torch.rand(5, 3)
>>> print(x)
tensor([[0.2762, 0.7214, 0.6547],
        [0.0372, 0.7130, 0.0999],
        [0.5160, 0.2023, 0.4847],
        [0.2998, 0.3513, 0.2312],
        [0.2725, 0.0701, 0.4293]])
>>> import torch
>>> torch.cuda.is_available()
True
>>> exit()

D:\AlphaPose>python demo.py --indir ${img_directory} --outdir examples/res
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from dataloader import ImageLoader, DetectionLoader, DetectionProcessor, DataWriter, Mscoco
  File "D:\AlphaPose\dataloader.py", line 7, in <module>
    from SPPE.src.utils.img import load_image, cropBox, im_to_torch
  File "D:\AlphaPose\SPPE\src\utils\img.py", line 269
    x = x.cuda(async=True)
                   ^
SyntaxError: invalid syntax

**Comment by iwroldtan** [comment]
> `python3 demo.py --indir ${img_directory} --outdir examples/res ` this command will lead this error?
> 
> Make sure your python version.
> 
> My environment is Win10 and Pytorch 0.4.1, demo running well.

modify the code,"x = x.cuda(async=True)" --> "x = x.cuda(True)"

**Comment by naeioi** [comment]
The root of this problem is that `async` becomes a reserved keyword in python3.7.
Ref: https://docs.python.org/3.7/reference/lexical_analysis.html#keywords

**Comment by xiaoweiChen** [comment]
@naeioi 
Wow! Before see you answer, I alway think 3.7 check carefully... :/

**Comment by stjamesmichael** [comment]
hi, I can't run alphapose project on my windows 10. 
I installed cuda 10.2 and add environment to path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin" and add dll file of intel-openmp-2018.0.3-0.tar to the bin path.
I used pytorch version 0.4.0
but error occured. error is following:
G:\work\python\AlphaPose>python webcam_demo.py --vis
Traceback (most recent call last):
  File "webcam_demo.py", line 11, in <module>
    from dataloader_webcam import WebcamLoader, DetectionLoader, DetectionProcessor, DataWriter, crop_from_dets, Mscoco
  File "G:\work\python\AlphaPose\dataloader_webcam.py", line 7, in <module>
    from SPPE.src.utils.img import load_image, cropBox, im_to_torch
  File "G:\work\python\AlphaPose\SPPE\src\utils\img.py", line 269
    x = x.cuda(async=True)
                   ^
SyntaxError: invalid syntax

Why this happened?
Please help me.
