### ISSUE TITLE
About AlphaPose based on Caffe

### ISSUE THREAD

**Issue by ZhongXiaoFang** [MVIG-SJTU/AlphaPose#206]
Hello　everyone !  
  I implement the caffe-based AlphaPose  according to the　AlphaPose network composition based on pytorch. and can train this caffe-based AlphaPose using COCO dataset.  but the result models can't detect person keypoints accurately .  It looks like detect randomly and no one keypoints is locatted in the person accurately.

I hope you can give me some advice to help me? or someone have implement the AlphaPose based on caffe can share experience．　please don't close this issue ,  thank you very much

**Comment by xiaoweiChen** [comment]
Could show your code or repo address?

**Comment by YuliangXiu** [comment]
maybe you can refer to this official implementation of [RMPE](https://github.com/MVIG-SJTU/RMPE), which is the predecessor of AlphaPose
