### ISSUE TITLE
when loading duc_se.pth, but it is killed.

### ISSUE THREAD

**Issue by pingqi** [MVIG-SJTU/AlphaPose#207]
Hi, when I test a video, it is killed during loading the   duc_se.pth.So, how can I do?Thanks.
python3 video_demo.py --video examples/video/00001.avi --outdir examples/res --save_video --sp
....../h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loading YOLO model..
....../torch/nn/modules/upsampling.py:122:UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
....../torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Loading pose model from ./models/sppe/duc_se.pth
  6%|##1                                 | 1364/22746 [18:58<4:57:23,  1.20it/s]Killed

**Comment by pingqi** [comment]
OOM

**Comment by DragonAndSky** [comment]
how to solved it ,i think my memory is enough

**Comment by DragonAndSky** [comment]
@pingqi
