### ISSUE TITLE
about the PoseFlow keypoints 

### ISSUE THREAD

**Issue by lianuo** [MVIG-SJTU/AlphaPose#208]
Hi~,Thanks for your solution.
I have a question about the tracking result.

after run the PoseFlow, I got the tracked keypoints with only 15 points. I found the new partsid is as follow, so id 6,7 were removed? 
rmpe_part_ids = [0, 1, 2, 3, 4, 5, 10, 11, 12, 13, 14, 15, 8, 9]

could you tell me why?
Thank you

**Comment by YuliangXiu** [comment]
This line was just used when doing the evaluation on PoseTrack dataset, cuz the keypoint order of PoseTrack dataset is different from alphapose's.

[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
