### ISSUE TITLE
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'

### ISSUE THREAD

**Issue by zcl912** [MVIG-SJTU/AlphaPose#211]
我在训练的时候，用的命令为python3 train.py --dataset coco --expID coco --nClasses 17 --LR 1e-4，
但是报以下错误：RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'

**Comment by zcl912** [comment]
问题已经解决

**Comment by shboy** [comment]
@zcl912 

> 问题已经解决

想问下是怎么解决的呢

**Comment by zcl912** [comment]
> 问题已经解决

出现这个问题的原因是torchsample中的类型不匹配，将torchsample中的数据类型改成一致的就行了
