### ISSUE TITLE
_deepmatching.so: undefined symbol: PyCObject_Type

### ISSUE THREAD

**Issue by pingqi** [MVIG-SJTU/AlphaPose#213]
hi,when I combine the deepmatching module,then there is an error.How to solve the problem below?I have done as follows:
make clean all
make python
python
import deepmatching

the problem is :
root@c479899290a0:/home/xxx/AlphaPose-pytorch/PoseFlow/deepmatching# python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepmatching
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/AlphaPose-pytorch/PoseFlow/deepmatching/deepmatching.py", line 32, in <module>
    _deepmatching = swig_import_helper()
  File "/home/xxx/AlphaPose-pytorch/PoseFlow/deepmatching/deepmatching.py", line 28, in swig_import_helper
    _mod = imp.load_module('_deepmatching', fp, pathname, description)
  File "/root/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/root/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/xxx/AlphaPose-pytorch/PoseFlow/deepmatching/_deepmatching.so: undefined symbol: PyCObject_Type

**Comment by pingqi** [comment]
There are two versions of python. So,CPYTHONFLAGS in Makefile do not match the python
cmd.

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
