### ISSUE TITLE
Open Source? License?

### ISSUE THREAD

**Issue by teaddicted** [MVIG-SJTU/AlphaPose#214]
Hey,

You've written that alphapose is open-source but the license says it's for non-commercial use only? which makes it Not-open-source according to:

-----------------
https://opensource.org/faq
Can Open Source software be used for commercial purposes?

Absolutely. All Open Source software can be used for commercial purpose; the Open Source Definition guarantees this. You can even sell Open Source software.

--------------

I'm just interested to know more about licensing of alphapose because I'm interested. Please can you let me know more about it?

Thanks.

**Comment by Fang-Haoshu** [comment]
Hi! Thanks for your interest. For commercial queries, please send an query email to lucewu@cs.sjtu.edu.cn and cc fhaoshu@gmail.com
