### ISSUE TITLE
Pytorch Pose Flow have no expect result

### ISSUE THREAD

**Issue by xiaoweiChen** [MVIG-SJTU/AlphaPose#215]
@YuliangXiu 

Thanks for porting the PoseFlow to pytorch.

I use AlphaPose on my video, and generate the json. 
Using the default json fromat.

While, the json format is not suitable for PoseFlow.
I add some code in `tracker-general.py`, like below:

```python
.....

# load json file without tracking information
    with open(notrack_json,'r') as f:
        notrack = json.load(f)
        
        # add by xiaowei
        if type(notrack) is list:
        
            new_notrack = {}
            
            for index in tqdm(range(len(notrack))):
            
                curInfo = notrack[index]
                img_name = curInfo['image_id']
                new_notrack[img_name] = []
                infoMap = {"score" : curInfo['score'], "keypoints": curInfo["keypoints"]}
                
            notrack = new_notrack
        # add by xiaowei
        
        for img_name in tqdm(sorted(notrack.keys())):
            track[img_name] = {'num_boxes':len(notrack[img_name])}
            for bid in range(len(notrack[img_name])):
                track[img_name][bid+1] = {}
                track[img_name][bid+1]['box_score'] = notrack[img_name][bid]['score']
                track[img_name][bid+1]['box_pos'] = get_box(notrack[img_name][bid]['keypoints'], os.path.join(image_dir,img_name))
                track[img_name][bid+1]['box_pose_pos'] = np.array(notrack[img_name][bid]['keypoints']).reshape(-1,3)[:,0:2]
                track[img_name][bid+1]['box_pose_score'] = np.array(notrack[img_name][bid]['keypoints']).reshape(-1,3)[:,-1]

.......
```

And I use ffmpeg split my video to pictures into a directory, which as the PoseFlow `--imgdir` option.

Then, the script is running well.

Emmm, I got output json like this....
```
    "102.jpg": [],
    "103.jpg": [],
    "104.jpg": [],
    "105.jpg": [],
    "106.jpg": [],
    "107.jpg": [],
    "108.jpg": [],
    "109.jpg": [],
    "110.jpg": [],
    "111.jpg": [],
    "112.jpg": [],
    "113.jpg": [],
```
All picture is empty list... I don't know the reason.

And in `--visdir`, the pictures is same as before.

So, could you give some suggest?  
Or, give your complete step for PoseFlow and add a simple PoseFlow demo into repo?

**Comment by YuliangXiu** [comment]
you only define the **infoMap** variable, but where do you use it?

you can refer to [general version](https://github.com/MVIG-SJTU/AlphaPose/tree/master/PoseFlow#for-any-datasets-general-version)to get final tracking results. you'd better use the estimated json file endswith -forvis, whose format is regular for next tracking process.

**Comment by YuliangXiu** [comment]
I have modified the [tracker-general.py](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/tracker-general.py#L116). Currently, you can run pose tracking successfully on alphapose estimation results generated by both pytorch version and torch version. The usage README has also been updated, please refer to [general version](https://github.com/MVIG-SJTU/AlphaPose/tree/master/PoseFlow#for-any-datasets-general-version).

**Comment by xiaoweiChen** [comment]
@YuliangXiu 

Thanks for your work. I update the code, the track function is working and generate the expect image.

the one of picture like below:
![1](https://user-images.githubusercontent.com/2756670/50335541-952b4000-0546-11e9-94d4-a534ced51c03.PNG)

And there is another problem. 

I merge the pictures into a video by ffmpeg. 
While, I found the Pose is not matching the picture...

May, I need your suggestes... again... :|

**Comment by YuliangXiu** [comment]
can you send me the image sequences to yuliangxiu@sjtu.edu.cn

**Comment by xiaoweiChen** [comment]
Well, I sent the detail for you.

**Comment by YuliangXiu** [comment]
I have replied to your email.

A better solution is to first convert video into frames with the help of ffmpeg and then use the demo.py to get alphapose-results.json. The default video-to-frames strategy of cv2.videocapture (video_demo.py) and ffmpeg may be different, which will result in unaligned image_ids.

**Comment by xiaoweiChen** [comment]
Thanks, I read your mail. And I'm trying the demo.py.

The image path in json is not friendly for Windows user. 
I change the `write_json` function in pPose_nms.py:
```python
            if for_eval:
                result['image_id'] = int(im_name.split('/')[-1].split('.')[0].split('_')[-1])
            else:
                result['image_id'] = im_name.split('/')[-1]
```
to
```python
            if for_eval:
                result['image_id'] = int(im_name.split(os.sep)[-1].split('.')[0].split('_')[-1])
            else:
                result['image_id'] = im_name.split(os.sep)[-1]
```
May, your working is under Linux or Mac OS, so use '/' to split path.
Use `os.sep` will prefect deal with the path issue.

I will update the result for tracking latter on.
