### ISSUE TITLE
pytorch 1.0

### ISSUE THREAD

**Issue by bloodymeli** [MVIG-SJTU/AlphaPose#216]
Hi,

It seems that running the code with pytorch 1.0 gives very different results from pytorch 0.4.1. 
For example, the accuracy metric for the trained model on pytorch 1.0 is ~0.5, while on pytorch 0.4.1 it is ~0.85. Can you please comment on that? How to transfer the code for 1.0?

**Comment by Fang-Haoshu** [comment]
Hi thanks. We are currently updating it to pytoch 1.0. Before that, I suggest using pytorch 0.4.0 for training.

**Comment by leonshek** [comment]
> Hi thanks. We are currently updating it to pytoch 1.0. Before that, I suggest using pytorch 0.4.0 for training.

@Fang-Haoshu how is the work of updating going? need your 1.0 pytorch version of alphapose.thx
