### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by zerostan** [MVIG-SJTU/AlphaPose#217]
刚接触姿态估计还是个新手，请问，在pytorch的版本中两个网络是分开训练（在检测的数据集上训练检测模型，在单人姿态估计的训练集上训练SPPE），还是在检测模型已经训练好的基础上结合检测去训练SPPE，我只看了pytorch版本的网络，里面没有看到训练的过程。

**Comment by Jeff-sjtu** [comment]
检测模型我们没有训练，是直接使用yolo3训练好的结果。SPPE模型的训练在`train_sppe`文件夹。

**Comment by zerostan** [comment]
所以SPPE网络的训练有没有关联到检测网络，还是它的训练过程是一个独立的分支，最后结合检测网络进行多人姿态估计？

**Comment by pingqi** [comment]
@zerostan 请问你有coco和mpii数据集的标注文件吗？

**Comment by zeroMrCc** [comment]
coco2017的数据集已经有了，没有mpii的数据集。

**Comment by pingqi** [comment]
@zeroMrCc    coco2017的数据集标注文件，能发我一份吗？我只需要标注文件，数据集是有了，我的邮箱是pingqi_123@163.com，我找不到，官网也不好下。
