### ISSUE TITLE
do not understand PosFlow 3X FASTER. What dose it compare with?

### ISSUE THREAD

**Issue by iwroldtan** [MVIG-SJTU/AlphaPose#219]

**Comment by YuliangXiu** [comment]
compare to the previous poseflow version using deepmatching

**Comment by yxchng** [comment]
@YuliangXiu Why don't you apply the optimization on the PyTorch's version and make it fast, rather than switching to Torch and Tensorflow?

**Comment by YuliangXiu** [comment]
We provided the pytorch version of alphapose @yxchng, please refer to readme

**Comment by yxchng** [comment]
你这里说alphapose（general版本）比pytorch版本快乐三倍。我的问题是为什么同样的优化不要在pytorch版本上做，而是换到了torch和tensorflow。有什么特别的原因吗？

**Comment by YuliangXiu** [comment]
@yxchng alphapose is a pose estimation framework, its results can be directly used in poseflow. 3x faster means the poseflow with orb is faster than poseflow with deepmatching, this speed does not consider the pose estimation process but only take pose trakcing time into consideration. poseflow is not based on pytorch, it contains no deep learning models, you can regard it as a pure module for tracking human poses cross frames.
