### ISSUE TITLE
新手提问，训练相关，CUDA内存溢出

### ISSUE THREAD

**Issue by hatsunemiku02** [MVIG-SJTU/AlphaPose#223]
文件"/data3/zhaohang/AP2/AlphaPose/train_sppe/src/evaluation.py", line 43, in <module>
    gaussian_kernel.cuda()
报错：RuntimeError: CUDA error: out of memory
测试print(torch.cuda.is_available())是true，请问这是什么原因

**Comment by hatsunemiku02** [comment]
还有个问题，训练数据集是 coco的train2017和val2017吗？

**Comment by xiaoweiChen** [comment]
把训练的batch改小就可以了
