### ISSUE TITLE
about the PoseFlow keypoints for posetrack dataset

### ISSUE THREAD

**Issue by lianuo** [MVIG-SJTU/AlphaPose#224]
@YuliangXiu 
Hi, I have a question about evalutaion for posetrack dataset
in alpha pose method , the key point have left and right eye ,but the ground truth of posetrack dataset is head top and head bottom ,how could we evaluate the result without the right position of head top and head bottom ?

**Comment by YuliangXiu** [comment]
you should use [MPII format](https://github.com/MVIG-SJTU/AlphaPose/blob/master/doc/output.md) as output format
