### ISSUE TITLE
cuda、cudnn版本

### ISSUE THREAD

**Issue by Xchangjiang** [MVIG-SJTU/AlphaPose#226]
请问所需要的cuda版本和cudnn版本是怎样的?

**Comment by xiaoweiChen** [comment]
就个人测试和训练来看，我用的是pytorch版本。
对于CUDA版本没有什么要求，只要和pytorch能匹配上就可以。

cuDNN需要禁用，因为网络中有BN层，cuDNN可能会导致训练不收敛的情况，具体如何去禁用在训练的readme里面有介绍。

**Comment by Xchangjiang** [comment]
不好意思说  补充一下  我问的是 torch版本

**Comment by qingfengmuye** [comment]
> 不好意思说 补充一下 我问的是 torch版本

pytorch 0.4 or 0.4.1

**Comment by leonshek** [comment]
doubi

**Comment by yudw15** [comment]
1.0.1.post2 is ok too
