### ISSUE TITLE
Discrepancy between pytorch branch and torch branch

### ISSUE THREAD

**Issue by bloodymeli** [MVIG-SJTU/AlphaPose#228]
Hi,

I have run a video file in the two branches and got very different results.
The inputs file is [here](https://www.dropbox.com/s/nsht3g5tf6wj6nn/Leg-raise1.mp4?dl=0).

The output file of the pytorch branch is [here](https://www.dropbox.com/s/5sr2qrshjfurcx1/AlphaPose_Leg-raise1.avi?dl=0).

The output file of the torch branch is [here](https://www.dropbox.com/s/us4gc0ij65rl82s/Leg-raise1-AP.mp4?dl=0)

Can you please comment on the difference?

**Comment by Fang-Haoshu** [comment]
Hi, these two branches are not expected to have the same results. The pytorch branch runs faster while the torch branch has a higher accuracy for now. You can choose a branch depends on your purpose.
