### ISSUE TITLE
About the keypoint neck or head buttom

### ISSUE THREAD

**Issue by lianuo** [MVIG-SJTU/AlphaPose#229]
@YuliangXiu  thanks for reply, I notice that the neck  keypoints in mpii format is calculate by the left and right shouder.but in pose track data set . the head buttom is not neck ,and have a distance to the middle point of left and right shouder.

so my question is ,does the Alphapose predict the heatmap of head bottom and headtop? or calculate these value from other keypoints?

Thank you~

**Comment by YuliangXiu** [comment]
@Jeff-sjtu

**Comment by Jeff-sjtu** [comment]
Alphapose have 33 channels of heatmaps(17coco + 16mpii), we now only take the first 17 channels, which didn't contain head and neck. Neck and head are in the last 16 channels.

**Comment by lianuo** [comment]
@Jeff-sjtu thank you , so I could get other 16mpii by modify the code of prediction.

**Comment by Jeff-sjtu** [comment]
Yes. :) @lianuo
