### ISSUE TITLE
run ./run.sh  error

### ISSUE THREAD

**Issue by dalewen** [MVIG-SJTU/AlphaPose#23]
/home/liutl/torch7/install/bin/luajit: /home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: module 'threads' not found:No LuaRocks module found for threads
	no field package.preload['threads']
	no file '/home/liutl/.luarocks/share/lua/5.1/threads.lua'
	no file '/home/liutl/.luarocks/share/lua/5.1/threads/init.lua'
	no file '/home/liutl/torch7/install/share/lua/5.1/threads.lua'
	no file '/home/liutl/torch7/install/share/lua/5.1/threads/init.lua'
	no file './threads.lua'
	no file '/home/liutl/torch7/install/share/luajit-2.1.0-beta1/threads.lua'
	no file '/usr/local/share/lua/5.1/threads.lua'
	no file '/usr/local/share/lua/5.1/threads/init.lua'
	no file '/home/wanggw/.luarocks/share/lua/5.1/threads.lua'
	no file '/home/wanggw/.luarocks/share/lua/5.1/threads/init.lua'
	no file '/home/liutl/.luarocks/lib/lua/5.1/threads.so'
	no file '/home/liutl/torch7/install/lib/lua/5.1/threads.so'
	no file './threads.so'
	no file '/usr/local/lib/lua/5.1/threads.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/wanggw/.luarocks/lib/lua/5.1/threads.so'
stack traceback:
	[C]: in function 'error'
	/home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main-alpha-pose.lua:1: in main chunk
	[C]: in function 'dofile'
	...utl/torch7/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406620
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/wanggw/Work/AlphaPose-master/AlphaPose-master/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/wanggw/Work/AlphaPose-master/AlphaPose-master/examples/results/POSE/alpha-pose-results-forvis.json'
wanggw@liutl:~/Work/AlphaPose-master/AlphaPose-master$

**Comment by Fang-Haoshu** [comment]
luarocks install threads

**Comment by dalewen** [comment]
/home/liutl/torch7/install/bin/luajit: /home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: /home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: /home/liutl/torch7/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH="/usr/local/cuda/lib64/libcudnn.so.5"

stack traceback:
	[C]: in function 'error'
	/home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	.../Work/AlphaPose-master/AlphaPose-master/predict/util.lua:12: in main chunk
	[C]: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...utl/torch7/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/wanggw/Work/AlphaPose-master/AlphaPose-master/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/wanggw/Work/AlphaPose-master/AlphaPose-master/examples/results/POSE/alpha-pose-results-forvis.json'
wanggw@liutl:~/Work/AlphaPose-master/AlphaPose-master$ 

 cuda  cuda-6.5  cuda-7.0  cuda-8.0  all can not find  libcudnn.so.5

**Comment by dalewen** [comment]
/home/liutl/torch7/install/bin/luajit: /home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: /home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: /home/liutl/torch7/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH="/usr/local/cuda/lib64/libcudnn.so.5"

stack traceback:
[C]: in function 'error'
/home/liutl/torch7/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
.../Work/AlphaPose-master/AlphaPose-master/predict/util.lua:12: in main chunk
[C]: in function 'dofile'
main-alpha-pose.lua:7: in main chunk
[C]: in function 'dofile'
...utl/torch7/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405d50
Traceback (most recent call last):
File "parametric-pose-nms-MPII.py", line 256, in 
get_result_json(args)
File "parametric-pose-nms-MPII.py", line 243, in get_result_json
test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in init
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/wanggw/Work/AlphaPose-master/AlphaPose-master/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
File "json-video.py", line 63, in 
with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/wanggw/Work/AlphaPose-master/AlphaPose-master/examples/results/POSE/alpha-pose-results-forvis.json'
wanggw@liutl:~/Work/AlphaPose-master/AlphaPose-master$

cuda cuda-6.5 cuda-7.0 cuda-8.0 all can not find libcudnn.so.5
