### ISSUE TITLE
speed too slow on cpu

### ISSUE THREAD

**Issue by lxy5513** [MVIG-SJTU/AlphaPose#230]
您好， 首先感谢能够开源！
请问一下，这个适合在移动设备上跑吗？我在cpu上跑比gpu上差远了，FPS超过1了。请问，在移动设备上、cpu上理论速度有多少？

**Comment by xiaoweiChen** [comment]
你可以看一下其backbone用的的网络，是SE-Resnet101，这是上交团队预训练好的，其大小有200+M。

如果你的移动端没有相应的硬件加速模块，那么不会跑的很快。
你可以计算一下网络所需要的算力，我估计的AlphaPose的在SE-Resnet 101为backbone的情况下好像是15Gfloats。
因为移动端的芯片主频和处理器数量不同，所以你需要根据你自己所要使用的进行评估。根据算力算出理论速度。

不过，在移动端，数据在总线上的传输也要消耗时间，就要看你具体所用的芯片总线带宽如何了。

**Comment by lxy5513** [comment]
大体明白了，非常感谢你的回答。

**Comment by lxy5513** [comment]
另外我想请问，为什么处理长视频速度要比处理短视频慢，例如我处理300frames以下的视频（单人）速度可以达到50+FPS，然而处理一个800frames的视频，速度只有20+FPS。  
具体来说是在运行过程中det time逐渐减慢。运行过程中det time从0.001逐渐涨到了0.01   

另外在webcam_demo.py中，det time一直是在0.01左右，请问正常吗？

**Comment by xiaoweiChen** [comment]
确定两个视频的分辨率是否一致。
还有就是Pose前接的人体检测，默认的是yolo3是否有很多误检。
这两个会影响到执行的速度。

webcam的我只是用来简单的运行过，并没有进行仔细的测试。

至于正不正常，你可以根据自己的经验做一下判断。
因为大家用的硬件不一定相同，所以在性能耗时方面不好给你一个所谓“正常”的参考。

**Comment by lxy5513** [comment]
我对同一个视频，处理速度越来越慢感到奇怪。   
 
请您看一下，这是我运行过程中的速度变化  
det time: 0.0013 | pose time: 0.0133 | post processing: 0.0045:  19%|█████████▏                                       | 155/828 [00:03<00:13, 48.54it/s

det time: 0.0089 | pose time: 0.0129 | post processing: 0.0060:  40%|███████████████████▊                             | 335/828 [00:09<00:19, 25.27it/s]

det time: 0.0128 | pose time: 0.0127 | post processing: 0.0068:  64%|███████████████████████████████▏                 | 527/828 [00:17<00:12, 24.92it/s]

det time: 0.0147 | pose time: 0.0127 | post processing: 0.0071:  87%|██████████████████████████████████████████▌      | 719/828 [00:25<00:04, 24.30it/s]

我不明白det time速度为什么变化这么大，另外我使用的配置如下
> torch Version: 0.4.0  
python Version:3.5.2 
GPU: 1080ti , memory: 12G

**Comment by xiaoweiChen** [comment]
profile这个选项我没有打开过，所以没有进行测试。
不过，根据你提供的信息，yolo检测的速度的确越来越慢了，这的确有些奇怪。
缩放到416x416的耗时应该每帧差不多，yolo3也是全图做检测，应该不会出现这种情况才对。

如果很在意的话，可以自己查一下代码。
我关注这个库主要是因为人体姿态估计，所以前端接的检测器我并不是太在意。
在检测方面，我就没办法给你更好的建议了，抱歉 ：/

**Comment by lxy5513** [comment]
好的，我自己研究研究，感谢你的答复。

**Comment by mstc-xqp** [comment]
> 您好， 首先感谢能够开源！
> 请问一下，这个适合在移动设备上跑吗？我在cpu上跑比gpu上差远了，FPS超过1了。请问，在移动设备上、cpu上理论速度有多少？

hi 你最后在嵌入式跑了吗  alphapose在cpu上怎么跑呢 defcon_conv 那些都要去掉把？
