### ISSUE TITLE
The problem with deepmatching，could you please give me some advices?

### ISSUE THREAD

**Issue by Tylerjoe** [MVIG-SJTU/AlphaPose#231]
When compile the pose track, it couldn't find the atlas, 
so I change the path to "LAPACKLDFLAGS=/usr/lib64/atlas/libtatlas.so  # multi-threaded blas".
After that , I followed the instruction：
make clean all.

There are some errors , 
std.h: In function ‘memswap’:
std.h:47:15: error: expected ‘)’ before ‘&’ token
     *((double*&)a)++ = *(double*)b;
               ^
std.h:47:19: error: lvalue required as increment operand
     *((double*&)a)++ = *(double*)b;
                   ^
std.h:48:15: error: expected ‘)’ before ‘&’ token
     *((double*&)b)++ = tmp;
               ^
std.h:48:19: error: lvalue required as increment operand
     *((double*&)b)++ = tmp;
                   ^
std.h:53:13: error: expected ‘)’ before ‘&’ token
     *((char*&)a)++ = *(char*)b;
             ^
std.h:53:17: error: lvalue required as increment operand
     *((char*&)a)++ = *(char*)b;
                 ^
std.h:54:13: error: expected ‘)’ before ‘&’ token
     *((char*&)b)++ = tmp;
             ^
std.h:54:17: error: lvalue required as increment operand
     *((char*&)b)++ = tmp;
                 ^
std.h: At top level:
std.h:62:1: error: unknown type name ‘bool’
 static inline bool ispowerof2( long n ) {
 ^
In file included from deep_matching.h:20:0,
                 from maxfilter.h:20:
pixel_desc.h:30:3: error: unknown type name ‘bool’
   bool norm_pixels;       // 1: normalize pixels separately / 0: normalize atomic patches
   ^
In file included from maxfilter.h:20:0:
deep_matching.h:23:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
In file included from deep_matching.h:20:0,
                 from io.h:22:
pixel_desc.h:30:3: error: unknown type name ‘bool’
   bool norm_pixels;       // 1: normalize pixels separately / 0: normalize atomic patches
   ^
In file included from io.h:22:0:
deep_matching.h:23:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
In file included from deep_matching.h:20:0,
                 from main.h:24:
pixel_desc.h:30:3: error: unknown type name ‘bool’
   bool norm_pixels;       // 1: normalize pixels separately / 0: normalize atomic patches
   ^
In file included from main.h:24:0:
deep_matching.h:23:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
pixel_desc.h:30:3: error: unknown type name ‘bool’
   bool norm_pixels;       // 1: normalize pixels separately / 0: normalize atomic patches
   ^
In file included from deep_matching.h:20:0,
                 from conv.h:20:
pixel_desc.h:30:3: error: unknown type name ‘bool’
   bool norm_pixels;       // 1: normalize pixels separately / 0: normalize atomic patches
   ^
In file included from conv.h:20:0:
deep_matching.h:23:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
In file included from deep_matching.h:20:0:
pixel_desc.h:30:3: error: unknown type name ‘bool’
   bool norm_pixels;       // 1: normalize pixels separately / 0: normalize atomic patches
   ^
deep_matching.h:23:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
make: *** [deepmatching] Error 1
could you please give some advice. Thanks sincerely.

**Comment by YuliangXiu** [comment]
#97
