### ISSUE TITLE
can you provide SE-Resnet50 pre-trained model please?

### ISSUE THREAD

**Issue by lilichu** [MVIG-SJTU/AlphaPose#232]
if I want to train my own dataset, I need SE-Resnet50 pre-trained model from imagenet. so can you provide SE-Resnet50 pre-trained model please?

**Comment by Jeff-sjtu** [comment]
Sorry, We don't have pre-trained SE-Resnet50 on imagenet.

**Comment by lilichu** [comment]
@Jeff-sjtu  thanks for your response. So you train sppe from scratch? When I want to train sppe such as:
`python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --trainBatch 8`
I need to train it from scratch?
thanks!

**Comment by Jeff-sjtu** [comment]
@lilichu You can load the weights of origin Resnet50 to SE-Resnet50 as its pre-trained weights.
