### ISSUE TITLE
Whether is it to export trained model to ONNX?

### ISSUE THREAD

**Issue by lxy5513** [MVIG-SJTU/AlphaPose#234]
Hi, I want use the model by mxnet? could you tell whether it is support to extport trained model to ONNX format ? if can, How to export ? Thank you very much .

**Comment by Fang-Haoshu** [comment]
Hi, thanks. We are currently also working on a mxnet version. But I do not know about the ONNX. Perhaps you can take a try! If you got any progress, we are also happy to hear your updates!

**Comment by learnermaxRL** [comment]
Hi @Fang-Haoshu  I am trying to create one single graph which can be transported to ONNX as a single model file ready for production.Can you tell me if you have any pointers to help me in this direction
