### ISSUE TITLE
Negative value keypoints

### ISSUE THREAD

**Issue by zviba** [MVIG-SJTU/AlphaPose#235]
Hi,

I am running AlphaPose and getting negative values for some keypoints, e.g.,  {"image_id": 33348_0.png", "category_id": 1, "keypoints": [72.549560546875, -0.05249999463558197, 0.00282743526622653....]}
 What is the meaning of the negative values?

Thanks,
Zvi

**Comment by Fang-Haoshu** [comment]
well, does the point locates at the edges?

**Comment by zviba** [comment]
Thank you for your reply! It is very much possible so since I used AlphaPose only on the bounding boxes and not on the whole frame. Will AlphaPose "guess" keypoints outside the image?

**Comment by Fang-Haoshu** [comment]
Yes, perhaps you can regard negative value as 0?
