### ISSUE TITLE
6e050eae5a076cf89884e9b6dd459bb7aa4f2431 have bugs

### ISSUE THREAD

**Issue by xiaoweiChen** [MVIG-SJTU/AlphaPose#237]
@Jeff-sjtu 
I base your 6e050eae5a076cf89884e9b6dd459bb7aa4f2431 commit find two error on Pytroch 0.4.0

-----

**operator error**

```
  File "/home/xiaowei/openSource/AlphaPose-offical/SPPE/src/utils/img.py", line 253, in cropBox
    pad_size = [(lenH - box_shape[0]) // 2, (lenW - box_shape[1]) // 2]
TypeError: unsupported operand type(s) for //: 'Tensor' and 'int'

```
May, the Pytorch 1.0.0 supported this operator for tensor.
While, I running under Pytorch 0.4.0 have error. 
`//` -> `/` will make the error gone.

-----

**image render error**

Solved the above error, when I save the images by demo. I find only one man pose has been drawn, the others is not.
I am not fix this issue, and find 6e050eae5a076cf89884e9b6dd459bb7aa4f2431 commit lead this.

The Result like below:
![2](https://user-images.githubusercontent.com/2756670/50819753-f71cdf80-1365-11e9-87b2-40c6ff367192.jpg)

---

**padding error?**

When I test video and webcam demo, I get this error.
```
  File "E:\openSourceProjecrts\AlphaPose-offical\SPPE\src\utils\img.py", line 258, in cropBox
    img[:, :ul[1], :], img[:, :, :ul[0]] = 0, 0
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)
```
I comment out the two lines:
```python
#img[:, :ul[1], :], img[:, :, :ul[0]] = 0, 0
#img[:, br[1] + 1:, :], img[:, :, br[0] + 1:] = 0, 0
```
This error is gone.

----

**Comment by Jeff-sjtu** [comment]
I'm sorry that the zero-indexing operation is not supported in 0.4.0, I'll fix this. :)
