### ISSUE TITLE
模型评测的问题

### ISSUE THREAD

**Issue by wangyarui** [MVIG-SJTU/AlphaPose#239]
你好，很高兴达成合作，首先，这个代码的opt部分写的太好了，很有调理。
我写了一个json2H5的脚本，把自己使用标注工具标注的一部分数据成功转换成了.h5格式，然后可以成功训练。把训练的模型model_6000.pth替换了原有的duc_se.pth代码，并调整了部分接口，运行demo和webcomDemo，可以有很好的结果检测结果。训练代码和demo很完整，但是，我想复现一下alphapose的mAP评测结果，运行了train_sppe中的evaluation，修改了接口对应了自己的数据，运行生成了一个Alphapose-results.json。通过已经训练模型得到输出和标注的结果做对比，得到的AP和AR都是1。。
这是第一个Alphapose-results.json，为什么说第一个呢，因为我发现运行demo.py选定文件夹，也可以生成同样的Alphapose-results.json（采用相同的图片，76张图片，包含288个标注数据），我发现这两个json文件的大小不一样，结果相差也很大，demo.py和evaluation.py得到的Alphapose-results.json有什么差别嘛？
谢谢！:0

**Comment by Jeff-sjtu** [comment]
你好，evaluation.py并不是对给定的76张照片进行预测，而是对模型在coco数据集上的一个简单评估。预测的话使用demo.py即可。

**Comment by wangyarui** [comment]
@Jeff-sjtu 感谢你很快答复，现在我们已经把它改成了在我们自己标注数据集上的评估，单个关键点的评估也是在这里对8？ 一直很好奇，代码网络模型中，DUC是什么的缩写？对整个COCO模型的评估，是采用demo跑整个coco数据集得到的Alphapose-results.json，然后调用eval.py中的getmap评估的对嘛？

**Comment by wangyarui** [comment]
@wangyarui 也许21号提问会少一些...感谢....

**Comment by Jeff-sjtu** [comment]
你好，得到json之后可以使用getmap评估。但是如果你是需要评估自己的数据集的话，需要对getmap函数作出修改，比如替换ground truth的json文件，以及更改imgList。

**Comment by wangyarui** [comment]
@Jeff-sjtu 已解决，谢谢　还有最后一个问题，就是今天看了以下demo.py运行出的数据，除了score字段的都很正确，但是score字段都是1.几和２.1,就去看了demo.py的代码，在pPose_nms.py中发现一段代码：
```
final_result.append({
            'keypoints': merge_pose - 0.3,
            'kp_score': merge_score,
            'proposal_score': torch.mean(merge_score) + bbox_scores_pick[j] + 1.25 * max(merge_score)
        })
```
请问是'proposal_score': torch.mean(merge_score) + bbox_scores_pick[j] + 1.25 * max(merge_score)　这个操作引起的嘛？（在训练我们自己的数据集时我们设定的关键点是１４个，代码里面和关键点个数相关的，也都已经作出了修改）还是其他代码proposal_score计算引起的？...训练的模型跑webcamDemo测试没问题，是想要的１４个关键点检测的结果，应该就是write_json()写入的问题..谢谢，求赐教丫

**Comment by Jeff-sjtu** [comment]
对的，proposals的分数是没有归一化的，此处可能会大于一

**Comment by wangyarui** [comment]
@Jeff-sjtu 不进行归一化不会影响getmap的测评结果对吧？
请问方便说一下归一化的位置吗？是下面这段代码嘛？原本想debug代码单步调试看结果的，debug不动测试用的电脑还特别卡。
```
proposal_score': torch.mean(merge_score) + bbox_scores_pick[j] + 1.25 * max(merge_score)
```
真心感谢你那么快回复我。嘻嘻　:)

**Comment by Jeff-sjtu** [comment]
不影响的，算mAP的时候是看分数的相对大小，所以是否归一化不影响最后的分数。此处对分数做了一个处理，使得相对分数更加准确。

**Comment by Cronusf** [comment]
你好，为什么我用模型跑出来的json文件和COCO数据集annotations里面person_keypoints_val2017.json大小不一样？一个15M左右，一个10M，评估的时候出现错误，提示结果不对应？应该怎样评估模型啊？求指导 @wangyarui  @Jeff-sjtu @YuliangXiu

**Comment by GuoHaiYang123** [comment]
我在运行evaluation.py时出现了以下的错误：
Traceback (most recent call last):
  File "F:/360Downloads/Alphapose/AlphaPose-pytorch/train_sppe/src/evaluation.py", line 13, in <module>
    from predict.opt import opt
  File "F:\360Downloads\Alphapose\AlphaPose-pytorch\train_sppe\src\predict\opt.py", line 1
    ../opt.py
    ^
SyntaxError: invalid syntax
不知道问题出在哪里 @wangyarui @Jeff-sjtu

**Comment by yangyuke001** [comment]
@wangyarui 请问你用的是什么标注工具呢?感谢!
