### ISSUE TITLE
./run.sh: line 78: th: command not found

### ISSUE THREAD

**Issue by winterwater** [MVIG-SJTU/AlphaPose#24]
hi,when I run this command  "./run.sh --indir examples/demo/ --outdir examples/results/ --vis" ,it returns the following error,I don't know what's the 'th' command mean,please give me some advice ,thanks 

the entire error information as follow:

pose estimation with RMPE...
./run.sh: line 78: th: command not found
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/zzy/work/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/zzy/work/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json

**Comment by Fang-Haoshu** [comment]
Hi, you need to install torch

**Comment by winterwater** [comment]
I have installed torch ,I will check it again,thanks

**Comment by Fang-Haoshu** [comment]
maybe it's not installed correctly or not added to the bashrc file. If it's installed correctly, th command should be able to run it.

**Comment by zhijian-liu** [comment]
Or maybe you have installed install torch. In this case, you should do `source ~/.bashrc` to make `th` command available (or you can restart a Terminal session).

**Comment by winterwater** [comment]
thanks ,it's ok ,but there is another problem ,init.lua:389: module 'hdf5' not found:No LuaRocks module found for hdf5, do I solve it with  this? "luarocks install hdf5"

**Comment by Fang-Haoshu** [comment]
exactly

**Comment by winterwater** [comment]
sorry,but I have another proplem,error as follow ,before all of these,I have this problem,"libcudnn.so.6: cannot open shared object file: No such file or directory",so I change my cudnn7.0 to 6.0,do I need to change it to cudnn5.0 now? I have installed cuda8.0,thanks

error infor:

home/zzy/torch/install/bin/luajit: /home/zzy/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zzy/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zzy/torch/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH="/usr/local/cuda/lib64/libcudnn.so.5"

**Comment by winterwater** [comment]
I have added cudnn5.0 to cuda ,that's ok .but I want to know the device requirements ,because it's out of memery now, crying.....anyway ,thanks so much ,have a good day

**Comment by Fang-Haoshu** [comment]
how about cudnn7.0. We are using cudnn7.0 on our server

**Comment by Fang-Haoshu** [comment]
if it oom, try to add flag: --batch 1

**Comment by winterwater** [comment]
using --batch 1 is ok ,thanks so much
