### ISSUE TITLE
跑demo的时候，测试图片是多人，但是检测结果只有一个人被检测到，这是什么问题呢？

### ISSUE THREAD

**Issue by KCHENPENGFEI** [MVIG-SJTU/AlphaPose#240]
![1](https://user-images.githubusercontent.com/30197452/50899873-5ce49680-144e-11e9-9030-a7907399afc8.jpg)
![2](https://user-images.githubusercontent.com/30197452/50899875-5f46f080-144e-11e9-9692-42b25c10b813.jpg)
![3](https://user-images.githubusercontent.com/30197452/50899876-6110b400-144e-11e9-825e-437df53ec126.jpg)

**Comment by xiaoweiChen** [comment]
用的也是pytorch 0.4.0么? 

这个是最新提交引入的bug，https://github.com/MVIG-SJTU/AlphaPose/issues/237 已经提交了。
上交的同学正在修复中。

**Comment by piaozhx** [comment]
我也遇到类似的问题了, 经过debug发现是预处理时候的问题, 
把[dataloader.py](https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/dataloader.py#L764)中的
```
inps[i] = cropBox(tmp_img, upLeft, bottomRight, opt.inputResH, opt.inputResW)
```
改为
```
inps[i] = cropBox(tmp_img.clone(), upLeft, bottomRight, opt.inputResH, opt.inputResW)
```

就可以正常运行了

**Comment by xiaoweiChen** [comment]
@piaozhx 你的方式的确能修复这个问题

**Comment by KCHENPENGFEI** [comment]
@piaozhx 我试试看

**Comment by KCHENPENGFEI** [comment]
@xiaoweiChen 我用的pytorch1.0

**Comment by xiaoweiChen** [comment]
@KCHENPENGFEI 目前pytorch分支估计对1.0.0支持的不是很好。
方便用webcam和video的demo进行一下测试么？看看在1.0.0下还有没有其他的问题。

**Comment by KCHENPENGFEI** [comment]
@xiaoweiChen 我测试了，1.0版本可以跑video的demo，并且也是可以检测出多人的，由于我没有显示器，webcam可能测试不了了

**Comment by xiaoweiChen** [comment]
@KCHENPENGFEI 好的，多谢啦！

**Comment by Fang-Haoshu** [comment]
bug fixed, thanks
