### ISSUE TITLE
can't debug for demo.py

### ISSUE THREAD

**Issue by lilichu** [MVIG-SJTU/AlphaPose#241]
**ubuntu
pycharm**
hi!  I can run demo.py successfully. But if I debug demo.py, it will stop at 
https://github.com/MVIG-SJTU/AlphaPose/blob/6e050eae5a076cf89884e9b6dd459bb7aa4f2431/demo.py#L45

could you please help me? thanks!

**Comment by xiaoweiChen** [comment]
you can see the dataloader.py.
The process create multi-process here.
May this is the reason for your issue.

**Comment by xiaoweiChen** [comment]
en, multiprocess is hard for debugging. You can use pdb, this like gdb, if you know that.

May this website can help you : https://www.jetbrains.com/help/pycharm/thread-concurrency-visualization.html

**Comment by zouxuelian** [comment]
> I added --sp to the demo.py and it uses single process to run the script and it's normal to debug, but multiprocessing still gets error.

how do--sp  add to demo.py
