### ISSUE TITLE
About 2d joint point format for alphapose output（conpare with OpenPose）

### ISSUE THREAD

**Issue by huanglai666** [MVIG-SJTU/AlphaPose#243]
Thank you for your excellent work. From the results of the paper, thanks to your work, mAP and fps have been greatly improved. We are trying to replace the openpose part of the original project with the alphapose implementation.
Before doing this, my question is that the input method used in our original project is to use each **2d joint point (x, y)** and **confidence scores C** as the input training network. Is the output format of alphapose the same as openpose? **I mean whether the number of skeleton joints output is equal to or more than the openpose project and whether it has the same ‘confidence scores’**
Congratulations again on getting such good results.Looking forward to your team's response

**Comment by Fang-Haoshu** [comment]
Hi, our output format can be the same as OpenPose. You can check our doc https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/doc/output.md for more details.
Having fun with AlphaPose!

**Comment by Vasanthengineer4949** [comment]
sir how to set the format flag
