### ISSUE TITLE
why speed so slow

### ISSUE THREAD

**Issue by jinfei3459** [MVIG-SJTU/AlphaPose#244]
`command:
python video_demo.py --video test-video/paidui.mp4 --outdir examples/res --save_video --sp --vis_fast
`
det time: 5.410 | pose time: 0.59 | post processing: 0.0626:  77%|████████████████████████████████████████▌            | 383/500 [38:43<11:49,  6.07s/it]

**Comment by learnermaxRL** [comment]
how?

**Comment by liubianting** [comment]
how to solve?

**Comment by YeHaijia** [comment]
how to solve?
