### ISSUE TITLE
I don't quite understand the framework of the pytorch training code.

### ISSUE THREAD

**Issue by hutao568** [MVIG-SJTU/AlphaPose#247]
Hello, thank you very much for the open source code .But,I don't quite understand the framework of the pytorch training code.In your paper, my understanding of AlphaPose is as follows. First enter an image, go through the human body detection, get a bounding box to be adjusted, then pass (STN + SPPE + SDTN) module and parallel (STN + SPPE) module which is used to help STN better adjust the parameters(I don't know if I understand this place correctly).Finally through the pose NMS module.This time forward propagation is complete.But in this repositories, I did not find the above process. I only saw the code for training single person pose estimation.

So,I want to know if there are other modules mentioned in your paper in your code?

**Comment by GerrieWell** [comment]
I have same question. Seem like pytorch version is different from paper implementation.
