### ISSUE TITLE
about SELayer

### ISSUE THREAD

**Issue by hutao568** [MVIG-SJTU/AlphaPose#248]
Hello, thank you very much for the open source code.After reading the sppe code of your pytorch version, I don't understand the SELayer module. In your AlphaPose/train_sppe/src/models/layers/SE_module.py, you used nn.AdaptiveAvgPool2d(1) for pooling.I don't quite understand why this is the case. In a traditional single-person pose estimation network, the output is generally a heat map and does not require a fully connected layer. So, can you tell me the purpose of SELayer?

**Comment by dekathomas** [comment]
Hello, have you got the answer of your question? Because I don't understand, too.
