### ISSUE TITLE
save separate json in pytroch version

### ISSUE THREAD

**Issue by JudyYe** [MVIG-SJTU/AlphaPose#249]
Hi, 

I found there is no save to separate flag in pytorch version. ('opt.py')
Does pytorch support save results to separate files? Or did I miss something? 

Thanks!

**Comment by xiaoweiChen** [comment]
`--outdir` can specify the output json file save directory. There is not for json file name option now.

**Comment by JudyYe** [comment]
Thanks for your quick reply. 
I am actually referring to `--sep` flag which saves each images to individual files instead of one big json. It is a useful feature for large data. But it seems pytorch does not support this yet?

**Comment by Fang-Haoshu** [comment]
Hi, try using --format cmu or --format open. You can refer to doc/output.md for more details.
