### ISSUE TITLE
Is SSTN used in the 'final_model.t7'?

### ISSUE THREAD

**Issue by YukiNagato** [MVIG-SJTU/AlphaPose#25]
I have read the paper about RMPE, in which symmetric spatial transformer network(SSTN) was used to enhance SPPE. However, i didn't find SSTN in the 'final_model.t7' when drawing the network graph using nngraph, so i wonder whether the SSTN is used in the final model?

**Comment by Fang-Haoshu** [comment]
Hi, it is not used in our torch model. We add a parallel SPPE when using the SSTN and it should be discarded during testing period. However, torch doesn't support loading part of the model during testing and this will affect our inference efficiency. Caffe supports loading part of the weights, thus you can find SSTN in our old repo: https://github.com/MVIG-SJTU/RMPE, which is implemented in Caffe

**Comment by KeyKy** [comment]
using the SSTN and it should be discarded during testing period. So discarded SSTN results to 1% AP drop?? Why do you discard SSTN? @Fang-Haoshu
