### ISSUE TITLE
How to generate the alphapose-results-forvis-tracked.json

### ISSUE THREAD

**Issue by wcy116** [MVIG-SJTU/AlphaPose#253]
Thanks for your excellent work and I meet two questions when I try to run the PoseFlow:
1. How to generate the 'alphapose-results-forvis-tracked.json', the args of out_json when I want to run 'tracker-general.py'? I can just get the 'alphapose-results.json' after running AlphaPose.
2. For PoseTrack dataset evaluation, I need to get the 'alpha-pose-results-val.json' first. And is it true that I have to find all the videos from val and use AlphaPose to run them separately, then write the results in a same json file, finally rename it 'alpha-pose-results-val.json'? Or are there any elegant ways?
Thank you very much.

**Comment by YuliangXiu** [comment]
alphapose-results-forvis-tracked.json is the output file but not input file of tracker-general.py. So you can only get it when you finish running tracker-general.py.

you can get the val datasets  according to the posetrack annotation files, and then you need to use alphapose to run them seperately, then write the results in  the same json file with the format like lpha-pose-results-sample.json

**Comment by hellozjj** [comment]
> alphapose-results-forvis-tracked.json

In the result output file alphapose-results-forvis-tracked.json, how does the joints ranking in key 'keypoints', and the unit of 'keypoints' for （x,y）is pixel?

**Comment by LeThuHien22** [comment]
yes, I dont understand why the image shape is (1080, 1920, 3) but the coordinate of elbow keypoint is (1967, 675). Please anwer my question. Thank you
