### ISSUE TITLE
Bug in opt.py causes --fast_inference False to have no effect

### ISSUE THREAD

**Issue by vtyw** [MVIG-SJTU/AlphaPose#255]
If you use --fast_inference False it gets set to True because of the reason pointed out [here](https://stackoverflow.com/questions/41655897/why-is-argparse-not-parsing-my-boolean-flag-correctly?noredirect=1&lq=1) and [here](https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse/19233287).

**Comment by KCHENPENGFEI** [comment]
You can replace the "type=bool" with "type=ast.literal_eval". And don't forget to "import ast", maybe can help you.

**Comment by Fang-Haoshu** [comment]
Hi, you are right. But "--fast_inference" is False by default, thus you do not need to set it.

**Comment by vtyw** [comment]
But it's set to True by default.
