### ISSUE TITLE
关于训练和测试时nClasses不匹配问题

### ISSUE THREAD

**Issue by KCHENPENGFEI** [MVIG-SJTU/AlphaPose#256]
train_sppe中的opt.py文件中nClasses默认值是17，也就是说coco数据集中17个关键点，但是在测试时的opt.py中nClasses是33，并且我看了你们提供的训练好的模型，最后一层的输出channel也是33，所以想问一下，最后一层输出channel到底是33还是17？

**Comment by xiaoweiChen** [comment]
使用上交同学预训练好的模型输出是33个，前17个是coco的，后16个是mpii的。默认应该是输出coco的结果，在代码中会将后16个结果舍弃，然后用前17个来推算关键点的位置。
如果你要自己训练的话，这里就根据你所使用的数据集来了

**Comment by qazzombie** [comment]
您好，您自己有训练模型吗，自己训练的模型可以用吗

**Comment by KCHENPENGFEI** [comment]
@qazzombie 可以自己训练，但是效果没有很好

**Comment by qazzombie** [comment]
您就是直接训练，然后拿过去用的是吗，那您除了改了classes的数量之外还改了哪里吗，因为我自己训练的模型用不了，根本找不到关键点。我感觉作者代码是不是少给了，因为论文里说的有一个并行的SPPE用来训练的好像都没有

**Comment by KCHENPENGFEI** [comment]
代码的部分我基本上没有改，我也觉得少给了一些代码，我训练跑出来map最高只有40多，我现在在对着原文仔细再看一次代码。


原始邮件
发件人:qazzombienotifications@github.com
收件人:MVIG-SJTU/AlphaPoseAlphaPose@noreply.github.com
抄送:Kchenchen_gs@zju.edu.cn; Authorauthor@noreply.github.com
发送时间:2019年4月18日(周四) 09:48
主题:Re: [MVIG-SJTU/AlphaPose] 关于训练和测试时nClasses不匹配问题 (#256)


您就是直接训练，然后拿过去用的是吗，那您除了改了classes的数量之外还改了哪里吗，因为我自己训练的模型用不了，根本找不到关键点。我感觉作者代码是不是少给了，因为论文里说的有一个并行的SPPE用来训练的好像都没有

**Comment by qazzombie** [comment]
我是代码基本看完了，除了他们自己论文里提出来的那个posenms，但是最后发现真的就是自己训练的模型没有出效果，想问一下您是只改了那个channel吧

**Comment by KCHENPENGFEI** [comment]
对的，就是改了最后一层输出的数量


原始邮件
发件人:qazzombienotifications@github.com
收件人:MVIG-SJTU/AlphaPoseAlphaPose@noreply.github.com
抄送:Kchenchen_gs@zju.edu.cn; Authorauthor@noreply.github.com
发送时间:2019年4月18日(周四) 10:02
主题:Re: [MVIG-SJTU/AlphaPose] 关于训练和测试时nClasses不匹配问题 (#256)


我是代码基本看完了，除了他们自己论文里提出来的那个posenms，但是最后发现真的就是自己训练的模型没有出效果，想问一下您是只改了那个channel吧

**Comment by qazzombie** [comment]
那您训练的时候有设置什么参数吗，真的是想不明白为啥我的会没有效果，您的至少还有效果

**Comment by KCHENPENGFEI** [comment]
@qazzombie 训练次数太少了吧，lr不要太大

**Comment by qazzombie** [comment]
我这个训练次数和lr都是按照他的来，没有改变，您是改了吗，我改一下参数试试

**Comment by qazzombie** [comment]
我发现一个问题就是从他的H5文件里读出来的图片很多是重复的，读10张只有三张是不一样的，读20张，有十张是重复的，这个应该对训练的结果影响很大吧，所以我真的很好奇为啥你们可以出结果

**Comment by KCHENPENGFEI** [comment]
h5里面读出来的是bbox，同一张图里面如果有多个人就会由多个bbox，所以这个是没有问题的

**Comment by liuchanfeng165** [comment]
> h5里面读出来的是bbox，同一张图里面如果有多个人就会由多个bbox，所以这个是没有问题
@KCHENPENGFEI 
同学，你是怎么训练出yolov3的权重呢，我训练得到pth文件，但怎么转yolov3的呢

**Comment by KCHENPENGFEI** [comment]
@liuchanfeng165 前面检测人的那部分我没有训练，直接拿的现成的模型

**Comment by qazzombie** [comment]
对了，您保存的权重文件是pkl格式的吗还是pth格式的呢，因为我改了训练次数什么的还是没有效果。我是把权重文件的格式改成了pth的了，原代码中是pkl的。

**Comment by KCHENPENGFEI** [comment]
@qazzombie 这两个没有什么区别，都可以的

**Comment by qazzombie** [comment]
> @qazzombie 这两个没有什么区别，都可以的

不是吧，我之前是保存成pkl的但是运行不了。。。所以才改成pth的，主要是我怎么训练都没有效果，我快要丧心病狂了什么都要怀疑下
