### ISSUE TITLE
some video can run,but some occur error

### ISSUE THREAD

**Issue by jinfei3459** [MVIG-SJTU/AlphaPose#257]
发现我用视频来运行video_demo.py有的视频会报错，而且错误还不一样
 `运行这个视频的时候`python video_demo.py --video test-video/103000.mp4 --outdir examples/res --save_video --sp --vis_fast`
就发生了下面这个错误
`Loading pose model from ./models/sppe/duc_se.pth
73 22497
det time: 0.011 | pose time: 0.06 | post processing: 0.0025:   1%|▏                           | 174/22497 [00:13<28:16, 13.16it/s]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch/dataloader.py", line 461, in update
    inps, pt1, pt2 = crop_from_dets(inp, boxes, inps, pt1, pt2)
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch/dataloader.py", line 832, in crop_from_dets
    opt.inputResH, opt.inputResW)
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch/SPPE/src/utils/img.py", line 258, in cropBox
    img[:, :ul[1], :], img[:, :, :ul[0]] = 0, 0
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)

det time: 0.011 | pose time: 0.06 | post processing: 0.0025:   1%|▏                         | 174/22497 [00:30<1:04:08,  5.80it/s]`

当我换另一个视频的时候`python video_demo.py --video test-video/080000.mp4 --outdir examples/res --save_video --sp --vis_fast`
会报下面这个错
`/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
[h264 @ 0x2449720] corrupted macroblock 13 15 (total_coeff=-1)
[h264 @ 0x2449720] error while decoding MB 13 15
Loading YOLO model..
[h264 @ 0x7f2818002e40] corrupted macroblock 13 15 (total_coeff=-1)
[h264 @ 0x7f2818002e40] error while decoding MB 13 15
Loading pose model from ./models/sppe/duc_se.pth
[mpeg4 @ 0x31d0de0] The encoder timebase is not set.
Could not open codec 'mpeg4': Unspecified error
Traceback (most recent call last):
  File "video_demo.py", line 76, in <module>
    cv2.VideoWriter_fourcc(*'XVID'), fps, frameSize).start()
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch/dataloader.py", line 676, in __init__
    assert self.stream.isOpened(), 'Cannot open video for writing'
AssertionError: Cannot open video for writing
`

**Comment by Jeff-sjtu** [comment]
你好，第一个问题已经在新的commit中修复了。

**Comment by xiaoweiChen** [comment]
第二个问题很明显是操作问题：
```
assert self.stream.isOpened(), 'Cannot open video for writing'
AssertionError: Cannot open video for writing
```
对应的视频流已经打开，无法进行写入。
