### ISSUE TITLE
Installing and running on Mac with CPU

### ISSUE THREAD

**Issue by edrdos101** [MVIG-SJTU/AlphaPose#258]
I'm trying to run the demo on my Mac which doesn't have a CUDA-compatible GPU. As I went through different installation steps, I kept bumping into various missing cuda dependencies and had to get rid of them by simply commenting the relevant cuda mentions (as was mentioned by users in other threads)

Unfortunately, I don't think this is just a matter of removing all `.cuda()`, `CUDA = TRUE` and `load_cuda()` commands as there are other issues that I don't think can be fixed by simply ignoring the GPU.

For example, while running the run.sh file I get this:
`module 'cunn' not found:No LuaRocks module found for cunn`

Upon trying to install `cunn` I obviously run into issues installing `cutorch` as it relies on the `nvcc`

I would really like to know if there's something that can be done about CUDA without just going and deleting every mention of it - this just doesn't feel like a sustainable solution

**Comment by xiaoweiChen** [comment]
The pytorch resolution:
https://github.com/MVIG-SJTU/AlphaPose/issues/116#issuecomment-422239346
