### ISSUE TITLE
Unsupported HDF5 version: 1.10.1

### ISSUE THREAD

**Issue by chenxu31** [MVIG-SJTU/AlphaPose#26]
I tried to run the demo and got the following errors:

--------------------------------------------------------------------------------------------------------
generating bbox from Faster RCNN...
2018-02-27 20:27:32.093717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:938] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 11.20GiB
Free memory: 11.13GiB
2018-02-27 20:27:32.093935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:959] DMA: 0
2018-02-27 20:27:32.093947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:969] 0:   Y
2018-02-27 20:27:32.093960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1028] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:06:00.0)
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/xxx/github/AlphaPose/examples/demo/

100%|█████████████████████████████████████████████████████████████████████████| 3/3 [00:06<00:00,  2.25s/it]
pose estimation with RMPE...
/usr/local/common/distro/install/bin/lua: ...l/common/distro/install/share/lua/5.1/trepl/init.lua:389: ...cal/common/distro/install/share/lua/5.1/hdf5/ffi.lua:71: Unsupported HDF5 version: 1.10.1
stack traceback:
        [C]: in function 'error'
        ...l/common/distro/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        /home/xxx/github/AlphaPose/predict/util.lua:7: in main chunk
        [C]: in function 'dofile'
        ...l/common/distro/install/share/lua/5.1/paths/init.lua:84: in function 'dofile'
        main-alpha-pose.lua:7: in main chunk
        [C]: in function 'dofile'
        ...distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/xxx/github/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/xxx/github/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'
--------------------------------------------------------------------------------------------------------

It seems like a version compatability problem.
However, I am not familiar with LUA.
Could you kindly give me some advice?

**Comment by Fang-Haoshu** [comment]
maybe try
sudo apt-get install libhdf5-serial-dev
luarocks install hdf5


What OS are u using?

**Comment by chenxu31** [comment]
CentOS 7.3.
I installed libhdf5 by "yum install hdf5-devel" and then "luarocks install hdf5".

**Comment by Fang-Haoshu** [comment]
How about upgrade the version of HDF5? I am using Ubuntu and not sure what HDF5 version you should use...

**Comment by Fang-Haoshu** [comment]
You can try google the instructions for installing torch on CentOS and see what HDF5 you can use

**Comment by chenxu31** [comment]
Well, maybe I should try to downgrade the version of HDF5 instead of upgrading it？
Since the source codes in where the error occurs ("distro/install/share/lua/5.1/hdf5/ffi.lua:71") are as follows:
------------------------------------------------------------------
if maj[0] ~= 1 or min[0] ~= 8 then
    error("Unsupported HDF5 version: " .. maj[0] .. "." .. min[0] .. "." .. rel[0])
end
hdf5.version = {tonumber(maj[0]), tonumber(min[0]), tonumber(rel[0])}
---------------------------------------------------------------------

Am I right?

**Comment by Fang-Haoshu** [comment]
Not sure what maj[0] and min[0] refer to here. You can add a  print(maj[0]) here and see whether you should upgrade or downgrade

**Comment by chenxu31** [comment]
Thanks, I have fixed the problem.
In fact, there are two HDF5s on my server, one from yum (v1.8.12) and the other from anaconda (v1.10.1).
I just reinstall the hdf5 in anaconda by specifying the version to be 1.8.13 (since v1.8.12 is unavailable in anaconda), then everything seems ok now.

**Comment by Fang-Haoshu** [comment]
Cool

**Comment by ZhangYK124** [comment]
hello,I have same problems, 
and i am using Ubuntu18.04,
what should i do?
Could you kindly give me some advice?
