### ISSUE TITLE
Segmentation fault: 11 when running video_demo

### ISSUE THREAD

**Issue by edrdos101** [MVIG-SJTU/AlphaPose#260]
I run a pytorch version on a Mac Mojave with Python 3.7 and get the following error half-way through the video processing:

```
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
  0%|                                                   | 0/138 [00:00<?, ?it/s]/usr/local/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
  8%|███▎                                      | 11/138 [03:11<30:22, 14.35s/it]

Segmentation fault: 11

```

The command line is as follows: 

`$ python3 video_demo.py --video examples/Video/snatch.mp4   --outdir examples/res --save_video --sp`

**Comment by edrdos101** [comment]
Should also note that I still get rendered output, just not the whole video

**Comment by xiaoweiChen** [comment]
May, you can try to loacte this error and show the git commit information to development team.
"Segmentation fault: 11" only on Mac, strict for memory usage, so if there have no Apple device your issue can not reproduce.

**Comment by ironllamagirl** [comment]
Did you find a solution to this? I am getting the same error running on ubuntu 18 

Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
  0%|                                                                                                                    | 0/700 [00:00<?, ?it/s]/home/SIC/hessefi/venv/AlphaPose/virenv/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
  1%|▊                                                                                                           | 5/700 [00:07<17:17,  1.49s/it]
Segmentation fault (core dumped)


`

**Comment by civilpat** [comment]
> Did you find a solution to this? I am getting the same error running on ubuntu 18
> 
> Loading YOLO model..
> Loading pose model from ./models/sppe/duc_se.pth
> 0%| | 0/700 [00:00<?, ?it/s]/home/SIC/hessefi/venv/AlphaPose/virenv/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
> warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
> 1%|▊ | 5/700 [00:07<17:17, 1.49s/it]
> Segmentation fault (core dumped)
> 
> `



> Did you find a solution to this? I am getting the same error running on ubuntu 18
> 
> Loading YOLO model..
> Loading pose model from ./models/sppe/duc_se.pth
> 0%| | 0/700 [00:00<?, ?it/s]/home/SIC/hessefi/venv/AlphaPose/virenv/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
> warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
> 1%|▊ | 5/700 [00:07<17:17, 1.49s/it]
> Segmentation fault (core dumped)
> 
> `

Hi, did you find the solution? I encountered the same problem but without too much information shown in terminal. I have output in json file but not images. Detail is as follows: 

Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
100%|████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 10.08it/s]
===========================> Finish Model Running.
Segmentation fault (core dumped)

**Comment by fiass** [comment]
hi, me have this problem 
File "webcam_demo.py", line 55, in <module>
    pose_model = InferenNet_fast(4 * 1 + 1, pose_dataset)
  File "C:\Users\Fiass\Desktop\CamFB\AlphaPose-pytorch\SPPE\src\main_fast_inference.py", line 61, in __init__
    model.load_state_dict(torch.load('./models/sppe/duc_se.pth'))
  File "C:\Users\Fiass\Anaconda3\lib\site-packages\torch\serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './models/sppe/duc_se.pth'

**Comment by thancaocuong** [comment]
@fiass you need to download sppe pretrained(named duc_se.pth) and place it into ./models/sppe directory. It will work

**Comment by thancaocuong** [comment]
@civilpat  you check the DataWriter class in dataloader.py. It append the result to final_result. So when you run video_demo with large file. It will run out of memory. so you will get core dump. Moever, you need to check queue size of detection_loader and det_processor to fit with your hardware. when too many frames in queue, It will run into "core dump".
