### ISSUE TITLE
fatal: repository 'https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/' not found

### ISSUE THREAD

**Issue by StatML** [MVIG-SJTU/AlphaPose#265]
Hi, when I clone the pytorch repo, I met the following issue :(

`git clone https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch`

> Cloning into 'alphapose-pytorch-git'...
> fatal: repository 'https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/' not found

**Comment by Fang-Haoshu** [comment]
you should clone alphapose and then check out to branch pytorch.
