### ISSUE TITLE
luarocks install hdf5报错

### ISSUE THREAD

**Issue by fwanghuan** [MVIG-SJTU/AlphaPose#268]
下载了最新版本的Alphapose按照教程进行安装，但是在用脚本安装hdf5时报错如下：

root@ck-service:/working/source/ai/alphapose/AlphaPose# ./install.sh 
Requirement already satisfied: easydict in /usr/local/lib/python3.6/dist-packages (1.9)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (4.29.1)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (4.0.0.21)
Requirement already satisfied: numpy>=1.11.3 in /usr/local/lib/python3.6/dist-packages (from opencv-python) (1.16.0)
Requirement already satisfied: h5py in /root/.local/lib/python3.6/site-packages (2.9.0)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.6/dist-packages (from h5py) (1.16.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from h5py) (1.10.0)
Installing https://rocks.moonscript.org/hdf5-2.0.0-1.src.rock...
Using https://rocks.moonscript.org/hdf5-2.0.0-1.src.rock... switching to 'build' mode
Warning: variable CFLAGS was not passed in build_variables
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/gcc'
gcc -c -o gcclua.o -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include -fPIC -xc++  -O2 -Wall -Wformat-security -I/usr/include/lua5.2 gcclua.c
gcc -o gcclua.so gcclua.o -shared -Wl,-s -Wl,--as-needed -llua5.2
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/gcc'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/test'
gcc -S -std=c99 -Wall -pedantic -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/test/../gcc/gcclua.so -fplugin-arg-gcclua-script=event.lua ./event.c
gcc -S -std=c99 -Wall -pedantic -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/test/../gcc/gcclua.so -fplugin-arg-gcclua-script=globals.lua ./globals.c
gcc -S -std=c99 -Wall -pedantic -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/test/../gcc/gcclua.so -fplugin-arg-gcclua-script=tree.lua ./tree.c
gcc -S -std=c++98 -Wall -pedantic -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/test/../gcc/gcclua.so -fplugin-arg-gcclua-script=tree-cp.lua ./tree-cp.cxx
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua/test'
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua'
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test'
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=array.lua array.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=composite.lua composite.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=enum.lua enum.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=function.lua function.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=pointer.lua pointer.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=scalar.lua scalar.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=variable.lua variable.c
gcc -S -std=gnu99 -Wall -fplugin=/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test/../../gcc-lua/gcc/gcclua.so -fplugin-arg-gcclua-script=vector.lua vector.c
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl/test'
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/gcc-lua-cdecl'
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/hdf5'
cc1: fatal error: H5pubconf.h: 没有那个文件或目录
compilation terminated.
gcc -E -o C.i -I/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/hdf5/../gcc-lua-cdecl/ffi-cdecl C.c
C.c:11:18: fatal error: hdf5.h: 没有那个文件或目录
compilation terminated.
Makefile:33: recipe for target 'C.i' failed
make[1]: *** [C.i] Error 1
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-1506/lua-hdf5/hdf5'
Makefile:44: recipe for target 'hdf5' failed
make: *** [hdf5] Error 2

Error: Build error: Failed building.

**Comment by fwanghuan** [comment]
问题已经解决，忘记安装torch了。

**Comment by liudatutu** [comment]
@fwanghuan 我安装了torch7，和你报错的一样啊

**Comment by AishuaiYao** [comment]
我出现了同样的问题，急急急
