### ISSUE TITLE
RuntimeError:CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by cocolixiao** [MVIG-SJTU/AlphaPose#269]
* CUDA 9.0
* pytorch 0.4.0
* windows
* python 3.6
when i run python demo.py --indir examples/demo/ --outdir examples/results/ --save_img --sp，i got cuda error.

**Comment by cocolixiao** [comment]
solved

**Comment by jejay** [comment]
can I ask you how you solved it?
