### ISSUE TITLE
求助！！运行中的一些问题

### ISSUE THREAD

**Issue by yyyyyff** [MVIG-SJTU/AlphaPose#272]
您好！ 我的电脑是windows10, cuda9.2, pytorch0.4.1, python3.6
请问要到哪里查看检测后的图片呢？ 我按照您的说明运行程序后，example/res文件夹里有一个.json文件和一个vis文件夹，但是vis文件夹是空的。。。 我运行的代码如下
hp@pc MINGW64 /d/AlphaPose-pytorch/AlphaPose-pytorch                             
$ python demo.py --indir examples/demo --outdir examples/res --save_img --sp --p osebatch 10 --vis                                                                Loading YOLO model..                                                             
**D:\Anaconda3\lib\site-packages\torch\nn\modules\upsampling.py:122: UserWarning:  nn.Upsampling is deprecated. Use nn.functional.interpolate instead.               
 warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate inst ead.")**                                                                           Loading pose model from ./models/sppe/duc_se.pth                                 100%\|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒\| 2/2 [00:02<00:00,  1.28s/it]                          ===========================> Finish Model Running.                               ===========================> Rendering remaining images in the queue...          ===========================> If this step takes too long, you can enable the --v is_fast flag to use fast rendering (real-time).
--
此外，运行时会出现如上所示的 warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate inst ead.，请问这是因为什么呢？会影响结果吗？怎么能使它不报这个warning呢？
最后，如果要检测视频，视频需要什么格式呢？mp4吗？
特别需要您的回答QAQ感谢~！！

**Comment by xiaoweiChen** [comment]
你这个运行没问题，warning是因为0.4.0和0.4.1的差别。
你要用视频的话，要用webcam_demo.py。
建议仔细看一下pytorch分支的ReadMe。

**Comment by yyyyyff** [comment]
好的好的谢谢！
那我该到哪里查看检测后的图片呢？？
我试了
python demo.py --list examples/list-coco-demo.txt --indir examples/demo --outd ir examples/res --save_img --sp --posebatch 10 --vis
也试了
$ python demo.py --indir examples/demo --outdir examples/res --save_img --sp --p osebatch 10 --vis
但将文件翻了个遍也没有找到检测结果图像。

**Comment by xiaoweiChen** [comment]
examples/res 这个下面应该有个vis文件夹吧。结果都保存在里面

**Comment by yyyyyff** [comment]
嗯嗯有vis文件夹，但是这个文件夹是空的呢。只有.json文件里是有内容的。
您看是不是我输入的命令有问题呢QAQ

**Comment by xiaoweiChen** [comment]
我运行的时候没有加 --p osebatch 10 这个，你可以去掉试试看

**Comment by yyyyyff** [comment]
试了一下去掉--posebatch 10
vis里还是空的。。。(╥╯^╰╥)

**Comment by xiaoweiChen** [comment]
你加了--vis选项，有图像显示出来么？

**Comment by yyyyyff** [comment]
嗯嗯有图像显示出来，但是是那种 显示一下就马上消失了的那种

**Comment by xiaoweiChen** [comment]
因为显示的停顿只有30ms，所以感觉就是闪一下。
调试一下代码吧，看看到底哪里的问题，自己尝试定位一下。
dataloader.py的DataWriter类，就是用来保存和显示结果图片的。

**Comment by yyyyyff** [comment]
好的我试试
谢谢您~！

**Comment by leidawt** [comment]
@yyyyyff 请问解决了吗？

**Comment by 363325971** [comment]
为什么现在运行demo需要coco数据集，不然ops里会报错

  Traceback (most recent call last):
    File "C:\Users\Administrator\eclipse-workspace\AlphaPose-mxnet\demo.py", line 5, in <module>
      from opt import opt
    File "C:\Users\Administrator\eclipse-workspace\AlphaPose-mxnet\opt.py", line 129, in <module>
      os.mkdir("./exp/{}".format(opt.dataset))
  FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './exp/coco'

**Comment by GuoHaiYang123** [comment]
我也遇到类似的情况，不过我发现，如果仅仅对一张图片进行处理，那么在vis文件夹下确实会出现不显示处理后的图片的情况，不过如果是对几张图片一起处理时就基本不会出现这种状况，另外对多张图片进行处理时使用--vis_fast能加快处理速度

**Comment by haohao-hu** [comment]
找到原因了：是path的问题：将dataloader.py第680行
cv2.imwrite(os.path.join(opt.outputpath, 'vis', im_name), img)
改为这个：
cv2.imwrite(os.path.join(opt.outputpath, 'vis', os.path.basename(im_name)), img)
