### ISSUE TITLE
关于数据集问题

### ISSUE THREAD

**Issue by chenxp106** [MVIG-SJTU/AlphaPose#274]
您好，我在用torch训练时。在您放的链接里下载了annot_coco.h5和person_keypoints_val2014.json，但是训练的图片要2017年的，这个会不会跟2014的对不上
|-- src
|-- exp
|-- data
`-- |-- coco
    `-- |-- annot_coco.h5
        |-- person_keypoints_val2014.json
        `-- images
            |-- trainval2017
            |   |-- 000000000001.jpg
            |   |-- 000000000002.jpg
            |   |-- 000000000003.jpg
            |   |-- ...

**Comment by yudw15** [comment]
不会，那个json文件好像用不上

**Comment by 2429581027** [comment]
您好，我想问下trainval2017是什么呢，我只有train2017、val2017和test2017
