### ISSUE TITLE
您好，自己训练后的模型，跑demo出错，这是什么问题呢

### ISSUE THREAD

**Issue by chenxp106** [MVIG-SJTU/AlphaPose#276]
$ python demo.py --indir img --outdir examples/res --save_img
Loading YOLO model..
/home/manager/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/home/manager/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Loading pose model from ./models/sppe/duc_se.pth
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    pose_model = InferenNet_fast(4 * 1 + 1, pose_dataset)
  File "/home/manager/cxp/code/torch/AlphaPose-pytorch/SPPE/src/main_fast_inference.py", line 63, in __init__
    model.load_state_dict(torch.load('./models/sppe/model_0.pkl'))
  File "/home/manager/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FastPose:
	Unexpected key(s) in state_dict: "preact.bn1.num_batches_tracked", "preact.layer1.0.bn1.num_batches_tracked", "preact.layer1.0.bn2.num_batches_tracked", "preact.layer1.0.bn3.num_batches_tracked", "preact.layer1.0.downsample.1.num_batches_tracked", "preact.layer1.1.bn1.num_batches_tracked", "preact.layer1.1.bn2.num_batches_tracked", "preact.layer1.1.bn3.num_batches_tracked", "preact.layer1.2.bn1.num_batches_tracked", "preact.layer1.2.bn2.num_batches_tracked", "preact.layer1.2.bn3.num_batches_tracked", "preact.layer2.0.bn1.num_batches_tracked", "preact.layer2.0.bn2.num_batches_tracked", "preact.layer2.0.bn3.num_batches_tracked", "preact.layer2.0.downsample.1.num_batches_tracked", "preact.layer2.1.bn1.num_batches_tracked", "preact.layer2.1.bn2.num_batches_tracked", "preact.layer2.1.bn3.num_batches_tracked", "preact.layer2.2.bn1.num_batches_tracked", "preact.layer2.2.bn2.num_batches_tracked", "preact.layer2.2.bn3.num_batches_tracked", "preact.layer2.3.bn1.num_batches_tracked", "preact.layer2.3.bn2.num_batches_tracked", "preact.layer2.3.bn3.num_batches_tracked", "preact.layer3.0.bn1.num_batches_tracked", "preact.layer3.0.bn2.num_batches_tracked", "preact.layer3.0.bn3.num_batches_tracked", "preact.layer3.0.downsample.1.num_batches_tracked", "preact.layer3.1.bn1.num_batches_tracked", "preact.layer3.1.bn2.num_batches_tracked", "preact.layer3.1.bn3.num_batches_tracked", "preact.layer3.2.bn1.num_batches_tracked", "preact.layer3.2.bn2.num_batches_tracked", "preact.layer3.2.bn3.num_batches_tracked", "preact.layer3.3.bn1.num_batches_tracked", "preact.layer3.3.bn2.num_batches_tracked", "preact.layer3.3.bn3.num_batches_tracked", "preact.layer3.4.bn1.num_batches_tracked", "preact.layer3.4.bn2.num_batches_tracked", "preact.layer3.4.bn3.num_batches_tracked", "preact.layer3.5.bn1.num_batches_tracked", "preact.layer3.5.bn2.num_batches_tracked", "preact.layer3.5.bn3.num_batches_tracked", "preact.layer3.6.bn1.num_batches_tracked", "preact.layer3.6.bn2.num_batches_tracked", "preact.layer3.6.bn3.num_batches_tracked", "preact.layer3.7.bn1.num_batches_tracked", "preact.layer3.7.bn2.num_batches_tracked", "preact.layer3.7.bn3.num_batches_tracked", "preact.layer3.8.bn1.num_batches_tracked", "preact.layer3.8.bn2.num_batches_tracked", "preact.layer3.8.bn3.num_batches_tracked", "preact.layer3.9.bn1.num_batches_tracked", "preact.layer3.9.bn2.num_batches_tracked", "preact.layer3.9.bn3.num_batches_tracked", "preact.layer3.10.bn1.num_batches_tracked", "preact.layer3.10.bn2.num_batches_tracked", "preact.layer3.10.bn3.num_batches_tracked", "preact.layer3.11.bn1.num_batches_tracked", "preact.layer3.11.bn2.num_batches_tracked", "preact.layer3.11.bn3.num_batches_tracked", "preact.layer3.12.bn1.num_batches_tracked", "preact.layer3.12.bn2.num_batches_tracked", "preact.layer3.12.bn3.num_batches_tracked", "preact.layer3.13.bn1.num_batches_tracked", "preact.layer3.13.bn2.num_batches_tracked", "preact.layer3.13.bn3.num_batches_tracked", "preact.layer3.14.bn1.num_batches_tracked", "preact.layer3.14.bn2.num_batches_tracked", "preact.layer3.14.bn3.num_batches_tracked", "preact.layer3.15.bn1.num_batches_tracked", "preact.layer3.15.bn2.num_batches_tracked", "preact.layer3.15.bn3.num_batches_tracked", "preact.layer3.16.bn1.num_batches_tracked", "preact.layer3.16.bn2.num_batches_tracked", "preact.layer3.16.bn3.num_batches_tracked", "preact.layer3.17.bn1.num_batches_tracked", "preact.layer3.17.bn2.num_batches_tracked", "preact.layer3.17.bn3.num_batches_tracked", "preact.layer3.18.bn1.num_batches_tracked", "preact.layer3.18.bn2.num_batches_tracked", "preact.layer3.18.bn3.num_batches_tracked", "preact.layer3.19.bn1.num_batches_tracked", "preact.layer3.19.bn2.num_batches_tracked", "preact.layer3.19.bn3.num_batches_tracked", "preact.layer3.20.bn1.num_batches_tracked", "preact.layer3.20.bn2.num_batches_tracked", "preact.layer3.20.bn3.num_batches_tracked", "preact.layer3.21.bn1.num_batches_tracked", "preact.layer3.21.bn2.num_batches_tracked", "preact.layer3.21.bn3.num_batches_tracked", "preact.layer3.22.bn1.num_batches_tracked", "preact.layer3.22.bn2.num_batches_tracked", "preact.layer3.22.bn3.num_batches_tracked", "preact.layer4.0.bn1.num_batches_tracked", "preact.layer4.0.bn2.num_batches_tracked", "preact.layer4.0.bn3.num_batches_tracked", "preact.layer4.0.downsample.1.num_batches_tracked", "preact.layer4.1.bn1.num_batches_tracked", "preact.layer4.1.bn2.num_batches_tracked", "preact.layer4.1.bn3.num_batches_tracked", "preact.layer4.2.bn1.num_batches_tracked", "preact.layer4.2.bn2.num_batches_tracked", "preact.layer4.2.bn3.num_batches_tracked", "duc1.bn.num_batches_tracked", "duc2.bn.num_batches_tracked". 
	While copying the parameter named "conv_out.weight", whose dimensions in the model are torch.Size([33, 128, 3, 3]) and whose dimensions in the checkpoint are torch.Size([17, 128, 3, 3]).
	While copying the parameter named "conv_out.bias", whose dimensions in the model are torch.Size([33]) and whose dimensions in the checkpoint are torch.Size([17]).
/home/manager/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by yudw15** [comment]
将opt.py中的--nClasses的默认值改为17试试
祝你成功

**Comment by YixiaoZhang** [comment]
@chenxp106 遇到了同样的问题，你有解决这个问题吗？

**Comment by chenxp106** [comment]
我的是pytorch版本的问题。可以参考这个链接
https://blog.csdn.net/mdjxy63/article/details/85113643
