### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by hslyu** [MVIG-SJTU/AlphaPose#281]
Hi, I tried to fetch the weights, but failed with below comment:

----

Resolving mvig.sjtu.edu.cn (mvig.sjtu.edu.cn)... 202.121.182.216
Connecting to mvig.sjtu.edu.cn (mvig.sjtu.edu.cn)|202.121.182.216|:80... failed: Connection refused.
unzip: cannot find or open output.zip, output.zip.zip or output.zip.ZIP.

----

It seems same issue discussed at #171. Would you check whether the server is opened?

Regards,
hslyu

**Comment by Fang-Haoshu** [comment]
Hi, thanks! Before we fix the problem, you can download the model from google drive manually.
