### ISSUE TITLE
关于yolo

### ISSUE THREAD

**Issue by RandomFool123** [MVIG-SJTU/AlphaPose#287]
你好，请问检测人物和检测关节点都是用的yolo的模型吗？因为在贵校团队的论文中并没有提到使用的检测方法，而我在实际跑程序的时候，发现只加载了yolo和joint-candidate SPPE这两个模型。

**Comment by YuliangXiu** [comment]
yolo只是用来检测人的box，box用来crop出human image，然后SPPE是用在这个human image上出单人骨骼关键点的，使用yolo主要是看中了yolo速度性能上的优越。

**Comment by RandomFool123** [comment]
好的，十分感谢！
