### ISSUE TITLE
ImportError while Quick Start running  run.sh

### ISSUE THREAD

**Issue by HarlanTuring** [MVIG-SJTU/AlphaPose#288]
I have followed all tips from Installation, but I met this import_error of no modules,  below is the report 
-------------------------------------------------------------------------------------------------
harlan@harlan-911K:~/PoseDetect/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 19, in <module>
    from model.config import cfg
  File "/home/harlan/PoseDetect/AlphaPose/human-detection/tools/../lib/model/__init__.py", line 1, in <module>
    from . import config
  File "/home/harlan/PoseDetect/AlphaPose/human-detection/tools/../lib/model/config.py", line 9, in <module>
    from easydict import EasyDict as edict
ImportError: No module named easydict
pose estimation with RMPE...
/home/harlan/torch/install/bin/luajit: /home/harlan/torch/install/share/lua/5.1/trepl/init.lua:389: /home/harlan/torch/install/share/lua/5.1/hdf5/ffi.lua:74: Unsupported HDF5 version: 1.10.2
stack traceback:
	[C]: in function 'error'
	/home/harlan/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/harlan/PoseDetect/AlphaPose/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...rlan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 10, in <module>
    from six.moves import xrange
ImportError: No module named six.moves
visualization...
mkdir: 无法创建目录"/home/harlan/PoseDetect/AlphaPose/examples/results//RENDER": 没有那个文件或目录
Traceback (most recent call last):
  File "json-video.py", line 4, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm

-----------------------------------------------------------------------------------
the strange thing is that I have equiped these packests, but still can not solve this problem.

-----------------------------------------------------------------------------------
harlan@harlan-911K:~/PoseDetect/AlphaPose$ pip install easydict
Requirement already satisfied: easydict in /home/harlan/.local/lib/python3.6/site-packages (1.9)
harlan@harlan-911K:~/PoseDetect/AlphaPose$ pip install six
Requirement already satisfied: six in /home/harlan/anaconda3/lib/python3.6/site-packages (1.11.0)
harlan@harlan-911K:~/PoseDetect/AlphaPose$ pip install tqdm
Requirement already satisfied: tqdm in /home/harlan/.local/lib/python3.6/site-packages (4.31.1)
-----------------------------------------------------------------------------------
Is  this related to my approach to  torch's  installation ? 
Thank you for any help.

**Comment by Fang-Haoshu** [comment]
Hi, it seems your pip is for python3. Our code use python2. So maybe you can try pip2 install six?

**Comment by HarlanTuring** [comment]
Thanks.  Yes, that's it. I solved the above problem with pip2, but then trapped wrong tensorflow version.I will have some try for older version.

**Comment by Fang-Haoshu** [comment]
cool！
