### ISSUE TITLE
能否控制识别人数?

### ISSUE THREAD

**Issue by chenloveheimei** [MVIG-SJTU/AlphaPose#291]
你好,我叫阿龙.
我跑的是AlphaPose_pytorch版本的webcam,实时的代码.
我想问下,代码里面有控制识别人数的参数吗?
如果没有,请问需要怎么做呢
谢谢.

**Comment by Fang-Haoshu** [comment]
目前还没办法，可以试试把conf的阈值调高一点 --conf 0.5这样子

**Comment by chenloveheimei** [comment]
我主要是想提速,就认为,人数固定为1个或者2个,找到了指定人数就退出,这样,帧率就会提高.如果一直识别N多个人,可能帧率就一直很慢,会不会这样呢?
