### ISSUE TITLE
gpu not released, becomes higher and higher

### ISSUE THREAD

**Issue by lishuchao012** [MVIG-SJTU/AlphaPose#293]
I modify a little. I write a flask server, upload image and begin to detect by AlphaPose .  I find gpu becomes higher after upload some images, again upload some becomes more higer. From 1074MiB to 1529MiB to 1829MiB. 
`@app.route('/imageUploadForVueBase64', methods=['POST'], strict_slashes=False)
def imageUploadForVueBase64():
    new_file_path = ""
    try:
        file_dir = os.path.join(basedir, app.config['UPLOAD_FOLDER'])
        if not os.path.exists(file_dir):
            os.makedirs(file_dir)
        formData = request.form.to_dict()

        #decode base64
        base64Str = formData["base64Str"]
        imgData = base64.b64decode(base64Str)
        new_file_name = "{}{}{}".format(randomStr(), ".", "jpg")
        new_file_path = os.path.join(file_dir, new_file_name)

        #save image
        file = open(new_file_path, 'wb')
        file.write(imgData)
        file.close()

        '''start detect'''
        imageHeight, imageWidth, finalResult = alpha_util2.detectByAlphaForVue(app.pose_model, file_dir, new_file_name, app.detectionLoader)
        return jsonify({"success": 200, "imageHeight": imageHeight, "imageWidth": imageWidth, "finalResult": finalResult})
` 

`if __name__ == '__main__':

    # Load pose model
    pose_dataset = alpha_util2.Mscoco()
    pose_model = InferenNet(4 * 1 + 1, pose_dataset)
    pose_model.cuda()
    pose_model.eval()
    app.pose_model = pose_model
    app.detectionLoader = alpha_util2.DetectionLoader()
    app.run(host="0.0.0.0", port=5555)`

**Comment by yudw15** [comment]
torch.cuda.empty_cache() 试试

**Comment by lishuchao012** [comment]
It worked, thank you very much!

**Comment by lishuchao012** [comment]
@yudw15 It worked, thank you very much!

**Comment by learnermaxRL** [comment]
@lishuchao012  have you written an api to predict on batch of images?

**Comment by lishuchao012** [comment]
@learnermaxRL you can write like this : 

`def detectByAlpha(pose_model, file_dir, im_names, detectionLoader):

    mode = MODE

    # Load input images
    data_loader = ImageLoader(im_names, batchSize=1, img_dir=file_dir, format='yolo').start()`
