### ISSUE TITLE
Cannot unzip model (output.zip)

### ISSUE THREAD

**Issue by cschell** [MVIG-SJTU/AlphaPose#295]
Hi, I'm trying to setup AlphaPose, but `fetch_models.sh` fails with unzip complaining about the downloaded `output.zip` not being a valid archive:

```
unzip output.zip
Archive:  output.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of output.zip or
        output.zip.zip, and cannot find output.zip.ZIP, period.
```

When I download [output.zip](mvig.sjtu.edu.cn/publications/rmpe/output.zip) and try to unzip it manually, I get the same error (on my iMac (Mojave) as well as on my Ubuntu box (18.10)).

Here is the [Dockerfile](https://gist.github.com/cschell/4d8bee3f076b230baf6847547186894b) I used to build AlphaPose, the error can be reproduced with `docker run --runtime=nvidia -it [imagename] bash -c ./fetch_models.sh`

Is the archive just broken or do I need some specific zip-version?

**Comment by butugo** [comment]
Hi, I meet the same issue as you. I guess some error occurred  during file upload.

**Comment by Fang-Haoshu** [comment]
Hi, thanks for reporting the bug! It seems the server is broken. You can try download the files from Google drive.

**Comment by cschell** [comment]
Ah, Google brought me back to the Readme, where I found the [Google Drive](https://drive.google.com/file/d/1dMiUPMvt5o-S1BjDkzUJooEoT3GgasxB/view) link – that one works, thanks :)
