### ISSUE TITLE
In demo.py which step called the draw function to draw the keypoints ?

### ISSUE THREAD

**Issue by kli017** [MVIG-SJTU/AlphaPose#296]
Hello, Thank you for the awesome project. I have a question about the visualization of results. 
When you add --vis you can visual the keypoints on the images. However after go through the demo.py I cannot found the function of drawing.  Could you give me a little hint of this? Thanks!

**Comment by eeric** [comment]
@kli017 
on the 144th line, in fn.py, 
>>def vis_frame(frame, im_res, format='coco')

**Comment by kli017** [comment]
@eeric Thanks! Already found

**Comment by swg209** [comment]
@kli017  Hi， I also meet this problem, I am using the version of pytorch , and the demo.py is no more than 144 line, could you help me ?

**Comment by eeric** [comment]
@swg209 
on the 144th line, in fn.py，not in demo.py
