### ISSUE TITLE
Some bugs in poseflow

### ISSUE THREAD

**Issue by ZongweiZhou1** [MVIG-SJTU/AlphaPose#30]
Hey, @YuliangXiu 
This is a very good job.
But when I tried to read the codes in poseflow , i find some bugs there.

I think the method 'cal_bbox_iou' is not correct. for example, when there is no overlap between boxA and boxB, the iou get by this function is wrong.
Thus, I think it may be modified like this:

`def cal_bbox_iou(boxA, boxB):
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[2], boxB[2])
    xB = min(boxA[1], boxB[1])
    yB = min(boxA[3], boxB[3])
    if xA < xB and yA < yB:
        interArea = (xB - xA + 1) * (yB - yA + 1)
        boxAArea = (boxA[1] - boxA[0] + 1) * (boxA[3] - boxA[2] + 1)
        boxBArea = (boxB[1] - boxB[0] + 1) * (boxB[3] - boxB[2] + 1)
        iou = interArea / float(boxAArea + boxBArea - interArea+0.00001)
    else:
        iou=0.
    return iou`

Is there something I ignoring?

**Comment by YuliangXiu** [comment]
@ZongweiZhou1 Yes, you are right, this is a foolish bug made by me. I corrected it just now. 
Very thanks!
