### ISSUE TITLE
pytorch 版本 poseflow (general version) 一问

### ISSUE THREAD

**Issue by GuPeterChan** [MVIG-SJTU/AlphaPose#301]
谢谢你们团队提供了高品质的姿态估计模型, 我现在正在使用AlphaPose 处理一些走路的视频, 但因为动态模糊的关系, 有时侯估计出来的结果会把左脚跟右脚反转了, 就是估计出来的左脚ankle 和knee 其实应该是真实的右脚ankle 和knee。我从之前的issue 得知现在PoseFlow 不会修正 pose estimation 的结果, 请问以后会增加这个功能吗? 对于左,右脚反转这个问题, 请问你们能不能给我一些建议去解决呢?

**Comment by YuliangXiu** [comment]
Yes, the "Inversion" problem is one of main keypoint location errors. 
![image](https://user-images.githubusercontent.com/7944350/54907075-ac037900-4f1f-11e9-8863-13ac7b4599dc.png)

Maybe you can first do pose estimation on every frame and then excuse some smoothing operations (such as fix inversion errors by considering adjacent frames' poses) to fix this problem

**Comment by Lukikay** [comment]
> Yes, the "Inversion" problem is one of main keypoint location errors.
> ![image](https://user-images.githubusercontent.com/7944350/54907075-ac037900-4f1f-11e9-8863-13ac7b4599dc.png)
> 
> Maybe you can first do pose estimation on every frame and then excuse some smoothing operations (such as fix inversion errors by considering adjacent frames' poses) to fix this problem

Many thanks for the advice! I'm studying the pose estimation problem now and very interested in this PR curve figure. Could you please let me know the source paper of this figure or any citing information? I think it will be helpful to my literature review, thanks again!

**Comment by YuliangXiu** [comment]
Ronchi, M. R., & Perona, P. (2017). Benchmarking and Error Diagnosis in Multi-instance Pose Estimation. In Proceedings of the IEEE International Conference on Computer Vision (Vol. 2017–Octob, pp. 369–378). https://doi.org/10.1109/ICCV.2017.48
