### ISSUE TITLE
指标计算

### ISSUE THREAD

**Issue by chenxp106** [MVIG-SJTU/AlphaPose#307]
您好，请问论文中的map指标是怎么算出来的，是调用eval.py文件吗？

**Comment by KCHENPENGFEI** [comment]
evaluation.py里面有getmap函数

**Comment by chenxp106** [comment]
ok，thanks

**Comment by chenxp106** [comment]
在哪里能下载文件 test-dev.h5？

**Comment by KCHENPENGFEI** [comment]
@chenxp106 他们没有提供，我自己做了一个

**Comment by chenxp106** [comment]
@KCHENPENGFEI 能提供一下连接地址吗，谢谢啦

**Comment by KCHENPENGFEI** [comment]
你留我一个邮箱吧

**Comment by chenxp106** [comment]
@KCHENPENGFEI  chenxp106@163.com
非常感谢

**Comment by oujieww** [comment]
我想问下，有人计算了作者在这个项目里提供的 “yolov3-spp + duc_se” 的mAP嘛？请问有人自己做过eval嘛？想要知道下mAP

**Comment by KCHENPENGFEI** [comment]
@oujieww 我做了，我用自己跑的模型，mAP可以达到40多，但是用了PyraNet就很差

**Comment by oujieww** [comment]
@KCHENPENGFEI 你没有试过作者给的这一整套的“yolov3-spp + duc_se” 的mAP嘛？

**Comment by KCHENPENGFEI** [comment]
@oujieww spp不就是duc_se么？我用的yolov3检测出人的bbox，然后放到due_se模型去跑了

**Comment by GuoHaiYang123** [comment]
test-dev.h5能不能也给我发一份，我的邮箱2423419980@qq.com @KCHENPENGFEI @chenxp106 ,十分感谢

**Comment by nickshawn** [comment]
同求`test-dev.h5`，方便的话，也请给我发一份 @KCHENPENGFEI @chenxp106 ，万分感谢！邮箱：[xiaolei199311@126.com](xiaolei199311@126.com)

**Comment by yangyuke001** [comment]
@KCHENPENGFEI 
请给我邮箱：yangyuke001@126.com 发一份test-dev.h5，万分感谢！

**Comment by lizhen2017** [comment]
@KCHENPENGFEI 您好, 可以发我下test-dev.h5这个文件吗？另外需要下载test2017的image是是吗？

**Comment by alohays** [comment]
@KCHENPENGFEI 您好, 可以发我下test-dev.h5这个文件吗?
我的邮箱是 swack9751@korea.ac.kr。先谢谢了。

**Comment by Fang-Haoshu** [comment]
https://drive.google.com/file/d/0BxORzoJl8N9PRy1ISnF0WnljLXRtNkFscmVfNDI4R0ptc04w/view?usp=drive_web Can you check if it works?

**Comment by alohays** [comment]
Thank you very much!

I'll check it out.



2019년 12월 13일 (금) 오후 6:16, Fred Fang <notifications@github.com>님이 작성:

**Comment by chenxp106** [comment]
@Fang-Haoshu 你好，昨天发的那份test-dev.h5,我跑了下，用的是作者提供的模型，MAP只有26。问下，你那边能跑多少

**Comment by yangyuke001** [comment]
@Fang-Haoshu @chenxp106 
这个test-dev.h5里的人像个数为12176，而同目录下的test-dev_images.txt里面的人像个数为11916，相差260个，所以我在想：这两个文件是不匹配的。作者方便的话麻烦确认一下。

error：
/train_sppe/src/predict/annot/coco_minival.py", line 32
ssert len(self.images) == self.annot['xmin'].shape[0]

**Comment by alohays** [comment]
> @Fang-Haoshu @chenxp106
> 这个test-dev.h5里的人形个数为12176，而同目录下的test-dev_images.txt里面的人形个数为11916，相差260个，所以很可能：这两个文件是不匹配的。作者方便的话麻烦确认一下。
> 
> error：
> /train_sppe/src/predict/annot/coco_minival.py", line 32
> ssert len(self.images) == self.annot['xmin'].shape[0]

I have the same error

**Comment by Fang-Haoshu** [comment]
Sorry guys. Seems the file is not correct.
https://drive.google.com/open?id=0BxORzoJl8N9PSTB2QWZBSUMxS1huc290VFZxOW9NZmhydHZr
You can use this one and replace the whole folder

**Comment by Fang-Haoshu** [comment]
Thanks Yuke @yangyuke001 @chenxp106
