### ISSUE TITLE
在pytorch 0.4.1和1.01版本里，webcam_demo.py还 是不能提取多人骨骼信息

### ISSUE THREAD

**Issue by xiaoxiaotao** [MVIG-SJTU/AlphaPose#308]
在pytorch 0.4.1和pytorch1.0.1里，运行webcam_demo.py只能提取一个人的骨骼信息。issues里给出的方法仅限于0.4.0，其他版本不好使啊

**Comment by xiaoxiaotao** [comment]
刚刚解决了这个问题，在dataloader_webcam.py这个程序里，找到
inps[i] = cropBox(tmp_img, upLeft, bottomRight, opt.inputResH, opt.inputResW)改为：
inps[i] = cropBox(tmp_img.clone(), upLeft, bottomRight, opt.inputResH, opt.inputResW)

**Comment by leonshek** [comment]
@xiaoxiaotao Hi，你有用1.0跑通图片测试代码demo.py吗？有的话是怎么更改让代码支持的呢？

**Comment by xiaoxiaotao** [comment]
@leonshek 图片一直可以啊，你那里有什么错误吗，你贴出来啊

**Comment by leonshek** [comment]
@xiaoxiaotao 
python 2.7 + pytorch 1.0.0报错：
from dataloader import ImageLoader, DetectionLoader, DetectionProcessor, DataWriter, Mscoco
File ".../dataloader.py", line 9, in <module>
    from yolo.preprocess import prep_image, prep_frame, inp_to_image
File ".../yolo/preprocess.py", line 70
    img = img.view(*network_dim, 3).transpose(0, 1).transpose(0, 2).contiguous()
SyntaxError: only named arguments may follow *expression

python 3.6 + pytorch 0.4.0就行。
