### ISSUE TITLE
Human Detection Performance

### ISSUE THREAD

**Issue by sberryman** [MVIG-SJTU/AlphaPose#31]
Using a GTX 1080 with 8 GB RAM what would you expect human detection inference performance to be?

I made some changes to demo-alpha-pose.py related to TensorFlow session config. I removed `allow_growth=True` and replaced it with `per_process_gpu_memory_fraction=4` and then I run 3 docker instances. This has been an easy way in the past for me to maximize the GPU utilization. I'm able to keep the GPU at 90%+ utilization based on watching `watch -n 1 nvidia-smi` I did NOT adjust any of the config variables and I removed writing to HDF5 files and instead push to MongoDB via RabbitMQ.

I'm only getting around 1.8-2 images (3264x1836 resolution which gets scaled down as `cfg.TEST.MAX_SIZE=1000`) per second though. Is that expected? I believe I was getting closer to 3-4 images per second using this card while running inference on Mask RCNN (Matterports version) I'll test using my 1080 TI's in a few days to see the performance bump with more CUDA cores and memory.

**Comment by Fang-Haoshu** [comment]
Hi, for human detection we use the resnet152 based model from: https://github.com/endernewton/tf-faster-rcnn. If the mask-rcnn you use is based on resnet101, then it can be faster

**Comment by sberryman** [comment]
Good to know, thanks for the reply
