### ISSUE TITLE
[bug] mxnet branch wrong model file

### ISSUE THREAD

**Issue by gachiemchiep** [MVIG-SJTU/AlphaPose#311]
Hello @Fang-Haoshu 
I think the model uploaded inside mxnet branch is wrong. 
Would you mind re-upload it .

Log is as follow : 

```bash
(dl_3.6) gachiemchiep@gachiemchiep-dev-truong:AlphaPose$ python demo.py 
*************************
Namespace(LR=0.0001, addDPG=False, board=True, confidence=0.1, crit='MSE', dataset='coco', det_model='frcnn', detbatch=1, dtype='float32', epoch=0, eps=1e-08, expID='default', format=None, gpu_id=[0], hardMining=False, hmGauss=1, inp_dim='608', inputResH=256, inputResW=192, inputlist='', inputpath='', loadModel=None, load_from_pyt=False, logging_file='training.log', lr_decay=0.1, lr_decay_epoch='20,60', map=True, mode='normal', nClasses=17, nEpochs=100, nThreads=60, nms_thresh=0.6, optMethod='rmsprop', outputResH=64, outputResW=48, outputpath='examples/res/', posebatch=80, pre_resnet=True, rotate=40, save_img=False, scale=0.3, snapshot=1, syncbn=False, trainBatch=28, trainIters=0, try_loadModel=None, use_pretrained_base=True, valIters=0, validBatch=24, vis=False, visdom=False)
*************************
Loading yolo3_darknet53_coco ...
Modifying output layers to ignore non-person classes...
Loading SPPE ...
===Pretrain Base===
Model file is not found. Downloading.
Downloading ../exp/pretrain/resnet101_v1b-a455932a.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/resnet101_v1b-a455932a.zip...
100%|███████████████████████████████████████████████████████████████████████| 100191/100191 [00:06<00:00, 16631.08KB/s]
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    pose_estimator = PoseEstimator(img_cropper, batch_size=opt.posebatch)
  File "/datadrive/workspace/github/pose_estimation/AlphaPose/pipeline.py", line 500, in __init__
    self.net.load_parameters('sppe/params/duc_se.params')
  File "/home/gachiemchiep/opt/miniconda2/envs/dl_3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 402, in load_parameters
    params[name]._load_init(loaded[name], ctx)
  File "/home/gachiemchiep/opt/miniconda2/envs/dl_3.6/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 237, in _load_init
    self.name, str(self.shape), str(data.shape))
AssertionError: Failed loading Parameter 'conv5_weight' from saved params: shape incompatible expected (17, 0, 3, 3) vs saved (33, 128, 3, 3)

```

**Comment by Jeff-sjtu** [comment]
Sorry, please use command `python demo.py --nClasses 33` to run the demo. e9e642fe5ae5ae4bc7a06f6d5137150e31d2d945

**Comment by gachiemchiep** [comment]
Hello @Jeff-sjtu 
Adding --nClasses 33 make the script run fine . 
But after running the script, i don't see any output image at ./examples/res. 
Is there any other option need to be added ?

**Comment by Jeff-sjtu** [comment]
Hi, you can add `--save_img` to save visualization results.

**Comment by gachiemchiep** [comment]
@Jeff-sjtu 
Thank you man. It worked great

**Comment by LiutsingWo** [comment]
> Hi, you can add `--save_img` to save visualization results.
Hi @Jeff-sjtu 
Nice answer，however, I did it, msg as flowing:
G:\AlphaPose-mxnet>python3 demo.py --nClasses 33 --save_img
*************************
Namespace(LR=0.0001, addDPG=False, board=True, confidence=0.1, crit='MSE', datas
et='coco', det_model='frcnn', detbatch=1, dtype='float32', epoch=0, eps=1e-08, e
xpID='default', format=None, gpu_id=[-1], hardMining=False, hmGauss=1, inp_dim='
608', inputResH=256, inputResW=192, inputlist='', inputpath='', loadModel=None,
load_from_pyt=False, logging_file='training.log', lr_decay=0.1, lr_decay_epoch='
20,60', map=True, mode='normal', nClasses=33, nEpochs=100, nThreads=60, nms_thre
sh=0.6, optMethod='rmsprop', outputResH=64, outputResW=48, outputpath='examples/
res/', posebatch=80, pre_resnet=True, rotate=40, save_img=True, scale=0.3, snaps
hot=1, syncbn=False, trainBatch=28, trainIters=0, try_loadModel=None, use_pretra
ined_base=True, valIters=0, validBatch=24, vis=False, visdom=False)
*************************
Loading yolo3_darknet53_coco(保存在本文件夹下吧，去掉路径可自动下载) ...
Modifying output layers to ignore non-person classes...
Loading SPPE ...
===Pretrain Base===
Crop persons from original images
  0%|                                                    | 0/1 [00:00<?, ?it/s]f
inishly
process_i:  0
100%|█████████████████████████████████████
███████| 1/1 [00:01<00:00,  1.00s/it]
ImageLoader: 0.240014s
Detector: 0.068004s
---------------------------------------------------------------------
But actually,it didnt work for saving pic,help me,pls......

**Comment by gachiemchiep** [comment]
Hello @LiutsingWo 
As in the demo.py , the output is saved inside examples/vis
```python

vis_dir = 'examples/res'
if not os.path.exists(vis_dir):
    os.makedirs(vis_dir)
while not pose_processor.stopped:
    time.sleep(1)
```

Please check the examples/vis . 
I uploaded some of result image here. the blue point is he pose 

![000000000016](https://user-images.githubusercontent.com/2300329/56071202-cff00700-5dc7-11e9-8761-a235e37cb80d.jpg)

**Comment by LiutsingWo** [comment]
> Hello @LiutsingWo
> As in the demo.py , the output is saved inside examples/vis
> 
> ```python
> vis_dir = 'examples/res'
> if not os.path.exists(vis_dir):
>     os.makedirs(vis_dir)
> while not pose_processor.stopped:
>     time.sleep(1)
> ```
> 
> Please check the examples/vis .
> I uploaded some of result image here. the blue point is he pose
> 
> ![000000000016](https://user-images.githubusercontent.com/2300329/56071202-cff00700-5dc7-11e9-8761-a235e37cb80d.jpg)
FYI@gachiemchiep 
thanks，I got it  and learned about this DIR , in fact  it cannot  output pic with no any error . I ran it in win7 ,cpu  only . 
  after few hours.....
Mabe , thread code  is not supporte in win ,I guess, when I was ran six pics ,  that producted first pic   , and its log as following:

./examples/res\1.jpg
not pose_processor.stopped
->DetectionProcessor runed finally..
-》pose_proce_i:  4
Detector: 0.013667s
not pose_processor.stopped
-》pose_proce_i:  5
not pose_processor.stopped

I didnt found another one any more。。。
 img_list= ['examples/demo/pic1.jpg','examples/demo/2.jpg','examples/demo/3.jpg']

**Comment by gachiemchiep** [comment]
@LiutsingWo 
inside the pipeline.py there is a line . So the code need gpu to work. i tried to change to cpu only but it does not work too. maybe you should try with pc that support nvidia gpu.
```bash
ctx = mx.gpu()
```

**Comment by LiutsingWo** [comment]
> @LiutsingWo
> inside the pipeline.py there is a line . So the code need gpu to work. i tried to change to cpu only but it does not work too. maybe you should try with pc that support nvidia gpu.
> 
> ```shell
> ctx = mx.gpu()
> ```
3Q @gachiemchiep 
  I did ctx=mx.cpu according MXnet  doc  and it did work with cpu only ,but mabe cannot support unless be  modified
