### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by RICKYrelive** [MVIG-SJTU/AlphaPose#312]
Can I run alphapose on Mac OS without the CUDA  ?
在没有CUDA的MacOS可以运行吗?

**Comment by RICKYrelive** [comment]
Answer:https://github.com/MVIG-SJTU/AlphaPose/issues/116#issuecomment-422239346

**Comment by RICKYrelive** [comment]
Also , in <...>\AlphaPose\AlphaPose\SPPE\src\main_fast_inference.py you should replace line 61 with: model.load_state_dict(torch.load('./models/sppe/duc_se.pth',map_location=lambda storage, loc: storage))

**Comment by RICKYrelive** [comment]
For fun, went through the directory and ran:
"""sed -ie 's/.cuda()/.cpu()/g' *.py"""
and:
"""sed -ie 's/CUDA=True/CUDA=False/g' *.py"""

This roughly changed everything over to CPU, but now dealing with issues about being unable to serialize opencv VideoCapture object.

**Comment by GuoHaiYang123** [comment]
你是在Git里面运行命令行的吗?Pytorch版本的我试过，不需要在Git里运行，直接到cmd里就不会报错了
