### ISSUE TITLE
how about the evaluation result of released weights

### ISSUE THREAD

**Issue by oujieww** [MVIG-SJTU/AlphaPose#314]
Hi , i have some question, Alphapose result on coco is good, your group said pytorch-version can achieves 71mAp on COCO dataset. Is this result producted by the "yolov3-spp.weights(from darknet pretrained ) + duc_se.pth" ? 

the pretrained weight published there, is not same as paper ----- std+hg+stdn . So ,i want ask is the 71mAP resulted from " yolov3-spp +  duc_se"? 
if not , how about the "" yolov3-spp +  duc_se""  result ? mAP?

**Comment by oujieww** [comment]
主要就是想问下，主页上写的pytorch版本的 71mAP是用什么模型以及什么方式得到的，比如“faster rcnn +stn hg + sdtn” 还是 “box groundtruth + stn+hg+sdtn”? 提供的“yolov3-spp + duc_se” 这两个模型参数，能否达到主页上系的71mAP呢？

**Comment by Fang-Haoshu** [comment]
Hi, yes it is
