### ISSUE TITLE
[request] Hardware specification used for test

### ISSUE THREAD

**Issue by gachiemchiep** [MVIG-SJTU/AlphaPose#315]
Hello @Fang-Haoshu 
Thank you for your great work

Currently, AlphaPose does archive like "23 fps on COCO validation set."
But the hardware specification is not clear at all. 
Would you mind include your machine's specification into README file. 

By the way, for the famous OpenPose, they have really useful benchmark sheet : 
https://docs.google.com/spreadsheets/d/1-DynFGvoScvfWDA1P4jDInCkbD4lg0IKOYbXgEq0sK0/edit#gid=0

**Comment by Fang-Haoshu** [comment]
Hi, thanks for the advice. We use a single Nvidia 1080 Ti
Currently we don't have so much card for testing. Sorry for that.

**Comment by gachiemchiep** [comment]
@Fang-Haoshu 
Thank you for your reply.
