### ISSUE TITLE
Testing on my own videos

### ISSUE THREAD

**Issue by superhanson** [MVIG-SJTU/AlphaPose#32]
An error occurred when I used it to test my own video，
’
convert video to images...
./run.sh: line 55: ffmpeg: command not found
generating bbox from Faster RCNN...
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-03-14 00:18:30.331615: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-14 00:18:30.331682: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-14 00:18:30.331704: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/hansheng/AlphaPose/video-tmp

0it [00:00, ?it/s]
pose estimation with RMPE...
MPII	
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140542779459456:
  #000: ../../../src/H5Dio.c line 171 in H5Dread(): no output buffer
    major: Invalid arguments to routine
    minor: Bad value
/home/hansheng/torch/install/bin/luajit: /home/hansheng/torch/install/share/lua/5.1/hdf5/dataset.lua:78: HDF5DataSet:all() - failed reading data from [HDF5DataSet (83886081 /xmin DATASET)]
stack traceback:
	[C]: in function 'error'
	/home/hansheng/torch/install/share/lua/5.1/hdf5/dataset.lua:78: in function 'all'
	/home/hansheng/AlphaPose/predict/util.lua:39: in function 'loadAnnotations'
	main-alpha-pose.lua:27: in main chunk
	[C]: in function 'dofile'
	...heng/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
parametric-pose-nms-MPII.py:104: UserWarning: loadtxt: Empty input file: "/home/hansheng/AlphaPose/examples/results/BBOX/score-proposals.txt"
  scores_proposals = np.loadtxt(os.path.join(outputpath,"BBOX/score-proposals.txt"), ndmin=1)
parametric-pose-nms-MPII.py:18: UserWarning: loadtxt: Empty input file: "scores-proposals.txt"
  proposal_scores = np.loadtxt("scores-proposals.txt", ndmin=1)
visualization...
0it [00:00, ?it/s]
rendering video...
./run.sh: line 96: ffmpeg: command not found
‘

**Comment by LilySys** [comment]
Hi,I have two questions.
One is how long it takes your algorithm to process a frame of image (including detection), and the other is how long it takes to process a frame of image (excluding detection).

**Comment by Fang-Haoshu** [comment]
Hi, as the log says: ./run.sh: line 96: ffmpeg: command not found
please install ffmpeg
