### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by qazzombie** [MVIG-SJTU/AlphaPose#323]
为什么训练到 十多次之后就没有结果了

**Comment by Jeff-sjtu** [comment]
I will update the PyTorch version **AlphaPose** and release the new distributed training code soon.

**Comment by wduo** [comment]
@qazzombie Hi 十多次是指训练迭代次数吗？没有结果是指没有收敛吗？
@Jeff-sjtu 非常期待

**Comment by qazzombie** [comment]
> I will update the PyTorch version **AlphaPose** and release the new distributed training code soon.
thanks so much

**Comment by qazzombie** [comment]
> 没有



> @qazzombie Hi 十多次是指训练迭代次数吗？没有结果是指没有收敛吗？
> @Jeff-sjtu 非常期待

就是有时候训练的会效果很差，关键点找不到

**Comment by hellboywyh** [comment]
请问pytorch版本只有sppe的训练代码吗，我好像没看见整体的训练代码……
