### ISSUE TITLE
关于训练结果

### ISSUE THREAD

**Issue by KCHENPENGFEI** [MVIG-SJTU/AlphaPose#324]
有人拿作者给的FastPose这个模型跑出好的结果了吗？我训练的acc卡在75左右了，但是作者的duc_se.pth的acc可以达到90。

**Comment by wduo** [comment]
第几阶段的acc卡在75左右？

**Comment by KCHENPENGFEI** [comment]
跑了100个epoch左右

**Comment by qazzombie** [comment]
我训练的精度可以挺高的，七八十次可以到八十多，但是valid的精度会越来越差，差到不正常。而且valid的精度高效果就好，精度差效果就不行

**Comment by KCHENPENGFEI** [comment]
@qazzombie 你改过代码么？我跑的是pytorch的版本

**Comment by qazzombie** [comment]
我跑的也是pytorch版本，没有改，就改了下学习率
---原始邮件---
发件人:"Kchen"<notifications@github.com>;
发送时间:2019年4月24日(星期三) 晚上9:00
收件人:"MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com>;
抄送人:"qazzombie"<1666245397@qq.com>;"Mention"<mention@noreply.github.com>;
主题:Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)


@qazzombie 你改过代码么？我跑的是pytorch的版本
 
&mdash;

**Comment by KCHENPENGFEI** [comment]
@qazzombie 我试试更新一下代码😂

**Comment by wduo** [comment]
大家是在COCO数据集上跑的吗？

**Comment by qazzombie** [comment]
请问您训练的时候会出现训练的精度越来越高，但是验证的精度越来越差的情况吗。而且我不是训练的越久模型就越好，而是越差。训练到四五十次的时候训练的精度可以到八十多，但是验证的精度就不正常会变成0.000几。您会出现这样的情况吗，您觉得这会是啥原因 呢

**Comment by KCHENPENGFEI** [comment]
过拟合了，后期降低学习律

**Comment by qazzombie** [comment]
> 过拟合了，后期降低学习律

我本来也觉得是这样的原因，但是我测试了一下训练的图片，效果也不怎么样呀

**Comment by KCHENPENGFEI** [comment]
你训练效果好的话，拿训练图片做测试肯定不会差的吧，要么就是你代码问题

**Comment by qazzombie** [comment]
> 要么

我就是用的作者的代码，没有改什么。所以我就是valid的精度好效果才会好，我觉得简直是太奇怪了

**Comment by KCHENPENGFEI** [comment]
@qazzombie 你80多的的训练策略是怎么样的？学习率还有逼得参数设置了多少？我训练了好久最多就80

**Comment by Fang-Haoshu** [comment]
@qazzombie 这是pytorch batch norm的一个bug，需要把cudnn batchnorm关掉

**Comment by liuchanfeng165** [comment]
> @qazzombie 这是pytorch batch norm的一个bug，需要把cudnn batchnorm关掉

怎么设置呢，一直查不到。。。

**Comment by liuchanfeng165** [comment]
> cudnn

不太明白，cpn也用cudnn batchnorm，为什么就这个阉割版本的pytorch就不行？是作者复现还是，手下学生搞出来的？

**Comment by liuchanfeng165** [comment]
> @qazzombie 这是pytorch batch norm的一个bug，需要把cudnn batchnorm关掉

更加无语的是，alphapose的pytorch测试mini测试集用训练60次比不上 18次训练的CPN的384.288.model测试结果——前前后后相差0.5:0.9相差20mAP！！！

**Comment by GuoHaiYang123** [comment]
我目前关掉cuDNN对BN层的加速train acc达到91%，valid acc达到87%，增加dpg后train和valid acc都在85%附近@liuchanfeng165 ，我之前用的pytorch1.1.0精度都在60%附近徘徊，把pytorch1.1.0换成0.4.1之后，继续加载原来的model训练,精度直接飙升30个点，但loss貌似差不多，据交大的开发者说是由于pytorch1.0以后的版本修改了部分精度计算函数返回值造成的，实际model的performance是一样的

**Comment by qazzombie** [comment]
> 我目前关掉cuDNN对BN层的加速train acc达到91%，valid acc达到87%，增加dpg后train和valid acc都在85%附近@liuchanfeng165 ，我之前用的pytorch1.1.0精度都在60%附近徘徊，把pytorch1.1.0换成0.4.1之后，继续加载原来的model训练,精度直接飙升30个点，但loss貌似差不多，据交大的开发者说是由于pytorch1.0以后的版本修改了部分精度计算函数返回值造成的，实际model的performance是一样的

dpg是什么意思呀，还有就是如何关掉对BN层的加速呀

**Comment by GuoHaiYang123** [comment]
1.关BN层加速的操作见这个链接第3步：
https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md
注意点：在cmd 里用命令python
                                       import torch
                                       print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可
2.DPG是数据增强的意思 @qazzombie

**Comment by qazzombie** [comment]
好的，谢谢啦，但是我为什么每次加上她们的数据增强之后训练结果并没有什么太大的提升呀，有时候反而会下降，感觉他们的网络也不是很稳定的感觉，有时候可以训练好有时候不行


------------------ 原始邮件 ------------------
发件人: "GuoHaiYang123"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 中午11:27
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com>;
抄送: "1666245397"<1666245397@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)




1.关BN层加速的操作见这个链接第3步：
 https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md
 注意点：在cmd 里用命令python
 import torch
 print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可
 2.DPG是数据增强的意思 @qazzombie

**Comment by GuoHaiYang123** [comment]
是的，我不加DPG时train acc在91%左右，加了以后train acc在86%附近，有下降现象，应该是扩充了数据量，使模型泛化性更好了，训练时repo的acc貌似下降，实际performance应该是提升的



---原始邮件---
发件人: "qazzombie"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 中午11:31
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"GuoHaiYang123"<2423419980@qq.com&gt;;
主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)


好的，谢谢啦，但是我为什么每次加上她们的数据增强之后训练结果并没有什么太大的提升呀，有时候反而会下降，感觉他们的网络也不是很稳定的感觉，有时候可以训练好有时候不行 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "GuoHaiYang123"<notifications@github.com&gt;; 
 发送时间: 2019年9月10日(星期二) 中午11:27 
 收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;; 
 抄送: "1666245397"<1666245397@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 
 主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324) 
 
 
 
 
 1.关BN层加速的操作见这个链接第3步： 
  https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md 
  注意点：在cmd 里用命令python 
  import torch 
  print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可 
  2.DPG是数据增强的意思 @qazzombie

**Comment by qazzombie** [comment]
那个让BN不加速的那句话是加在代码中吗，还是直接用命令运行呀。而且这个是用在windows中的是吗？还是linux也可以用呀，因为我直接用命令行运行的话是通不过的。
而且好像可以直接用torch.backends.cudnn.benchmark = False来直接关闭cudnn


------------------ 原始邮件 ------------------
发件人: "GuoHaiYang123"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 中午11:37
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com>;
抄送: "1666245397"<1666245397@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)



是的，我不加DPG时train acc在91%左右，加了以后train acc在86%附近，有下降现象，应该是扩充了数据量，使模型泛化性更好了，训练时repo的acc貌似下降，实际performance应该是提升的 
 
 
 
 ---原始邮件--- 
 发件人: "qazzombie"<notifications@github.com&gt; 
 发送时间: 2019年9月10日(星期二) 中午11:31 
 收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;; 
 抄送: "Comment"<comment@noreply.github.com&gt;;"GuoHaiYang123"<2423419980@qq.com&gt;; 
 主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324) 
 
 
 好的，谢谢啦，但是我为什么每次加上她们的数据增强之后训练结果并没有什么太大的提升呀，有时候反而会下降，感觉他们的网络也不是很稳定的感觉，有时候可以训练好有时候不行  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "GuoHaiYang123"<notifications@github.com&gt;;  
  发送时间: 2019年9月10日(星期二) 中午11:27  
  收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;  
  抄送: "1666245397"<1666245397@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;  
  主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)  
   
   
   
   
  1.关BN层加速的操作见这个链接第3步：  
   https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md  
   注意点：在cmd 里用命令python  
   import torch  
   print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可  
   2.DPG是数据增强的意思 @qazzombie

**Comment by GuoHaiYang123** [comment]
我是win10系统，在GitBash里输入的那个命令

---原始邮件---
发件人: "qazzombie"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 晚上7:07
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"GuoHaiYang123"<2423419980@qq.com&gt;;
主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)


那个让BN不加速的那句话是加在代码中吗，还是直接用命令运行呀。而且这个是用在windows中的是吗？还是linux也可以用呀，因为我直接用命令行运行的话是通不过的。 
 而且好像可以直接用torch.backends.cudnn.benchmark = False来直接关闭cudnn 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "GuoHaiYang123"<notifications@github.com&gt;; 
 发送时间: 2019年9月10日(星期二) 中午11:37 
 收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;; 
 抄送: "1666245397"<1666245397@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 
 主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324) 
 
 
 
 是的，我不加DPG时train acc在91%左右，加了以后train acc在86%附近，有下降现象，应该是扩充了数据量，使模型泛化性更好了，训练时repo的acc貌似下降，实际performance应该是提升的  
   
   
   
  ---原始邮件---  
  发件人: "qazzombie"<notifications@github.com&amp;gt;  
  发送时间: 2019年9月10日(星期二) 中午11:31  
  收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&amp;gt;;  
  抄送: "Comment"<comment@noreply.github.com&amp;gt;;"GuoHaiYang123"<2423419980@qq.com&amp;gt;;  
  主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)  
   
   
  好的，谢谢啦，但是我为什么每次加上她们的数据增强之后训练结果并没有什么太大的提升呀，有时候反而会下降，感觉他们的网络也不是很稳定的感觉，有时候可以训练好有时候不行   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "GuoHaiYang123"<notifications@github.com&amp;gt;;   
   发送时间: 2019年9月10日(星期二) 中午11:27   
   收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&amp;gt;;   
   抄送: "1666245397"<1666245397@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;   
   主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)   
     
     
     
     
   1.关BN层加速的操作见这个链接第3步：   
    https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md   
    注意点：在cmd 里用命令python   
    import torch   
    print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可   
    2.DPG是数据增强的意思 @qazzombie

**Comment by liuchanfeng165** [comment]
@GuoHaiYang123  谢修改方法~请问你用原模型跑数据minival500_images.txt  mAP多少
比较我的，看看
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets= 20 ] = 0.687
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets= 20 ] = 0.872
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets= 20 ] = 0.752
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.633
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.774
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 20 ] = 0.720
Average Recall (AR) @[ IoU=0.50 | area= all | maxDets= 20 ] = 0.889
Average Recall (AR) @[ IoU=0.75 | area= all | maxDets= 20 ] = 0.778
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.661
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.809
(0.6865449578411594, 0.872474837601182)

**Comment by qazzombie** [comment]
同学你好，请问你有没有发现就是训练好的模型，最后结果是好的但是中间层的输出会有很大的值的情况出现，就是中间卷积层的输出不是一个数量级的，有的是几千，有的是几万，几十万，有的是0.几，1.几这样正常的值。




------------------ 原始邮件 ------------------
发件人: "GuoHaiYang123"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 晚上7:10
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com>;
抄送: "1666245397"<1666245397@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)



我是win10系统，在GitBash里输入的那个命令 
 
 ---原始邮件--- 
 发件人: "qazzombie"<notifications@github.com&gt; 
 发送时间: 2019年9月10日(星期二) 晚上7:07 
 收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;; 
 抄送: "Comment"<comment@noreply.github.com&gt;;"GuoHaiYang123"<2423419980@qq.com&gt;; 
 主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324) 
 
 
 那个让BN不加速的那句话是加在代码中吗，还是直接用命令运行呀。而且这个是用在windows中的是吗？还是linux也可以用呀，因为我直接用命令行运行的话是通不过的。  
  而且好像可以直接用torch.backends.cudnn.benchmark = False来直接关闭cudnn  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "GuoHaiYang123"<notifications@github.com&gt;;  
  发送时间: 2019年9月10日(星期二) 中午11:37  
  收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;  
  抄送: "1666245397"<1666245397@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;  
  主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)  
   
   
   
  是的，我不加DPG时train acc在91%左右，加了以后train acc在86%附近，有下降现象，应该是扩充了数据量，使模型泛化性更好了，训练时repo的acc貌似下降，实际performance应该是提升的   
     
     
     
   ---原始邮件---   
   发件人: "qazzombie"<notifications@github.com&amp;gt;   
   发送时间: 2019年9月10日(星期二) 中午11:31   
   收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&amp;gt;;   
   抄送: "Comment"<comment@noreply.github.com&amp;gt;;"GuoHaiYang123"<2423419980@qq.com&amp;gt;;   
   主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)   
     
     
   好的，谢谢啦，但是我为什么每次加上她们的数据增强之后训练结果并没有什么太大的提升呀，有时候反而会下降，感觉他们的网络也不是很稳定的感觉，有时候可以训练好有时候不行    
       
       
    ------------------ 原始邮件 ------------------    
    发件人: "GuoHaiYang123"<notifications@github.com&amp;gt;;    
    发送时间: 2019年9月10日(星期二) 中午11:27    
    收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&amp;gt;;    
    抄送: "1666245397"<1666245397@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;    
    主题: Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)    
       
       
       
       
    1.关BN层加速的操作见这个链接第3步：    
     https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md    
     注意点：在cmd 里用命令python    
     import torch    
     print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可    
     2.DPG是数据增强的意思 @qazzombie

**Comment by DonaldKam** [comment]
@liuchanfeng165  Hey it seems you achieve the test on minival500_images.txt. I checked the files times and could not find the corresponding h5 annot file, could you plz tell me how to get the h5 annot file?

**Comment by liuchanfeng165** [comment]
> @liuchanfeng165 Hey it seems you achieve the test on minival500_images.txt. I checked the files times and could not find the corresponding h5 annot file, could you plz tell me how to get the h5 annot file?

The demo doesn't require h5 file but train . the repo provides the h5 file when in trining .

**Comment by lizhen2017** [comment]
> 1.关BN层加速的操作见这个链接第3步：
> https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md
> 注意点：在cmd 里用命令python
> import torch
> print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可
> 2.DPG是数据增强的意思 @qazzombie

sed 的命令是要把文件哪一行的文字替换，数字就是1245。所以最终你用什么命令关闭的BN？

**Comment by lizhen2017** [comment]
> 1.关BN层加速的操作见这个链接第3步：
> https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md
> 注意点：在cmd 里用命令python
> import torch
> print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可
> 2.DPG是数据增强的意思 @qazzombie

sed 的命令是要把文件哪一行的文字替换，数字就是1245。所以最终你用什么命令关闭的BN？
@GuoHaiYang123

**Comment by qazzombie** [comment]
好像直接在代码中加上torch.backends.cudnn.enabled = False就可以，但是我是直接改的源码。还有就是你应该直接点开https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md&nbsp;看这里的第三步


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lizhen2017"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 上午10:57
收件人:&nbsp;"MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送:&nbsp;"1666245397"<1666245397@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 关于训练结果 (#324)



 
1.关BN层加速的操作见这个链接第3步：
 https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/train_sppe/README.md
 注意点：在cmd 里用命令python
 import torch
 print(torch.backends.cudnn.version())可以查看一个数字，去替代sed -i "****s/......."****处的数字即可
 2.DPG是数据增强的意思 @qazzombie
  
sed 的命令是要把文件哪一行的文字替换，数字就是1245。所以最终你用什么命令关闭的BN？
 @GuoHaiYang123
