### ISSUE TITLE
online_demo.py问题

### ISSUE THREAD

**Issue by CompliceU** [MVIG-SJTU/AlphaPose#325]
Hello, thank you very much for sharing, but at the moment I hope to do some gesture estimation work in real time, but found that when using your online_demo.py file, I found that the speed is not stable, I don’t know what kind of parameter adjustment can be used. Thank you for improving its speed and smoothness of display. @YuliangXiu

**Comment by YuliangXiu** [comment]
I think it is related to the number of people of one frame. @Jeff-sjtu

**Comment by CompliceU** [comment]
However, when I am currently using it, I will find that as time goes by, there are too many people in the middle, which will cause the display to be stuck, which looks like ppt. Can I change this by changing which parameters? @ @YuliangXiu @Jeff-sjtu

**Comment by YuliangXiu** [comment]
maybe you can export rendered frames one by one and then convert these sequential images into one video

**Comment by Fang-Haoshu** [comment]
How about using the video_demo.py?
