### ISSUE TITLE
Only single person detected at a time.

### ISSUE THREAD

**Issue by learnermaxRL** [MVIG-SJTU/AlphaPose#326]
Hi when I am running the demo on videos using

 python webcam_demo.py --webcam 0 --vis --fast_inference False.

I only get single person getting detected at  a time.Is it related to any configuration?

**Comment by Fang-Haoshu** [comment]
Hi, can you try it again? Just update the pytorch branch

**Comment by learnermaxRL** [comment]
Hi,
Its working,
Also it would be great if you can create a simple API which can take in batch of images and return the results and visualized images,if not can you point out easiest way to do it in your code.?

**Comment by Fang-Haoshu** [comment]
In fact the demo.py support such feature :D
