### ISSUE TITLE
Output on human pose tracking

### ISSUE THREAD

**Issue by WuZhuoran** [MVIG-SJTU/AlphaPose#327]
Hi, 

i am now using pytorch version of AlphaPose, when we input a video, all the skeletons in output will be same color distribution.

Is this possible that different people have different color skeleton  (Just like original poseflow)? 

<img width="381" alt="Screen Shot 2019-04-26 at 2 48 11 PM" src="https://user-images.githubusercontent.com/8717187/56838298-57129580-6832-11e9-963c-6113a4633452.png">. 

where is the code for drawing color? Did you write this part in Lua?

Thank you.

**Comment by WuZhuoran** [comment]
I found the code in fn.py file. Solved

**Comment by aalzooke** [comment]
@WuZhuoran  Are you able to do the tracking without using poseflow?
