### ISSUE TITLE
FastPose论文

### ISSUE THREAD

**Issue by KCHENPENGFEI** [MVIG-SJTU/AlphaPose#328]
今天去2050听了卢老师的分享会，想请问一下你们FastPose的论文大概什么时候能发出来呢？

**Comment by Fang-Haoshu** [comment]
Not an issue. Close

**Comment by Fang-Haoshu** [comment]
You can email Prof.Lu for more details. :D

**Comment by ArchNew** [comment]
这FastPose越看越像是对Simple Baselines的另一种实现。只不过upscale的方式从deconv改为了subconv，另外，channel数有些区别。

**Comment by dekathomas** [comment]
What is the difference of subconv and deconv @ArchNew?
