### ISSUE TITLE
Weights to reproduce results from the Paper on CrowdPose

### ISSUE THREAD

**Issue by KuehlschrankDino** [MVIG-SJTU/AlphaPose#332]
Thank you for providing the matching code for the CrowdPose Paper! 
However, I am not sure if you released the weights or the code for training on CrowdPose. 
Are the weights available to the public so the results on CrowdPose can be reproduced?
If so where can I find them? 

Thanks for your attention. I’m looking forward to your reply.

**Comment by Jeff-sjtu** [comment]
Sorry, the pretrained weights are not released now. I will consider releasing the weight in the [CrowdPose](https://github.com/Jeff-sjtu/CrowdPose) repo soon.
