### ISSUE TITLE
关于原子姿态函数

### ISSUE THREAD

**Issue by liuchanfeng165** [MVIG-SJTU/AlphaPose#334]
上海交大同学你好，我找了好久就发现cpp文件含atom这类关键词，看了训练的函数始终没找到，关于原子态拟合的函数，可否告知，有劳了。

**Comment by Fang-Haoshu** [comment]
Hi, atom pose is generated offline and not included in this repo. Thanks for your interest.

**Comment by liuchanfeng165** [comment]
> Hi, atom pose is generated offline and not included in this repo. Thanks for your interest.

原来如此，对应姿态需要拟合的话，online不应该存在四个姿态对应的分类吗，处理后包含于h5文件？
