### ISSUE TITLE
Does it support CPU ?

### ISSUE THREAD

**Issue by aalzooke** [MVIG-SJTU/AlphaPose#335]
Can i run the code on my CPU? if not, We can you add feature to support CPU

**Comment by KaiWangCanada** [comment]
Having the same problem. 

The training process cost a lot of computing, which requires GPU. However, using the model should need much less computing power, should be able to run on CPU (sometimes on mobile phones). 

If the model can be used with CPU only, then it can be used in a lot more places.

**Comment by Taospirit** [comment]
the same problem for me, hope for CPU support!

**Comment by elm-kok** [comment]
[Link](https://drive.google.com/file/d/134JjE4KkqSPlRdGH5D6B_aQ0nA6y9asY/view?usp=sharing)
I made this for my project. you can use conda
" conda env create -f alpha_pose_cpu_environment.yml "
for alpha_pose_cpu enviroment if you use linux.
Hope this helps.

**Comment by Taospirit** [comment]
i have fixed the problem with following steps, hope for help.
1. You must replace `.cuda()` to `.cpu()` and `CUDA=True` to `CUDA=False` in the whole project pytorch version. 
2. in <...>\AlphaPose\AlphaPose\SPPE\src\main_fast_inference.py, you should replace line 61 with: model.load_state_dict(torch.load('./models/sppe/duc_se.pth',map_location=lambda storage, loc: storage))

See also in:
#116 (comment)

**Comment by canonrock16** [comment]
> For CPU support [Link](https://drive.google.com/file/d/134JjE4KkqSPlRdGH5D6B_aQ0nA6y9asY/view?usp=sharing)
> I modified Alpha Pose code for my project. you can use conda
> `conda env create -f alpha_pose_cpu_environment.yml`
> for alpha_pose_cpu enviroment if you use linux.
> 
> ![](https://raw.githubusercontent.com/elm-kok/NLP_2019/master/Screenshot%20from%202019-07-06%2013-30-21.png)
> 
> Hope this helps.

I could use your CPU ver.Thanks a lot!!
(But alpha_pose_cpu_environment.yml didn't work well. ResolvePackageNotFound occurred.)
