### ISSUE TITLE
多路视频监控的修改方法

### ISSUE THREAD

**Issue by liuxufenfeiya** [MVIG-SJTU/AlphaPose#336]
作者的webcam_demo.py只提供了单路摄像头，我把这个代码改成了支持多路摄像头的了

我把具体的方法写在csdn上了，有需要的可以去看看哈~
https://blog.csdn.net/u013837919/article/details/89917876

放两张效果图，第一张是我弄了6个不同的视频，第二张由于缺乏测试摄像头，于是我就把一个摄像头取6次
![2019-05-07 14-27-03屏幕截图](https://user-images.githubusercontent.com/33931180/57277001-b6479400-70d5-11e9-9cda-6a9fbbaf7661.png)

![2019-05-07 14-33-23屏幕截图](https://user-images.githubusercontent.com/33931180/57277413-b2684180-70d6-11e9-97fc-dee3b391659c.png)

**Comment by YuliangXiu** [comment]
thanks so much
