### ISSUE TITLE
some questions about poseflow

### ISSUE THREAD

**Issue by ZongweiZhou1** [MVIG-SJTU/AlphaPose#34]
@YuliangXiu 
Hey, I have some questions when i run the poseflow part of this repo to track pedestrians. Could you me a hand?

1. Globally optimal solution is obtained by the Hungarian algorithm to solve bipartite matching problem. Thus no matter what the similarity is, one node in set A will be assigned a node from set B even if the smallest similarity is negative, if there are same number of nodes in A and B, which will cause many mismatches. So I'm wondering whether a threshold is needed to select convincing matches after the line: 120 in tracker.py.

2. I find a margin '10 frames' is set to find the lost target. And for the lost target, the box and pose corresponding to the lastest detection are copied. However, matching points obtained by deepmatching  are between successive frames. So, i think the copy operator may leads to mismatches in some cases. Am i right?

**Comment by YuliangXiu** [comment]
1. During bipartite matching period, the values in cost matrix are all positive, you can find the cost calculate function in [utils.py](https://github.com/MVIG-SJTU/AlphaPose/blob/master/poseflow/utils.py#L180), so the smallest similarity must be positive. I think there is no need for threshold.

2. You are right. So sorry for this BIG carelessness😂... considering the long time on calculating deepmatching results, I think a quick fix can be only using box/pose IoU(without deepmatching) for match-scores when matching lost target with margin frames. I will fix it later.

Many many thanks to your correctness!

**Comment by ZongweiZhou1** [comment]
@YuliangXiu
 Yeah，for the 1st question, i know all the similarities are positive, and i just give an extreme example :) .   
Here we have a,b,c in 1st frame and a', b', d in 2nd frame for example, where a,a' are detections of same target, b,b' are detections of same target, but c,d are detections of different targets. Then without thresholding, hungarian algorithm will assign d to c, is it not?

**Comment by YuliangXiu** [comment]
OK, I get your point. Although it's very embarrassing, I have to admit this is another careless mistake... I will update a new version later. Very thanks for your correctness, I think this will help PoseFlow get better performance. You are a pretty careful man. I will add your username into next version code.

**Comment by YuliangXiu** [comment]
@ZongweiZhou1 
I have updated a new version of [utils.py](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/utils.py#L92) and [tracker.py](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/tracker.py#L149), but the final results did not improve a lot. I set the default matching threshold as 0.8, while this is not the best threshold. 0.2 is the best threshold, but if we set matching threshold as 0.2, it is almost similar to old Hungarian algorithm with no match-score threshold.

My solution is pretty coarse. If you have some new ideas to improve final performance, PR is very welcome!

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
