### ISSUE TITLE
python 版本

### ISSUE THREAD

**Issue by hacker-wei** [MVIG-SJTU/AlphaPose#340]
你好。我现在想把输入换成我的图片，可是现在出现了这个错误
![图片](https://user-images.githubusercontent.com/32689594/57591931-87fb0600-7566-11e9-9a75-6662a07fc508.png)是不是python版本需要2版本的？？？

**Comment by hacker-wei** [comment]
如何将这个json文件里面的内容显示出来呢？？？请问能不能麻烦您提供一下代码？

**Comment by GuoHaiYang123** [comment]
我也遇到这个问题，Pytorch版本的找不到训练代码入口，只能demo,Mxnet版本的配置了出问题，各种files not found

**Comment by Fang-Haoshu** [comment]
@GuoHaiYang123 pytorch版本的训练代码不是在https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/train_sppe吗..

**Comment by GuoHaiYang123** [comment]
谢谢，我找到了，但貌似只是SPPE的训练代码，有全部的训练代码吗？ @Fang-Haoshu

**Comment by QuYJLeo** [comment]
> 谢谢，我找到了，但貌似只是SPPE的训练代码，有全部的训练代码吗？ @Fang-Haoshu

你好，你有mxnet版本的关于mpii的训练代码吗，作者只提供了coco的训练代码。。
