### ISSUE TITLE
显示33个关键点

### ISSUE THREAD

**Issue by Erikfather** [MVIG-SJTU/AlphaPose#342]
直接调用训练好的duc_se.pth模型，显示的依然是coco数据集的17个关键点，但是opt里面是33，请问我应该怎么显示全部的33个关键点呢，或者只显示mpii的16个关键点，谢谢

**Comment by YuliangXiu** [comment]
please refer to https://github.com/MVIG-SJTU/AlphaPose/blob/master/doc/output.md
