### ISSUE TITLE
查看参数值以及mAP

### ISSUE THREAD

**Issue by yyyyyff** [MVIG-SJTU/AlphaPose#343]
您好，请问duc_se.pth就是你们训练好的模型吗？
请问要怎么打开这个pth文件来查看各个参数（例如loss值，学习率等）的值呢？
以及，论文中对于coco数据集测评的mAP值是如何通过代码求出的呢？

**Comment by yyyyyff** [comment]
除此之外，如何查看每层的权重呢？

**Comment by Fang-Haoshu** [comment]
Hi, you can refer to pytorch forum. Best.
