### ISSUE TITLE
关于人脸、手部及其他关键点训练问题

### ISSUE THREAD

**Issue by wduo** [MVIG-SJTU/AlphaPose#344]
Hi @Jeff-sjtu @Fang-Haoshu 请问能否将Alphapose用于人脸、手部或足部关键点训练呢(若已具备对应的目标检测算法)？您有什么好的建议或意见吗？

**Comment by YuliangXiu** [comment]
not yet, current alphapose can only be used for body keypoint estimation. If you want to use it on face or hand, you need to train the facial landmark estimator and hand keypoint estimator seperately

**Comment by wduo** [comment]
@YuliangXiu 感谢您的回复！
也就是说，如果我有人脸关键点的标注数据，那么就可以用Alphapose框架来训练人脸关键点估计？(假设已经有人脸检测器)
@YuliangXiu @zhijian-liu @Fang-Haoshu @Jeff-sjtu 如果直接将Alphapose人体关键点估计程序用于人脸关键点估计的训练，您认为可行吗？
