### ISSUE TITLE
请问这个关节点是2D还是3D？

### ISSUE THREAD

**Issue by hacker-wei** [MVIG-SJTU/AlphaPose#347]
我用视频数据集进行提取关节点的时候，为啥我是51个点，是不是三个值表示一个关节点
![图片](https://user-images.githubusercontent.com/32689594/58300844-d3d76600-7e16-11e9-84cc-17b6316a81d4.png)

**Comment by YuliangXiu** [comment]
Please refer to https://github.com/MVIG-SJTU/AlphaPose/blob/master/doc/output.md for the output format
