### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by littlestrange** [MVIG-SJTU/AlphaPose#349]
I only got the information ''Segmentation fault'' when I ran ython3 video_demo.py --video /home/jimy/caffe/caffe/caffe_rtpose/2.mp4 --outdir examples/res --2.mp4.
 appreciated for any tips for solving this .

**Comment by Fang-Haoshu** [comment]
what is --2.mp4?

**Comment by littlestrange** [comment]
2.mp4 is just a video as a input for the video_demo.py. I had debug video_demo.py using GDB instrument ,the infomation as follow:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff16152a9 in GlobalError::PushToStack() ()
   from /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0
Any tips will be appreciated @Fang-Haoshu

> I only got the information ''Segmentation fault'' when I ran ython3 video_demo.py --video /home/jimy/caffe/caffe/caffe_rtpose/2.mp4 --outdir examples/res --2.mp4.
> appreciated for any tips for solving this  @Fang-Haoshu

**Comment by Fang-Haoshu** [comment]
python3 video_demo.py --video /home/jimy/caffe/caffe/caffe_rtpose/2.mp4 --outdir examples/res
I think it should work. It's pretty weird...
