### ISSUE TITLE
Makefile:5: recipe for target `clean' failed make: *** [clean] Error 127

### ISSUE THREAD

**Issue by garimss** [MVIG-SJTU/AlphaPose#350]
I am running this on anaconda command prompt on windows 10. Getting this error each time. Not sure what is the reason? 

(base) D:\git_hub\AlphaPose\human-detection\lib>make clean
      0 [main] make 2088 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
rm -rf *.pyc
make: /bin/sh: Command not found
Makefile:5: recipe for target `clean' failed
make: *** [clean] Error 127

**Comment by Fang-Haoshu** [comment]
the master branch is not supposed to support windows. please refer to the pytorch branch
