### ISSUE TITLE
Flip inference not in MXNET

### ISSUE THREAD

**Issue by learnermaxRL** [MVIG-SJTU/AlphaPose#351]
Hi,

MXnet version is faster,i can see that you have not used flipped inference which you are using in alphapose.Is it intentional?
If no can you please provide pointers for flipped average inference in MXNet model as well

**Comment by Jeff-sjtu** [comment]
Hi, we use flipped average in training phase.
https://github.com/MVIG-SJTU/AlphaPose/blob/mxnet/train.py#L200

**Comment by learnermaxRL** [comment]
why not during infrence as well?

**Comment by Jeff-sjtu** [comment]
Actually, you can use it in the inference phase. We forgot to add this feature at that time.

**Comment by learnermaxRL** [comment]
Already added it might have effects on accuracy,also the way threading and queue have been used more often than not the algo runs in race condition when starting and sometimes increasing batch size in bbox prediction misses boxes.
Do you know why that happens?

**Comment by GuoHaiYang123** [comment]
Do you have annot_clean.h5 file? If you got it,can you send it to my mailbox 2423419980@qq.com,thanks a lot.
