### ISSUE TITLE
AssertionError: Cannot capture source

### ISSUE THREAD

**Issue by garimss** [MVIG-SJTU/AlphaPose#352]
(caffe) D:\git_hub\pytorch_alphapose\AlphaPose>python video_demo.py --video examples/video/exit_row.mp4 --outdir examples/res --save_video --sp
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:901)
warning: examples/video/exit_row.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:902)
Traceback (most recent call last):
  File "video_demo.py", line 41, in <module>
    data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()
  File "D:\git_hub\pytorch_alphapose\AlphaPose\dataloader.py", line 185, in __init__
    assert self.stream.isOpened(), 'Cannot capture source'
AssertionError: Cannot capture source

**Comment by Vacumn** [comment]
have the same question too

**Comment by Vacumn** [comment]
have you sorted it?
