### ISSUE TITLE
muti-gpu is bad than single-gpu

### ISSUE THREAD

**Issue by liuxufenfeiya** [MVIG-SJTU/AlphaPose#357]
在8块1080ti下，分别用单gpu和多gpu测试，进行视频检测，
多gpu时，我加了一行代码，nn.DataParallel(net, device_ids=[1,2,3])，分别放到调用yolo和sppe那里，
跑的时候发现，单gpu平均60帧左右，gpu使用率70%，多gpu不到40帧，每个gpu使用率不到30%,单gpu效果要远远好于多gpu，很奇怪？

**Comment by Fang-Haoshu** [comment]
可能这时候CPU或者硬盘的性能变成瓶颈了吧
