### ISSUE TITLE
Invalid syntax sppe/models/fn.py

### ISSUE THREAD

**Issue by pcriadoperez** [MVIG-SJTU/AlphaPose#365]
Hi I am trying to get the demo.py running and I get this error:

sppe/models/fn.py, line 67
print(f'==={name}===')
Syntax error: Invalid syntax

**Comment by learnermaxRL** [comment]
{} should be accompanied by .format(),change it or delete it?

**Comment by Fang-Haoshu** [comment]
Thanks @learnermaxRL
