### ISSUE TITLE
No module named 'torch._six'

### ISSUE THREAD

**Issue by songfish** [MVIG-SJTU/AlphaPose#368]
My environment
python 3.6.2
cuda 9.0
pytorch 0.1.12

When I run this in terminal: 
python demo.py --indir /data/yusong/code/AlphaPose-pytorch/examples/demp/image/ --save_img

Traceback(most recent call last):
File "demo.py", line 11, in <module>
from dataloader import ImageLoader, DetectionLoader, DetectionProcessor, DataWriter, Mscoco
File "......./dataloader.py", line 35, in <module>
from fn import vis_frame
File".../fn.py", line 5, in <module>
from torch._six import string_classes, int_classes
ModuleNotFoundError: No module named 'torch._six'

**Comment by Fang-Haoshu** [comment]
pytorch 0.1.12 is too old. We need pytorch 0.4.0
