### ISSUE TITLE
How to use the retrained-yoloV3-weights to replace the default-yoloV3-weights?

### ISSUE THREAD

**Issue by Yuyang-999** [MVIG-SJTU/AlphaPose#371]
In pytorch version:
How to use the retrained-yoloV3-weights to replace the default-yoloV3-weights?
The retrained-yoloV3-weights may be suitable for particular use. 
Thanks.

**Comment by learnermaxRL** [comment]
Load the model file in the line
self.det_model.load_weights('models/yolo/yolov3-spp.weights') in Pytorch ?

You have to load the weights in Detection stage which outputs the boxes for pose prediction.
