### ISSUE TITLE
How can i choice GPU ID， I have two GPU，but one of them is too old    i am running  PyTorch version

### ISSUE THREAD

**Issue by laomaup** [MVIG-SJTU/AlphaPose#372]

**Comment by learnermaxRL** [comment]
Run  different instance of programme on different gpus ,you can change CUDA_VISIBLE_DEVICES in each of the script and run the models.

**Comment by Fang-Haoshu** [comment]
CUDA_VISIBLE_DEVICES=1 python3 demo.py

**Comment by GuoHaiYang123** [comment]
Where to change the script     @@@@as"CUDA_VISIBLE_DEVICES=1"? 
@Fang-Haoshu @learnermaxRL
