### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = './data/coco/annot_clean.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by GuoHaiYang123** [MVIG-SJTU/AlphaPose#373]
where is the "annot_clean.h5"?

**Comment by Fang-Haoshu** [comment]
Sorry, it should be annot_coco.h5, just fix it. BTW, mxnet training cannot reproduce the accuracy due to SGD problem, we are still looking into the problem and the current weights are transfered from pytorch version.

**Comment by GuoHaiYang123** [comment]
ok,I got it,thanks a lot.




------------------ 原始邮件 ------------------
发件人: "Fred Fang"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上8:22
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com>;
抄送: "郭海洋"<2423419980@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MVIG-SJTU/AlphaPose] OSError: Unable to open file (unable toopen file: name = './data/coco/annot_clean.h5', errno = 2, error message = 'Nosuch file or directory', flags = 0, o_flags = 0) (#373)




Sorry, it should be annot_coco.h5, just fix it. BTW, mxnet training cannot reproduce the accuracy due to SGD problem, we are still looking into the problem and the current weights are transfered from pytorch version.
