### ISSUE TITLE
PoseFlow : Posetrack Dataset decompression error

### ISSUE THREAD

**Issue by gregoireandre** [MVIG-SJTU/AlphaPose#38]
Hello,

First of all thank you for sharing your implementation which seems really promising ! I tried to install following the Readme instructions but when I try to download the data from posetrack using :
cat *.tar* | tar -xvf - -i
I run into an error ..
It seems that some images are corrupted and so the decompression fails.
Did you have similar problems during decompression of the dataset ? If so how did you solve the problem ?
Finally, is it necessary to download the whole posetrack dataset or only specific batch ? Would it be possible to add those informations in the Readme ?

Thank you again for sharing your work,

Cheers

**Comment by YuliangXiu** [comment]
Hi,
You can see #35 . There are 8 tar files in total. You need to download all of them and then use `cat *.tar* | tar -xvf - -i` for decompression.

**Comment by YuliangXiu** [comment]
@gregoireandre Can you decompress these tar files successfully now?
