### ISSUE TITLE
Module 'torch.nn' has no attribute 'ModuleDict'

### ISSUE THREAD

**Issue by carolynenewman** [MVIG-SJTU/AlphaPose#385]
While working on demo.py, I am getting the error: AttributeError: module 'torch.nn' has no attribute 'ModuleDict'. I am working in a Conda virtual env, with Pytorch 0.4.0 installed. I tried downloading Pytorch 2.2 but my computer says that it is not available to install. Any suggestions? Thanks!

**Comment by Sentient07** [comment]
Guess this might be helpful : https://github.com/MVIG-SJTU/AlphaPose/issues/359
