### ISSUE TITLE
Key point output problem

### ISSUE THREAD

**Issue by sdustdk1427** [MVIG-SJTU/AlphaPose#386]
Excuse me, I want to change the coordinates of the output of the key points to integer format, where should I change?

**Comment by eri820503** [comment]
I also have same question. I follow run.md and output.md to run demo.py while setting --format open and --dataset mpii. But the output still has 17 parts which likes default. Any other option should also be set?

**Comment by eri820503** [comment]
I have the answer from https://github.com/MVIG-SJTU/AlphaPose/issues/158.
Thanks
