### ISSUE TITLE
Reproducing trained SPPE model

### ISSUE THREAD

**Issue by ariel415el** [MVIG-SJTU/AlphaPose#390]
Hi, I was trying to reproduce the **duc_se.pth** model but without success.

I'm using the code in train_sppe with the default parameters in opt.py.
The model trains well and the train and validation losess decrease nicely, Nevertheless the results I'm getting after ~48 hr with a 1080TI (#318)  are not as good as your trained model.

Can you confirm the model was trained with the default parameters in the opt.py file?
Did you train on COCO only or other datasets?
Can you share the time it took the model to get this good?

Thanks

**Comment by Fang-Haoshu** [comment]
Hi，the released model was trained on MPII, COCO and AIC

**Comment by ariel415el** [comment]
Thanks. 
Can you please elaborate about training time and hyper parameters?
