### ISSUE TITLE
train_sppe 是crowdpose的么？

### ISSUE THREAD

**Issue by surelyee** [MVIG-SJTU/AlphaPose#391]
pytorch版本的代码sppede 权重duc_se.pth是crowdpose的么？里边再训练sppe的时候有论文中interference joint那部分么？

**Comment by Fang-Haoshu** [comment]
Hi，目前应该还没有，谢谢

**Comment by ZJU-lishuang** [comment]
Did you plan to release out the train code for the crowdpose?And If you plan to do this, can you tell me the time?
