### ISSUE TITLE
about the version of pytorch

### ISSUE THREAD

**Issue by kingwii** [MVIG-SJTU/AlphaPose#392]

**Comment by kingwii** [comment]
my pytorch version is 1.1.0 ,but you need 0.4.0,can it work ,and i meet this question
nvidia@nvidia-desktop:~/AlphaPose$ python3 demo.py --indir examples/demo/ --outdir examples/result
Loading YOLO model..
THCudaCheck FAIL file=/home/nvidia/pytorch/torch/csrc/generic/StorageSharing.cpp line=245 error=71 : operation not supported

can you give me some advice ,my tools is nvidia jeston tx2

**Comment by kingwii** [comment]
RuntimeError: cuda runtime error (71) : operation not supported at /home/nvidia/pytorch/torch/csrc/generic/StorageSharing.cpp:245
 i am totally a freshman about pytorch ,and installing it takes me a lot of time ,and it work much more diffcult than caffe , so ,please give me some advice
thank you

**Comment by liuxufenfeiya** [comment]
没问题的，我的pytorch1.1的版本都能正常跑

**Comment by Fang-Haoshu** [comment]
Hi, I can work with pytorch 1.1, so it maybe some other problems?

**Comment by Luyang1125** [comment]
I got the same issue. Did you fix it already?

**Comment by kingwii** [comment]
of course l find the solution for mine.l add the' --sp' ,then it works well

**Comment by kingwii** [comment]
@Luyang1125 maybe it will help you
