### ISSUE TITLE
PoseFlow: is image dir input necessary?

### ISSUE THREAD

**Issue by JoeyChuuichi** [MVIG-SJTU/AlphaPose#393]
The example code needs a imgdir input.
However, my application is a video with lots of frames. 
If I output each frame, it takes a large amount of time and space. 
```
python tracker-general.py --imgdir ${image_dir}$ 
                          --in_json ${results_dir}$/alphapose-results.json 
                          --out_json ${results_dir}$/alphapose-results-forvis-tracked.json
                          --visdir ${render_dir}$
```
From your research paper, I think it may be possible for the algorithm to track the identity only through the json file where there are the keypoints pixel locations.
Is there any such function in the project?

我会说中文, 欢迎用中文讨论

**Comment by JoeyChuuichi** [comment]
My targe is to output a format like this 
```
{
    "person1":[
        {"joints in frame1":[x1,y1,c1,...,xk,yk,ck]},
        {"joints in frame2":[x1,y1,c1,...,xk,yk,ck]},
        ....
        {"joints in frame_last":[x1,y1,c1,...,xk,yk,ck]},
    ],
.
.
.
    "person_n":[
        {"joints in frame1":[x1,y1,c1,...,xk,yk,ck]},
        {"joints in frame2":[x1,y1,c1,...,xk,yk,ck]},
        ....
        {"joints in frame_last":[x1,y1,c1,...,xk,yk,ck]},
    ],

}
```
Is there any quick way so that I can have data of this type?

**Comment by Fang-Haoshu** [comment]
Hi currently the image dir is necessary for computing frame-wise features. You can modify the code to directly access frames in videos instead.

**Comment by JoeyChuuichi** [comment]
@Fang-Haoshu 
Okay I will have a try.
