### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Vacumn** [MVIG-SJTU/AlphaPose#397]
python3 video_demo.py --video Desktop/videos/ --outdir examples/res --save_video
Traceback (most recent call last):
  File "video_demo.py", line 41, in <module>
    data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()
  File "/home/bozhon/AlphaPose-pytorch/dataloader.py", line 185, in __init__
    assert self.stream.isOpened(), 'Cannot capture source'
AssertionError: Cannot capture source

How am I going to sort it out?
Any help, many thanks

**Comment by Fang-Haoshu** [comment]
--video Desktop/videos/Videoname, such as --video Desktop/videos/ 1.mp4

**Comment by wwdok** [comment]
> --video Desktop/videos/Videoname, such as --video Desktop/videos/1.mp4

I run with `python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --outdir examples/res --vis --webcam 0`,still have this issue

**Comment by hemuhang2002** [comment]
I met the same problem when I try
`python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml  --checkpoint pretrained_models/fast_res50_256x192.pth --outdir examples/res/webcam --vis --webcam 0`
the error:
`Traceback (most recent call last):
  File "scripts/demo_inference.py", line 170, in <module>
    det_loader = WebCamDetectionLoader(input_source, get_detector(args), cfg, args)
  File "/root/AlphaPose/alphapose/utils/webcam_detector.py", line 20, in __init__
    assert stream.isOpened(), 'Cannot capture source'
AssertionError: Cannot capture source`

**Comment by grayskripko** [comment]
webcam stream won't work in a straightforward manner in Google Colab.
Just asked ChatGPT to write a function that starts capturing frames when I press Capture and ends with Stop, limiting to 100. The second return object it time left from the previuos frame shot

```
import cv2
import numpy as np
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photos(max_frames=100):
  js = Javascript('''
    async function takePhotos(maxFrames) {
      const div = document.createElement('div');
      const stop = document.createElement('button');
      stop.textContent = 'Stop';
      div.appendChild(stop);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      let capturing = true;
      const dataArray = [];
      const timeArray = [];
      let prevTime = Date.now();
      let frameCount = 0;

      stop.onclick = () => {
        capturing = false;
        stream.getVideoTracks()[0].stop();
        div.remove();
      };

      while (capturing && frameCount < maxFrames) {
        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);

        const currentTime = Date.now();
        const elapsedTime = currentTime - prevTime;
        prevTime = currentTime;
        timeArray.push(elapsedTime);

        dataArray.push(canvas.toDataURL('image/jpeg'));

        frameCount++;

        await new Promise(resolve => setTimeout(resolve, 100));
      }

      return {dataArray, timeArray};
    }
    ''')
  display(js)
  result = eval_js('takePhotos({})'.format(max_frames))
  data_urls = result['dataArray']
  time_deltas = result['timeArray']

  frames = []

  for data_url in data_urls:
    binary = b64decode(data_url.split(',')[1])
    img_np = cv2.imdecode(np.frombuffer(binary, dtype=np.uint8), cv2.IMREAD_COLOR)
    frames.append(img_np)

  return frames, time_deltas


```
