### ISSUE TITLE
Ask for updated paper 

### ISSUE THREAD

**Issue by Xiangyu-CAS** [MVIG-SJTU/AlphaPose#4]
Hi,  I noticed this edition of RMPE performanced much better than before, from 61% mentioned in ICCV paper to 72%.   

However, I just checked the link of paper and found out it had not been updated yet.  So, when will the updated paper be released ?

At last, congratulation for your great work .

**Comment by Fang-Haoshu** [comment]
Hi, thanks~ We have submitted a new version of paper to arXiv and it will be updated very soon.

**Comment by Fang-Haoshu** [comment]
The paper on our website has been updated! Check it out here: http://mvig.sjtu.edu.cn/research/alphapose/rmpe.pdf

**Comment by Xiangyu-CAS** [comment]
: ) Thanks ！
