### ISSUE TITLE
How to deal with invisible keypoint?

### ISSUE THREAD

**Issue by lilhope** [MVIG-SJTU/AlphaPose#40]
Hi, MVIG groups:
     I'm quite a newer for human keypoint detection, thanks for your excellent work. I have a question, how to deal with invisible keypoints during train? And, I can't find the preprocess code for MSCOCO to make the `annt.h5` file, so I'm confused.

**Comment by Fang-Haoshu** [comment]
Hi,
for invisible keypoints, the label is a heatmap without activation.
The annot.h5 is uploaded and you can use it directly.

**Comment by kl456123** [comment]
Hi, I want to know that if I train model with invisible points , will the performance drop ?
