### ISSUE TITLE
Difference between yolov3-spp.weights and old yolov3.weights?

### ISSUE THREAD

**Issue by djr2015** [MVIG-SJTU/AlphaPose#400]
I noticed you changed the yolov3 weights file name and model in Sept 2018. Going by previous comments it seems that the previous model was obtained by just training for object detection task on COCO. I was wondering if the new model is different from the old one and if so how?

**Comment by Fang-Haoshu** [comment]
Hi, thanks for the post. The spp version is a new yolo version updated by the yolo author. You can check the yolo's official website for more details.
