### ISSUE TITLE
Can't build on Ubuntu

### ISSUE THREAD

**Issue by jakezhaojb** [MVIG-SJTU/AlphaPose#401]
Hi Fellows,

  Is this repository still maintained? When I ran through the instruction, I found it not compiled properly:

`cpu_nms.c: In function ‘__pyx_pf_7cpu_nms_cpu_soft_nms’:
cpu_nms.c:2226:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_8 = ((__pyx_v_pos < __pyx_v_N) != 0);
                               
cpu_nms.c:2737:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_8 = ((__pyx_v_pos < __pyx_v_N) != 0);
                               
cpu_nms.c: In function ‘__Pyx_PyCFunction_FastCall’:
cpu_nms.c:8496:12: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth’
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
            ^
cpu_nms.c: In function ‘__Pyx__ExceptionSave’:
cpu_nms.c:8926:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     *type = tstate->exc_type;
                   ^
cpu_nms.c:8927:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     *value = tstate->exc_value;
                    ^
cpu_nms.c:8928:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     *tb = tstate->exc_traceback;
                 ^
cpu_nms.c: In function ‘__Pyx__ExceptionReset’:
cpu_nms.c:8935:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                      ^
cpu_nms.c:8936:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                       ^
cpu_nms.c:8937:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                    ^
cpu_nms.c:8938:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = type;
           ^
cpu_nms.c:8939:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = value;
           ^
cpu_nms.c:8940:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = tb;
           ^
cpu_nms.c: In function ‘__Pyx__GetException’:
cpu_nms.c:8995:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                      ^
cpu_nms.c:8996:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                       ^
cpu_nms.c:8997:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                    ^
cpu_nms.c:8998:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = local_type;
           ^
cpu_nms.c:8999:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = local_value;
           ^
cpu_nms.c:9000:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = local_tb;
`

**Comment by Fang-Haoshu** [comment]
Hi, it looks weird. We haven't met that before. I would recommend using the pytorch branch since it's more user friendly

**Comment by Fang-Haoshu** [comment]
I guess you are runing the master branch?
