### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by jakezhaojb** [MVIG-SJTU/AlphaPose#403]
Dear authors,

  Do you plan on updating the repo with a newer version of PyTorch? In particular, PyTorch 0.4.0 isn't available on pip anymore..

**Comment by Fang-Haoshu** [comment]
Oh I see... Thanks! We have tested with PyTorch v1.1 so far. Perhaps you can use pytorch 1.1. We are currently developing new models and re-organizing our code. Will release them soon! Many thanks!

**Comment by jakezhaojb** [comment]
thank you Fang
