### ISSUE TITLE
關於使用到的SPPE

### ISSUE THREAD

**Issue by eric8607242** [MVIG-SJTU/AlphaPose#404]
您好，想請問此AlphaPose的實做中所使用的SPPE，是否為論文上所提到的Stacked hourglass
networks，因為看程式碼中有看到相關的module，可是並沒有使用到，非常謝謝您的回覆

**Comment by Fang-Haoshu** [comment]
您好，master branch使用的是stacked hourglass， pytorch用的是我们的新模型，可以参见crowdpose的论文，谢谢

**Comment by eric8607242** [comment]
了解了～謝謝您的回覆
