### ISSUE TITLE
关于PoseNMS的问题

### ISSUE THREAD

**Issue by tangchen2** [MVIG-SJTU/AlphaPose#406]
您好作者，这段时间学习阅读了pytorch版本AlphaPose的代码，关于PoseNMS部分有一些疑惑，在predict的pPose_nms.py中pose_nms中第一步是常规的nms，通过相似度的比较来选出picked_id以及重叠被舍弃的merge_id，但之后第二部分p_merge_fast有些没太明白为什么要有这步操作，看起来像是根据对应的picked_pose在merge_pose中求取了一个总和的值，然后作为最终pose的预测。
疑惑的是 为什么不直接将第一步求出的pick_id对应的pose作为最终预测呢？
希望作者能帮忙解答一下，十分感谢！

**Comment by Fang-Haoshu** [comment]
也可以的哈，只是merge一下效果可能好一些~
