### ISSUE TITLE
Is Alphapose used for gait identification?

### ISSUE THREAD

**Issue by Arroosh** [MVIG-SJTU/AlphaPose#408]
Hello!
@Fang-Haoshu Is there any way to use multi person pose estimation for identification purpose? Or can you upgrade the code for identification purpose in the near future.

Thanks in advance

**Comment by Fang-Haoshu** [comment]
Hi! Maybe you can try pose tracking in our repo?

**Comment by Fang-Haoshu** [comment]
No response, closed
