### ISSUE TITLE
FLIP THE IMAGE BEFORE TRANING

### ISSUE THREAD

**Issue by carolchenyx** [MVIG-SJTU/AlphaPose#412]
The codes are very great. I want to flip the images and then put them to retrain the model. I flipped the coco dataset , and chang the coordinates of bndboxes and keypooints.    
    bndboxes[i][0][1] =  height - bndbox_right_y
    bndboxes[i][0][3] =  height - bndbox_left_y
    parts[i][j][1]  = height - parts_item[1]
But the acc is very row. when epoch is 50, the acc is about 22%. I don't know why and need your suggestion. Many thanks.

**Comment by GuoHaiYang123** [comment]
Can you tell me how to change the coordinates of keypoints in ".json file" after flipping the coco dataset?Could you send the code for me?my mailbox is 2423419980@qq.com,thanks a  lot.

**Comment by Fang-Haoshu** [comment]
Hi, I guess a better method is to rotate the cropped image for 180 degrees. Thus, you don't need to modify the bounding boxes.
