### ISSUE TITLE
nvcc binary could not be ?

### ISSUE THREAD

**Issue by ZAtakan** [MVIG-SJTU/AlphaPose#413]
Hello
I was just trying to test the code but received the following after make; can anyone help please ?

python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
MAKE: *** [all] Error 1

**Comment by Fang-Haoshu** [comment]
Hi! Are nvidia driver and cuda installed properly?
