### ISSUE TITLE
sub sampling videos

### ISSUE THREAD

**Issue by songkevinc** [MVIG-SJTU/AlphaPose#414]
I was wondering if you have any options to sub sample videos, so that we just run the algorithm for every 3rd frame. I think I can just add something to the VideoLoader to do that, but I thought this might also be a good option to have in general. Please let me know what you think and any help would be appreciated!

**Comment by Fang-Haoshu** [comment]
Hi, yeah, you can modify the VideoLoader and drop 2 frames every time when you are extracting frames.

**Comment by Fang-Haoshu** [comment]
https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/dataloader.py#L232
The simplest way is to read three times and save for only one time.
