### ISSUE TITLE
run out of memory while run video_demo with .MOV files

### ISSUE THREAD

**Issue by thancaocuong** [MVIG-SJTU/AlphaPose#415]
Hi, I have ran video_demo.py with avi file and it's perfect. But when I tried to run with .mov video, my ram usage increased steady. I did read #227 and find maybe it's similar.
`line 59, in prep_frame
    img_ = img[:, :, ::-1].transpose((2, 0, 1)).copy()
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (3, 608, 608) and data type int64`
do you have any suggestions for me? thank you all!

**Comment by Fang-Haoshu** [comment]
Well, a possible reason is that decoding .MOV file needs large RAM for opencv. It's hard for us to locate the problem for now because I guess it's related to decoder problem... Sorry for that, but I guess you can convert the video using another command like ffmpeg first?

**Comment by thancaocuong** [comment]
thank you, I will try

**Comment by thancaocuong** [comment]
@Fang-Haoshu  I think it may be because my videos have lots of people, so when jump to dynamic_write_results function in ./yolo/util,py, this function costs a lot of ram.
