### ISSUE TITLE
放弃阉割了STN的pytorch，测试结果coco-minival500_images.txt 就0.69mAP，不建议这版本放入论文cp

### ISSUE THREAD

**Issue by liuchanfeng165** [MVIG-SJTU/AlphaPose#419]
几个月前搞好的，本来想放入论文对比，呵呵，为了尊重作者的“辛苦”，算了。。。
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.687
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.872
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.752
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.633
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.774
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.720
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.889
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.778
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.661
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.809
(0.6865449578411594, 0.872474837601182)
如果测试完整的val2017，结果不敢想象，不敢用这些放入论文对比。。。。
话说，论文留下8k测试评估，那结果是。。。。希望公开pkl文件，对比对比。。。
特别是训练那里，说去掉BN层就能够达到90% acc——祝各位好好研究caffe板。。。

**Comment by Fang-Haoshu** [comment]
Hi, 感谢关注！
你是想说论文里的点数问题？AlphaPose是基于我们系列工作rmpe，crowdpose，poseflow中积累的经验开源的pose姿态库，比ICCV发表的论文高了不少，不过还没有新paper，未来可以发布一下。COCO leaderboard（http://cocodataset.org/#keypoints-leaderboard）上有我们之前上传的结果的分数（fast-20-fps， 71.7），也可以关注，另外master版本的话跑出来是72.3。如果想要复现ICCV paper，你可以看看RMPE那个repo，之前我在一些issue里也有回复过。
pytorch版用的detector和pose estimator都跟ICCV paper不一样，为了方便学界同行使用，着重进行了速度上的优化，pth也全都公开了哈。
训练那里也不是去掉BN，而是pytorch有BN的bug需要关掉。另外我们讨论了一下，不知道你说的8k测试评估和caffe版是在指哪方面的疑惑呢？
不过话说回来，我们最近正准备继续升级AlphaPose，比现在更高更快更强！欢迎关注！


> 几个月前搞好的，本来想放入论文对比，呵呵，为了尊重作者的“辛苦”，算了。。。
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets= 20 ] = 0.687
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets= 20 ] = 0.872
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets= 20 ] = 0.752
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.633
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.774
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 20 ] = 0.720
> Average Recall (AR) @[ IoU=0.50 | area= all | maxDets= 20 ] = 0.889
> Average Recall (AR) @[ IoU=0.75 | area= all | maxDets= 20 ] = 0.778
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.661
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.809
> (0.6865449578411594, 0.872474837601182)
> 如果测试完整的val2017，结果不敢想象，不敢用这些放入论文对比。。。。
> 话说，论文留下8k测试评估，那结果是。。。。希望公开pkl文件，对比对比。。。
> 特别是训练那里，说去掉BN层就能够达到90% acc——祝各位好好研究caffe板。。。

**Comment by liuchanfeng165** [comment]
1.研究工作重要程度，大家心知肚明，但对于使用者而言重点不是多好，而是原训练好的模型评估结果尽可能如README所说；
2.看过许多CVPR，ICCV论文目标检测和训练大家都知道，论文迭代次数可以和我们训练迭代次数不一样，但结果相差很大，咋办，谁放心比较，万一自己论文被reject呢，谁又能说自己的模型就比人家好，多训练一次两次都可以（事实上更多，耗时就两三天）；
3.我们辛辛苦苦改好了，调好了，结果训练过程epoch居然远远超过原作的，结果却不行 #188，好在总有两三篇论文的代码训练后比较接近原作。耳。。。

**Comment by liuchanfeng165** [comment]
补充，为了证明STN有效性（因为该模型加入不了pytorch一起训练，忘了哪个issue说了），大可用GTbbox测试预训练模型，mAP=70%：
alphapose-results-gt_bbox  
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.698
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.887
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.762
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.647
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.773
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.728
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.893
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.783
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.675
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.807
(0.6980530843133953, 0.8870391458040584)

**Comment by Jeff-sjtu** [comment]
@liuchanfeng165 你好，需要与paper结果比较，请比较[RMPE论文的代码](https://github.com/MVIG-SJTU/RMPE)，AlphaPose Pytorch分支的结果目前并不对应任何一篇论文。
AlphaPose是我们基于之前系列工作，平衡了检测的速度与精度而开源的pose姿态库。PyTorch分支目前由于版本滞后（pytorch 0.4.0）的原因，会带来很多问题。支持pytorch 1.1以上版本代码的开发进度已接近尾声，届时会修复当前版本代码的各种issue，训练精度也有很大的提高。同时，我们会放出训练log，以方便开发者复现。
感谢您的关注。

**Comment by DonaldKam** [comment]
@liuchanfeng165   Hey it seems you achieve the test on minival500_images.txt. I checked the files times and could not find the corresponding h5 annot file, could you plz tell me how to get the h5 annot file?

**Comment by DonaldKam** [comment]
@Jeff-sjtu  I checked the files times and could not find the corresponding h5 annot file, could you plz tell me how to get the h5 annot file?

**Comment by liuchanfeng165** [comment]
> @liuchanfeng165 Hey it seems you achieve the test on minival500_images.txt. I checked the files times and could not find the corresponding h5 annot file, could you plz tell me how to get the h5 annot file?

AlphaPose/train/data/coco/anno.h5
actually u could  reference it  as follow:
    #print(h5_imgname)
    h5_imgname = np.array(h5_imgname)
    h5_bndbox = np.array(h5_bndbox)
    h5_keypoints = np.array(h5_keypoints)
    #print(h5_imgname)
    h5file = h5py.File('./'+name , 'w')
    h5file.create_dataset('imgname', data=h5_imgname)
    h5file.create_dataset('bndbox',data=h5_bndbox)
    h5file.create_dataset('part',data=h5_keypoints)

https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/train_sppe
