### ISSUE TITLE
How to choose the score threshold for each joints

### ISSUE THREAD

**Issue by adwardlee** [MVIG-SJTU/AlphaPose#420]
Hi @all,
Thanks for providing the code. After running the demo.py in pytorch version, it can generate file with joints locations and confidence scores. Could you please tell me how to choose the score threshold to eliminate the possibly fake joint locations? Thanks.

**Comment by Fang-Haoshu** [comment]
Hi, it depends, you can try different values to see what value is the most suitable for your project. I guess you can start with 0.2?
