### ISSUE TITLE
采用多进程运行 video_demo.py 程序停止不动 是出现死锁了吗

### ISSUE THREAD

**Issue by Fight-hawk** [MVIG-SJTU/AlphaPose#423]
CUDA_VISIBLE_DEVICES=0 python video_demo.py --video ../kanhaipeng_video.mp4  --outdir ./output --save_video
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
 13%|#######                                              | 21/158 [00:19<00:06, 22.23it/s]

**Comment by Fang-Haoshu** [comment]
你好！ 看起来有可能？可以重新跑下试试~

**Comment by Fight-hawk** [comment]
python的多进程还真是差劲 我跑了n遍了 都是一样的结果 都在这里卡住了
