### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by dmg206** [MVIG-SJTU/AlphaPose#424]
1， RMPE论文中有PGPG和 STN+Parallel SPPE ，但是开源代码中没有看到，为什么没有在开源代码中加入这两部分？
2， 对于STN+Parallel SPPE是怎么样训练的？我看了论文还是不理解具体怎么训练得？

**Comment by dmg206** [comment]
@Jeff-sjtu

**Comment by Jeff-sjtu** [comment]
你好，关于RMPE论文的代码，请参考RMPE的[code](https://github.com/Fang-Haoshu/RMPE)。
