### ISSUE TITLE
Training SPPE

### ISSUE THREAD

**Issue by DonaldKam** [MVIG-SJTU/AlphaPose#425]
Glad to find the amazing Alphapose and i try the codes in “train_sppe” and succeed in running the codes. But i am confused about the displayed information "acc". What is  the "acc" used to evaluate?  Keypoint detection? If so, where is the human detector in “train_sppe” as i think codes in “train_sppe” are only for SPPE, without human detector?
If  “train_sppe” does not  contain human detector，how can it performe keypoint detection?
Another Q，as is described in Readme， annot_coco.h5 and person_keypoints_val2014.json are needed during training SPPE，what are they used for, respectively？ If they are labels for training and validation，why not both in h5 or json format？
Looking forward to the reply.

**Comment by thancaocuong** [comment]
They generate sample box from annotation

**Comment by thancaocuong** [comment]
Btw,  I used coco api  to load data from annotation, dont need h5 file 
😂😂

**Comment by ayashaagrawal** [comment]
> I used coco api to load data from annotation
how u did it??

**Comment by Fang-Haoshu** [comment]
Hi, we update the training code for coco. It's more user-friendly now. You can check out the master branch for more details.
