### ISSUE TITLE
load model failed.

### ISSUE THREAD

**Issue by ZiFung** [MVIG-SJTU/AlphaPose#426]
AttributeError: 'NoneType' object has no attribute 'shape'

loading pose model from ./models/sppe/duc_se.pth
0%|                                                    | 0/6 [00:00<?, ?it/s]

Always 0% .

I don't know what's wrong with it.

**Comment by Fang-Haoshu** [comment]
Are you running with input dir? I guess there are some other files that are not images in the dir.

**Comment by ZiFung** [comment]
I use this:
python3 demo.py --indir examples/demo/ --outdir examples/results/ --save_img
And there are only images in examples/demo/
version:
torch==0.4.0
cuda==8.0.61
cudnn==7.13

**Comment by ZiFung** [comment]
> Are you running with input dir? I guess there are some other files that are not images in the dir.

I use this:
python3 demo.py --indir examples/demo/ --outdir examples/results/ --save_img
And there are only images in examples/demo/
version:
torch==0.4.0
cuda==8.0.61
cudnn==7.13

**Comment by ZiFung** [comment]
> Are you running with input dir? I guess there are some other files that are not images in the dir.

thanks

**Comment by Angel113110** [comment]
@ZiFung@Fang-Haoshu 
I met the same error. But in my folder, there are all images. I tried many times but failed. Can you give me some help? Thanks!
