### ISSUE TITLE
运行速度慢且GPU占用率低。

### ISSUE THREAD

**Issue by Chuangtao413** [MVIG-SJTU/AlphaPose#427]
您好，首先感谢开源。
    我下载使用的是pytorch branch下的版本，在使用video_demo.py时发现速度很慢（大约 2.9 it/s，在使用speed_up.md中的方法后速度大约为 4.5 it/s），另外CPU占用率很高，接近100%（有时却稳定在30-40%），而GPU占用率一直很低。
    我的电脑配置：i9-9900K，16G内存，RTX2080 Ti。
    环境： python 3.6 ，cuda 10.0， pytorch 1.0。
    希望您能给出如何提高速度以及在GPU上运行的意见，谢谢！
-----------------------------------------------------------------------------
Hi, thanks for open source.

I downloaded the version under pytorch branch and found it slow when using video_demo .py(about 2.9 it/s, 4.5 it/s when using the way in speed_up.md), high CPU usage （near 100% ，but sometimes stable at 30-40%）, and low GPU usage.

My computer configuration: i9-9900k, 16GB memory, RTX2080 Ti.

Environment: python 3.6, cuda 10.0, pytorch 1.0.

I hope you can give your opinion on how to improve the speed and run on the GPU. Thank you!

**Comment by Fang-Haoshu** [comment]
Hi! 请问能上传一张示例图片吗 大概视频是多少人呢

**Comment by Chuangtao413** [comment]
您好，感谢得到您的回复。运行过程状态及视频截图如下，麻烦您。
![7d3ee9d5eb8a844d7f354d9def2d246](https://user-images.githubusercontent.com/53992483/66256511-0d56af80-e7c1-11e9-9f6d-0a4238f3fdee.png)

![bedbad4723435630dca82fe66f3614b](https://user-images.githubusercontent.com/53992483/66256507-092a9200-e7c1-11e9-9793-0f13c762d285.png)

**Comment by Chuangtao413** [comment]
输入视频分辨率为1440*1080，23.98帧/秒。

**Comment by Fang-Haoshu** [comment]
噢噢 windows下由于系统原因不支持多线程，所以会慢一些

**Comment by Chuangtao413** [comment]
好的，谢谢！
