### ISSUE TITLE
Too slow or stop running when use video_demo.py

### ISSUE THREAD

**Issue by ZiFung** [MVIG-SJTU/AlphaPose#430]
I have tried video_demo.py with mp4 and avi. Both failed.
The progress bar shows the progress is always under 20% and doesn't move.
The GPU is 0%. But it has took up to 1.3GB GPU Memory already.
Please help!

**Comment by ZiFung** [comment]
![WechatIMG4736](https://user-images.githubusercontent.com/33444699/66398779-f5756a80-ea10-11e9-9b52-9d8cf33ec632.jpeg)

**Comment by Fang-Haoshu** [comment]
Hi, can you share some info of the video? Like resolution, people number, etc

**Comment by ZiFung** [comment]
Resolution: 1920 x 1080
People number: one or two
Framerate: 30f/s
Codec: H.264

**Comment by ZiFung** [comment]
When I try with the provided images demo, it sometimes works. But with my images it stays zero more often.

**Comment by ZiFung** [comment]
I found that  when I run with 100 images, it failed. But when I seperate them into ten part and run with them respectly, they are all ok!!

**Comment by Fang-Haoshu** [comment]
It sounds like the hardware resources are exhausted when running too long?

**Comment by ZiFung** [comment]
16 frames with GTX1080, exhausted for sure?

**Comment by ZiFung** [comment]
openpose works fine, thanks.
