### ISSUE TITLE
关于feature map和sppe网络结构的一些问题

### ISSUE THREAD

**Issue by EasonGZY** [MVIG-SJTU/AlphaPose#436]
您好,我想要提取alphapose姿态识别对每个图片的特征值，这个特征值应该位于sppe网络的feature map位置吧？请问这个应该在sppe文件夹的哪个文件可以找到姿态识别的特征提取信息呢？

**Comment by Fang-Haoshu** [comment]
您好，我们没有保存feature map

**Comment by EasonGZY** [comment]
@Fang-Haoshu 好的，还想问下具体用到对单人姿态估计的网络分别是哪些吗？我想自己写一个输出feature map的脚本
