### ISSUE TITLE
Get results in MPii keypoint order ?

### ISSUE THREAD

**Issue by energizer92** [MVIG-SJTU/AlphaPose#438]
Hi,

i am not sure if i understood this correct. Can i setup the keypoint order for MPII ?
In https://github.com/MVIG-SJTU/AlphaPose/blob/master/doc/output.md it says there are Results for COCO and MPII - but i only get keypoints in the COCO order 

what am i doing wrong ?

**Comment by Fang-Haoshu** [comment]
Hi, are you running with master branch or pytorch branch?

**Comment by energizer92** [comment]
i think its the pytorch branch but i am not sure - did download this like 4months ago

**Comment by Fang-Haoshu** [comment]
I guess you need to check your branch cause their usages are different

**Comment by energizer92** [comment]
hm does this rly matter ? The output.md for pytorch and master is the same

**Comment by TimeEternal** [comment]
see SPPE/src/main_fast_inference.py
in the forward function, out has the shape of (N,33,80,64 ). Along dimension 1, the first seventeen numbers are coco, the others are mpii  as I think

**Comment by Ehsan-Yaghoubi** [comment]
Hi,
@Fang-Haoshu 

As the default, the produced `Json` file includes 51 integer numbers for each image. I want to get the Results for MPII (16 body parts). I tried to change coco in the code to `mpii` in several places (I changed the `--dataset` to `mpii`) of the code, but it still gives 51 points.

**Comment by TimeEternal** [comment]
>You should fix the code in `SPPE/src/main_fast_inference.py`, Line42. The first 17 channels is for coco while last 16 is mpii.

_Originally posted by @Jeff-sjtu in https://github.com/MVIG-SJTU/AlphaPose/issues/158#issuecomment-430184134_

**Comment by Fang-Haoshu** [comment]
Hi guys! I just add a new model to the model zoo. You can use the Halpe_26 keypoints version. It includes both MPII and COCO keypoints and foot keypoints, 26 points in total! You can see the demo in the readme.

**Comment by Fang-Haoshu** [comment]
@TimeEternal @energizer92 @Ehsan-Yaghoubi @
