### ISSUE TITLE
train_sppe数据集的询问

### ISSUE THREAD

**Issue by EasonGZY** [MVIG-SJTU/AlphaPose#439]
你好，我在train_sppe的README里COCO data里看到使用的coco数据集是2017，但是标注文件是person_keypoints_val2014.json的，请问二者是不是有矛盾？使用的是哪一版的coco？是否有笔误
还有想确定一下在images/trainval2017里是把训练集和验证集统一放在一个文件夹下吗？

**Comment by tianjiahao** [comment]
person_keypoints_val2014.json这个好像没有用到。训练的数据应该是作者提供的annot_coco.h5文件，是通过train2017和val2017的json文件转换的；images/trainval2017就是把训练集和验证集统一放在一个文件夹下。

**Comment by ysq319** [comment]
我一开始也疑惑，后面跑代码才发现，图片都放在images文件夹里就可以了。.json文件，好像确实没用，用的是.h5的文件。我想问的是，能不能直接用.json文件？能用的话，.h5文件跟.json文件的使用对训练有多大影响么？

**Comment by ZHyuwind** [comment]
你好，annotation的.h5文件怎么转或者.h5文件怎么获得？如果使用.json文件替换，获取变量比较麻烦。请问怎么作处理？谢谢

**Comment by tianjiahao** [comment]
@ysq319 用.json的话应该需要自己去修改代码，源码是用.h5的，至于影响的话应该不大，都是标注数据，只是数据读取格式改变了而已。
