### ISSUE TITLE
运行demo对多个文件夹下的图片遇到一些问题

### ISSUE THREAD

**Issue by EasonGZY** [MVIG-SJTU/AlphaPose#442]
您好，我看运行demo必须要手动输入图片文件夹的地址和输出位置，但我要处理的图片有很多文件夹，所以写了一个for嵌套循环来依次识别每一个文件夹下的地址，把这个地址传给了inputpath
```
args = opt
args.dataset = 'coco'
if not args.sp:
    torch.multiprocessing.set_start_method('forkserver', force=True)
    torch.multiprocessing.set_sharing_strategy('file_system')

if __name__ == "__main__":
    inputpath = args.inputpath
    data_path = r'/home/guanziyi/alphapose/test/UCF11_updated_mpg/'
    classes = ['basketball', 'biking', 'diving', 'golf_swing', 'horse_riding', 'soccer_juggling',
               'swing', 'tennis_swing', 'trampoline_jumping', 'volleyball_spiking', 'walking']
    class_name = classes[0]
    files = os.listdir(data_path + class_name)
    files = files[1:-1]
    for this_file in files:
        filename = os.listdir(data_path + class_name + '/' + this_file)
        for in_names in filename:# images'folder names
            inputpath =data_path + class_name + '/' + this_file+'/'+in_names
    inputlist = args.inputlist
    
    
    
    mode = args.mode
    if not os.path.exists(args.outputpath):
        os.mkdir(args.outputpath)

    if len(inputlist):
        im_names = open(inputlist, 'r').readlines()
    elif len(inputpath) and inputpath != '/':
        for root, dirs, files in os.walk(inputpath):
            im_names = files
    else:
        raise IOError('Error: must contain either --indir/--list')

    # Load input images
    data_loader = ImageLoader(im_names, batchSize=args.detbatch, format='yolo').start()

    # Load detection loader
    print('Loading YOLO model..')
    sys.stdout.flush()
    det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
    det_processor = DetectionProcessor(det_loader).start()
    
    # Load pose model
    pose_dataset = Mscoco()
    if args.fast_inference:
        pose_model = InferenNet_fast(4 * 1 + 1, pose_dataset)
    else:
        pose_model = InferenNet(4 * 1 + 1, pose_dataset)
    pose_model.cuda()
    pose_model.eval()
    runtime_profile = {
        'dt': [],
        'pt': [],
        'pn': []
    }

    # Init data writer
    writer = DataWriter(args.save_video).start()

    data_len = data_loader.length()
    print('data length= ',data_len)
    im_names_desc = tqdm(range(data_len))
    batchSize = args.posebatch
    count=0
    for i in im_names_desc:
        count=count+1
        start_time = getTime()
        with torch.no_grad():
            (inps, orig_img, im_name, boxes, scores, pt1, pt2) = det_processor.read()
            if boxes is None or boxes.nelement() == 0:
                writer.save(None, None, None, None, None, orig_img, im_name.split('/')[-1])
                continue

            ckpt_time, det_time = getTime(start_time)
            runtime_profile['dt'].append(det_time)
            # Pose Estimation
            
            datalen = inps.size(0)
            leftover = 0
            if (datalen) % batchSize:
                leftover = 1
            num_batches = datalen // batchSize + leftover

            hm = []
            for j in range(num_batches):
                inps_j = inps[j*batchSize:min((j +  1)*batchSize, datalen)].cuda()
                hm_j = pose_model(inps_j)
                hm.append(hm_j)
            hm = torch.cat(hm)
            ckpt_time, pose_time = getTime(ckpt_time)
            runtime_profile['pt'].append(pose_time)
            hm = hm.cpu()
```
之后省略了图片的输出，只是把hm特征提取了出来
然后直接运行demo.py，但是出错，报错信息如下：`Loading YOLO model..
Process Process-1:
Traceback (most recent call last):
  File "/home/guanziyi/anaconda3/envs/torch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/guanziyi/anaconda3/envs/torch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/guanziyi/alphapose/dataloader.py", line 151, in getitem_yolo
    img_k, orig_img_k, im_dim_list_k = prep_image(im_name_k, inp_dim)
  File "/home/guanziyi/alphapose/yolo/preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
`
请问您知道是哪里出问题了吗？如果想要改成直接运行demo，路径直接在demo里面写好，应该改哪个部分的代码呢

**Comment by Fang-Haoshu** [comment]
我猜有些文件夹下有不是图片的文件吧

**Comment by EasonGZY** [comment]
> 我猜有些文件夹下有不是图片的文件吧

您好，但是我检测了所有运行的文件夹下全都放着图片，还是报出同样的错误，请问要检测yolo是不是必须手动输入地址才可以呢？是否有可行的办法可以直接把路径放在demo.py里

**Comment by Fang-Haoshu** [comment]
这样的话 你可以试一下那个--list的选项 把图片的路径都写到文件里就行

**Comment by cyy-1102** [comment]
> 这样的话 你可以试一下那个--list的选项 把图片的路径都写到文件里就行

您好，我创建了一个.txt文件，里面存放着每个文件夹(文件夹里是该视频的图像帧)的路径，格式如下：
'/home/yy/桌面/img/235'
'/home/yy/桌面/img/1722'

当运行
python demo_inference
--cfg=/home/yy/AlphaPose/configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml
--checkpoint=/home/yy/AlphaPose/pretrained_models/fast_421_res152_256x192.pth
--list=/home/yy/桌面/123.txt
--outdir=/home/yy/桌面/examples
--pose_track

会出错：
Load SE Resnet...
Process Process-1:
Traceback (most recent call last):
  File "/home/yy/anaconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yy/anaconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yy/AlphaPose/alphapose/utils/detector.py", line 136, in image_preprocess
    img_k = self.detector.image_preprocess(im_name_k)
  File "/home/yy/AlphaPose/detector/yolo_api.py", line 69, in image_preprocess
    img, orig_img, im_dim_list = prep_image(img_source, self.inp_dim)
  File "/home/yy/AlphaPose/detector/yolo/preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

谢谢您
