### ISSUE TITLE
load model failed.

### ISSUE THREAD

**Issue by Angel113110** [MVIG-SJTU/AlphaPose#446]
Hi,author
  After I installed this powerful project. When I tried to test on my own data, I met an error. As follows:
Loading YOLO model..
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\paper\AlphaPose\dataloader.py", line 151, in getitem_yolo
    img_k, orig_img_k, im_dim_list_k = prep_image(im_name_k, inp_dim)
  File "D:\paper\AlphaPose\yolo\preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

Loading pose model from ./models/sppe/duc_se.pth
  0%|                                                                                          | 0/983 [00:00<?, ?it/s]

I check my data folder and I'm sure there are all images in this folder. I tried many times and could not solve it. Can you give me some help? Any advice is appreciate. Thanks!

**Comment by Fang-Haoshu** [comment]
Oh, that's weird. Can you check if the images are loaded correctly? I  think it can be the only reason
