### ISSUE TITLE
demo run errors SPPE.src.utils.img 

### ISSUE THREAD

**Issue by Tomwmg** [MVIG-SJTU/AlphaPose#447]
In this file, the function  im_to_torch(img) was written with a wrong way. When I add img=np.array(img), it goes well. When you open your code, please details atten atten atten. Dont waste our time,  so appreciated.

**Comment by Fang-Haoshu** [comment]
Hi, thanks for pointing out, but the code runs well in our testing. Could you detail that in what cases would it cause the error? It's pretty common that there are some bugs in the code and we have tried our best to avoid that. It would be great if you could give more advice and make the community better. Hope to hear more comments from you! BTW, you are not forced to use the code if it's a waste of time:D

**Comment by Tomwmg** [comment]
Thanks for your response. I have to apologize for what I  said in bug-angry (Maybe you felt the same way). Your work has made a great contribution. The bug happened when  I run  torch-branch demo.py with your example image  that  the program stuck in process. I found the function *.read() in demo.py cant get data and  stopped there. After debug, I found the function im_to_torch() uses numpy to transpose a torch tensor that casue  'dim_0 ...tuple ' error. When I first convert the input, the demo runs well. I'm sorry for my blunder again. Well, I always have a bug temper. Good luck.

**Comment by Fang-Haoshu** [comment]
Never mind, sorry for causing your unhappy. I guess you must have spent a lot of time debugging this problem. Really thankful for your kind help and pointing it out!
But still, it's pretty weird that it gets stuck... We will further check it. I have seen your PR and thanks again!
