### ISSUE TITLE
請教AlphaPose運行中，為何GPU使用率不高?

### ISSUE THREAD

**Issue by PenziSu** [MVIG-SJTU/AlphaPose#453]
作者你好，感謝開源貢獻。
我執行指令：python webcam_demo.py --webcam 0 --outdir examples/res --vis
預期程式將使用大量GPU資源，可是在我的主機上CPU滿載，GPU卻是少許。
可是我的畫面中只有我一人而已，CPU同樣滿載。

我嘗試在ubuntu 16.04執行同樣的指令。nvidia-smi觀察到GPU有負載。而在Windows 10就沒有負載了。
是否哪個環節設定不正確呢? 謝謝。

我的主機環境如下
CPU：AMD Athlon 7750
MEM：4GB
VGA：NVIDIA GeForce GTX 1060 3GB
DISK：256GB SSD
WEBCAM：logitech WEBCAM
OS：Windows 10
Python==3.7
Torch==1.3.0
Torchvision==0.4.1
CUDA==10.1
cuDNN for CUDA 10.1

**Comment by feixialong** [comment]
我这边也是同样的状态，作者似乎已经发现该问题。https://github.com/MVIG-SJTU/AlphaPose/issues/435#issuecomment-549012336

**Comment by PenziSu** [comment]
Hello @feixialong 我以為 #435 即將優化的是CPU的使用率，所以作者的意思是會一併調整，使用GPU資源? THX~;)

**Comment by Fang-Haoshu** [comment]
Hi, 谢谢指出， 对的， CVPR之后我们会优化一下CPU和GPU的使用效率问题，现在bottleneck在CPU，所以GPU利用率会低一些
