### ISSUE TITLE
coco test-dev 的精度才67.7?paper 上是70.9 是什么问题

### ISSUE THREAD

**Issue by lingtengqiu** [MVIG-SJTU/AlphaPose#455]
我今天用了您pytorch的版本,并且对他进行了best-match 的测试, 在coco 2017test-dev中我测得其精度为67.7 这个和paper post 的70.9 有出入吧具体是什么原因呢?是你pytorch 版本的精度比较低吗?

**Comment by renshaoqian** [comment]
我也遇到了这个问题,为什么开源的精度和paper 上的不一样呢.是pytorch版本的精度问题吗? 求解答.....

**Comment by Fang-Haoshu** [comment]
Hi, 感谢关注！
精度67.7有点低 可能是没开flip test？ pytorch版我们之前测应该是70左右的。
另外pytorch版确实会比master低 因为为了速度的原因，我们detector用的是yolov3，同时pose网络什么的也跟paper不一样
目前pytorch版是基于我们组做pose的经验包括rmpe，crowdpose等开发的，具体实现其实不完全对应某一篇paper，我们正在写一篇新的paper对应AlphaPose，不过一直没什么时间...还没写出来😂 我们CVPR之后接着努力...😂
我们最近更新了一下pytorch版，精度和速度又有些优化，CVPR之后会放出来 欢迎继续关注哈 ！
