### ISSUE TITLE
demo.py和webcam_demo.py无法保存图像和视频

### ISSUE THREAD

**Issue by lan786** [MVIG-SJTU/AlphaPose#459]
@Fang-Haoshu  您好， 谢谢你这么好的计划
我注意到这个存储库中有两个bug。
1:运行demo.py后，结果图像无法保存。只有json文件正在保存。
2:当我运行webcam_demo.py时，结果视频无法保存
如何解决这些问题？

**Comment by Fang-Haoshu** [comment]
您好 不是bug的 你可以看看我们的说明文档 关于怎么保存图像和视频 文档里都有写
