### ISSUE TITLE
met a problem with ./run.sh

### ISSUE THREAD

**Issue by AnnLoya** [MVIG-SJTU/AlphaPose#46]
i installed tensorflow(CPU&GPU) on python3 before, however the AlphaPose is based on python2, so i installed tensorflow1.6 with python2, and when it runs the ./run.sh,the feedback:
`generating bbox from Faster RCNN...
/home/ann/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-04-08 16:41:40.420039: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/ann/AlphaPose/examples/demo/

  0%|                                                     | 0/3 [00:00<?, ?it/s]unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
 33%|███████████████                              | 1/3 [00:31<01:02, 31.42s/it]unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
 67%|██████████████████████████████               | 2/3 [00:59<00:29, 29.98s/it]unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
100%|█████████████████████████████████████████████| 3/3 [01:28<00:00, 29.57s/it]
pose estimation with RMPE...
/home/ann/torch/install/bin/lua: /home/ann/torch/install/share/lua/5.2/trepl/init.lua:389: /home/ann/.luarocks/share/lua/5.2/hdf5/ffi.lua:56: expected align(#) on line 579
stack traceback:
	[C]: in function 'error'
	/home/ann/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
	/home/ann/AlphaPose/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	/home/ann/torch/install/share/lua/5.2/paths/init.lua:84: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	.../ann/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?
/home/ann/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/ann/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ann/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/ann/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/ann/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'`
maybe there are some problems with tf but i have no idea about these instructions. what else module do i must install?
and the tf version:
`tf.__version__
'1.6.0'`
please help me, thank u

**Comment by Fang-Haoshu** [comment]
Hi,
I can see two problems, the first one is the unknown error problem, which is really weird....
The second one is the 
"/home/ann/.luarocks/share/lua/5.2/hdf5/ffi.lua:56: expected align(#) on line 579"
Someone else has reported a similar problem before. I tried to google it and found that there is no specific answer to that. Everyone seems to have their own methods of solving it...
You can check the link here for more details and see if there are any suggestions that can help: https://github.com/deepmind/torch-hdf5/issues/79

**Comment by Fang-Haoshu** [comment]
We are also working on a pytorch version so you won't meet such problems. Stay tuned! :)

**Comment by AnnLoya** [comment]
thanks very much for your attention...and i suddenly found out that the nvidia driver crushed and i have fixed it and what's more i installed the torch7 again with luaJIT instead of lua5.2 or lua5.1, the feedback:
`./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
/home/ann/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/ann/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-04-11 19:54:10.896502: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/ann/AlphaPose/examples/demo/

100%|█████████████████████████████████████████████| 3/3 [01:34<00:00, 31.44s/it]
pose estimation with RMPE...
Site-local luarocks/core/site_config_5_1.lua file not found. Incomplete installation?
MPII	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-7514/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/ann/torch/install/bin/luajit: ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:144: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-7514/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'resize'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:144: in function 'createIODescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:188: in function 'func'
	/home/ann/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/ann/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	main-alpha-pose.lua:117: in function 'loop'
	main-alpha-pose.lua:176: in main chunk
	[C]: in function 'dofile'
	.../ann/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405e90
/home/ann/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/ann/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ann/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/ann/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/ann/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'`
well it's quite weird to show`Site-local luarocks/core/site_config_5_1.lua file not found. Incomplete installation?` and the "out of memory" problem. i will try lua5.1 to install torch and try to find satisfying version of gcc and g++ later, hope it will return good news. 
one more thing, when i check the ./install.sh of AlphaPose there goes:
`Requirement already satisfied: easydict in /home/ann/.local/lib/python3.5/site-packages
Requirement already satisfied: tqdm in /home/ann/.local/lib/python3.5/site-packages
Requirement already satisfied: opencv-python in /home/ann/miniconda3/lib/python3.5/site-packages
Requirement already satisfied: numpy>=1.11.1 in /home/ann/miniconda3/lib/python3.5/site-packages (from opencv-python)` 
i am confused about these lines, are these packages relying on tensorflow-gpu? my python2 has all these packages however it turns to python3.5.
anyway, thank you again, the AlphaPose is an remarkable achievement!

**Comment by AnnLoya** [comment]
thank you.

**Comment by nanokay** [comment]
hi,
sudo luarocks install hdf5
Installing https://luarocks.org/hdf5-2.0.0-1.src.rock
Warning: variable CFLAGS was not passed in build_variables
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua/gcc'
gcclua-config.h:1:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
gcc -c -o gcclua.o -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include -fPIC -O2 -Wall -Wformat-security -I/usr/include/lua5.2 gcclua.c
gcclua.c:7:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
Makefile:29: recipe for target 'gcclua.o' failed
make[2]: *** [gcclua.o] Error 1
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua/gcc'
Makefile:38: recipe for target 'gcc' failed
make[1]: *** [gcc] Error 2
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua'
Makefile:44: recipe for target 'gcc-lua' failed
make: *** [gcc-lua] Error 2

I find u said that finally i solved the problem by removing torch and installing it again with lua5.2 instead of luaJIT, and the rest hints are the same as above. refer to http://torch.ch/docs/getting-started.html. but I did this following ur solution,but this problem still occured.pls help me, thanks.Or could u give me ur email or wechat?I want to contact u and ask u for advice.

**Comment by nanokay** [comment]
my email is flashkay@126.com, thanks
