### ISSUE TITLE
请问有resnet50作为backbone的预训练模型？

### ISSUE THREAD

**Issue by ln23415** [MVIG-SJTU/AlphaPose#462]
您好，请问可以提供resnet50作为backbone的预训练模型吗？以resnet50作为backbone训练精度又怎样呢?

**Comment by Fang-Haoshu** [comment]
您好，还没有这个月或者下个月会更新一版哈

**Comment by ln23415** [comment]
好的谢谢 ln23415 邮箱：ln23415@hotmail.com 签名由 网易邮箱大师 定制 在2019年12月14日 13:04，Fred Fang 写道： 您好，还没有这个月或者下个月会更新一版哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
