### ISSUE TITLE
hm的数据代表feaature map吗

### ISSUE THREAD

**Issue by EasonGZY** [MVIG-SJTU/AlphaPose#465]
在运行demo和video_demo文件时我想获取feature map，我看pose model的最后一层已经是卷积层，
`            for j in range(num_batches):
                inps_j = inps[j*batchSize:min((j +  1)*batchSize, datalen)].cuda()
                hm_j = pose_model(inps_j)
                hm.append(hm_j)
            hm = torch.cat(hm)`
并且我打印了inps_j.shape和hm.shape，打印出来的shape分别为torch.Size([3, 3, 320, 256])
torch.Size([3, 17, 80, 64])，请问这四个维度分别代表什么意思呢？请问是传统feature map所代表的[n,c,w,h]吗？还有是输入的是3通道的，输出的是17通道吗？但感觉和opt文件输出的nClasses(Number of output channel)=33的数值不匹配，请问是什么原因呢？

**Comment by tianjiahao** [comment]
请问这四个维度分别代表什么意思呢？
就是传统的feature map所代表的[n,c,w,h]。
还有是输入的是3通道的，输出的是17通道吗？
输入rgb图，所以是3通道的，输出为coco标注的17个关键点，所以是17通道。
但感觉和opt文件输出的nClasses(Number of output channel)=33的数值不匹配，请问是什么原因呢？
opt中的33是作者用coco（17个关键点）和mpii（16个关键点）训练的到的模型，自己跑demo时改为17就行。

**Comment by EasonGZY** [comment]
@tianjiahao 好的感谢！不过还想确定一下，传统的feature map的第一维度n代表的是batch size，但我看了代码后感觉输出的feature map的第一维度n的信息是指的是对于一张图片（或一帧）对人检测的box数量吧？但如果对于多张图片进行处理的话如何形成一个四维tensor呢？感觉一般的对于feature map的处理貌似没有关于box的量

**Comment by EasonGZY** [comment]
好的感谢您耐心的回答！还想问您以下两个问题，1.请问这里的第一个维度n指的是什么意思呢？2.这里demo处理的hm和inp是指的卷积层最后一层feature map的输入和输出呢？还是最终姿态效果图的输入和输出呢？因为我现在想获取一个对多张图片输出的feature map结果[n,c,w,h]，但是单独提取hm还有box的信息，所以感觉不太像是feature map的信息
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
