### ISSUE TITLE
Option for only single person tracking

### ISSUE THREAD

**Issue by abcde13** [MVIG-SJTU/AlphaPose#467]
Is there way to only enable single person tracking? Ignoring the people in the background, just analyzing the largest person in the foreground?

**Comment by Fang-Haoshu** [comment]
Hi, we are working on a new version of alphapose and will release them this or next month. There will be a tracking option. Many thanks.

**Comment by sebo313** [comment]
Hi @Fang-Haoshu, any update on the new tracking option?

**Comment by tim20120526** [comment]
> Hi, we are working on a new version of alphapose and will release them this or next month. There will be a tracking option. Many thanks.

Hi @Fang-Haoshu, any update on the new tracking option?

**Comment by sebo361** [comment]
bump

**Comment by sebo361** [comment]
Hi @Fang-Haoshu do you have any update about the single person tracking? Or any pipeline you would propose to detect the pose of the most dominant person (largest bounding box in the image) only?
