### ISSUE TITLE
关于json中xy坐标的问题（x坐标震荡）

### ISSUE THREAD

**Issue by sims137** [MVIG-SJTU/AlphaPose#469]
首先我把视频逐帧剪切后生成一组图片，
把图片顺序输入生成一组json数据，
提取x和y的数值，生成一组时序图
![e511889704a2fb63b9a24f84a925660](https://user-images.githubusercontent.com/12858787/69690531-23b92180-1107-11ea-8b57-1262a77f6803.png)
这是膝盖的时序图
蓝色为x坐标的变化，橙色为y坐标的变化
按理说 x应该是下降或者上升的一个过程，但是这个图像显示的有震荡

提问：x坐标参照的坐标是什么   为什么会震荡  是否需要参考z的数值

**Comment by sims137** [comment]
抱歉  写错了   这是鼻子的时序图

**Comment by Fang-Haoshu** [comment]
xy就是图片里像素的坐标哈

**Comment by sims137** [comment]
> xy就是图片里即将的坐标哈

x是坐标没错   但是得到的数值会振荡， 人在行走间的位移变化应该是连续的递增或者递减，
但是我得到数据就是振荡的，假设初始值是2000，下一个x的节点就变成了1000，又会回到1900，在返回1000
有没有可能是x坐标相对的0点产生了变化

**Comment by sims137** [comment]
> xy就是图片里即将的坐标哈

还有一个小建议， 在直接读取一个文件夹的img文件时，不是顺序读取的，

**Comment by hellozjj** [comment]
这是哪个json文件的结果？

**Comment by sims137** [comment]
感谢您的回复！
对不起是我问题描述的有问题
是这样的，我们采集了一段人体行走的视频序列（强曝光的情况下），用alphapose识别关节，但是识别效果不好，得到的每个节点的时序曲线并不是连续的（图像呈现出锯齿状如图）。

这个问题我已经解决了。
还有一个新的问题是，alphapose 识别视频序列或者图像序列的理想分辨率是多少？
目前我们测试的是分辨路越高，效果越好。最高测试到了1920*1080。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hellozjj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 下午5:47
收件人:&nbsp;"MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送:&nbsp;"Zzzzzzz"<1503937010@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 关于json中xy坐标的问题（x坐标震荡） (#469)





 
这是哪个json文件的结果？
