### ISSUE TITLE
what is the relationship between AlphaPose and PoseFlow ?

### ISSUE THREAD

**Issue by GarrickLin** [MVIG-SJTU/AlphaPose#47]
I find that I can run `AlphaPose` normally without `PoseFlow` component. What is the relationship between AlphaPose and PoseFlow ?

**Comment by Fang-Haoshu** [comment]
AlphaPose is an accurate multi-person pose estimation system.  To associate poses that indicates the same person across frames, we also provide an efficient online pose tracker called PoseFlow.  One for pose estimation and one for pose tracking

**Comment by YuliangXiu** [comment]
@GarrickLin PoseFlow can do online pose tracking at real-time speed when using fast feature matching algorithm (e.g. ORB), the reason why I use DeepMatching feature in code is for better performance in PoseTrack Challenge benchmarks.
