### ISSUE TITLE
Does Alphapose have c++ version?

### ISSUE THREAD

**Issue by lurenjiajingsi** [MVIG-SJTU/AlphaPose#473]
There are alphaposes that can already run the mxne framework, but python;So I want c++ to implement alphapose to run on mxnet

**Comment by Fang-Haoshu** [comment]
Hi, currently mxnet version have no c++ implementation. We are working on a pytorch based c++ version and will release this or next month.
Bests

**Comment by samylee** [comment]
hello guys, go and find c++ library: https://github.com/samylee/SamyleePoseApi-OpenLibrary

**Comment by chenscottus** [comment]
Does Alphapose have c++ version?

Many thanks!

-Scott
