### ISSUE TITLE
求test-dev.h5文件

### ISSUE THREAD

**Issue by yangyuke001** [MVIG-SJTU/AlphaPose#474]
@Fang-Haoshu @Jeff-sjtu 
请问方便发一份test-dev.h5文件吗？邮箱yangyuke001@126.com,万分感谢！

**Comment by alohays** [comment]
@Fang-Haoshu @Jeff-sjtu
请问方便发一份test-dev.h5文件吗？邮箱 swack9751@korea.ac.kr ,万分感谢！

**Comment by Fang-Haoshu** [comment]
https://drive.google.com/file/d/0BxORzoJl8N9PRy1ISnF0WnljLXRtNkFscmVfNDI4R0ptc04w/view?usp=drive_web

**Comment by Fang-Haoshu** [comment]
Sorry, the original file seems not correct. You can try this new one and replace the coco-newnms-images
https://drive.google.com/open?id=0BxORzoJl8N9PSTB2QWZBSUMxS1huc290VFZxOW9NZmhydHZr
