### ISSUE TITLE
missing frames when using demo.py to process sequence images

### ISSUE THREAD

**Issue by Angel113110** [MVIG-SJTU/AlphaPose#475]
Hi, author
    I met a wired problem when I used the demo.py to process sequence images. That is, it always missing some json files which contain pose information. I used it on my computer and set sp flag because of error happened on my computer when I didn't do this. How it happened? How can I solve this problem?

**Comment by Fang-Haoshu** [comment]
Hi, maybe it's because the person in those images are not detected. Because they are too difficult to detect. We are updating alphapose and will release a more powerful version this or next month. Hope our stronger model can solve this problem
