### ISSUE TITLE
Why doesn't `PCK_match` exist in parametric-pose-nms-MPII.py, but in parametric-pose-nms-COCO.py?

### ISSUE THREAD

**Issue by GerrieWell** [MVIG-SJTU/AlphaPose#478]
The `PCK_match` function can be found in pp-nms of coco dataset code.
Why it can't be found in parametric-pose-nms-MPII.py? Does it mean you found it isn't helpful? Or just miss the implementation for MPII dataset?

**Comment by Fang-Haoshu** [comment]
We didn't try that on MPII. I guess it would work. We got high enough scores on MPII so we did not finetune it further lol.
