### ISSUE TITLE
demo.py will stuck when it run for multiple images in one folder

### ISSUE THREAD

**Issue by BlueAnthony** [MVIG-SJTU/AlphaPose#479]
demo.py will stuck when it run for multiple images in one folder.
It will stuck around 57~62 image without any error message and I check these images are ok for inference individually.
And, sometimes it will show "RuntimeError: unable to write to file </torch_1711_597194251> at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/TH/THAllocator.c:383", but the the process still goes on.
Any suggestion?

**Comment by BlueAnthony** [comment]
I found if the number of picture is less than 65, any picture is ok.

**Comment by Fang-Haoshu** [comment]
This seems to be a multi-processing problem. What is your pytorch version?

**Comment by BlueAnthony** [comment]
@Fang-Haoshu
I use the image "pytorch/pytorch:0.4_cuda9_cudnn7" from pytorch's official docker hub.

**Comment by Fang-Haoshu** [comment]
It's weird... A simple workaround would be turning on the --sp flag to disable multi-processing.
I think we need to go deeper to found the bug..
