### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable in json-video.py

### ISSUE THREAD

**Issue by noahcao** [MVIG-SJTU/AlphaPose#48]
When estimating the keypoints with flag '--vis', such an error sometimes happens:

"_tkinter.TclError: no display name and no $DISPLAY environment variable" which is called back from the predict/json/json-video.py

And this bug is likely related to the version of matplotlib, and for my own case, this can be fixed in method below:

before the statement at the beginning of json-video.py:
`import matplotlib.pyplot as plt `

insert two lines:
`import matplotlib`
  `matplotlib.use('Agg')
`

**Comment by Fang-Haoshu** [comment]
Thanks for your feedback!

**Comment by WeiSong123** [comment]
@noahcao 
`Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.7
 [=================== 69/69 ===================>] Tot: 8s277ms | Step: 121ms    
----------Finished----------	
visualization...
  0%|                                                     | 0/3 [00:00<?, ?it/s]Exception KeyError: KeyError(<weakref at 0x7f9db0da01b0; to 'tqdm' at 0x7f9db0d97bd0>,) in <bound method tqdm.__del__ of   0%|                                                     | 0/3 [00:00<?, ?it/s]> ignored
Traceback (most recent call last):
  File "json-video.py", line 69, in <module>
    display_pose(inputpath, outputpath, imgname)    
  File "json-video.py", line 56, in display_pose
    fig.savefig(os.path.join(outputpath,'RENDER',imgname.split('/')[-1]),pad_inches = 0.0, bbox_inches=extent, dpi=13)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 583, in print_jpg
    return image.save(filename_or_obj, format='jpeg', **options)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 622, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG
`
please help me ,thinks

**Comment by hnuzhy** [comment]
thanks a lot~
