### ISSUE TITLE
Hello，I want to acquire one problem, yoloAlphapose 

### ISSUE THREAD

**Issue by ZHyuwind** [MVIG-SJTU/AlphaPose#480]

**Comment by ZHyuwind** [comment]
Hello，I have one problem that yolo code in Alphapose whether is  same as independent yolov3 code? when use yolov3-spps.weights to get boxs, I find there are two boxes in one person, one maybe detect half body, another detect complete body. would you meet this situation? or how to explain this situation?

**Comment by Fang-Haoshu** [comment]
Hi, this is because we lower the confidence of yolo detection. We use multiple proposals per person and use pose nms to eliminate redundant poses.

**Comment by ZHyuwind** [comment]
> Hi, this is because we lower the confidence of yolo detection. We use multiple proposals per person and use pose nms to eliminate redundant poses.

Thanks for your answer. I also have a problem that poseNMS maybe not eliminate redundant poses, instead of multiple proposals missleading SPPE to get keypoints.
If you convenient, please tell me why lower the confidence of yolo detection and specific process. Thanks again!

**Comment by Fang-Haoshu** [comment]
Oh, because higher confidence may miss some people, so we use lower confidence~

**Comment by dekathomas** [comment]
Sorry @ZHyuwind, did this question is referred to the **inference** process or the **training** process?
