### ISSUE TITLE
Batch process in pycharm

### ISSUE THREAD

**Issue by Angel113110** [MVIG-SJTU/AlphaPose#483]
Hi, author
I want to use alphapose to batch process images extracted from videos. A folder contains images extracted from one video. When I tried to do this. Error like this:

Exception in thread Thread-1:
Loading YOLO model..
Traceback (most recent call last):
File "D:\Anaconda\lib\threading.py", line 917, in _bootstrap_inner
self.run()
File "D:\Anaconda\lib\threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "D:\pycharm\teacher_analyse\Alphapose\dataloader.py", line 151, in getitem_yolo
img_k, orig_img_k, im_dim_list_k = prep_image(im_name_k, inp_dim)
File "D:\pycharm\teacher_analyse\Alphapose\yolo\preprocess.py", line 42, in prep_image
dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

I already set --sp flag in my code. After above error happened,

Loading pose model from ./models/sppe/duc_se.pth
0%| | 0/367 [00:00<?, ?it/s]
this happened, process seemed stop. The dir is right and no other files in each folder.
How it happened? Can you help me solve this problem?Thanks!

**Comment by Angel113110** [comment]
My process is: 
I extract images from one video. Then use alphapose to prediction on these images.
The alphapose can't support process one by one?

**Comment by Fang-Haoshu** [comment]
It supports.
Do not duplicate issues, thanks.
The possible reasons are listed in #481

**Comment by Fang-Haoshu** [comment]
Maybe you input the wrong command. What is your command for that?
Also, can you run the demo for images under example/demo? If yes, then there should be no problem for a dir with all images
Check what's wrong with the "orig_im", you need to debug it.
