### ISSUE TITLE
Demo code does not work

### ISSUE THREAD

**Issue by xcyan** [MVIG-SJTU/AlphaPose#486]
@Fang-Haoshu Any ideas?
![2](https://user-images.githubusercontent.com/8760875/71133629-fe707e00-21af-11ea-97ec-03fd04c919d5.jpg)
Command to replicate the issue:
```AlphaPose$ python demo.py --indir examples/demo/ --outdir examples/res --sp --save_img```

**Comment by Fang-Haoshu** [comment]
Hi Alex, is the bug fixed for python2? We updated the code for master branch, you can also try that. 
Best
