### ISSUE TITLE
Huuuuge happy to see new version.

### ISSUE THREAD

**Issue by yangyuke001** [MVIG-SJTU/AlphaPose#487]
Great job!
 It is wonderful if the blew two thing is completed ,
1  readme can not tell us how to train and test
2  there is no pre-trained model

**Comment by Fang-Haoshu** [comment]
Thanks. In fact they are all in readme...

**Comment by yangyuke001** [comment]
I am ashamed for my words.

**Comment by Fang-Haoshu** [comment]
Haha never mind. We will also add an example for training more detailly. You can find them in quick-start and model_zoo
