### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by hqphoenix** [MVIG-SJTU/AlphaPose#488]
AssertionError: 
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by Fang-Haoshu** [comment]
A simple way is to use the pytorch 0.4.0 branch: https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch
if you don't want to update your cuda driver
