### ISSUE TITLE
关于box传入sppe姿态网络的问题

### ISSUE THREAD

**Issue by EasonGZY** [MVIG-SJTU/AlphaPose#489]
您好，想问一下你们在以下代码保存每个人的pose信息时候，有进行过box的筛选吗，误报的box有去除掉吗？这里出来的hm的pose信息是一一对应的每个人box的信息的吗？还是指的是所有box（包括误报）经过姿态网络的结果呢？如果是应该如何准确获取每幅图中所有姿态特征的信息呢
         ` for j in range(num_batches):`
                `inps_j = inps[j*batchSize:min((j +  1)*batchSize, datalen)].cuda()`
                `hm_j = pose_model(inps_j)`
               ` hm.append(hm_j)`

**Comment by Jeff-sjtu** [comment]
你好，box nms以及pose nms都会去除冗余的检测结果。
