### ISSUE TITLE
ModuleNotFoundError: No module named 'cpu_nms'

### ISSUE THREAD

**Issue by hd120105** [MVIG-SJTU/AlphaPose#49]
Hi, I followed the instruction to install AlphaPose, but when I run the test demo, it comes out this error. How to solve this. Thanks.
cetc@cetc-computer:~/桌面/HD/AlphaPose-master/human-detection/lib$ make clean
rm -rf */*.pyc
rm -rf */*.so
cetc@cetc-computer:~/桌面/HD/AlphaPose-master/human-detection/lib$ make
python3 setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/utils
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/cetc/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cetc/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/cetc/anaconda3/include/python3.6m -c utils/bbox.c -o build/temp.linux-x86_64-3.6/utils/bbox.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -B /home/cetc/anaconda3/compiler_compat -L/home/cetc/anaconda3/lib -Wl,-rpath=/home/cetc/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/utils/bbox.o -o /home/cetc/桌面/HD/AlphaPose-master/human-detection/lib/utils/cython_bbox.cpython-36m-x86_64-linux-gnu.so
skipping 'utils/nms.c' Cython extension (up-to-date)
building 'utils.cython_nms' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/cetc/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cetc/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/cetc/anaconda3/include/python3.6m -c utils/nms.c -o build/temp.linux-x86_64-3.6/utils/nms.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -B /home/cetc/anaconda3/compiler_compat -L/home/cetc/anaconda3/lib -Wl,-rpath=/home/cetc/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/utils/nms.o -o /home/cetc/桌面/HD/AlphaPose-master/human-detection/lib/utils/cython_nms.cpython-36m-x86_64-linux-gnu.so
rm -rf build
cetc@cetc-computer:~/桌面/HD/AlphaPose-master$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 22, in <module>
    from newnms.nms import  soft_nms
  File "/home/cetc/桌面/HD/AlphaPose-master/human-detection/tools/../lib/newnms/nms.py", line 4, in <module>
   from cpu_nms import cpu_nms, cpu_soft_nms
ModuleNotFoundError: No module named 'cpu_nms'
pose estimation with RMPE...
./run.sh: 行 78: th: 未找到命令
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/cetc/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/cetc/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/cetc/桌面/HD/AlphaPose-master/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cetc/桌面/HD/AlphaPose-master/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by Fang-Haoshu** [comment]
Hi, in our run.sh，we use python2. The reason is that the cpu nms for py3 is not supported.

**Comment by wangy275** [comment]
how can i modify the code so that cpu nms is supported for py3

**Comment by zhFuECL** [comment]
Same problem here. Have you solved this problem? @wangy275
