### ISSUE TITLE
mxnet版本 ，运行python3 demo.py    程序卡了

### ISSUE THREAD

**Issue by python1806huqiugen** [MVIG-SJTU/AlphaPose#495]
*************************
Namespace(LR=0.0001, addDPG=False, board=True, confidence=0.5, crit='MSE', dataset='coco', det_model='frcnn', detbatch=1, dtype='float32', epoch=0, eps=1e-08, expID='default', format='coco', gpu_id=[1], hardMining=False, hmGauss=1, inp_dim='416', inputResH=256, inputResW=192, inputlist='', inputpath='', loadModel=None, load_from_pyt=False, logging_file='training.log', lr_decay=0.1, lr_decay_epoch='20,60', map=True, mode='normal', nClasses=33, nEpochs=100, nThreads=1, nms_thresh=0.5, optMethod='rmsprop', outputResH=64, outputResW=48, outputpath='examples/res/', posebatch=1, pre_resnet=True, rotate=40, save_img=True, scale=0.3, snapshot=1, syncbn=False, trainBatch=8, trainIters=0, try_loadModel=None, use_pretrained_base=True, valIters=0, validBatch=8, vis=False, visdom=False)
*************************
['./data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00049.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00052.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00055.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00058.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00061.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00067.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00076.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00079.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00082.png', './data/coco/images/trainval2017/ZH_Sensor1_Color2019-11-11-111454_00085.png']
Loading yolo3_darknet53_coco ...
Modifying output layers to ignore non-person classes...
Loading SPPE ...
===Pretrain Base===
  0%|          | 0/10 [00:00<?, ?it/s]***********************************1
 60%|██████    | 6/10 [00:06<00:04,  1.00s/it][14:13:26] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\cudnn\./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
100%|██████████| 10/10 [00:10<00:00,  1.00s/it]

**Comment by Fang-Haoshu** [comment]
这个看起来跑完了呀 没有卡吧？
