### ISSUE TITLE
mpii people bbox？

### ISSUE THREAD

**Issue by henbucuoshanghai** [MVIG-SJTU/AlphaPose#498]
the test dataset of mpii ,it has people bbox？or (x,y) about  16  kps?

**Comment by Jeff-sjtu** [comment]
Hi, we have uploaded the annotation file of `mpii` in json format [[annot_mpii.zip](https://drive.google.com/open?id=1HC6znReBeg-TMPZbmoldtYrMGlrEFamh)]

**Comment by henbucuoshanghai** [comment]
it has train and test？？？&nbsp; or i have&nbsp; to split by myself,0.9 and 0.1 randomly????

**Comment by henbucuoshanghai** [comment]
the json&nbsp; format,category_id': 1, 'iscrowd': 0, 'bbox': [821, 163, 202, 253], 'keypoints': [895, 293, 1, 910, 279, 1, 945, 223, 1, 1012, 218, 1, 961, 315, 1, 960, 403, 1, 979, 221, 1, 906, 190, 1, 912, 191, 1, 831, 182, 1, 871, 304, 1, 883, 229, 1, 888, 174, 1, 924, 206, 1, 1013, 203, 1, 955, 263, 1], 'num_keypoints': 16, 'image_id': 15601864, 'id': 1}



category_id???bbox?the (x,y) of top left points of people??
image_id????id???means??
it means ??


tks

**Comment by Jeff-sjtu** [comment]
Hi, we did not test on MPII. We use all the MPII dataset for training.

**Comment by henbucuoshanghai** [comment]
![image](https://user-images.githubusercontent.com/37647094/71952656-6f88db80-321a-11ea-931e-04ab538f19a2.png)
you use all it for training,but how to test it on mpii,           like the README????

**Comment by henbucuoshanghai** [comment]
please,tks

**Comment by Fang-Haoshu** [comment]
Oh hi, you mean the full test set. To obtain the results on test set, you need to refer to http://human-pose.mpi-inf.mpg.de/#evaluation
You need to send the results to the authors of MPII.

**Comment by Fang-Haoshu** [comment]
No box or kpts are available. All test data can only be accessed by the authors of MPII
