### ISSUE TITLE
super slow in liunx server

### ISSUE THREAD

**Issue by YeHaijia** [MVIG-SJTU/AlphaPose#499]
the sever configuration is:
CPU:Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz 
GPU:V100*1

but when I try to inference a 480*480 video, it inferences super slow.that is the inference message:
![image](https://user-images.githubusercontent.com/18445398/71894597-a9f66800-3189-11ea-8e83-148c4e0521f8.png)
it cost 30s perframe !!! 
in addition , it could be terminated without any warning .

**Comment by YeHaijia** [comment]
root@notebook-wvzxv-4gt7s /w/n/AlphaPose# sh scripts/inference.sh
Load SE Resnet...
Loading YOLO model..
Network successfully loaded
Loading pose model from ./pretrained_models/fast_421_res152_256x192.pth...
  0%|                                                                                                                               | 0/952 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found
Try to use other video encoders...
det time: 20.8606 | pose time: 6.4786 | post processing: 0.4477:   1%|▍                                                   | 8/952 [03:44<9:27:57, 36.10s/it]Killed

**Comment by YeHaijia** [comment]
it seems depend on the cpu rather than the gpu

**Comment by Fang-Haoshu** [comment]
Weird. Maybe the CPU is the bottleneck for your server? Could you see if the CPU is used heavily by other processes? Our program will also consume a lot of CPU resources.

**Comment by YeHaijia** [comment]
th CPU was just used by alphapose. It is strange that my PC(cpu:intel 8700K, GPU:RTX2060) is much faster than the server.
