### ISSUE TITLE
How many fps?

### ISSUE THREAD

**Issue by ifangcheng** [MVIG-SJTU/AlphaPose#5]
How many fps can the whole algorithm  achieve when run end-to-end(including the human detector part)?
Can AlphaPose run in real time?

**Comment by Fang-Haoshu** [comment]
The inference time depends on the number of persons in the image. On a Titan X GPU card, the inference time is about 0.2s per person.

**Comment by ouceduxzk** [comment]
the work depends on faster-rcnn, no wonder so slow

**Comment by Fang-Haoshu** [comment]
@ouceduxzk Yeah. We need to make a choice between accuracy and speed.

**Comment by ifangcheng** [comment]
@ Fang-Haoshu    if use other detector e.g. ssd, yolov2, instead of faster rcnn ,  is it possible to achieve real time while maintain high accuracy?

**Comment by ouceduxzk** [comment]
@Fang-Haoshu  how about using faster-rcnn but make it faster first, like in this work where faster-rcnn is 4x faster https://github.com/yihui-he/channel-pruning

**Comment by Fang-Haoshu** [comment]
Replacing the human detector can make our code faster, but the pose estimation network also costs some time and we need to design a new network for pose estimation if we want to achieve real time

**Comment by Ai-is-light** [comment]
@Fang-Haoshu do you pay your attention to designing the novel network?
Looking forward to any new ideas

**Comment by ujsyehao** [comment]
@ouceduxzk Have you try channel-pruning for faster RCNN acceleration?

**Comment by ouceduxzk** [comment]
@ujsyehao  not yet, but it is on my list to try out the channel pruning

**Comment by ujsyehao** [comment]
Hi @ouceduxzk, what is the test fps on your computer?
I test it on GTX 1070ti, I run ./run.sh --indir examples/demo --outdir examples/results --vis, and get fps below:
![44](https://user-images.githubusercontent.com/17454232/35905408-f4be4054-0c21-11e8-81a4-7a3e409ad790.png)
According to the information, the fps about 0.25. So is my test method wrong or the method itself is so slow?

**Comment by ujsyehao** [comment]
I test AlphaPose on GTX 1070ti, detection time per person about 0.18s(I use demo-alpha-pose.py), pose estimation time per person(I use main-alpha-pose.lua) has a wide range(0.3s- 1.7s) without pose nms.
(mode: normal, set batchsize=1). Is my data right?

**Comment by ujsyehao** [comment]
Can somebody help?

**Comment by garimss** [comment]
> Hi @ouceduxzk, what is the test fps on your computer?
> I test it on GTX 1070ti, I run ./run.sh --indir examples/demo --outdir examples/results --vis, and get fps below:
> 
> According to the information, the fps about 0.25. So is my test method wrong or the method itself is so slow?

how did you calculated FPS? and what does it mean 1.07s/it?

**Comment by Kumaava** [comment]
Is there an update? Need make the human detector model faster, are there any other fps benchmark models I can replace the existing model with?
