### ISSUE TITLE
A question about the data used in PoseFlow/deepmatching.py

### ISSUE THREAD

**Issue by Innerpeace90** [MVIG-SJTU/AlphaPose#50]
Hi, could you tell me the detailed name of the data used in [PoseFlow/deepmatching.py](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/deepmatching.py#L18), I donn't know which the data you used that satisfied the condition of "len(a.split("/")) == 9". When I debug the [code](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/deepmatching.py#L24), the value of vidnames is empty.

**Comment by Innerpeace90** [comment]
When I execute the document of [run.sh](https://github.com/MVIG-SJTU/AlphaPose/blob/master/run.sh) to generate [alpha-pose-results-{}.json](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/tracker.py#L63), there is an error, how can I solve it? 
![image](https://user-images.githubusercontent.com/31804830/39111166-b689452a-4706-11e8-96f9-4a769b0d639d.png)

**Comment by Innerpeace90** [comment]
I cann't find the document of [alpha-pose-results-{}.json](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/tracker.py#L63), is it just the alpha-pose-results-forvis.json? When I execute the run.sh,  both alpha-pose-results.json and alpha-pose-results-forvis.json are generated in Alphapose/examples/results/Pose. 3Q!

**Comment by YuliangXiu** [comment]
You can not run this code directly without downloading PoseTrack challenge dataset, downloading introduction can be found in [README](https://github.com/MVIG-SJTU/AlphaPose/tree/master/PoseFlow). Besides, I have updated the new PoseFlow codes, adding one [alpha-pose-results-sample.json](https://github.com/MVIG-SJTU/AlphaPose/tree/master/PoseFlow/alpha-pose-results-sample.json) for describing the structure of json file.

**Comment by Innerpeace90** [comment]
Thank you for your reply, where is the [.json](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/tracker.py#L234)? The .json I needed isn't included in posetrack_v0.75_labels.tar(). Where can I load it?

**Comment by Innerpeace90** [comment]
Could you share the .json for me?3Q~I try to convert mat to json according to your reply but the .json isn't generated. I don't find what is the problem.
![image](https://user-images.githubusercontent.com/31804830/39175302-88f32cbc-47dc-11e8-854c-b3abce3faa8e.png)

**Comment by Innerpeace90** [comment]
Thank you! I have converted the annotation file from Mat to Json with your help. Finanlly, I got the xx_mpii_relpath_5sec_testsub.json file after executing the tracker.py file, How to show the tracking effect  for a video by using the xx_mpii_relpath_5sec_testsub.json file?

**Comment by YuliangXiu** [comment]
tracking changes the person id in every frames.

**Comment by Innerpeace90** [comment]
If I use the images converted from myself video, how to make the Mat file which will be converted to [Json file](https://github.com/MVIG-SJTU/AlphaPose/blob/master/PoseFlow/tracker.py#L235)?3Q!

**Comment by Innerpeace90** [comment]
Sorry to bother you again. I found that content of point:[]  in the xx_mpii_relpath_5sec_testsub.json file generated by tracker.py was empty~

**Comment by YuliangXiu** [comment]
I did not test my code on the user-defined dataset, so I think it is better to write your own script to convert mat to json(refer to the data format of current generated json).

I do not think it is normal. Where do the scores come from, AlphaPose? Maybe you can write some visualization code to render skeleton results to make sure your results are reasonable.

**Comment by Innerpeace90** [comment]
The "pose_scoreI"  in my file is  come from Alphapose. All the values of "pose_scoreI" are between 0~1, I still cann't find where the problem is. I have adjusted the value of drop to 0.2, then the  content of point:[] in the final xx_mpii_relpath_5sec_testsub.json file  is not empty. The tracking effect is better than ever.

**Comment by YuliangXiu** [comment]
Yes, I think this is my fault, I do some post-processing after pose estimation, so my pose score is not between 0 and 1, you can tune the drop parameter according to your own dataset.

**Comment by Innerpeace90** [comment]
Can I find your post-processing job in the AlphaPose project cloned from this github? Or you have not upload this job?

**Comment by YuliangXiu** [comment]
I will add comments and necessary introduction to this file and upload it ASAP.

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
