### ISSUE TITLE
编码utf-8问题

### ISSUE THREAD

**Issue by Hoshizora-Linki** [MVIG-SJTU/AlphaPose#500]
![(CC47P7F(MH0}N~8H(9KQM7](https://user-images.githubusercontent.com/59411351/72401776-01976380-3788-11ea-80db-4fb512f4ae24.png)

如图

**Comment by Fang-Haoshu** [comment]
Maybe you need to rename the "都在这儿“ dir to a English name?

**Comment by Hoshizora-Linki** [comment]
I've tried, but this will make my files inoperative

**Comment by Fang-Haoshu** [comment]
Maybe put alphapose in another dir without chinese character

**Comment by Hoshizora-Linki** [comment]
thanks，help a lot
