### ISSUE TITLE
Alphapose/human-detection ????

### ISSUE THREAD

**Issue by betogulliver** [MVIG-SJTU/AlphaPose#502]
I'm trying to use Alphapose to reproduce the result in 'im2smpl' 
<https://github.com/ZhengZerong/im2smpl>

However, it seems 'im2smpl' is using and 'old' version of Alphapose.
'imp2spml' which includes  the Alphapose/human-detection directory

I could not find here in github any previous version of Alphapose that
has 'Alphapose/human-detection' directory structure.

However, I have found this 'previous???' versior of Alphapose

         https://gitee.com/jempson/AlphaPose/

that contains the diretory 'Alphapose/human-detection' as required by
'im2smpl'.

However I have problems, getting './AlphaPose/run.sh' to run (problems
with 'th ....')

Since that version seems to be not maintained anymore I wonder
if anybody here could point me to the right direction or what to do
next.

Any/all help appreciate it.

**Comment by Jeff-sjtu** [comment]
Hi @betogulliver, you can try to revert the master branch to the old version f591ab608c854a868e8ced8ada498034373ed28a.
