### ISSUE TITLE
100% cpu but no gpu usage

### ISSUE THREAD

**Issue by M-Younus** [MVIG-SJTU/AlphaPose#503]
Hi my cpu usage is 100% but gpu usage is 0%,I install pytorch for gpu and I am using `master` branch of AlphaPose on windows with 'nvidia geForce gtx 750' gpu.
I set `posebatch` to 2 and `detbatch` to 1, otherwise I got `cuda out of memory` error.

**Comment by Jeff-sjtu** [comment]
It seems the memory of GTX 750 is too small. Any idea of the GPU usage on windows? @Fang-Haoshu

**Comment by M-Younus** [comment]
> It seems the memory of GTX 750 is too small. Any idea of the GPU usage on windows? @Fang-Haoshu

hmm,yes I think the GTX 750 is too old for alphapose, if I used any video it is using 100% cpu and 0% gpu, but just now I test it by using --indir( directory with 3 images) and there is spike in gpu usage (~6%).

**Comment by M-Younus** [comment]
Hi @Fang-Haoshu,  can you please help us with this issue.

**Comment by M-Younus** [comment]
Switch to ubuntu and things are working as expected.

**Comment by l2009312042** [comment]
oh  no ！ when run  video_demo,my cpu usage is 100%  and my water cool cpu part  leak liquid , heart my machine ， so bad ！！！！！
