### ISSUE TITLE
RuntimeError in loading state_dict for FastPose

### ISSUE THREAD

**Issue by A-zih** [MVIG-SJTU/AlphaPose#504]
Hi! I am not sure whether my command is right or not. 
![1579176057916](https://user-images.githubusercontent.com/44132730/72523844-a0f94b00-389b-11ea-8d28-22774d4d94c2.jpg)
But I got the runtimeError and I don't know how to fix it. Perhaps I missed some steps while building it. Really need your help, thanks!
![1579176175312](https://user-images.githubusercontent.com/44132730/72523978-e584e680-389b-11ea-96c6-c280d1b246b6.jpg)

**Comment by Jeff-sjtu** [comment]
Hi, the checkpoint `simple_res50_256x192.pth` doesn't match the config file `256x192_res50_lr1e-3_1x.yaml`

**Comment by A-zih** [comment]
@Jeff-sjtu It works! thanks a lot! But I am having another issue.
![1579229161925](https://user-images.githubusercontent.com/44132730/72580403-ead34700-3916-11ea-9b4b-acaf0c511253.jpg)
I download **openh264-1.8.0-win64.dll** and I don't know which directory should I put it. But the result video still can be saved successfully.

**Comment by Jeff-sjtu** [comment]
Maybe you need to follow the [official instructions](https://github.com/cisco/openh264#for-windows-builds) to build OPENH264.

**Comment by sjwang222** [comment]
Hello, I was testing the 'Human-ReID based tracking' model and I encounter the similar error message.

I follow the instructions in [here](https://github.com/MVIG-SJTU/AlphaPose/tree/master/trackers) and here is my command:
`python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth --video raw_video/kj.mp4 --outdir raw_video/res/ --save_video, --pose_track`

Does this issue also arise from the mismatch of checkpoint and config? If so, what changes are supposed to be made? 

Thanks!
