### ISSUE TITLE
Why is the webcam program running and the camera starts, but no picture is displayed?

### ISSUE THREAD

**Issue by 1vpmaster** [MVIG-SJTU/AlphaPose#505]
python scripts/demo_inference.py --cfg configs/coco/resne
t/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --vis_fast --webcam 0
Loading YOLO model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
Network successfully loaded
Starting webcam demo, press Ctrl + C to terminate...
326it [00:37, 10.96it/s]^C===========================> Finish Model Running.

**Comment by Fang-Haoshu** [comment]
hi, you need to add flag --vis

**Comment by 1vpmaster** [comment]
but i add flag --vis_fast, this can't show the picture?

**Comment by fortminors** [comment]
it still doesn't show the webcam output. the command that i run is:

`python webcam_demo.py --webcam 0 --outdir examples/res --vis`
