### ISSUE TITLE
TypeError: can't pickle weakref objects

### ISSUE THREAD

**Issue by pgcavalcanti** [MVIG-SJTU/AlphaPose#506]
Hello,

I'm trying to run the demo_inference like that:
python scripts/demo_inference.py --cfg ./configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint ./pretrained_models/simple_res50_256x192.pth --video ./videos/corte_4.mp4 --outdir ./outputs/ --detector yolo --save_video

And I'm getting the following errors:
![image](https://user-images.githubusercontent.com/13369521/72634738-e8361900-3939-11ea-8670-93750cc8a40e.png)

Also tried to run on jpeg images, but the errors are the same.

The version of Python installed is 3.7.4 and the requirements were installed as indicated at docs/INSTALL.md.

Am I missing something or doing something wrong?

Thanks in advance.

**Comment by Fang-Haoshu** [comment]
Seems your computer cannot run multiprocessing.
Try enable the '--sp' flag for single processing.

**Comment by pgcavalcanti** [comment]
Yes, it works with the "--sp" flag. Thanks.
But any idea what is wrong with the multiprocessing? Suggestions to fix it?

**Comment by yileld** [comment]
插眼等一个答案hhh

**Comment by Fang-Haoshu** [comment]
Hi! Finally it is solved! You can check the latest version or commit https://github.com/MVIG-SJTU/AlphaPose/commit/cf2e2d57a255f16a790115fb77e3f35cafecb94b
