### ISSUE TITLE
ModuleNotFoundError : no module named 'detector.apis'

### ISSUE THREAD

**Issue by ashutoshsoni891** [MVIG-SJTU/AlphaPose#507]
![Screenshot from 2020-01-18 16-21-25](https://user-images.githubusercontent.com/34247549/72662571-b5118980-3a0e-11ea-885b-6cad927d3ff9.png)

Hi!

I have attached screenshot of Error .My pwd is "AlphaPose" .The "detector" Dir is already available but it is giving me error of ModuleNotFound.Please could you help me for the same.
Thanks in Advance!

Cheers!
Ash

**Comment by Fang-Haoshu** [comment]
Did you run setup.py as in the readme?

**Comment by ashutoshsoni891** [comment]
I did.

**Comment by Fang-Haoshu** [comment]
I successfully reproduce the error when I am not in the env of alphapose, after running "conda deactivate"
Did you quit the conda environment of alphapose?

**Comment by Fang-Haoshu** [comment]
Or is it the same python that you are using?

**Comment by iqraRajpoot** [comment]
@Fang-Haoshu  did you find the reason why is it working within conda env? why are you getting this detector.apis error?
