### ISSUE TITLE
Order of detected people in different frames

### ISSUE THREAD

**Issue by xiaodan9377** [MVIG-SJTU/AlphaPose#508]
The output Json format is as follows:
// for person_1 in image_1
 {
    "image_id" : string, image_1_name, 
    "category_id" : int, 1 for person
    "keypoints" : [x1,y1,c1,...,xk,yk,ck], 
    "score" : float,
 }
// for person_1 in image_2
{
    "image_id" : string, image_2_name, 
    "category_id" : int, 1 for person
    "keypoints" : [x1,y1,c1,...,xk,yk,ck], 
    "score" : float,
 },
 ...

After checking the locations of keypoints, the person_1 in image_1 may not be the person_1 in image_2. Is that correct? If yes, how to track the keypoints of same person through the video frames? Thanks!

**Comment by Fang-Haoshu** [comment]
It's correct.
What you mention is pose tracking. Enable the --tracking flag.
But it's still a experimental function. We do not guarantee its correctness
