### ISSUE TITLE
Can't find compatible version of torchvision to use with the PyTorch implementation

### ISSUE THREAD

**Issue by jessestauffer** [MVIG-SJTU/AlphaPose#509]
I tried cloning and running the PyTorch implementation of AlphaPose but can't find a version of torchvision that is compatible with torch 1.4.0.

```
ERROR: torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 0.4.0 which is incompatible.
```

**Comment by Fang-Haoshu** [comment]
torch 1.4.0 is too high
We suggest using the master branch. The torch and torchvision are 1.1.0 and 0.3.0

**Comment by jessestauffer** [comment]
Thank you - I will give it a go!
