### ISSUE TITLE
Could you please provide more details in the benchmark results?

### ISSUE THREAD

**Issue by ganler** [MVIG-SJTU/AlphaPose#511]
I am curious about your results on 23 FPS on the COCO validation set. My experiment using your `inference_demo` shows that it runs much slower than `openpose`. And due to your python multi-process design, my machine got stuck by the overhead of context switching. I am wondering if I was using your codes in the wrong way or just you didn't make proper benchmarks.

Open pose provides a table showing solid speed results: 
https://docs.google.com/spreadsheets/d/1-DynFGvoScvfWDA1P4jDInCkbD4lg0IKOYbXgEq0sK0/edit#gid=0

So it would be great if you could provide details about:
1. What kind of machine are you using
2. How is the image resolution
3. Did you set your batch size with 1 in the benchmark(It seems that using a batch size more than 1 is not accurate for the term "real-time")

Thanks for your great works!

**Comment by ganler** [comment]
BTW, the resolution of images in COCO dataset is 640x480. However, OpenPose can run 21.7FPS on 1080Ti with a resolution of 1280x720(3 times of 640x480).

**Comment by Fang-Haoshu** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose#runtime-analysis
OpenPose also benchmarks the results here and our speed is faster than their max accuracy, while our accuracy is 10+ mAP higher than their max acc. Same image set, same GPU, same batchsize.

There are many parameters you can tune for accuracy-speed tradeoff, which is what really matters..

**Comment by Fang-Haoshu** [comment]
A accuracy-speed is indeed very needed 😂

**Comment by ganler** [comment]
Thanks for your reply.
A trade-off is indeed important. And I see that the open pose cares about "steady inference" and they seemly take it as a shortcoming of the alpha pose. But from my perspective, the "unsteady speed" should not be blamed, but the longest inference time of the "unsteady speed". I mean there should be an upper bound of the number of humans one architecture could detect. And that is where we can calculate the "slowest unsteady speed".
