### ISSUE TITLE
想问一下pytorch版本处理视频一秒可以检测多少帧

### ISSUE THREAD

**Issue by EasonGZY** [MVIG-SJTU/AlphaPose#513]
想问下pytorch版本处理视频的FPS是多少？这个是根据服务器的配置不同而不一样吗？我运行的配置是4块GeForce GTX 1080 Ti

**Comment by 1vpmaster** [comment]
笔记本1660ti运行10fps

**Comment by Fang-Haoshu** [comment]
单卡2080ti 4-5个人的场景 大概是20fps
