### ISSUE TITLE
已经安装最新版本，如何运行进行姿态估计？

### ISSUE THREAD

**Issue by l976308589** [MVIG-SJTU/AlphaPose#516]
尊敬的作者您好。
感谢您的项目，我已经安装完毕。
能否以
.\\scripts\\inference.sh ${CONFIG} ${CHECKPOINT} ${VIDEO_NAME} # ${OUTPUT_DIR}, optional
为例子，讲解一下如何进行姿态估计？

因为以前alpha是多个项目分开，现在合并在一起，不知道哪一个是姿态估计，也不知道如何姿态估计

**Comment by yinjian28** [comment]
同问，已经安装完毕，请问如何运行姿势估计呀？

**Comment by Fang-Haoshu** [comment]
下载https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md里你需要的模型，CONFIG那里写对应的cfg相对路径  Checkpoint指向模型文件

**Comment by yinjian28** [comment]
您好，没太看明白，我已经安装了最新版本，文件如下图，也下载了mode_zoo中的fastPose模型。安装完毕之后没看到demo文件啊，不知道如何运行最新的姿势估计算法，请指导？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fred Fang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月19日(星期三) 凌晨0:35
收件人:&nbsp;"MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送:&nbsp;"青春年少"<1097482959@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 已经安装最新版本，如何运行进行姿态估计？ (#516)




下载https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md里你需要的模型，CONFIG那里写对应的cfg相对路径  Checkpoint指向模型文件
