### ISSUE TITLE
Detect pose from image array

### ISSUE THREAD

**Issue by atanas1054** [MVIG-SJTU/AlphaPose#521]
Hello,
Thank you for the nice repository. What is the easiest way to detect the pose of a person given an image array? I don't want to use DataWriter and queues but just a simple pose detection on array img as follows:

img = cv2.imread(...) 
pose_keypoints = detectPose(img)

**Comment by Fang-Haoshu** [comment]
Hi, there is an flag --img that can do pose estimation for an image, which points to a image name.
you can run the program by using such flag
For the wrapper, you may need to wrap the program by yourself.
