### ISSUE TITLE
Long-running script for repeated incoming calls

### ISSUE THREAD

**Issue by JivanRoquet** [MVIG-SJTU/AlphaPose#525]
I have a stream of incoming images, the specific frequency of it is unpredictable but let's say there comes 2 to 5 images per second.

Currently I have a setup where I call `demo_inference.py` every time an image comes up. The problem is that it quickly becomes engulfed because the model has to load every single time.

Is it possible to have a "long-running" python script waiting loading the model once at the start, and then responding very fast to any incoming image?

**Comment by Fang-Haoshu** [comment]
I guess you can checkout our video dataloader or image-list dataloader, which put images into a queue.
You can put the incoming images to a queue like that

**Comment by JivanRoquet** [comment]
The problem I see with this approach is that every time the list exhausts, then the process terminates and we need to start a new one when a new image comes in.

Is there a solution to keep the process alive even when idle?

Also, for bulk operations, is there a way for a caller application to get some progress feedback? I'm aware there's stdout but it works in a weird way with the progress bar.

**Comment by Fang-Haoshu** [comment]
Oh I see. You can modify the queue behaviour. Change it to something like

While True:

    If queue.empty()
    sleep(1)
    get_from queue()

You can place such code to somewhere in our pipeline.

**Comment by JivanRoquet** [comment]
Hi,

I've been trying to implement this queuing behaviour but I must say I have a hard time understanding where it should fit exactly. Should it be in `DetectionLoader` from detector.py or directly in demo_inference.py?

I'd be glad if you could point me to some direction here, and according to your guidance I'll submit a PR for your review.

What I'm thinking of is that it could be an additional option or flag when calling `./demo_inference.py`, for instance `--infinite` and if that flag is present, then the program would continue pooling when the directory or list file is exhausted.

**Comment by JivanRoquet** [comment]
Still no answer, went on using Detectron2 instead — AlphaPose is promising but unfortunately still a bit too academic for the moment, and not quite adapted for real-world use. Keep up the work though, very good performance and accuracy. I appreciate that this is a research project and that optimisation for real-world usage is not an immediate target or priority here.
