### ISSUE TITLE
Person bounding box from detector

### ISSUE THREAD

**Issue by JivanRoquet** [MVIG-SJTU/AlphaPose#527]
AlphaPose uses Yolo as a persons detector. Is it possible to get the persons’ bounding boxes from Yolo in the output from AlphaPose?

I can’t see it mentioned in the documentation.

**Comment by Fang-Haoshu** [comment]
You can modify vis_frame() function in writer. The third param is to visualize bbox. We get bbox from human keypoints.

**Comment by Fang-Haoshu** [comment]
add a --showbox flag for vis the box
