### ISSUE TITLE
Labeling tool for generating pose database

### ISSUE THREAD

**Issue by zirus23** [MVIG-SJTU/AlphaPose#528]
We're trying to have labelers create a dataset for our specific data, but can't find a tool to label it for alphapose. What tools were used for obtaining the datasets in alphapose?

**Comment by adriati** [comment]
I used LabelBox. Do you know if you need both .json file and h5 file to train in your own dataset?

**Comment by zirus23** [comment]
We're retraining Alphapose which I think can be done with just the keypoints.json (as in the mscoco example). Labelbox looks promising, we'll try it out.
