### ISSUE TITLE
Skip to next image and display a warning instead of crashing abruptly

### ISSUE THREAD

**Issue by JivanRoquet** [MVIG-SJTU/AlphaPose#530]
When rendering on a list of files using `demo_inference.py`:

```
Loading YOLO model..
Network successfully loaded
Loading pose model from /home/ubuntu/AlphaPose/pretrained_models/fast_res50_256x192.pth...
 24%|██████████████████████████████████████                                                                                                                         | 10340/43226 [24:18<1:02:33,  8.76it/s]Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/AlphaPose/alphapose/utils/detector.py", line 140, in image_preprocess
    img_k = self.detector.image_preprocess(im_name_k)
  File "/home/ubuntu/AlphaPose/detector/yolo_api.py", line 69, in image_preprocess
    img, orig_img, im_dim_list = prep_image(img_source, self.inp_dim)
  File "/home/ubuntu/AlphaPose/detector/yolo/preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

At this stage, AlphaPose is completely crashed and won't process any further image.

This kind of thing is very hard to test exhaustively before running AlphaPose, because as an external user we don't really know the reason of this error. The list of images has already been tested for missing images and there is absolutely none. Plus, all the images were loaded with Pillow.Image and the ones which weren't loaded successfully were discarded.

I'm guessing it might be nice, in this case, to simply display a warning to the user and move on to the next picture, instead of violently crashing the program in the middle of a 5-hours process, just because one image is faulty.

Fixing this seems to be the matter of a simple Try/Catch/Continue statement.

**Comment by JivanRoquet** [comment]
Looks like the faulty line is querying `shape` attribute on what is supposed to hold a CV2 image object.

Therefore a good way to preemptively test for this error is, on the user side, to check that every image loads fine with `cv2.imread(imgpath)` and that has a proper shape. If not, simply remove this image from the pool.

However, again, it would be nice if AlphaPose simply displayed a warning instead of crashing.

**Comment by Fang-Haoshu** [comment]
Thanks! I think it's a good idea to add a try-except function. We will add that in next version
