### ISSUE TITLE
快速推理中的问题

### ISSUE THREAD

**Issue by yinjian28** [MVIG-SJTU/AlphaPose#532]
快速推理中：./scripts/inference.sh ${CONFIG} ${CHECKPOINT} ${VIDEO_NAME} # ${OUTPUT_DIR}, optional    CONFIG代表什么？有哪些可选项？ CHECKPOINT具体代表什么？有哪些选项？求解答

**Comment by Fang-Haoshu** [comment]
alphapose/config/coco/256x192_res50_lr1e-3_1x.yaml
CHECKPOINT是模型文件

**Comment by yinjian28** [comment]
非常感谢回复，我还有几个问题
1:这个.yaml文件我看到coco文件夹有好几个，这有什么区别呀，这个文件是用来干什么的？
2:模型文件有提供吗，是不是需要自己用数据集训练？

---原始邮件---
发件人: "Fred Fang"<notifications@github.com&gt;
发送时间: 2020年2月27日(周四) 晚上9:13
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"yinjian28"<1097482959@qq.com&gt;;
主题: Re: [MVIG-SJTU/AlphaPose] 快速推理中的问题 (#532)



alphapose/config/coco/256x192_res50_lr1e-3_1x.yaml
 CHECKPOINT是模型文件

**Comment by macqueen09** [comment]
好几个yaml是给出了不同配置的模型,比如有res50的,有res150的,给出了不同版本可选.有的精度高一些(慢一些),有的精度低一些.
模型文件作者提供了,可以不用数据集训练直接看效果,也可以重新训练
