### ISSUE TITLE
STN实际上是如何实现的？

### ISSUE THREAD

**Issue by yileld** [MVIG-SJTU/AlphaPose#533]
最新v0.3.0的pytorch版。
按论文的意思应该是bbox的图片输入stn得到仿射变换参数，然后再由参数得到最终的bbox输入sppe。但我看实际上却是原始bbox通过simple_transform.test_transform得到最终bbox，并没有通过一个网络呀？

**Comment by Fang-Haoshu** [comment]
Hi, AlphaPose不包括STN，原始的repo请参考MVIG-SJTU/RMPE

**Comment by HongChow** [comment]
> Hi, AlphaPose不包括STN，原始的repo请参考MVIG-SJTU/RMPE
感谢Alphapose的工作,请问如果不包含STN影响有大,如果是前置摄像头,即人离摄像头较近时影响又会有多大?
