### ISSUE TITLE
Definition of "input size of detection network" of --inp_dim

### ISSUE THREAD

**Issue by JoeyChuuichi** [MVIG-SJTU/AlphaPose#538]
Need some more explanation for the "--inp_dim".

At [speed_up.md](doc/speed_up.md), there is a function which can help detect small size people: --inp_dim.

I really appreciate this function and would like to use it in the opposite way: filter the small size people I don't want to focus on.
Could you help explain more what does this number mean? Is it something like a perimeter of a bounding box?

**Comment by Fang-Haoshu** [comment]
Hi, in fact, you can use the flag --min_box_area directly. It will help filter the small box
You can check docs/run.md for the explanation.

Best wishes
