### ISSUE TITLE
 pose_score<drop

### ISSUE THREAD

**Issue by Innerpeace90** [MVIG-SJTU/AlphaPose#54]
Hi, I find that content of point:[] in the xx_mpii_relpath_5sec_testsub.json file generated by tracker.py is empty,. and the reason is that all the values of pose_score are less than drop value. Is that normal?

**Comment by YuliangXiu** [comment]
I do not think it is normal. Where does the scores come from, AlphaPose?

**Comment by YuliangXiu** [comment]
#50
