### ISSUE TITLE
Pretrained model available on BODY-25 ?

### ISSUE THREAD

**Issue by sebo361** [MVIG-SJTU/AlphaPose#540]
Hi everyone, I am wondering if somebody trained AlphaPose on the BODY-25 keypoint model below ?

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-body_25
![image](https://user-images.githubusercontent.com/29478970/76984773-94e34580-693f-11ea-9bcd-7af6fbb1d521.png)

**Comment by pranavgundewar** [comment]
I am also looking for 25 keypoints based AlphaPose

**Comment by Fang-Haoshu** [comment]
Hi! @sebo361  @pranavgundewar I just add it to the model zoo. You can use the Halpe_26 keypoints version. It includes both MPII and COCO keypoints and foot keypoints, 26 points in total! You can see the demo in the readme.

**Comment by Fang-Haoshu** [comment]
The first 17 keypoints are in COCO format, then (head-top, neck, hip) like MPII dataset, then Left big toe, Right big toe, Left small toe, Right small toe, Left heel, Right heel
Enjoy!

**Comment by sebo361** [comment]
Hi @Fang-Haoshu thank you for adding the new model, which is truly amazing!!

**Comment by JeanGoh** [comment]
Hi @Fang-Haoshu, how do I change from 17 keypoints to 26 keypoints version?
