### ISSUE TITLE
Can't install torch 1.1.0

### ISSUE THREAD

**Issue by Lucalucashhh** [MVIG-SJTU/AlphaPose#543]
Hi,

I tried to install torch using the command given in INSTALL.md 

> pip3 install torch==1.1.0 torchvision==0.3.0
But got an error like

> ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0

Can I use other version instead of 1.1.0?

**Comment by jersonal** [comment]
use conda。 dont use pip.
