### ISSUE TITLE
Error while executing python setup.py

### ISSUE THREAD

**Issue by Lucalucashhh** [MVIG-SJTU/AlphaPose#547]
Hi, I got a error while executing the setup.py like this:

`C:\Users\1\miniconda3\envs\Alphapose\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。

  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'detector.nms.nms_cuda' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\cstddef(7): fatal error C1083: 无法打开包括文件: “stddef.h”: No such file or directory

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`

Any suggestions to solve this?
Thanks

**Comment by Fang-Haoshu** [comment]
Hi, it seems a path error? We haven't met it before. Are there any solutions on google?

**Comment by Fang-Haoshu** [comment]
no response, close
