### ISSUE TITLE
编译前下载了两个权重文件，编译完成后推理，为什么还需要下载其他的权重？

### ISSUE THREAD

**Issue by liguoyu666** [MVIG-SJTU/AlphaPose#551]
如题

**Comment by liguoyu666** [comment]
(alphapose) lgy@lgy:~/PycharmProjects/AlphaPose-master$ python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml --checkpoint pretrained_models/fast_421_res152_256x192.pth --image examples/demo/1.jpg --save_img
Load SE Resnet...
Loading YOLO model..
Downloading: "https://download.pytorch.org/models/resnet152-b121ed2d.pth" to /home/lgy/.cache/torch/checkpoints/resnet152-b121ed2d.pth
Network successfully loaded
  0%|                                                                                                                | 57344/241530880 [01:46<130:30:05, 513.99it/s]

已经下好了权重，为啥推理时还要下载？

**Comment by liguoyu666** [comment]
您好，我在推理时，卡在了det_loader.read()这里。

(alphapose) lgy@lgy:~/PycharmProjects/AlphaPose-master$ python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint pretrained_models/simple_res50_256x192.pth --image examples/demo/1.jpg --outdir ./examples/res --detector yolo --save_img
Loading YOLO model..
Loading pose model from pretrained_models/simple_res50_256x192.pth...
  0%|                                                     | 0/1 [00:00<?, ?it/s]Network successfully loaded

调试发现时在　(inps, orig_img, im_name, boxes, scores, ids, cropped_boxes) = det_loader.read()　这一行卡住了。
加了--sp后:
(alphapose) lgy@lgy:~/PycharmProjects/AlphaPose-master$ python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint pretrained_models/simple_res50_256x192.pth --image examples/demo/1.jpg --outdir ./examples/res --detector yolo --save_img --sp
Loading YOLO model..
Network successfully loaded
非法指令 (核心已转储)

请帮我看下该怎么解决这个问题

**Comment by Fang-Haoshu** [comment]
你好，这个问题似乎解决了？
