### ISSUE TITLE
您好，我在推理时，卡在了det_loader.read()这里

### ISSUE THREAD

**Issue by liguoyu666** [MVIG-SJTU/AlphaPose#553]
(alphapose) lgy@lgy:~/PycharmProjects/AlphaPose-master$ python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint pretrained_models/simple_res50_256x192.pth --image examples/demo/1.jpg --outdir ./examples/res --detector yolo --save_img
Loading YOLO model..
Loading pose model from pretrained_models/simple_res50_256x192.pth...
0%| | 0/1 [00:00<?, ?it/s]Network successfully loaded

调试发现时在　(inps, orig_img, im_name, boxes, scores, ids, cropped_boxes) = det_loader.read()　这一行卡住了。
加了--sp后:
(alphapose) lgy@lgy:~/PycharmProjects/AlphaPose-master$ python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint pretrained_models/simple_res50_256x192.pth --image examples/demo/1.jpg --outdir ./examples/res --detector yolo --save_img --sp
Loading YOLO model..
Network successfully loaded
非法指令 (核心已转储)

请帮我看下该怎么解决这个问题

**Comment by liguoyu666** [comment]
我在这台电脑上又新建了个环境，重新编译一份相同的代码，然而还是遇到问题，
但是我在另一台电脑上，用相同的方法，就能够跑通代码，找了一下午也不知道是哪出错了。
python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint pretrained_models/simple_res50_256x192.pth --image examples/demo/1.jpg --outdir ./examples/res --detector yolo --save_img
Loading pose model from pretrained_models/simple_res50_256x192.pth...
Loading YOLO model..
Network successfully loaded
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]
===========================> Finish Model Running.
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
Results have been written to json.

加了--sp也能够跑通代码。

**Comment by Fang-Haoshu** [comment]
你好，这个说实话有点玄学...可以试试把qsize减小，batchsize减小，降低机器负荷。不行的话我们也没办法了😂

**Comment by liguoyu666** [comment]
> 你好，这个说实话有点玄学...可以试试把qsize减小，batchsize减小，降低机器负荷。不行的话我们也没办法了

谢谢，原因找到了，是显卡驱动的问题

**Comment by jixiaonanzhuaizhuai** [comment]
@liguoyu666  I have the same problem as you. How did you solve the problem of your graphics card driver?

**Comment by liguoyu666** [comment]
> @liguoyu666 I have the same problem as you. How did you solve the problem of your graphics card driver?

You can try unloading the driver and then refitting the NVIDIA driver, making sure you install it correctly

**Comment by jixiaonanzhuaizhuai** [comment]
@liguoyu666  Could you add WeChat for a private chat？ （WeChat: w963849321）Thank you!
