### ISSUE TITLE
关于输出的结果，我有两个问题，希望能够解答一下

### ISSUE THREAD

**Issue by hellozjj** [MVIG-SJTU/AlphaPose#557]
1. 我得到了三个结果文件alphapose-results-forvis-tracked.json， alphapose-results-forvis.json 和 alphapose-results.json 如果我希望利用某一个结果去估计关节的world position, 我应该用哪个文件呢？看到有答案说alphapose-results-forvis-tracked.json只是一个中间结果，是不是应该使用最终结果 alphapose-results.json？
2. 这些结果文件中keypoint的位置x,y 是在原始图片的像素位置吗？ 单位是像素吗？

希望知道的人能给一点解答，谢谢！

**Comment by Fang-Haoshu** [comment]
1 是的 alphapose-results.json
2 是的
