### ISSUE TITLE
电脑上有GPU0和1 ，但是训练模型为什么只能用GPU 0呢？

### ISSUE THREAD

**Issue by Davvwvvid** [MVIG-SJTU/AlphaPose#558]
我是想两个GPU一块用，但是不知道在哪改呢？
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 4.00 GiB total capacity; 2.98 GiB already allocated; 13.76 MiB free; 2.99 GiB reserved in total by PyTorch)

**Comment by Fang-Haoshu** [comment]
--gpu 0,1
不过双卡4G有点小 不建议训练哈

**Comment by Davvwvvid** [comment]
感谢回复
我注意到https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/opt.py 中没有定义  --gpu ，训练时调用会报错 train.py: error: unrecognized arguments: --gpu 0,1
https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/demo_inference.py 里面定义了--gpus 识别的时候可用
 是我的用法错误么？ @Fang-Haoshu

**Comment by Fang-Haoshu** [comment]
噢噢搞错了 训练的时候是自动用多gpu的 你这个是说gpu0 oom了， 但是gpu1也用了
