### ISSUE TITLE
Pose Flow NMS

### ISSUE THREAD

**Issue by Innerpeace90** [MVIG-SJTU/AlphaPose#56]
Hi，according to your paper, the method of Pose Flow NMS is different from the conventional NMS method using frame-by-frame Pose-NMS. However, the code in your github means that the NMS process depends on frame-by-frame Pose-NMS. The code about the Pose flow building puzzled me also, could you help me .

**Comment by YuliangXiu** [comment]
The implementation of Pose Flow is very different from what described in the paper, this is a naive bipartial matching algorithm which can guarantee reasonable results.

**Comment by Innerpeace90** [comment]
What's the meaning of  bipartial? This words cann't be find in dictionaries.

**Comment by YuliangXiu** [comment]
sorry, bipartite matching.二分图匹配

**Comment by Innerpeace90** [comment]
I have consulted some questions with my QQ email. Is it convenient for you to read and help me to solve the puzzles?3Q!

**Comment by Innerpeace90** [comment]
In your tracker.py, I cann't find where '10 frames' is set to find the lost target. If  there are 20 targets in the 1# frame and only 17 targets in the 2# frame, then how to deal with the remaining 3 targets without being matched in the 1# frame?

**Comment by YuliangXiu** [comment]
These 3 targets will be saved in a pool and then be used in the future matching. You can directly read my code, the matching logic is in utils.py file.

**Comment by Innerpeace90** [comment]
Hi, whether the code of pose_flow which is consistent with paper <<Pose Flow: Efficient Online Pose Tracking>> will be  released?

**Comment by Innerpeace90** [comment]
There is a problem about the inter_frame pose distance according to the ORB matching method  recommended in paper Pose_Flow: Efficient Online Pose Tracking. The size of bounding box surrounding keypoints  is 10% person bounding box size according to the standard PCK. I always cann‘t extract feature point in the  bounding box surrounding keypoints. Reason may be that the area of the box is small, leading the pixesl in the box are amost the same . However, when I increase the box area,  many keypoints which are not in the same pose are exactly similar. How to deal with the ORB matching problem?

**Comment by YuliangXiu** [comment]
You can alter the matching feature from ORB to DeepMatching.

**Comment by sberryman** [comment]
I can confirm DeepMatching based tracking is working excellent! I had to shorten the `link_len` for my particular dataset but working great.

**Comment by Innerpeace90** [comment]
Is the  tracking based on DeepMatching  a little slow？

**Comment by YuliangXiu** [comment]
Yes, a little slow, but it will guarantee better accuracy performance

**Comment by sberryman** [comment]
@Innerpeace90 The DeepMatching GPU version I was able to get around 25-30 per second with two GTX 1080 TI's and a GTX 1080.

**Comment by RomeroBarata** [comment]
Hi @sberryman, would that be possible for you to share the modifications you did to the `tracker.py` script to enable it to track a data set other than the PoseTrack? Thanks!

**Comment by RomeroBarata** [comment]
Thanks for your reply and tips @sberryman. I'll do the same and rewrite the script for my data sets. And in case I manage to make it general enough, I'll contribute it back to the repository :)
