### ISSUE TITLE
AlphaPose Install

### ISSUE THREAD

**Issue by DasLoki098** [MVIG-SJTU/AlphaPose#561]
Help on install please.

I am using (Windows 10, cpu only)
I have installed Anaconda (2020.02 - Python 3.7 - 64bit)
In Anaconda I typed this code taken from:
https://leadtosilverlining.blogspot.com/2019/01/alphapose-installation-training-and.html

```
(base) PS C:\MyFolder\TestFolder> conda activate torch-py3-0.4.0
(torch-py3-0.4.0) PS C:\MyFolder\TestFolder> conda install pytorch=0.4.0 -c pytorch
(torch-py3-0.4.0) PS C:\MyFolder\TestFolder> pip install cython setuptools tqdm
(torch-py3-0.4.0) PS C:\MyFolder\TestFolder> pip install -e git+https://github.com/ncullen93/torchsample.git#egg=torchsample
(torch-py3-0.4.0) PS C:\MyFolder\TestFolder> pip install visdom
(torch-py3-0.4.0) PS C:\MyFolder\TestFolder> pip install nibabel
(torch-py3-0.4.0) PS C:\MyFolder\TestFolder> git clone https://github.com/MVIG-SJTU/AlphaPose.git
```
All this is OK.

I then downloaded duc_se.pth & yolov3-spp.weights from Google drive and pasted into models/sppe & /models/yolo taken from:
https://github.com/Amanbhandula/AlphaPose/blob/master/doc/win_install.md

I pasted 10.png files (taken from mp4 video using FFmepeg) into 
C:\MyFolder\TestFolder\AlphaPose\examples\demo-images

When I run the AlphPose code:
`(torch-py3-0.4.0) PS C:\MyFolder\TestFolder\AlphaPose> python demo.py --sp --indir examples/demo-images --outdir examples/demo-results`

I get the following import error:

> Traceback (most recent call last):
>   File "demo.py", line 4, in <module>
>     import torchvision.transforms as transforms
>   File "C:\MyFolder\TestFolder\envs\torch-py3-0.4.0\lib\site-packages\torchvision\__init__.py", line 2, in <module>
>     from torchvision import datasets
>   File "C:\MyFolder\TestFolder\envs\torch-py3-0.4.0\lib\site-packages\torchvision\datasets\__init__.py", line 9, in <module>
>     from .fakedata import FakeData
>   File "C:\MyFolder\TestFolder\envs\torch-py3-0.4.0\lib\site-packages\torchvision\datasets\fakedata.py", line 3, in <module>
>     from .. import transforms
>   File "C:\MyFolder\TestFolder\envs\torch-py3-0.4.0\lib\site-packages\torchvision\transforms\__init__.py", line 1, in <module>
>     from .transforms import *
>   File "C:\MyFolder\TestFolder\envs\torch-py3-0.4.0\lib\site-packages\torchvision\transforms\transforms.py", line 16, in <module>
>     from . import functional as F
> File "C:\MyFolder\TestFolder\envs\torch-py3-0.4.0\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
>     from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
> ImportError: cannot import name 'PILLOW_VERSION'
> 

Can someone suggest how to fix this problem.

**Comment by Fang-Haoshu** [comment]
Have you run pip install -r requirements?

And you need torchvision==0.2.0
Also  you may need to change a version a pillow. But I don't know which one works...

**Comment by DasLoki098** [comment]
Thanks Fang-Haoshu for the quick reply. I very much appreciate it.

From what I have seen AlphaPose is a great program. It must have taken thousands of hours to create. Do you think you or the AlphaPose team can make a quick video on how to install all the requirements and run the program (Windows and/or Linux). It seems crazy not spending a small amount of time showing how to use it, when it has taken so long to develop it.  Doing this will allow everybody interested in the program to use it, get the developers citations, and help improve the program. At the moment everybody I have asked has spent weeks trying to install it, but hasn't been able to as there is little information and most on older incompatible versions. A simple video showing all the steps (including file location structure) with the latest version, will solve thousands of peoples problems.

Thanks again, DasLoki

**Comment by iotMice** [comment]
I am facing the similar issues of installing it on cpu only version.  If possible, then please create the instructions for it to run cpu only version.
Regards
