### ISSUE TITLE
Add GCC version < 6 as constraint

### ISSUE THREAD

**Issue by RSKothari** [MVIG-SJTU/AlphaPose#565]
setup fails when built with GCC 6.5. Seems like a common issue.
Solved by point gcc and g++ soft links to version GCC version 5. More details can be found here: https://github.com/facebookresearch/maskrcnn-benchmark/issues/25

**Comment by Fang-Haoshu** [comment]
Oh I see, thanks!

**Comment by RSKothari** [comment]
@Fang-Haoshu Requesting removing GCC<6 dependency as it causes lots of problems with other newer packages. Perhaps add a self trained RCNN module purely on torch?
