### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by iotMice** [MVIG-SJTU/AlphaPose#568]
I am trying to compile the setup file for the last 3 days but didn't get the success yet.

I am using Ubuntu 18.04 in Virtual box. I have a windows machine without GPU.
In ubuntu, I have installed PyTorch for the CPU version.
I have also installed the CUDA toolkit so that I can have nvcc compiler. Though I haven't installed a GPU driver as I don't have any GPU in the machine.

Can AlphaPose can be used without the GPU??

Please help me to figure out.

**Comment by Fang-Haoshu** [comment]
you can simply run it with --gpu -1 flag

**Comment by iotMice** [comment]
I am getting error on this line while installation
python setup.py build develop
here using --gpu -1 does not work as setup file does not take any argument  gpu flag.
