### ISSUE TITLE
I am getting Broken pipe issue in Detection Loader. Any idea how it can be resolved?

### ISSUE THREAD

**Issue by anilsh** [MVIG-SJTU/AlphaPose#570]
Following is the error sequence...

Loading YOLO model..
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-6-4e272e8a7b82> in <module>
     17 print('Loading YOLO model..')
     18 sys.stdout.flush()
---> 19 det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
     20 det_processor = DetectionProcessor(det_loader).start()
     21 

~/anils/Activity/AlphaPose-pytorch/dataloader.py in start(self)
    307             p = mp.Process(target=self.update, args=())
    308             p.daemon = True
--> 309             p.start()
    310         return self
    311 

~/vedantb/miniconda3/envs/anils/lib/python3.7/multiprocessing/process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

~/vedantb/miniconda3/envs/anils/lib/python3.7/multiprocessing/context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~/vedantb/miniconda3/envs/anils/lib/python3.7/multiprocessing/context.py in _Popen(process_obj)
    289         def _Popen(process_obj):
    290             from .popen_forkserver import Popen
--> 291             return Popen(process_obj)
    292 
    293     class ForkContext(BaseContext):

~/vedantb/miniconda3/envs/anils/lib/python3.7/multiprocessing/popen_forkserver.py in __init__(self, process_obj)
     33     def __init__(self, process_obj):
     34         self._fds = []
---> 35         super().__init__(process_obj)
     36 
     37     def duplicate_for_child(self, fd):

~/vedantb/miniconda3/envs/anils/lib/python3.7/multiprocessing/popen_fork.py in __init__(self, process_obj)
     18         self.returncode = None
     19         self.finalizer = None
---> 20         self._launch(process_obj)
     21 
     22     def duplicate_for_child(self, fd):

~/vedantb/miniconda3/envs/anils/lib/python3.7/multiprocessing/popen_forkserver.py in _launch(self, process_obj)
     52         self.finalizer = util.Finalize(self, os.close, (self.sentinel,))
     53         with open(w, 'wb', closefd=True) as f:
---> 54             f.write(buf.getbuffer())
     55         self.pid = forkserver.read_signed(self.sentinel)
     56 

BrokenPipeError: [Errno 32] Broken pipe

**Comment by Fang-Haoshu** [comment]
How about setting the queue size smaller? add a flag --qsize 100

**Comment by Fang-Haoshu** [comment]
no response, close
