### ISSUE TITLE
多人pose估计中，如何确认我关注的那个人的关节点？

### ISSUE THREAD

**Issue by ldepn** [MVIG-SJTU/AlphaPose#571]
在多人pose估计中，输出的json文件包含了每一个人的关节点，我在开始的一帧图片中确定了其中一个人关节点，如何后续的帧中自动确定这个人的关节点（这个人一直出现在后续的帧中）？

**Comment by MichaelTanger** [comment]
> 在多人pose估计中，输出的json文件包含了每一个人的关节点，我在开始的一帧图片中确定了其中一个人关节点，如何后续的帧中自动确定这个人的关节点（这个人一直出现在后续的帧中）？

pose tracking
