### ISSUE TITLE
mAP in train and val

### ISSUE THREAD

**Issue by Wei-Zhuo** [MVIG-SJTU/AlphaPose#579]
你好！我想请教一下，train时每隔两个epoch的gt_mAP与rcnn_mAP分别具有什么含义，以及val时的box_mAP以及det_mAP又分别对应什么含义？它们之间有什么区别？
谢谢！

**Comment by Wei-Zhuo** [comment]
@Fang-Haoshu
劳烦能够抽空赐教，谢谢！

**Comment by Fang-Haoshu** [comment]
gt_mAP与rcnn_mAP表示human bbox用的gt和用的rcnn检测的情况
box_mAP以及det_mAP也是表示human bbox用的gt和用的rcnn检测的情况

**Comment by hongyaohongyao** [comment]
> gt_mAP与rcnn_mAP表示human bbox用的gt和用的rcnn检测的情况
> box_mAP以及det_mAP也是表示human bbox用的gt和用的rcnn检测的情况

mAP是box的还是keypoints？

**Comment by lawo123** [comment]
> gt_mAP与rcnn_mAP表示human bbox用的gt和用的rcnn检测的情况 box_mAP以及det_mAP也是表示human bbox用的gt和用的rcnn检测的情况


> gt_mAP与rcnn_mAP表示human bbox用的gt和用的rcnn检测的情况 box_mAP以及det_mAP也是表示human bbox用的gt和用的rcnn检测的情况

![image](https://user-images.githubusercontent.com/44777088/137237397-a61a633c-10a5-4ca7-b507-e31b226ba8a1.png)
那请问这个结果是rcnn mAP的结果吗？为什么我直接下载的预训练模型测试的验证集只有70.2Ap呢？ @Fang-Haoshu
