### ISSUE TITLE
A problem in running run.sh

### ISSUE THREAD

**Issue by guozhongluo** [MVIG-SJTU/AlphaPose#58]
0
generating bbox from Faster RCNN...
/home/muse/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-05-07 16:46:22.005286: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/media/muse/MuseAR/DeepLearning/AlphaPose/examples/demo/

  0%|                                                                                        | 0/3 [00:00<?, ?it/s]/home/muse/.local/lib/python2.7/site-packages/tqdm/_monitor.py:89: TqdmSynchronisationWarning: Set changed size during iteration (see https://github.com/tqdm/tqdm/issues/481)
  TqdmSynchronisationWarning)
100%|████████████████████████████████████████████████████████████████████████████████| 3/3 [01:01<00:00, 20.54s/it]
pose estimation with RMPE...
MPII	
FATAL THREAD PANIC: (pcall) [string "  local Queue = require 'threads.queue'..."]:1: module 'threads.queue' not found:
	no field package.preload['threads.queue']
	no file '/home/muse/.luarocks/share/lua/5.1/threads/queue.lua'
	no file '/home/muse/.luarocks/share/lua/5.1/threads/queue/init.lua'
	no file '/home/muse/torch/install/share/lua/5.1/threads/queue.lua'
	no file '/home/muse/torch/install/share/lua/5.1/threads/queue/init.lua'
	no file './threads/queue.lua'
	no file '/home/muse/torch/install/share/luajit-2.1.0-beta1/threads/queue.lua'
	no file '/usr/local/share/lua/5.1/threads/queue.lua'
	no file '/usr/local/share/lua/5.1/threads/queue/init.lua'
	no file '/home/muse/torch/install/lib/threads/queue.so'
	no file '/home/muse/.luarocks/lib/lua/5.1/threads/queue.so'
	no file '/home/muse/torch/install/lib/lua/5.1/threads/queue.so'
	no file './threads/queue.so'
	no file '/usr/local/lib/lua/5.1/threads/queue.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/muse/torch/install/lib/threads.so'
	no file '/home/muse/.luarocks/lib/lua/5.1/threads.so'
	no file '/home/muse/torch/install/lib/lua/5.1/threads.so'
	no file './threads.so'
	no file '/usr/local/lib/lua/5.1/threads.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by Fang-Haoshu** [comment]
Using Lua 5.2 should fix this.

**Comment by benkmoore** [comment]
@Fang-Haoshu I have the same error here

[https://github.com/phillipi/pix2pix/issues/177]

Can you help me?

Any advice would be great, thanks!
