### ISSUE TITLE
Predictions produces two poses for 1 person

### ISSUE THREAD

**Issue by abcde13** [MVIG-SJTU/AlphaPose#581]
Couldn't find an issue for this, but wanted to ask if this issue has been seen.

I have a video where, upon looking at the frames of the video created by the `--save-video` flag, I see two poses overlayed on the single individual in the video. There is only 1 person in the video the entire time. Also, as expected, this can be seen in the output json files, where there are 2 people predicted in those frames.

**Comment by Fang-Haoshu** [comment]
Hi, it's normal. You can use the confidence score to filter the person you want. We save all possible predictions.
