### ISSUE TITLE
什么是kp_scores

### ISSUE THREAD

**Issue by kankanzheli** [MVIG-SJTU/AlphaPose#582]
在多人估计生成的alphapose_result.json文件中对每个关节点对应三个数据。前两个数据对应关节点的位置坐标。通过查看代码了解到第三个数据是kp_scores。这个kp_scores具体指什么呢？它是如何得到的呢？（或者计算他的函数是什么呢？）
期待您的回复

**Comment by Fang-Haoshu** [comment]
你好，是每个点的置信度，网络预测得到
