### ISSUE TITLE
算法还是使用的RMPE中的算法么？

### ISSUE THREAD

**Issue by lyfe667** [MVIG-SJTU/AlphaPose#588]
请问这个算法还是使用的RMPE中的算法吗？为什么我在源码中没有找到论文中提到的STN等部分？

**Comment by Fang-Haoshu** [comment]
你好，AlphaPose是基于RMPE的部分算法开发的（poseNMS, PGPG)，其中SSTN已经去掉了，我们最近在写一个AlphaPose新文章。SSTN的部分可以参考RMPE原repo
