### ISSUE TITLE
新版Alphapose跑不通

### ISSUE THREAD

**Issue by GuoHaiYang123** [MVIG-SJTU/AlphaPose#589]
最新版本的Alphapose，我按要求下载了预训练好的模型，用--checkpoint和--cfg分别定位到模型的位置以及.yaml文件，并加上了--sp --vis --showbox flag 在运行demo_inference.py程序时,依旧各种报错，例如：ModuleNotFoundError: No module named 'detector'、ImportError: cannot import name 'deform_conv_cuda' from  'alphapose.models.layers.dcn'之类，老版本的Alphapose我能成功运行，不知道新版本的问题出在哪里？还希望作者能解答一下，万分感谢！

**Comment by Fang-Haoshu** [comment]
没有安装？

**Comment by GuoHaiYang123** [comment]
安装什么？

**Comment by Fang-Haoshu** [comment]
doc/INSTALL.md

**Comment by GuoHaiYang123** [comment]
你好，请问windows系统下需要安装gcc（MinGW）吗？还是只要安装Visual Studio就行了？我遇到的cannot import name 'deform_conv_cuda' from 'alphapose.models.layers.dcn报错是因为没装gcc吗？还是因为版本不对？一直跑不通好难受 @Fang-Haoshu

**Comment by GuoHaiYang123** [comment]
python3.7,pytorch1.1.0、torchvision0.3.0、cython我都装了，CUDA10.2,我都装了,关于
export PATH=/usr/local/cuda/bin/:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
pip install cython
sudo apt-get install libyaml-dev
python setup.py build develop --user这一块儿我不清楚该怎么操作，希望能解答一下，谢谢 @Fang-Haoshu

**Comment by Fang-Haoshu** [comment]
就逐行安装就行 
python setup.py build develop --user得要跑

**Comment by GuoHaiYang123** [comment]
谢谢，我已经成功跑通了



---原始邮件---
发件人: "Fred Fang"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 上午9:53
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"GuoHaiYang123"<2423419980@qq.com&gt;;
主题: Re: [MVIG-SJTU/AlphaPose] 新版Alphapose跑不通 (#589)




 
就逐行安装就行
 python setup.py build develop --user得要跑

**Comment by samylee** [comment]
hello guys, go and find c++ library: https://github.com/samylee/SamyleePoseApi-OpenLibrary
