### ISSUE TITLE
如何在alphapose中使用efficientdet作为检测器？

### ISSUE THREAD

**Issue by Anikily** [MVIG-SJTU/AlphaPose#594]
detector中加入了efficientdet，但是model_zoo中没有运行的性能结果？

**Comment by xuchao1688** [comment]
efficientdet是新上线的检测器，相关调试和性能的测量还在进行中。要使用beta版本的话，首先将effdet模型权重放于`detector/efficientdet/weights/`下，在inference时 flag指定需要使用的effdet版本 `--detector ${detector name: efficientdet_d1 eg.}`

**Comment by Fang-Haoshu** [comment]
It is not fully evaluated and officially supported. You may use it at your own risk

**Comment by Fang-Haoshu** [comment]
https://github.com/rwightman/efficientdet-pytorch 权重的话可以在这里找到
