### ISSUE TITLE
关于transforms.py里的仿射变换矩阵

### ISSUE THREAD

**Issue by zhaoyongjun1113** [MVIG-SJTU/AlphaPose#596]
https://github.com/MVIG-SJTU/AlphaPose/blob/487885b685b04cb0d9cfe0282c927c5bc45a706d/alphapose/utils/transforms.py#L679-L685
这里的src_w=scale_tmp[0] 是否需要改为　src_h=scale_tmp[1]
对应的下面也要改成
src_dir = get_dir([0, src_h * -0.5], rot_rad)
dst_dir = np.array([0, dst_h * -0.5], np.float32)
这样子呢
对于demo中的3.jpg 有些许的结果差异

**Comment by Fang-Haoshu** [comment]
Hi, they should be the same. Can you show the result difference that you get? It seems we get the same results in our side.

**Comment by zhaoyongjun1113** [comment]
> Hi, they should be the same. Can you show the result difference that you get? It seems we get the same results in our side.

Yes,it certainly has no difference between two codes.Maybe I got a mistake at that time.

**Comment by Fang-Haoshu** [comment]
good
