### ISSUE TITLE
请问MODEL ZOO中的batch size和lr？

### ISSUE THREAD

**Issue by lyrgwlr** [MVIG-SJTU/AlphaPose#597]
请问 model zoo中的模型是用几卡跑的呢？总 batch size是多少？
我用8卡，每卡batch size=32, 总batch size=256，然后lr=0.001，cfg文件一样。
但是我复现结果在COCO上的det val mAP只有70.+mAP，而model zoo中给的是73.3mAP。
是我的 batch size 和 lr 对应不上的关系吗？
请赐教，感谢！

**Comment by Fang-Haoshu** [comment]
请问最后有加DPG跑吗？

**Comment by Fang-Haoshu** [comment]
说错 应该是PGPG

**Comment by lyrgwlr** [comment]
> 说错 应该是PGPG

没有加PGPG，master分支的代码里有PGPG吗？

**Comment by Jeff-sjtu** [comment]
你好，Fast Pose (DUC) - ResNet 152的训练cfg我们放错了，实际对应的配置应该是和log里面一致。
https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/logs/fast_421_res152_256x192.log#L4
抱歉这是我们的失误。
