### ISSUE TITLE
Differences of alpha-pose-results and alpha-pose-results-forvis

### ISSUE THREAD

**Issue by ZiyuanTonyZhang** [MVIG-SJTU/AlphaPose#60]
I didn't find any discribtions for those two files even in output.md. I know those are saved output results but what different? Thanks ahead.

**Comment by Fang-Haoshu** [comment]
Hi, forvis is a file for visualization, the information are the same in these two files, and they just have differences in format. You can simply use the first file, output.md gives the format for it.
