### ISSUE TITLE
how to install or run it on cpu only machine?

### ISSUE THREAD

**Issue by guoxiaolu** [MVIG-SJTU/AlphaPose#600]
when install, it seems some strong dependency to cuda. When run demo_inference.py directly, errors like "ImportError: cannot import name 'deform_conv_cuda' from 'alphapose.models.layers.dcn'" . how to deal with it to run it on cpu-only machine?
`make_cuda_ext(
            name='nms_cpu',
            module='detector.nms',
            sources=['src/nms_cpu.cpp']),
        make_cuda_ext(
            name='nms_cuda',
            module='detector.nms',
            sources=['src/nms_cuda.cpp', 'src/nms_kernel.cu']),
        make_cuda_ext(
            name='roi_align_cuda',
            module='alphapose.utils.roi_align',
            sources=['src/roi_align_cuda.cpp', 'src/roi_align_kernel.cu']),
        make_cuda_ext(
            name='deform_conv_cuda',
            module='alphapose.models.layers.dcn',
            sources=[
                'src/deform_conv_cuda.cpp',
                'src/deform_conv_cuda_kernel.cu'
            ]),
        make_cuda_ext(
            name='deform_pool_cuda',
            module='alphapose.models.layers.dcn',
            sources=[
                'src/deform_pool_cuda.cpp',
                'src/deform_pool_cuda_kernel.cu'
            ]),`

**Comment by Fang-Haoshu** [comment]
Hi，DCN does not support cpu, you may choose other networks.
