### ISSUE TITLE
How to create id from alphapose.json file?

### ISSUE THREAD

**Issue by subhamgupta053** [MVIG-SJTU/AlphaPose#603]
I have executed video_demo on a video and a json file is created.How can I use this Json file to create the id no. of each individual being in the video.

**Comment by Fang-Haoshu** [comment]
Hi, to obtain id, you can either use ''--detector tracker'' flag or use ''--posetrack'' flag

**Comment by Fang-Haoshu** [comment]
It's available on the master branch.
