### ISSUE TITLE
CrowdPose not working?

### ISSUE THREAD

**Issue by nicolasugrinovic** [MVIG-SJTU/AlphaPose#605]
Hi, thank you for the great work!

I want to use CrowdPose, I have installed the **pytorch branch** and I run with the same problem as in https://github.com/MVIG-SJTU/AlphaPose/issues/394#issue-476029626 . I see no difference in performance with the` --matching` option. Am I doing something wrong? I am using the following command:

`python demo.py --indir ./examples/basket/ --outdir examples/res_basket_matching/ --matching --save_img`

Also I see multi-color lines, not green/orange. The result is the following.

Thank you.

![in](https://user-images.githubusercontent.com/25443240/84668431-ecd01f00-af23-11ea-8651-3c376035cc65.jpg)

**Comment by Fang-Haoshu** [comment]
Hi, is the code modified? It seems the connections are all wrong.

**Comment by nicolasugrinovic** [comment]
Hi, no, I have not modified the code
