### ISSUE TITLE
poseflow real-time (online) webcame demo?

### ISSUE THREAD

**Issue by edwardnguyen1705** [MVIG-SJTU/AlphaPose#606]
Hi,
Have anyone tried to track pose in real-time? How about the whole pipeline (both pose estimator and tracker, assume there are 5 people in each frame) speed (fps).

**Comment by Fang-Haoshu** [comment]
In fact, the  poseflow cannot achieve realtime on my computer after embed it into the multi-processing framework. It consumes a lot of CPU. I guess you can try to use '--detector tracker' as realtime workaround. A better solution has been proposed and we will sync the code soon.

**Comment by edwardnguyen1705** [comment]
Hi @Fang-Haoshu ,
Thanks for your quick response. While waiting for your update, I will try as you suggested.
