### ISSUE TITLE
Rendering stuck at X images in the queue

### ISSUE THREAD

**Issue by RSKothari** [MVIG-SJTU/AlphaPose#608]
Will this result in any change in the `json` file of poses? Or is the rendering purely for display purposes? How do I disable rendering pose output videos? It is a very slow process for me. For some reason, `vis_fast` does not seem to work for me.

```
script = os.path.join(path_alphapose,
                      'scripts',
                      'demo_inference.py')

cfg_str = ' --cfg {}'.format(config)
ckpt_str = ' --checkpoint {}'.format(checkpoint)
vd_str = ' --video {}'.format(vidId)
outDir_str = ' --outdir {}'.format(outDir)
strRun = 'python {}'.format(script) + \
            cfg_str + \
            ckpt_str + \
            vd_str + \
            outDir_str + \
            ' --detbatch 10' + \
            ' --qsize 1024' + \
            ' --pose_track' + \
            ' --gpus 0'
```
Note that I even tried to explicitly turn `save_video=False` in `demo_inference.py` in line 197 - no luck.

**Comment by RSKothari** [comment]
Also, out of curiosity - does the pose estimation improve if we enable `pose_track` ?

**Comment by xuchao1688** [comment]
Please ensure that `vis`, `save_img` and `save_video` have been set `False`, which are `False` by default. In addition, except rendering images, other post-processing operations (like poseNMS) will occupy a part of cpu time.

**Comment by xuchao1688** [comment]
`pose_track` flag tracks the persons in a video. You can check the tracking result in `alphapose-results.json`, while it doesn't help improving pose estimation mAP directly.

**Comment by RSKothari** [comment]
So per frame pose estimates do not improve using the track estimates. Hmm, it would be so cool if you could interpolate joint locations for missing frames using tracklets or improve joint confidence by temporal modules. A flag named `interpolated` could be provide which would indicate the same. Anyway, thanks. I decided to disable tracking. This ensured that the images weren't written out.
