### ISSUE TITLE
图片识别得到alphapose-results.json的空文件

### ISSUE THREAD

**Issue by Jinger1218** [MVIG-SJTU/AlphaPose#611]
在终端使用命令python demo.py --indir examples/demo/2.jpg --outdir examples/res --sp 
得到了一个examples\res\alphapose-results.json的空文件。
请问一下为什么没有获取到结果？ 是否哪里操作有误？
python 3.6
gtx1660 cuda 10.0版本

![image](https://user-images.githubusercontent.com/23743474/85202799-8a1fbe80-b33b-11ea-8c59-562db7ac3124.png)
![image](https://user-images.githubusercontent.com/23743474/85202813-a1f74280-b33b-11ea-8c0a-4e569e21577a.png)

**Comment by Jinger1218** [comment]
PS C:\Users\15750\Desktop\AlphaPose> python demo.py --indir examples/demo/2.jpg --outdir examples/res --sp 
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
0it [00:00, ?it/s]
===========================> Finish Model Running.
PS C:\Users\15750\Desktop\AlphaPose>

**Comment by xuchao1688** [comment]
indir设置不正确，期望的输入是一个路径，所以改为`--indir examples/demo`。只想看单张图的结果的话，将`--indir`改为`--image`

**Comment by Jinger1218** [comment]
> indir设置不正确，期望的输入是一个路径，所以改为`--indir examples/demo`。只想看单张图的结果的话，将`--indir`改为`--image`

感谢，问题已经解决
