### ISSUE TITLE
Missing keypoints with Tracker detector

### ISSUE THREAD

**Issue by sebo361** [MVIG-SJTU/AlphaPose#612]
Hi guys,  I am using the tracker detector to get each person's ID throughout the entire video and its working great! I would like to plot only the most dominant person in the video and therefore I am choosing the person with the largest bounding box across frames - it works nicely so far.

However there a couple of frames in the video when no keypoints of this person get detected. I tried several combinations of parameters settings `CONFIDENCE` and `NMS_THRES` but there are still frames missing. With which inference settings can make the model sensitive in order to give me keypoints for every single frames (its fine if some keypoints are not accurate)?

**Comment by Fang-Haoshu** [comment]
Oh hi, how about setting confidence to a low value, says 0.1?

But it may result in redundant ids in other frames.

**Comment by sebo361** [comment]
Hi @Fang-Haoshu thanks for your quick answer! I even set the `CONFIDENCE` in both `yolo_cfg.py` as well as `tracker_cfg.py` to 0.01 and i am still not getting keypoints for all frames across the video..

I am using following simple method to "filter" keypoints of a person's ID:

```
keypoints1, keypoints2, keypoints3, keypoints4, keypoints5  = [], [], [], [], []
    for x in range(len(final_result)):
        for y in range(len(final_result[x]['result'])):
            if 1.0 in final_result[x]['result'][y]['idx']:
                keypoints1.append(final_result[x]['result'][y]['keypoints'])
            if 2.0 in final_result[x]['result'][y]['idx']:
                keypoints2.append(final_result[x]['result'][y]['keypoints'])
            if 3.0 in final_result[x]['result'][y]['idx']:
                keypoints3.append(final_result[x]['result'][y]['keypoints'])
            if 4.0 in final_result[x]['result'][y]['idx']:
                keypoints4.append(final_result[x]['result'][y]['keypoints'])
            if 5.0 in final_result[x]['result'][y]['idx']:
                keypoints5.append(final_result[x]['result'][y]['keypoints'])
```

Maybe I am missing something or there is a smarter way of doing it?

**Comment by Fang-Haoshu** [comment]
Hmmmm, that's weird. Maybe you can simply pad the missing keypoints using previous frame's results? A better tracking method will be online in July.

**Comment by sebo361** [comment]
Awesome thanks a lot @Fang-Haoshu and I am really excited about the upcoming tracking method!
