### ISSUE TITLE
undefined symbol: THPVariableClass

### ISSUE THREAD

**Issue by Yukun4119** [MVIG-SJTU/AlphaPose#614]
I always meet with this problem:
ImportError: /home/XXXXXXXX/exp/AlphaPose/alphapose/models/layers/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

**Comment by Fang-Haoshu** [comment]
Hi, it seems a problem of the pytorch. Is the installation correct? Can you try other models like the duc model?

**Comment by Yukun4119** [comment]
> Hi, it seems a problem of the pytorch. Is the installation correct? Can you try other models like the duc model?

Thanks a lot!! I have fixed this problem by reinstalling

**Comment by Fang-Haoshu** [comment]
great!
