### ISSUE TITLE
Running pose_track with single process

### ISSUE THREAD

**Issue by sebo361** [MVIG-SJTU/AlphaPose#615]
Hi Alphapose Team,

I would like to use your `pose_track` feature by running Alphapose as single process `--sp=True` but unfortunately it does not work. Any idea how to solve that? I definitely need to stick with running it as single process.

Thanks and best!

**Comment by Fang-Haoshu** [comment]
How about using flag --detector tracker and --sp for your tracking?

**Comment by sebo361** [comment]
Hi @Fang-Haoshu i currently using flag --detector tracker and --sp, but I work with videos where people sometimes step out of the video frame. Here the detector tracker assigns a new ID for the same person, but the pose_track method assigns the same ID for the same person which is what I am aiming for. Maybe your new tracker method you will release this month can do better?

**Comment by Fang-Haoshu** [comment]
Oh I see. Yes, it will do better.

**Comment by Fang-Haoshu** [comment]
Hi, the new tracking module is available now. You can download the tracking model in the trackers/ folder and use the flag --pose_track
