### ISSUE TITLE
model zoo fast pose是否有国内下载地址？

### ISSUE THREAD

**Issue by Jinger1218** [MVIG-SJTU/AlphaPose#617]
我这里的网络访问不上google云盘。 是否有百度网盘之类的 fast pose下载地址

**Comment by Fang-Haoshu** [comment]
您好， 好的 我们传一下

**Comment by CangHaiQingYue** [comment]
@Fang-Haoshu 大佬您好，有没有百度盘的连接放出来，咱上不去google drive。

**Comment by HHHcwb** [comment]
预训练模型国内可以下载了吗，我看model_zoo里面都还是google的链接

**Comment by Fang-Haoshu** [comment]
@CangHaiQingYue @HHHcwb @Jinger1218 你好，可以试一下现在model zoo里面的halpe 26, 有26个关键点，格式如下哈
The first 17 keypoints are in COCO format, then (head-top, neck, hip) like MPII dataset, then Left big toe, Right big toe, Left small toe, Right small toe, Left heel, Right heel
