### ISSUE TITLE
关于置信度

### ISSUE THREAD

**Issue by kankanzheli** [MVIG-SJTU/AlphaPose#618]
我尝试使用alphapose的代码在JAAD文件夹上。当行人的双眼被遮挡时（例如行人背向摄像头时），行人双眼的置信度应该较低。但是在实际情况下，在行人距离摄像头较近的情况下，任然有行人背向车辆但是双目置信度较高的结果。有什么方法能改善这种情况呢？可以通过更改训练alphapose模型的样本来改善这种情况吗？
期待你的回复

**Comment by Fang-Haoshu** [comment]
加上鼻子的点一起判断可以吗

**Comment by kankanzheli** [comment]
额，并没有多大的改善

**Comment by kankanzheli** [comment]
根据我现有的结果，在行人看向摄像头的情况下，头部关键点的置信度没有和行人到摄像头的距离产生良好的线性关系。而在行人不看向摄像头的情况下，双目两个关键点任然可能获得较高的置信度。
根据我的设想，在行人不看向摄像头时，大部分情况下，行人至少有一只眼睛被遮挡。至少一只眼睛的置信度较低。行人看向摄像头时，由于双眼朝向摄像头，所以双目必然得到较高置信度。
但直接根据现在程序得出的结果是不足以支持作出这样的判断的

**Comment by Fang-Haoshu** [comment]
那么可能需要增加一些训练样本了，这个应该主要受数据分布的影响比较大
