### ISSUE TITLE
How to train the full model?

### ISSUE THREAD

**Issue by shinerio** [MVIG-SJTU/AlphaPose#62]
I have read the README.md in the folder named train,it seems that it is just a single person pose estimator.How can i train the whole model in paper by myself.

**Comment by Fang-Haoshu** [comment]
Hi, you can checkout this repo: https://github.com/MVIG-SJTU/RMPE

**Comment by shinerio** [comment]
Thank you,but It seems that is an old version,can you reveal what's the difference between them results in the fact this one performs better than that.

**Comment by Fang-Haoshu** [comment]
Hi, you can get the answer here: #61

**Comment by shinerio** [comment]
Got it,Thank you for your patients

**Comment by shinerio** [comment]
Hi , i have reviewed most of the code,but nms training module was not found,can you tell where is  the code for  nms module,is it trained independently without other modules involved.

**Comment by Fang-Haoshu** [comment]
In https://github.com/MVIG-SJTU/AlphaPose/tree/master/predict/json
BTW, we do not train it

**Comment by shinerio** [comment]
Thank you,I have found that.With no training,how do you get the four params. Moreover,i also found that the PGPG module just uses some random transformation,but the paper said that it uses k-means to generate a group of atomic poses.How did that,hoping to hear reply from you.

**Comment by Fang-Haoshu** [comment]
Hi, please refers to the paper for how we get the params.
You can find the PGPG module in this repo: https://github.com/MVIG-SJTU/RMPE

**Comment by shinerio** [comment]
Sorry,I think i can't find that,but i find one here : https://github.com/Fang-Haoshu/multi-human-pose/blob/master/train/src/util/pose.lua and it is just a random transformation.Can you tell me a little more about the detail.
