### ISSUE TITLE
Training issues in windows

### ISSUE THREAD

**Issue by jianghongsun** [MVIG-SJTU/AlphaPose#620]
hi,Thank you for your sharing. I have some problems.
1. Using pip to install torch. when I running the train.py 
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda.

Can you give me some advice? Looking forward to your reply.

**Comment by Fang-Haoshu** [comment]
Hi, deform conv itself does not support windows. You can train other models like fast-duc

Best wishes
