### ISSUE TITLE
can i use this code to train hand landmarks?  

### ISSUE THREAD

**Issue by aa12356jm** [MVIG-SJTU/AlphaPose#621]
thanks for sharing the codes ,can i use this code to train hand landmark models?  how can i rewrite the code? can you give me some tips？ thanks

**Comment by Fang-Haoshu** [comment]
Hi, yes you can do so! Just modify the code in the dataset/ and make you own data loader.
In fact, we will release a model that contains hand keypoint in August. I guess it will be helpful to you.

**Comment by Fang-Haoshu** [comment]
In fact, there is a PR: https://github.com/MVIG-SJTU/AlphaPose/pull/534
You can check it out

**Comment by aa12356jm** [comment]
thanks,i will try

**Comment by Fang-Haoshu** [comment]
Hi，we add a new dataset and model named Halpe, it supports full body keypoints including hand. You can refer to that. I will update the dataset link today and the model soon!

**Comment by Fang-Haoshu** [comment]
Hi! You can checkout https://github.com/Fang-Haoshu/Halpe-FullBody

**Comment by aa12356jm** [comment]
ok，thanks
