### ISSUE TITLE
输入时间较长的视频  姿态估计和 跟踪的时候   时间很慢

### ISSUE THREAD

**Issue by Deepcong2019** [MVIG-SJTU/AlphaPose#624]
姿态估计  单进程、多进程和  跟踪的时候 单进程、多进程 都试过了   很慢

**Comment by Fang-Haoshu** [comment]
what is the command you use? How many people are there in the video? Many factors can influence the speed. The 20 fps are obtained on Nividia 2080Ti for images with 4-5 people

**Comment by Fang-Haoshu** [comment]
You need to provide more information because it is related to your environment.

**Comment by Deepcong2019** [comment]
机器配置  i7 9700k  8核8线程    显卡1080ti 12G  
帧中的人最少的3-4个  多的有不到20个
两分钟多的视频  姿态估计（单进程--sp）这一块5分钟，跟踪(用的单进程，多进程更慢)需要5分钟

![微信图片_20200715111543](https://user-images.githubusercontent.com/24631762/87499505-0ed8d080-c68d-11ea-976b-14182cdb90ee.png)

**Comment by Deepcong2019** [comment]
![微信图片_20200715111543](https://user-images.githubusercontent.com/24631762/87499549-27e18180-c68d-11ea-97df-20fddd8b30be.png)

**Comment by Fang-Haoshu** [comment]
20-40个人太多了
另外--posetrack这个功能我们测试下来也很慢，建议用--detector tracker这个flag来实现跟踪，另外我们八月份会上线新版跟踪，会更快一些
