### ISSUE TITLE
不加--sp是多进程 ，加了--sp是单线程，姿态估计这一块是不是属于I/O密集型   应该使用多线程？？？？   

### ISSUE THREAD

**Issue by Deepcong2019** [MVIG-SJTU/AlphaPose#625]
编程小白   希望指教

**Comment by xuchao1688** [comment]
`--sp`是单进程，子进程的任务改由多线程实现。

**Comment by Deepcong2019** [comment]
` def start_worker(self, target):
        if self.opt.sp:
            p = Thread(target=target, args=())

        else:
            p = mp.Process(target=target, args=())

        # p.daemon = True
        p.start()
        return p`

这个Thread  是多线程吗 @xuchao1688

**Comment by Deepcong2019** [comment]
` def start_worker(self, target):
        if self.opt.sp:
            p = Thread(target=target, args=())

        else:
            p = mp.Process(target=target, args=())

        # p.daemon = True
        p.start()
        return p`

**Comment by xuchao1688** [comment]
是的

**Comment by Deepcong2019** [comment]
好的  谢谢 @xuchao1688
