### ISSUE TITLE
Files not sorted (alphabetically) in demo script

### ISSUE THREAD

**Issue by theRealSuperMario** [MVIG-SJTU/AlphaPose#626]
Hi

I noticed that the files are not being processed in alphabetic order when running the demo script. This might cause some problems when people want to have the same within the json files when running it repeatedly on the same folder.

However it is a minor issue since the json file will have the id stored, so sorting by id is possible after all.

I think it would still make sense to just sort the list beforehand, like so:

https://github.com/theRealSuperMario/AlphaPose/commit/411669a54e9b2dfe9d2cc73f0ffa0835f0fb1cc5

I could make a PR if desired.

Cheers

**Comment by Fang-Haoshu** [comment]
Oh I see. Sure it would help:D Many thanks!

What will the order be if we use sorted() function? For example, will it return results like:

1.jpg 11.jpg 2.jpg 3.jpg 8.jpg

or
1.jpg 2.jpg 3.jpg  8.jpg 11.jpg

**Comment by theRealSuperMario** [comment]
Unfortunately, it will be like this

<img width="343" alt="image" src="https://user-images.githubusercontent.com/6517465/87449419-7b0bf380-c5fd-11ea-8c50-787aef5d3fc6.png">


But I think this is a problem of the file naming convention rather than the sorted function.

More on this [here](https://stackoverflow.com/questions/18282370/in-what-order-does-os-walk-iterates-iterate)

**Comment by Fang-Haoshu** [comment]
Oh I see. Haha yes. I guess we can use natural sort: https://stackoverflow.com/questions/5967500/how-to-correctly-sort-a-string-with-a-number-inside
Though it might be slower😂

**Comment by theRealSuperMario** [comment]
I didn't even know about this, but it sounds like the natural thing to do
(pun intended).

**Comment by christw16** [comment]
It can use natsort
https://pypi.org/project/natsort/

from natsort import natsorted, ns
and then in demo_inference.py line 129
=> im_names = natsorted(im_names) would be fine

**Comment by Fang-Haoshu** [comment]
Oh wow. It looks great! Could you make a PR and we are about to merge it!:D

**Comment by christw16** [comment]
@Fang-Haoshu  ok~ thx

**Comment by Fang-Haoshu** [comment]
Thank you guys! Fixed in the latest commit.
