### ISSUE TITLE
It takes too long to detect many people

### ISSUE THREAD

**Issue by liguoyu666** [MVIG-SJTU/AlphaPose#627]
It takes too long to detect many people，the function get_func_heatmap_to_coord() needs to loop for everyone. Can we reduce the time of detecting for many people?

**Comment by Fang-Haoshu** [comment]
Hi, yes it's a problem. But we cannot find a way to speed up this part yet. Seems hard to parallelize it.

**Comment by liguoyu666** [comment]
> Hi, yes it's a problem. But we cannot find a way to speed up this part yet. Seems hard to parallelize it.

thank you for your reply
