### ISSUE TITLE
Cannot use --save_img

### ISSUE THREAD

**Issue by christw16** [MVIG-SJTU/AlphaPose#628]
Here is what I face the problem, It seems that it can not save the image. 

=======================
(alphapose) XXXXX@XXXXX-WS-E500-G5-WS690T:~/AlphaPose$ python3 scripts/demo_inference.py --cfg pretrained_models/256x192_res50_lr1e-3_1x-simple.yaml --checkpoint pretrained_models/simple_res50_256x192.pth --indir examples/demo/ --outdir ./examples/res/--save_img --vis_fast --flip --gpus 0,1
Loading YOLO model..
Loading pose model from pretrained_models/simple_res50_256x192.pth...
Network successfully loaded
 33%|███████████████                              | 1/3 [00:03<00:06,  3.26s/it]Process Process-4:
Traceback (most recent call last):
  File "/home/.conda/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/.conda/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/AlphaPose/alphapose/utils/writer.py", line 127, in update
    img = vis_frame(orig_img, result, add_bbox=(self.opt.pose_track | self.opt.tracking | self.opt.showbox))
  File "/home/AlphaPose/alphapose/utils/vis.py", line 186, in vis_frame_fast
    cv2.line(img, start_xy, end_xy, line_color[i], 2 * (kp_scores[start_p] + kp_scores[end_p]) + 1)
TypeError: Argument 'thickness' is required to be an integer
===================================================================================

Could you help me to see the error?
Thank you very much!

**Comment by Fang-Haoshu** [comment]
I see. Can you try modify the vis.py, line 186, in vis_frame_fast
cv2.line(img, start_xy, end_xy, line_color[i], 2 * (kp_scores[start_p] + kp_scores[end_p]) + 1)

to

cv2.line(img, start_xy, end_xy, line_color[i], 2 * int(kp_scores[start_p] + kp_scores[end_p]) + 1)

**Comment by christw16** [comment]
@Fang-Haoshu  thanks! I will try it now~

**Comment by christw16** [comment]
@Fang-Haoshu  it works~
Thanks a lot!

**Comment by xuchao1688** [comment]
This bug doesn't appear in the past because the type of kp_scores is `torch.Tensor` and there may be an inner type conversion from float to int when using `cv2` api. However, this is still a bug. We just fix this bug by explictly applying `int` type conversion to these ambiguous variables in [latest commit](https://github.com/MVIG-SJTU/AlphaPose/commit/e8023accab84254ca04e4d7576cd983f0e8efe7e).

**Comment by Fang-Haoshu** [comment]
cool!
