### ISSUE TITLE
Bounding Box Area and Score Computation Weights

### ISSUE THREAD

**Issue by RomeroBarata** [MVIG-SJTU/AlphaPose#63]
Hi,

Why in `AlphaPose/PoseFlow/utils.py` the area of the bounding boxes computed by the function `cal_bbox_iou` adds 1 to the measurements of the boxes?

And, in the `best_matching_hungarian` function, shouldn't lines 186 and 188 be swapped?

**Comment by YuliangXiu** [comment]
The 1 is used to handle "zero division" problem.

Yes, these two lines should be swapped.

**Comment by RomeroBarata** [comment]
Thank you for the clarifications!
