### ISSUE TITLE
AssertionError('im2col step must divide batchsize',)

### ISSUE THREAD

**Issue by chenrxi** [MVIG-SJTU/AlphaPose#632]
Have you ever met this error and i cannot find the method to fix it, thanks

**Comment by Fang-Haoshu** [comment]
Hi, we haven't met it before. It's a weird problem. Can you paste the whole information? And what is the PyTorch version you use?

**Comment by chenrxi** [comment]
![image](https://user-images.githubusercontent.com/60959000/87666060-8a747380-c79a-11ea-8071-af99f7f7e2ca.png)
it seems that it has a mistake in deform_conv.py.  I cannot understand that i have ran the demo successfully for most of the time but it suddenly occurs the bug.
![image](https://user-images.githubusercontent.com/60959000/87666408-28683e00-c79b-11ea-94d3-ad78dfd5efac.png)
i will check the demo and thank you for your help

**Comment by chenrxi** [comment]
i reduce the posebatch to 64 and it works

**Comment by Fang-Haoshu** [comment]
lol that's weird... anyway happy to hear that
