### ISSUE TITLE
在图像上展示骨骼

### ISSUE THREAD

**Issue by kankanzheli** [MVIG-SJTU/AlphaPose#633]
最近，我使用alphapose对行人进行检测。这个行人是背向摄像头的。所以他的双眼无法被检测到。生成的骨骼图像也没有标注出这个行人双眼的关键点位置。但是在生成的结果json文件中，任然展示了双眼的位置信息（只是置信度较低）。我的问题是，如何把全部的关键点在图像上标注出来呢？即使行人背向摄像头，也把结果文件中双眼的位置标注到图像上呢？
另外一个问题是生成的骨骼的线条太粗了，有什么办法可以让线条细一点吗？
（我使用的是alphapose0.2版本）

**Comment by kankanzheli** [comment]
额，除此之外，我想要在我的毕业论文中引用你们论文中的图像。请问这样做可以吗？

**Comment by Fang-Haoshu** [comment]
你好 可以的 只需要参考文献中注明引用就没问题

图像的话，可以修改https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/vis.py里面的vis frame函数 例如260行就是过滤confidence阈值的

**Comment by Fang-Haoshu** [comment]
0.2版本的话也是找一下vis.py相关的函数
