### ISSUE TITLE
使用demo里的图片报错，用我自带的图片就没事，不知道什么情况

### ISSUE THREAD

**Issue by Sibalaxi** [MVIG-SJTU/AlphaPose#635]
执行的语句是：
python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --image images/6.jpg --outdir output/ --save_img

报错：
Process Process-4:
Traceback (most recent call last):
  File "/home/zzy/anaconda3/envs/alphapose/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zzy/anaconda3/envs/alphapose/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zzy/PycharmProjects/AlphaPose-master/alphapose/utils/writer.py", line 127, in update
    img = vis_frame(orig_img, result, add_bbox=(self.opt.pose_track | self.opt.tracking | self.opt.showbox))
  File "/home/zzy/PycharmProjects/AlphaPose-master/alphapose/utils/vis.py", line 268, in vis_frame
    img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)
TypeError: Argument 'alpha' can not be treated as a double

**Comment by xuchao1688** [comment]
In File "/home/zzy/PycharmProjects/AlphaPose-master/alphapose/utils/vis.py", line 127,
how about modifying `img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)`
into `img = cv2.addWeighted(bg, float(transparency), img, float(1 - transparency), 0)`

**Comment by Sibalaxi** [comment]
> In File "/home/zzy/PycharmProjects/AlphaPose-master/alphapose/utils/vis.py", line 127,
> how about modifying `img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)`
> into `img = cv2.addWeighted(bg, float(transparency), img, float(1 - transparency), 0)`

**Comment by Sibalaxi** [comment]
> In File "/home/zzy/PycharmProjects/AlphaPose-master/alphapose/utils/vis.py", line 127,
> how about modifying `img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)`
> into `img = cv2.addWeighted(bg, float(transparency), img, float(1 - transparency), 0)`

**Comment by Sibalaxi** [comment]
> In File "/home/zzy/PycharmProjects/AlphaPose-master/alphapose/utils/vis.py", line 127,
> how about modifying `img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)`
> into `img = cv2.addWeighted(bg, float(transparency), img, float(1 - transparency), 0)`

I just tried adding --vis_fast to the end and the error disappeared,thanks for your reply!
