### ISSUE TITLE
How to get FPS of the training

### ISSUE THREAD

**Issue by christw16** [MVIG-SJTU/AlphaPose#636]
Here is what I type:

python ./multiperson_2d_keypoints_video.py --cfg pretrained_models/256x192_res152_lr1e-3_1x-duc.yaml --checkpoint pretrained_models/fast_421_res152_256x192.pth --video Catchimage/video/wing.mp4 --outdir output/video1/ --flip --vis_fast --gpus 0,1 --sp --save_video

Thank you!

**Comment by Fang-Haoshu** [comment]
Hi, do you mean the inference? I remember that the fps will appear on the shell

**Comment by Fang-Haoshu** [comment]
Can you find it on the right part of the progress bar?

**Comment by christw16** [comment]
ok, thank you for your answering~
