### ISSUE TITLE
How to evaluate the mAP

### ISSUE THREAD

**Issue by alice1222** [MVIG-SJTU/AlphaPose#637]
作者你好：
看过一些询问怎么计算mAP的问题,但对于如何操作还是有很大的疑问,请问可以说明一下操作步骤吗？谢谢你
妳们的工作真的很伟大

**Comment by xuchao1688** [comment]
We follow the standard mAP calculation provided by mscoco api. You can go to [official website](https://cocodataset.org/#keypoints-eval) for more details about this.
