### ISSUE TITLE
Device-agnostic code

### ISSUE THREAD

**Issue by bedilbek** [MVIG-SJTU/AlphaPose#639]
Hi. Thank you for the brilliant implementation.

But, regarding the code, haven't you thought of migrating whole code base into device-agnostic code, so that all the steps from building to running the project become smooth and seamless despite the fact that user use only cpu, gpu, or multi-gpu infrastructure. 

Any help on that or are there any intentions to do that in the future?

Best Regards

**Comment by Fang-Haoshu** [comment]
Hi, in fact it supports cpu, gpu, or multi-gpu by the flag --gpu -1, --gpu 0 or --gpu 1,2,3

**Comment by Fang-Haoshu** [comment]
Is that what you might need?:D

**Comment by bedilbek** [comment]
> Hi, in fact it supports cpu, gpu, or multi-gpu by the flag --gpu -1, --gpu 0 or --gpu 1,2,3

I mean the .cuda() methods that are used in most of the parts, or do those parts meant to be run only on gpu?

**Comment by Fang-Haoshu** [comment]
Nope, .cuda() is only used with a condition. You can look into the code of the master branch. Now the code is Device-agnostic.

**Comment by bedilbek** [comment]
Thanks for the quick reply, what about building the project for cpu devices?

**Comment by bedilbek** [comment]
![image](https://user-images.githubusercontent.com/23011104/88248233-d99a3700-ccb9-11ea-8fa1-dad9cd95c196.png)
Does this also implies i do not need cuda while installing the project?

**Comment by bedilbek** [comment]
@Fang-Haoshu can you also look at the above cuda requirements that are needed for extension modules while building the project?

**Comment by Fang-Haoshu** [comment]
Oh I see.  Yes, it seems we need to also include a cpu version for the setup. You can skip the cuda part for a workaround.

**Comment by bedilbek** [comment]
That's why I was proposing this issue to make full project device-agnostic with cpu build and gpu build. As far as I understood, I could successfully build the project with commenting out make_cuda_ext() calls. B

**Comment by bedilbek** [comment]
@Fang-Haoshu That's why I was proposing this issue to make the project full device-agnostic with cpu build and gpu build. As far as I understood, I could successfully build the project with commenting out `make_cuda_ext()` calls. But, anyway as this cuda extensions are written for layers **Resnet** and other models, I could not run `demo_inference.py` and I got error that there is no shared library `deform_conv_cuda`. 
![image](https://user-images.githubusercontent.com/23011104/88295842-60c9c800-cd17-11ea-8ee6-79dfeb8ea41b.png)

So, I believe skipping cuda part also won't help to build the project for cpu.
Maybe, to make project full device-agnostic some parts of `deform_conv_cuda`, `deform_pool_cuda` needs refinements for cpu builds.

So I am waiting for your response.

**Comment by NeelayS** [comment]
Hey @bedilbek , were you able to get AlphaPose running on CPU ?

**Comment by bedilbek** [comment]
> Hey @bedilbek , were you able to get AlphaPose running on CPU ?

Hey @NeelayS, according to this PR #604, there is a forked [repository](https://github.com/MVIG-SJTU/AlphaPose/issues/604) where you can run on CPU. I could successfully run it there.
