### ISSUE TITLE
A question about running poseflow tracker.py

### ISSUE THREAD

**Issue by kemangjaka** [MVIG-SJTU/AlphaPose#64]
Hi, Thanks for providing the code!
I tried to run the human pose tracking (poseflow), but I met a problem. 

After I run the ./run.sh to the posetrack_data, I got alpha-pose-result.json file.
However, the format of alpha-pose-result.json file is different from the alpha-pose-results-sample.json.
Therefore, I couldn't run the tracker.py to this json file. 
I got the error below. 

```
Traceback (most recent call last):
  File "tracker.py", line 60, in <module>
    for imgpath in tqdm(sorted(notrack.keys())):
AttributeError: 'list' object has no attribute 'keys'
```

Any advice?
Thanks!

**Comment by YuliangXiu** [comment]
You need to write some scripts to convert alpha-pose-result.json to alpha-pose-results-sample.json, because AlphaPose is designed for single frame image while PoseFlow is based on multi frames video. Thus the json format is a little different.

**Comment by my-hello-world** [comment]
@YuliangXiu 您好~感谢分享。
1.写脚本转换下形式是吗？是不是这个追踪只适合非常短的视频，因为我跑了个几十秒的视频都有一两千帧了。我看您的例子就几十帧，难道是针对几秒的视频吗？
2.您有直接能运行的demo吗？（您的数据）因为我想看下跑通情况，再进行学习；还是只能先用alphapose处理自己的视频后，再tracking啊。

**Comment by YuliangXiu** [comment]
1. There is no limitation on frame number, I only test my code in PoseTrack dataset and the video of this dataset only contains about tens of frames, but this code can be directly used for any videos
2. You will find some demo pictures and evaluation charts in my BMVC paper
3. Yes, you should firstly use AlphaPose to do pose estimation on every frame and then use PoseFlow to track them.

@my-hello-world

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization. @kemangjaka
