### ISSUE TITLE
How to get results in MPII keypoints with master branch

### ISSUE THREAD

**Issue by owandering** [MVIG-SJTU/AlphaPose#642]
Hi, I am running AlphaPose with master branch. How can I get results in MPII keypoints?

**Comment by Fang-Haoshu** [comment]
Hi！We will update new models soon (hopefully next week) which contains the MPII keypoints

**Comment by lan786** [comment]
@Fang-Haoshu When we will get updated model for MPII keypoints?

**Comment by firatbey** [comment]
@Fang-Haoshu Is there any progress on this? I am also waiting on this.

**Comment by Fang-Haoshu** [comment]
Hi! @lan786 @owandering @firatbey  I just add it to the model zoo. You can use the Halpe_26 keypoints version. It includes both MPII and COCO keypoints and foot keypoints, 26 points in total! You can see the demo in the readme.

**Comment by Fang-Haoshu** [comment]
The first 17 keypoints are in COCO format, then (head-top, neck, hip) like MPII dataset, then Left big toe, Right big toe, Left small toe, Right small toe, Left heel, Right heel
