### ISSUE TITLE
simple inference demo

### ISSUE THREAD

**Issue by AllenDun** [MVIG-SJTU/AlphaPose#643]
great repo! A simple and clean inference demo could be included in the repo? The file `demo_inference.py`  is great for input with a video file or an image dir. But  for just a single image or a numpy image from buffer, the pipeline is too complicated. A simple and clean inference demo with a single image helps to better understand the process and easily be used in other applications, such as action recogintion based on skeleton, inference as a service. Thanks.

**Comment by Fang-Haoshu** [comment]
Oh yes, good idea! Will work on that

**Comment by Fang-Haoshu** [comment]
Hi, you can refer to scripts/demo_api.py now.
