### ISSUE TITLE
windows教程写的好不详细 还有多写点中文行不 你是在国外吗 访问github很方面吗

### ISSUE THREAD

**Issue by dugudongfangshuo** [MVIG-SJTU/AlphaPose#644]

**Comment by Fang-Haoshu** [comment]
其实我感觉windows教程一步步来已经很详细了
当然也欢迎你做贡献，按你的想法为社区提供更好的教程：D

这个repo除了国人也有很多国外的研究者使用 所以全是英文文档，也欢迎你做一份中文的说明哈

**Comment by wwdok** [comment]
windows的一步步教程在哪里，就这个？
![Uploading image.png…]()
