### ISSUE TITLE
demo_inference.py will stuck when add '--save_video'.

### ISSUE THREAD

**Issue by Eooming** [MVIG-SJTU/AlphaPose#646]
Hello.
There are some problem when I run demo_inference.py. When I add '--save_video', it will loop Infinitely while rendering the picture.
When the commend is 'python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --video examples/demo/222.mp4 --outdir examples/res --gpus 1 --save_video'. 
The result will be 

'Loading YOLO model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
Network successfully loaded
  0%|                                                                              | 0/375 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found
Try to use other video encoders...
  2%|█                                                                     | 6/375 [00:02<05:45,  1.07it/s]Process Process-4:
  2%|█▍                                                                    | 8/375 [00:02<04:07,  1.48it/s]Traceback (most recent call last):
  File "/home/ftl/miniconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ftl/miniconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ftl/code/AlphaPose-master-video/alphapose/utils/writer.py", line 130, in update
    img = vis_frame(orig_img, result, add_bbox=(self.opt.pose_track | self.opt.tracking | self.opt.showbox))
  File "/home/ftl/code/AlphaPose-master-video/alphapose/utils/vis.py", line 268, in vis_frame
    img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)
TypeError: Argument 'alpha' can not be treated as a double
100%|████████████████████████████████████████████████████████████████████| 375/375 [00:19<00:00, 19.45it/s]
===========================> Finish Model Running.
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...
===========================> Rendering remaining 374 images in the queue...'

But when the commend is 'python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --video examples/demo/222.mp4 --outdir examples/res --gpus 1'. (The difference between them is '--save_video').
The result will be
'Loading YOLO model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
Network successfully loaded
100%|████████████████████████████████████████████████████████████████████| 375/375 [00:18<00:00, 19.80it/s]
===========================> Finish Model Running.
===========================> Rendering remaining 65 images in the queue...
===========================> Rendering remaining 47 images in the queue...
===========================> Rendering remaining 32 images in the queue...
===========================> Rendering remaining 12 images in the queue...
===========================> Rendering remaining 0 images in the queue...
Results have been written to json.'

The same problem will appear when add '--save_img'.

could any of you help me?

Regards.

**Comment by Fang-Haoshu** [comment]
In File "/home/ftl/code/AlphaPose-master-video/alphapose/utils/vis.py", line 268, in vis_frame
how about modifying img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)
into img = cv2.addWeighted(bg, float(transparency), img, float(1 - transparency), 0)

**Comment by Eooming** [comment]
Thank a lot.
Your suggestion is very helpful.
There is another problem when I run demo_inference.py.
When testing set is more than 8000 images, demo_inference.py will stuck, just like one of issues here.
18%|██████▊                                | 1499/8520 [04:20<17:25,  6.72it/s]

I tried to add '--qsize 128', but it doesn't seem to work. And I also disabled the '--save_img' flag.

Do you have any idea to solve this?

Regards.

**Comment by Fang-Haoshu** [comment]
I guess some threads were dead. Could you try add --sp flag to see what will happen?

**Comment by Eooming** [comment]
Thank a lot.
It can run normally when I add --sp flag.
