### ISSUE TITLE
关于添加新的关键点检测的方法

### ISSUE THREAD

**Issue by yuzhiw** [MVIG-SJTU/AlphaPose#650]
你好，请问我最近想做步态识别的应用，想使用alphapose 模型新加几个关键点检测，以达到检测的需求，该怎么做呢？希望能得到作者的指点和回复，谢谢。

**Comment by Fang-Haoshu** [comment]
您好 我们这周会更新一个新模型 有额外的关键点哈 你也可以自己训练一个模型

**Comment by Fang-Haoshu** [comment]
Hi! I just add it to the model zoo. You can use the Halpe_26 keypoints version. It includes both MPII and COCO keypoints and foot keypoints, 26 points in total! You can see the demo in the readme.

**Comment by yuzhiw** [comment]
thank&nbsp; you，i think it could help me a lot



---原始邮件---
发件人: "Fred Fang"<notifications@github.com&gt;
发送时间: 2020年8月15日(周六) 晚上9:18
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"yuzhiw"<1575195168@qq.com&gt;;
主题: Re: [MVIG-SJTU/AlphaPose] 关于添加新的关键点检测的方法 (#650)




 
Hi! I just add it to the model zoo. You can use the Halpe_26 keypoints version. It includes both MPII and COCO keypoints and foot keypoints, 26 points in total! You can see the demo in the readme.

**Comment by Fang-Haoshu** [comment]
The first 17 keypoints are in COCO format, then (head-top, neck, hip) like MPII dataset, then Left big toe, Right big toe, Left small toe, Right small toe, Left heel, Right heel
Enjoy!

**Comment by Fang-Haoshu** [comment]
Hi! You can checkout https://github.com/Fang-Haoshu/Halpe-FullBody

**Comment by yuzhiw** [comment]
我每次安装alphapose 在Windows系统上 基于pytorch1.1.0以上的版本的时候 Python setup build&nbsp; 就会报错 主要是说cl. exe与 pytorch 不兼容 请问有什么解决办法吗 如果我基于pytorch0.4.0，运行旧版本的模型，是否能运行最新的包括脚趾关键点的模型呢&nbsp; 请尽快回复&nbsp; 谢谢啦



---原始邮件---
发件人: "Fred Fang"<notifications@github.com&gt;
发送时间: 2020年8月16日(周日) 中午11:59
收件人: "MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"yuzhiw"<1575195168@qq.com&gt;;
主题: Re: [MVIG-SJTU/AlphaPose] 关于添加新的关键点检测的方法 (#650)




 
The first 17 keypoints are in COCO format, then (head-top, neck, hip) like MPII dataset, then Left big toe, Right big toe, Left small toe, Right small toe, Left heel, Right heel
 Enjoy!
