### ISSUE TITLE
three pics in demo folder,but only get two pics out

### ISSUE THREAD

**Issue by xuexianju** [MVIG-SJTU/AlphaPose#652]
nice project.
I'm running demo.py in pytorch branch , 

according to the doc, three pics in demo folder, after running this:
python3 E:\AlphaPose-pytorch\demo.py --indir examples/demo/ --outdir examples/results/ --save_img --format coco

I only got two pics in the result folder.

![image](https://user-images.githubusercontent.com/37840973/89912032-ae559880-dc24-11ea-90cf-9b941c76669e.png)

**Comment by xuexianju** [comment]
It's the multi-tread issue.

in dataloader.py ,

change:

    def running(self):
        # indicate that the thread is still running
        time.sleep(0.2)
        return not self.Q.empty()

to :

    def running(self):
        # indicate that the thread is still running
        time.sleep(2)
        return not self.Q.empty()

then work.

**Comment by Fang-Haoshu** [comment]
Oh i see. Thanks!
