### ISSUE TITLE
New Pretrained Models with COCO and MPII keypoints 

### ISSUE THREAD

**Issue by firatbey** [MVIG-SJTU/AlphaPose#655]
Hi, do you have new pretrained model that outputs both COCO (17 body parts) and MPII (16 body parts) keypoints ? So far only model that outputs 33 keypoints is the previous implementation with tensorflow.

**Comment by Fang-Haoshu** [comment]
Hi! I just add it to the model zoo. You can use the Halpe_26 keypoints version. It includes both MPII and COCO keypoints and foot keypoints, 26 points in total! You can see the demo in the readme.

**Comment by firatbey** [comment]
@Fang-Haoshu can you provide a description of the keypoints output for this model like this one: https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/output.md . I cannot seem to find any description on. Thanks for the really fast reply.

**Comment by Fang-Haoshu** [comment]
Hi, the first 17 keypoints are in COCO format, then (head-top, neck, hip) like MPII dataset, then Left big toe, Right big toe,  Left small toe, Right small toe, Left heel, Right heel

**Comment by Fang-Haoshu** [comment]
Updated in Halpe dataset:  https://github.com/Fang-Haoshu/Halpe-FullBody
