### ISSUE TITLE
作者您好，我想问一下AlphaPose可以针对手指部位的关节添加关键点吗

### ISSUE THREAD

**Issue by HHHcwb** [MVIG-SJTU/AlphaPose#656]

**Comment by Fang-Haoshu** [comment]
你好！是的，我们刚刚更新完，你可以在readme里看到demo，明天应该会更新数据集的github仓库，模型也在路上了哈

**Comment by Fang-Haoshu** [comment]
Hi! You can checkout  https://github.com/Fang-Haoshu/Halpe-FullBody
