### ISSUE TITLE
Pose_track error

### ISSUE THREAD

**Issue by sebo361** [MVIG-SJTU/AlphaPose#657]
Hi Team,
thank you for this wonderful new pose_track module which in most of the cases works really well. However i some video it has trouble to match the correct ID like in the video I attached (I know it's a really though video). Do you have any suggestion how to improve it?

![Alphapose_Pose_track](https://user-images.githubusercontent.com/29478970/90381052-22f16280-e07d-11ea-9310-3acfe4278ac8.gif)

**Comment by Fang-Haoshu** [comment]
@tang-hy Are there any method to improve this?

**Comment by tang-hy** [comment]
Hello, can you send this video to us? Email:thutanghy@gmail.com

**Comment by sebo361** [comment]
Hi @tang-hy I just sent you the video to your email. Thanks!

**Comment by tang-hy** [comment]
Hi @sebo361 I have replied to your email.

**Comment by sebo361** [comment]
Hi @tang-hy thank you for your email! I pulled the Alphapose repo again and didn't touch any arguments or options but I am still getting the same error with PoseTrack of mismatching the IDs. Here is my command:

`python -i scripts/demo_inference.py --save_video --video 033.mp4 --pose_track --cfg configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml --checkpoint pretrained_models/fast_421_res152_256x192.pth --detbatch 3`

 Can you please share your arguments/options for --pose_track which gives you an error free tracking with this video?

**Comment by tang-hy** [comment]
> Hi @tang-hy thank you for your email! I pulled the Alphapose repo again and didn't touch any arguments or options but I am still getting the same error with PoseTrack of mismatching the IDs. Here is my command:
> 
> `python -i scripts/demo_inference.py --save_video --video 033.mp4 --pose_track --cfg configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml --checkpoint pretrained_models/fast_421_res152_256x192.pth --detbatch 3`
> 
> and here is my `tracker_cfg.py`:
> 
> ```
> cfg.nid = 1000
> cfg.arch = "osnet_ain" # "osnet" or "res50-fc512"
> cfg.loadmodel = "trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"
> cfg.frame_rate =  30
> cfg.track_buffer = 240 
> cfg.conf_thres = 0.5
> cfg.nms_thres = 0.4
> cfg.iou_thres = 0.5
> ```
> 
> Can you please share your arguments/options for --pose_track which gives you an error free tracking with this video?

How about changing the `cfg.arch` to “res50-fc512”?

**Comment by Fang-Haoshu** [comment]
@tang-hy maybe we need to upload the models?

**Comment by Fang-Haoshu** [comment]
Hi @sebo361 the res50_fc512 is at https://mega.nz/#!9PQTXIpL!iI5wgieTCn0Jm-pyg9RCu0RkH43pV3ntHhr1PeqSyT4

**Comment by sebo361** [comment]
Thank you so much @Fang-Haoshu

**Comment by sebo361** [comment]
Hi @tang-hy and @Fang-Haoshu,

also with the res50_fc512 tracking model I get the same error of mismatching the person's ID. Here are my tracker configs again and the output video:

```
cfg.nid = 1000
cfg.arch = "res50-fc512" # "osnet_ain" or "osnet" or "res50-fc512"
cfg.loadmodel = "trackers/weights/resnet50_fc512_msmt_xent.pth.tar" # trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"
cfg.frame_rate =  30
cfg.track_buffer = 240 
cfg.conf_thres = 0.8
cfg.nms_thres = 0.4
cfg.iou_thres = 0.5
```


![poseTrack-min](https://user-images.githubusercontent.com/29478970/91152086-d03c2a00-e6be-11ea-8310-11484302a206.gif)


@tang-hy do you have the same configs when having the error-free tracking result on that video? Might it be possible that different Yolo configs than the default ones have an impact on the pose_track result? If so, can you please share your Yolo configs too?

**Comment by tang-hy** [comment]
Hi @sebo361 you can reference [this](https://github.com/tang-hy/AlphaPose/commit/b07cd99b67eaef874c0e4f013ce461350b1c02b2) .

**Comment by sebo361** [comment]
Hi @tang-hy, yes this fixes the error - thank you so much for helping!

**Comment by 1190200311** [comment]
> 嗨，你可以参考[这个](https://github.com/tang-hy/AlphaPose/commit/b07cd99b67eaef874c0e4f013ce461350b1c02b2).

您好，链接已经失效，同样遇到id变化类似的问题，请问有解决方案吗
