### ISSUE TITLE
Can i train my own dataset on this AlphaPose? I want to build a dataset of small robot and try to track keypoints and pose of it, how can i train this network?

### ISSUE THREAD

**Issue by xkevincode** [MVIG-SJTU/AlphaPose#67]

**Comment by Fang-Haoshu** [comment]
Hi, yes, you can train it on your own dataset. Please refer to the train folder for detailes

**Comment by Yuy1024** [comment]
@xkevincode 
Hi,
1.Have you successfully train on your own dataset?
Thank you!

**Comment by 1998anwesha** [comment]
Hi,
@Fang-Haoshu, is the train folder not present anymore? I would like to train alphapose on my own data, can you kindly let me know how I should do it because I did not find any train folder here.
