### ISSUE TITLE
yolo detection

### ISSUE THREAD

**Issue by athulvingt** [MVIG-SJTU/AlphaPose#670]
Input: imgs(torch.FloatTensor,(b,3,h,w)): pre-processed mini-batch image input
               orig_dim_list(torch.FloatTensor, (b,(w,h,w,h))): original mini-batch image size
        Output: dets(torch.cuda.FloatTensor,(n,(batch_idx,x1,y1,x2,y2,c,s,idx of cls))): human detection results

could u please explain the output parameters, and i noticed value of 'n' changes in different iteration, Is it the number of objects detected in frame? I tried with yolov3-tiny and yolov3-spp, the program crashed as the value of n increased

**Comment by Fang-Haoshu** [comment]
hi, yes, the n is the number of human

**Comment by athulvingt** [comment]
for an image with 2-4 people , value of n was 1-10 (when used yolov3-tiny it even reached 26)

**Comment by Fang-Haoshu** [comment]
tune the conf value in detector/yolo_cfg.py

**Comment by athulvingt** [comment]
I feel nms is not working properly. I am not an expert in this field, I am sorry, If i were wrong.

**Comment by athulvingt** [comment]
what is c and s in this (n,(batch_idx,x1,y1,x2,y2,c,s,idx of cls))) , and is (x1,x1,y1,x2,y2) the dimension of the bounding box in real image or in the  output of yolo detector

**Comment by Fang-Haoshu** [comment]
hi, it can be found in yolo's repo

**Comment by samylee** [comment]
hello guys, go and find c++ library: https://github.com/samylee/SamyleePoseApi-OpenLibrary

**Comment by Klawens** [comment]
what is c and s
