### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by PengZH99** [MVIG-SJTU/AlphaPose#672]
Did anyone encounter this mistake when they retrained the models?

File "scripts/train.py", line 151, in validate_gt
    assert pred.ndim == 4
AttributeError: 'Tensor' object has no attribute 'ndim'

**Comment by Fang-Haoshu** [comment]
sorry, it should be dim(), ndim is only supported for pytorch>=1.2
I just fix the issue
