### ISSUE TITLE
Halpe_26 models gives only 17 keypoints

### ISSUE THREAD

**Issue by Sumith1896** [MVIG-SJTU/AlphaPose#674]
I'm using the latest Halpe_26 model listed in Model zoo using demo_inference.py with the following sample commnad:

```
python sumith/AlphaPose/scripts/demo_inference.py \
        --cfg sumith/AlphaPose/pretrained_models/256x192_res50_lr1e-3_1x.yaml \
        --checkpoint sumith/AlphaPose/pretrained_models/halpe26_fast_res50_256x192.pth \
        --indir {frames_path} \
        --outdir {pose_path} \
        --flip
```

it only gives me 17 keypoints in the output json

**Comment by Fang-Haoshu** [comment]
Hi, I re-upload the model again. Can you re-download the model and try again?

**Comment by Sumith1896** [comment]
It's working great, thank you @Fang-Haoshu
