### ISSUE TITLE
Pipeline of finetuning a pretrained model

### ISSUE THREAD

**Issue by sebo361** [MVIG-SJTU/AlphaPose#675]
Hi Team,

what is the procedure when finetuning a pretrained model like the COCO ResNet152 you provide on an own dataset? Should I just add the path of the pretrained model to the [config file](https://github.com/MVIG-SJTU/AlphaPose/blob/master/configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml) in `PRETRAINED: ''`? How about using the `TRY_LOAD: ''` option?

I assume my own dataset i want to finetune on needs to be in the same format (Json + image structure) like COCO dataset, right?

**Comment by Fang-Haoshu** [comment]
Hi，if the output is the same as the original model(e.g. same 17 points), then you can use PRETRAINED, if the output is different, then use TRY_LOAD
You can modify the custom.py in the dataset/ folder to adapt to your dataset.

**Comment by sebo361** [comment]
Amazing, thanks @Fang-Haoshu!
