### ISSUE TITLE
help！stuck when inference

### ISSUE THREAD

**Issue by ltm920716** [MVIG-SJTU/AlphaPose#677]
hello，
I installed alphapose successfully, but there is a problem in demo_inference.
![image](https://user-images.githubusercontent.com/12007227/91680310-64096c80-eb7d-11ea-882e-8205e8516b01.png)
it stuck.
![image](https://user-images.githubusercontent.com/12007227/91680378-9915bf00-eb7d-11ea-959c-2004b40343da.png)
if add --sp，there is a segment fault
![image](https://user-images.githubusercontent.com/12007227/91680410-bb0f4180-eb7d-11ea-9eff-9d5a7869cdb1.png)
my environment is cuda10，centos7，torch1.2.0，1080Ti，please help！

**Comment by Fang-Haoshu** [comment]
Hi, it the yolo weights placed at the proper place?

**Comment by ltm920716** [comment]
> Hi, it the yolo weights placed at the proper place?

yeah，the path is 'AlphaPose/detector/yolo/data/yolov3-spp.weights'

**Comment by Fang-Haoshu** [comment]
it is really weird. do you solve it later?

**Comment by ltm920716** [comment]
hello @Fang-Haoshu,
it is the environment issue，I solved it by adopt docker image bellow：
pytorch/pytorch:1.4-cuda10.1-cudnn7-devel

**Comment by fabiozappo** [comment]
Hi @ltm920716 could you upload or link your Dockerfile?

**Comment by ltm920716** [comment]
Hello @fabiozappo，my steps below，you can have a try：

docker run -it --name=alphapose --gpus=all --shm-size=4G  pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
cd /home
git clone --depth=1 https://hub.fastgit.org/MVIG-SJTU/AlphaPose.git
cd AlphaPose/
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
apt update
apt-get install libyaml-dev
apt install libgl1-mesa-glx
apt-get install libglib2.0-0
python -m pip install cython
pip install natsort easydict matplotlib munkres opencv-python pycocotools scipy==1.1.0 tensorboardx terminaltables timm==0.1.20 visdom
python setup.py build develop
# python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --save_img

**Comment by PEACEandSAFE** [comment]
Hi. How did you solve it? Did you just update pytorch to 1.4 and reinstall?

**Comment by ltm920716** [comment]
hello @PEACEandSAFE ,
 I use this docker env: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel is ok
