### ISSUE TITLE
cannot import name 'deform_conv_cuda', which does not exist in that relative path

### ISSUE THREAD

**Issue by abc123yuanrui** [MVIG-SJTU/AlphaPose#678]
![image](https://user-images.githubusercontent.com/37522312/91721497-37d10880-ebdc-11ea-83c9-fca1e92f6f48.png)

**Comment by Fang-Haoshu** [comment]
Hi, is the setup.py properly installed?

**Comment by abc123yuanrui** [comment]
> Hi, is the setup.py properly installed?

Hello, Fang. Thank you for your instance response. I've run setup.py build. Is there other command I need to do with this setup?

**Comment by Fang-Haoshu** [comment]
happy to hear that
