### ISSUE TITLE
A bug in reid！

### ISSUE THREAD

**Issue by ltm920716** [MVIG-SJTU/AlphaPose#679]
hello，the bug bellow：
![image](https://user-images.githubusercontent.com/12007227/91789752-d9d70c00-ec41-11ea-8704-561ff4ad4fc1.png)
here，human[idx] is a list like [[1.0],[6.0]]

**Comment by Fang-Haoshu** [comment]
Hi, yes it is a known issue. Hmm, we are expecting the tracker to give only one box for each person. You can add a [0] index after the .tolist() at this line: https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/pPose_nms.py#L300
