### ISSUE TITLE
Facing a Problem When Training the Model

### ISSUE THREAD

**Issue by Alan-Woo** [MVIG-SJTU/AlphaPose#68]
Hi! I have installed AlphaPose and run run.sh successfully. The output's performance is very good. However, I met a weird problem when I tried to finetune the model following your training guide in AlphaPose/train/README.md.
Following is the error:

> aw@aw-TM:~/wgy/ap/train/src$ th main.lua -expID finetune
> Saving everything to: /home/aw/wgy/ap/train/exp/coco/finetune	
> Input is a vector of length: 3	
> Output is a table	
> 	 Entry 1 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 2 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 3 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 4 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 5 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 6 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 7 is a tensor with dimensions: 33 x 80 x 64	
> 	 Entry 8 is a tensor with dimensions: 33 x 80 x 64	
> ==> Creating model from file: models/hg-prm.lua	
> ==> Converting module to nn.DataParallelTable	
> ==> Converting model to CUDA	
> ==> Starting epoch: 1/20	
> /home/aw/wgy/torch/install/bin/luajit: ...e/aw/wgy/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 6 callback] /home/aw/wgy/torch/install/share/lua/5.1/image/init.lua:370: /home/aw/wgy/ap/train/data/coco/images/COCO_train2014_000000333152.jpg         !: No such file or directory
> stack traceback:
> 	[C]: in function 'error'
> 	/home/aw/wgy/torch/install/share/lua/5.1/image/init.lua:370: in function 'loadImage'
> 	/home/aw/wgy/ap/train/src/util/pose.lua:57: in function 'generateSample'
> 	/home/aw/wgy/ap/train/src/util/pose.lua:286: in function 'loadData'
> 	/home/aw/wgy/ap/train/src/util/dataloader.lua:79: in function </home/aw/wgy/ap/train/src/util/dataloader.lua:76>
> 	[C]: in function 'xpcall'
> 	...e/aw/wgy/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
> 	/home/aw/wgy/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/aw/wgy/torch/install/share/lua/5.1/threads/queue.lua:41>
> 	[C]: in function 'pcall'
> 	/home/aw/wgy/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
> 	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk
> stack traceback:
> 	[C]: in function 'error'
> 	...e/aw/wgy/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
> 	/home/aw/wgy/ap/train/src/util/dataloader.lua:92: in function 'dataloader'
> 	/home/aw/wgy/ap/train/src/train.lua:49: in function 'step'
> 	/home/aw/wgy/ap/train/src/train.lua:164: in function 'train'
> 	main.lua:19: in main chunk
> 	[C]: in function 'dofile'
> 	.../wgy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50

Actually, the image "COCO_train2014_000000333152.jpg" indeed exists in the path "/home/aw/wgy/ap/train/data/coco/images/COCO_train2014_000000333152.jpg". The problem is the filename becomes "COCO_train2014_000000333152.jpg         !" when loading the image. I don't know why there is messy code after the image's name. And the messy code appears randomly, not for all the filenames.
Could you give me some suggestion? Thanks!

**Comment by Fang-Haoshu** [comment]
Hi, can you try replacing https://github.com/MVIG-SJTU/AlphaPose/blob/master/train/src/util/dataset/coco.lua#L68
with 
return paths.concat(opt.dataDir,'coco','images',ffi.string(self.annot.imgname_coco[idx]:char():data()):sub(1,16))

**Comment by Alan-Woo** [comment]
@Fang-Haoshu 
Replacing the line in "coco.lua" with 
`return paths.concat(opt.dataDir,'coco','images',ffi.string(self.annot.imgname_coco[idx]:char():data()):sub(1,31))` solved this problem!
Thank you very much!

**Comment by Fang-Haoshu** [comment]
cool
