### ISSUE TITLE
How can i change color of Skeleton? (use demo_inference.py)

### ISSUE THREAD

**Issue by Aqua5** [MVIG-SJTU/AlphaPose#680]
i use AlphaPoseV0.3.0

I want to draw only one line in white and the rest in blue.
then which code should I fix??
Where's the code that draws Skeleton?

**Comment by sebo361** [comment]
Hi @Aqua5, for changing the color please check [these lines of vis.py](https://github.com/MVIG-SJTU/AlphaPose/blob/038435e060a4e1194d9a6e8fef51b3730c5a21f0/alphapose/utils/vis.py#L200-L206)

**Comment by Fang-Haoshu** [comment]
Yes. Thanks @sebo361
