### ISSUE TITLE
The new target of training

### ISSUE THREAD

**Issue by PengZH99** [MVIG-SJTU/AlphaPose#681]
If I want to train the targets that are not in coco datasets,do i have to train the yolo model first?

**Comment by Fang-Haoshu** [comment]
Hi, for yolo model you need to refer to the yolo repo first. We use the yolov3 pytorch version: https://github.com/MVIG-SJTU/AlphaPose/tree/master/detector/yolo#a-pytorch-implementation-of-a-yolo-v3-object-detector
