### ISSUE TITLE
How to use online PoseFlow in video or webcamera?

### ISSUE THREAD

**Issue by chaisheng123** [MVIG-SJTU/AlphaPose#683]
Hello, I'm very appreciate with your project AlphaPose!
And after reading the tracker-general.py, I think it is offline demo, how to modify it to online demo?
 Thanks.

**Comment by tang-hy** [comment]
Hi, @chaisheng123 you can use our online tracking method with `--pose_track`.

**Comment by chaisheng123** [comment]
> Hi, @chaisheng123 you can use our online tracking method with `--pose_track`.

Thanks,  I have a pose estimate model and want to embed tracking system, now after reading the demo_inference.py and tracker_api.py, I don't know how to embed your code into my projects. Also, the tracking method is base to model, I want to use a simple method. Any advice, thanks.

**Comment by Fang-Haoshu** [comment]
a simpler method is to use --detector tracker for realtime demo

**Comment by chaisheng123** [comment]
> a simpler method is to use --detector tracker for realtime demo

Hello, thanks you for your reply, when I run python ./scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoints pretrained_models/fast_res50_256x192.pth --vedio ./examples/demo/xxx.mp4 --outdir examples/res --detector tracker,  I encountered an error 'FileNotFoundError: [Errno 2] No such file or directory: 'detector/tracker/data/jde.1088x608.uncertainty.pt'', how to solve it ?

**Comment by Fang-Haoshu** [comment]
hi, you need to download the model weights. You can find instructions in the readme of trackers/ and detector/tracker

**Comment by chaisheng123** [comment]
> hi, you need to download the model weights. You can find instructions in the readme of trackers/ and detector/tracker
Thanks, I have already download this model.
