### ISSUE TITLE
CPU inference

### ISSUE THREAD

**Issue by NeelayS** [MVIG-SJTU/AlphaPose#684]
I was going through the issues pertaining to using AlphaPose for inference on CPU. However, those discussions seem to be from before the latest August version release. From the `TODO` in `README`, it looks like AlphaPose now supports inference on CPU as well. Could you guide me on how that can be done ?
Thanks!

**Comment by Fang-Haoshu** [comment]
hi you can run by use flag --gpu -1

**Comment by NeelayS** [comment]
No changes to be done before the build ?

**Comment by Fang-Haoshu** [comment]
yep, you can directly install it following the readme :D 
But if your PC does not have a GPU and nvcc, you need to delete the cuda_extend things in the setup.py

**Comment by NeelayS** [comment]
Could you tell me exactly what all I'd need to remove from setup.py for a CPU only build ?

**Comment by NeelayS** [comment]
I get the following error when I try to run it with a --gpu -1 flag 
`ImportError: cannot import name 'deform_conv_cuda'
`

**Comment by athulvingt** [comment]
```
        make_cuda_ext(
            name='nms_cpu',
            module='detector.nms',
            sources=['src/nms_cpu.cpp']),
        make_cuda_ext(
            name='nms_cuda',
            module='detector.nms',
            sources=['src/nms_cuda.cpp', 'src/nms_kernel.cu']),
        make_cuda_ext(
            name='roi_align_cuda',
            module='alphapose.utils.roi_align',
            sources=['src/roi_align_cuda.cpp', 'src/roi_align_kernel.cu']),
        make_cuda_ext(
            name='deform_conv_cuda',
            module='alphapose.models.layers.dcn',
            sources=[
                'src/deform_conv_cuda.cpp',
                'src/deform_conv_cuda_kernel.cu'
            ]),
        make_cuda_ext(
            name='deform_pool_cuda',
            module='alphapose.models.layers.dcn',
            sources=[
                'src/deform_pool_cuda.cpp',
                'src/deform_pool_cuda_kernel.cu'
            ]),

```


I removed these from setup.py , but i get the error


 File "scripts/demo_inference.py", line 17, in <module>
    from alphapose.models import builder
  File "/content/AlphaPose/alphapose/models/__init__.py", line 1, in <module>
    from .fastpose import FastPose
  File "/content/AlphaPose/alphapose/models/fastpose.py", line 10, in <module>
    from .layers.SE_Resnet import SEResnet
  File "/content/AlphaPose/alphapose/models/layers/SE_Resnet.py", line 9, in <module>
    from .dcn import DeformConv, ModulatedDeformConv
  File "/content/AlphaPose/alphapose/models/layers/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/content/AlphaPose/alphapose/models/layers/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'

**Comment by Fang-Haoshu** [comment]
Hi, dcn module is not supported without CUDA. Thus you cannot use the -dcn model
