### ISSUE TITLE
Process stuck at loading pose model

### ISSUE THREAD

**Issue by NeelayS** [MVIG-SJTU/AlphaPose#686]
While running the demo inference script, the execution gets stuck at the loading pose model stage. What could be the possible reasons for this ?

![Screenshot from 2020-09-05 16-19-22](https://user-images.githubusercontent.com/44301912/92303637-7c6df280-ef94-11ea-8e1d-e6f0ab39a840.png)

**Comment by 1045245078** [comment]
How did you solve the problem? I met the same problem.

**Comment by yonggqiii** [comment]
Same here, the pre trained model doesn't get loaded.

**Comment by NeelayS** [comment]
A fresh installation did the trick for me

**Comment by wethemel** [comment]
I have the same problem, tried to reinstall multiple times. Any tips?

**Comment by Luizerko** [comment]
#1064 seems to do the job, but only for loading the model. It's still possible to have problems with the processing queue (kind of addressed in #989 ).
