### ISSUE TITLE
Inference do not work 

### ISSUE THREAD

**Issue by hulkwork** [MVIG-SJTU/AlphaPose#690]
Hello,
I have this error 

> "AlphaPose/alphapose/models/layers/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs"

When I run 

> python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/

I try to install by this tuto https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md with conda 

OS : ubuntu 18.04

**Comment by Fang-Haoshu** [comment]
Hi, it seems it's a cuda version problem. You can refer to this two links: https://github.com/open-mmlab/mmdetection/issues/48
https://github.com/facebookresearch/maskrcnn-benchmark/issues/223

**Comment by hulkwork** [comment]
I try with cuda 10.1 but it still not work. 
I will try with cuda 9 and If i found how to dolce it i could put a Dockerfile

**Comment by Fang-Haoshu** [comment]
Oh I see. Thanks for your effort. You can also try models without dcn, such as FastPose or FastPose-duc

**Comment by Stephenfang51** [comment]
> Oh I see. Thanks for your effort. You can also try models without dcn, such as FastPose or FastPose-duc

what model don't need DCN ? I tried 

Fast Pose | ResNet50 | YOLOv3 | 256x192 | 72.0 | 3.54 iter/s | model | cfg | log

it still needs dcn so the errors also occurs.
-- | -- | -- | -- | -- | -- | -- | -- | --
