### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by athulvingt** [MVIG-SJTU/AlphaPose#691]
The inference time for yolo  in alphapose video_demo(1 image per batch) is 10e-5, but on webcam it is 0.3, why is it so? Can someone please help me? I am running on CPU not GPU

**Comment by Fang-Haoshu** [comment]
video_demo？ Are you using the pytorch branch?
video_demo use a multi-process, while online_demo.py doesn't. I guess it is the difference

**Comment by athulvingt** [comment]
Yes pytorch branch and i am using --sp argument

**Comment by Fang-Haoshu** [comment]
--sp use multi-thread to preload the detection results. Besides, the webcam may be slower since the data cannot be prefetch. We prefetch the image and video frame data.
