### ISSUE TITLE
paper issued

### ISSUE THREAD

**Issue by raymond5891** [MVIG-SJTU/AlphaPose#693]
I found that there is a huge difference between alphapose and RMPE, do we have issued paper recently?

**Comment by Fang-Haoshu** [comment]
Hi, yes, alphapose is built upon RMPE and has evolved a lot. We are working on a new paper. But it is not finished yet.

**Comment by Fang-Haoshu** [comment]
Hi, the paper is public at http://arxiv.org/abs/2211.03375
Thanks for your interest! @raymond5891
