### ISSUE TITLE
How can I detect  full body with hands (no face)?

### ISSUE THREAD

**Issue by Witek-** [MVIG-SJTU/AlphaPose#694]
I successfully ran the standard 17 point model and Halpe 26 point model. 
I understand that Halpe_136 is not available yet at the moment, right? When can we expect it?
I imagine, detection all 136 points will slow down the inference. Will it be possible to detect full body and hands but without face?

**Comment by Fang-Haoshu** [comment]
Hi, in fact it won't slow down the speed. You may try the Halpe 136 model here: https://drive.google.com/file/d/1NyOuVLb5oIYP4LZmp9BSAQdbGjEk--gv/view?usp=sharing
cfg file: https://drive.google.com/file/d/1d9BSHnIXS3OVGNa4lc1de4qTsybY-N9_/view?usp=sharing

But note that it is not the final model. We are still training it so far and could expect a better accuracy afterwards. Stay tuned!

**Comment by Witek-** [comment]
Thank you. The cfg file you linked to above is incorrect (133 joints). I tried the one that is already in the repository and it worked, but quite poorly - most body joints were missed and hands, although all joints were detected, were very unstable. Is it due to wrong config file used?

**Comment by Fang-Haoshu** [comment]
I think you can modify the joint number to 136. The exist cfg file in the repo is not suitable for this model.

**Comment by Fang-Haoshu** [comment]
Oh, an important thing is that the score may be small for visualization. You can multiple the score for 2 times.
