### ISSUE TITLE
CPU 速度

### ISSUE THREAD

**Issue by mstc-xqp** [MVIG-SJTU/AlphaPose#696]
你好！我用CPU训练是一张图片7秒，这个速度正常吗

请问如果 直接用深度图的数据集 训练模型  不改变网络
 
这样效果我看有人达到90% 应该不行吧?

**Comment by Fang-Haoshu** [comment]
你好 这个速度正常的
深度图这个不太清楚 有可能可以

**Comment by mstc-xqp** [comment]
那是在嵌入式基本不能跑了把？
