### ISSUE TITLE
install error with nvcc 

### ISSUE THREAD

**Issue by cswwp** [MVIG-SJTU/AlphaPose#698]
Hi @Fang-Haoshu  I just build install followed install.md, but it show an error
running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.6/alphapose
running build_ext
building 'detector.nms.nms_cuda' extension
gcc -pthread -B /home/wangwenpeng/anaconda3/envs/alphapose/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/TH -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/wangwenpeng/anaconda3/envs/alphapose/include/python3.6m -c detector/nms/src/nms_cuda.cpp -o build/temp.linux-x86_64-3.6/detector/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda/bin/nvcc -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/TH -I/home/wangwenpeng/anaconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/wangwenpeng/anaconda3/envs/alphapose/include/python3.6m -c detector/nms/src/nms_kernel.cu -o build/temp.linux-x86_64-3.6/detector/nms/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
unable to execute ':/usr/local/cuda/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda/bin/nvcc' failed with exit status 1

and this is my nvcc --version info

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by cswwp** [comment]
Solved by vi my .bashrc with correct cuda_home

**Comment by Markshilong** [comment]
> Solved by vi my .bashrc with correct cuda_home

Could you please show more details?
