### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by xwr96** [MVIG-SJTU/AlphaPose#699]
hi! I would like to ask that the key point coordinates extracted in video are in alphapose-results.json? If not, how to get the coordinates of these key points? thanks

**Comment by Fang-Haoshu** [comment]
yes, in alphapose-results.json

**Comment by xwr96** [comment]
@Fang-Haoshu sorry to interrupt you again. 
Where is the folder or file that the key coordinates are generated? because i want to see how it work?

**Comment by Fang-Haoshu** [comment]
Hi, json file should be in the res/ folder.
And if you run with flag --save_img, it will be saved into res/vis/

**Comment by xwr96** [comment]
> Hi, json file should be in the res/ folder.
> And if you run with flag --save_img, images will be saved into res/vis/

I think you misunderstand me. I don't mean where the results are stored, but where is the code for extracting coordinates

**Comment by Fang-Haoshu** [comment]
you can checkout the alphapose/writer.py

**Comment by xwr96** [comment]
> you can checkout the alphapose/utils/writer.py

thanks a lot
