### ISSUE TITLE
How to run CrowdPose?

### ISSUE THREAD

**Issue by tjumiao** [MVIG-SJTU/AlphaPose#705]
Hi, thanks for the great work!

I would like to run CrowdPose to see how it performs compared to Alphapose (Or Fastpose?). Although in the CrowdPose.md, it writes:

`
python3 demo.py --indir ${img_directory} --outdir examples/res --matching
`

However, even in the pytorch branch, I don't find any line of code that uses the argument args.matching in demo.py. Is the crowdpose really adopted if I run the command above? Or is it I understand the code wrongly?

In addition, could you explain what is the difference between AlphaPose and FastPose?

Thank you.

**Comment by Fang-Haoshu** [comment]
Hi，yes,  in the pytorch branch, the --matching flag would handle it.
The FastPose is our developed model architecture under AlphaPose project.
