### ISSUE TITLE
Fix 'box' --> 'bbox' key in write_json

### ISSUE THREAD

**Issue by Sumith1896** [MVIG-SJTU/AlphaPose#707]
I think the right key check [here](https://github.com/MVIG-SJTU/AlphaPose/blob/0e6315dd69055ff6d8a7a4a731d71f13ff212dd9/alphapose/utils/pPose_nms.py#L498)  should be `bbox` instead of `box`

**Comment by Fang-Haoshu** [comment]
Oh, thanks for the reminder! It is indeed a bug. The key should be ``box``. I just update the code: https://github.com/MVIG-SJTU/AlphaPose/commit/ad03490a4b095de868c13c3c0db834f93ec3eccb

**Comment by Sumith1896** [comment]
Thanks @Fang-Haoshu
