### ISSUE TITLE
Demo inference freezes when trying to load pose model

### ISSUE THREAD

**Issue by yonggqiii** [MVIG-SJTU/AlphaPose#708]
Hi,

Whenever I attempt to run the demo inference script, the program freezes when attempting to load the pose model.

Screenshot is as shown:
![image](https://user-images.githubusercontent.com/46869871/95247303-48624780-0848-11eb-96c0-8e54752fbc97.png)

# Steps to reproduce
1) Run conda installation and setup without CUDA support. It involves: removing make_cuda_ext parts in get_ext_modules in setup.py, removing all `from .dcn import DCN` lines in alphapose/models/layers/*.py, removing `from . import roi_align_cuda` from alphapose/utils/roi_align/roi_align.py, and removing `from . import nms_cpu, nms_cuda` from detector/nms/nms_wrapper.py
2) Run `python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --gpus -1 --debug`

Rebooting / re-installing did not fix the problem.

# Environment
I am running Arch Linux with AMD GPU, hence no CUDA installed.

Not really sure how to make this work, appreciate it, thanks!

EDIT: I installed using the conda instructions

**Comment by Fang-Haoshu** [comment]
Hi， I am not sure what happened😂 Can you try add --sp flag to disable the multi-processing?

**Comment by imozi1999** [comment]
Hi @Fang-Haoshu im having the same problem, can u show me how to fix this. 
Thanks in advance

**Comment by imozi1999** [comment]
> Hi， I am not sure what happenedjoy Can you try add --sp flag to disable the multi-processing?

Hi, sorry for the noob question but how do i add --sp flag

**Comment by wethemel** [comment]
I too have this problem. Using a RTX3090, i have CUDA installed, but it stops at "Loading pose model..." Tried to reinstall Alphapose several times, reinstalled CUDA, conda and even ubuntu. 
Running Ubuntu 20.04

**Comment by Fang-Haoshu** [comment]
@wethemel The RTX 3090 requires pytorch 1.7+, which is too new for this code. You may need to merge a pull request that add supports for pytorch>1.5

**Comment by adel6666** [comment]
Hello @wethemel, I have the same problem as you, have you found a solution?

**Comment by wethemel** [comment]
Yes, it is @Fang-Haoshu says, RTX3090 requires pytorch 1.7+, and AlphaPose only supports 1.5<. You cant use the RTX3090 (i guess none of the RTX30xx) until the code is updated. I refer to Fangs statement that "You may need to merge a pull request that add supports for pytorch>1.5"
