### ISSUE TITLE
ModuleNoteFoundError:No module named 'torchsample'

### ISSUE THREAD

**Issue by huangzhenjie** [MVIG-SJTU/AlphaPose#71]
When I follow the steps to run the AlphaPose(PyTorch), it appear this bug.So, How should I do?Please help me,thanks!!!!!

**Comment by Jeff-sjtu** [comment]
Hi, you can install the dependences as followed
``` shell
pip install -e git+https://github.com/ncullen93/torchsample.git#egg=torchsample
pip install visdom
pip install nibabel
pip install h5py  # this will be removed in the formal version
```

**Comment by huangzhenjie** [comment]
thanks,I can run it.

**Comment by mabdullahrafique** [comment]
You also need to install pandas, 
pip install pandas

**Comment by shekhar-amit** [comment]
> Hi, you can install the dependencies as followed
> 
> ```shell
> pip install -e git+https://github.com/ncullen93/torchsample.git#egg=torchsample
> pip install visdom
> pip install nibabel
> pip install h5py  # this will be removed in the formal version
> ```

I followed the steps, even installed pandas, yet the error persists. Can anyone point out what other problem could it be?
