### ISSUE TITLE
Question about CrowdPose code in matching.py

### ISSUE THREAD

**Issue by WinstonDeng** [MVIG-SJTU/AlphaPose#710]
Hi,
I'm reading your code in matching.py, yet there is a question:
Which line is paired with this 'else' and why do you write it like this?  
[Details in here](https://github.com/MVIG-SJTU/AlphaPose/blob/ded84d450faf56227680f0527ff7e24ab7268754/matching.py#L169)
By the way, I can run `--matching` without any error.

**Comment by Fang-Haoshu** [comment]
Hi, crowdpose is not included in master branch yet, only on pytorch branch, thus this function is not used. Jeff is recently too busy for integration😂
