### ISSUE TITLE
--sp result in "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by imozi1999** [MVIG-SJTU/AlphaPose#717]
Hi, thank you for your great work.

while running demo i got the freeze screen like https://github.com/MVIG-SJTU/AlphaPose/issues/708

and i try adding the flag --sp like this:

python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --sp --indir examples/demo/

Result is like this:
Illegal instruction (core dumped)
![Screenshot from 2020-10-27 17-08-42](https://user-images.githubusercontent.com/55843525/97290627-62a5a900-187b-11eb-807e-d69777f8646b.png)

Sorry for my english and please help

im using ubuntu 18.04, Cuda 9.1 with a RTX card

**Comment by Fang-Haoshu** [comment]
Hi, can you check if the memory usage is too much. Try to lower the memory usage by --qsize 100 or --qsize 10
qsize means the buffer size, which is 1024 by default

**Comment by imozi1999** [comment]
Hello, thank you for your answer, i will try it and comment the result

**Comment by imozi1999** [comment]
Hello again, when i try to re-create the environment, my OS kinda broke down but somehow it fixed itself. Now everything running fine. I'm so confused
![Screenshot from 2020-11-02 11-52-31](https://user-images.githubusercontent.com/55843525/97831439-a2004980-1d02-11eb-9cda-9a213db134b7.png)


Again, thank you for your great work

**Comment by Fang-Haoshu** [comment]
LOL, so confused too 😂
Anyway, happy to see it works

**Comment by BoyackJ** [comment]
This exact thing has happened to me, but I have been unable to fix it. Do you know what you did exactly?
I have tried lowering my qsize to 10 and still receive the Illegal instruction (core dumped) when running with --sp flag on.

**Comment by imozi1999** [comment]
Hi  @BoyackJ, im not sure what i did to fix the problem. Can u double check if your CUDA is installed probably?
