### ISSUE TITLE
Help! ModuleNotFoundError: No module named 'cython_bbox'

### ISSUE THREAD

**Issue by chenjianqu** [MVIG-SJTU/AlphaPose#718]
When I run the demo:
`python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ `
There was a report error:
```
Traceback (most recent call last):  
  File "scripts/demo_inference.py", line 14, in <module>  
    from trackers.tracker_api import Tracker
  File "/home/alex/github/AlphaPose/trackers/tracker_api.py", line 24, in <module>
    from tracking.matching import *
  File "/home/alex/github/AlphaPose/trackers/tracking/matching.py", line 7, in <module>
    from cython_bbox import bbox_overlaps as bbox_ious
ModuleNotFoundError: No module named 'cython_bbox'
```
Can anyone tell me how to fix it? Think you!

**supplement**: When install Alphapose,run `python setup.py build develop`, it report some errors:
```
Installed /home/alex/github/AlphaPose
Processing dependencies for alphapose==0.3.0+cbc364f
Searching for easydict
Reading https://pypi.tuna.tsinghua.edu.cn/simple/easydict/
Download error on https://pypi.tuna.tsinghua.edu.cn/simple/easydict/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
Couldn't find index page for 'easydict' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.tuna.tsinghua.edu.cn/simple/
Download error on https://pypi.tuna.tsinghua.edu.cn/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
No local packages or working download links found for easydict
error: Could not find suitable distribution for Requirement.parse('easydict')
```

**Comment by zgsxwsdxg** [comment]
> ModuleNotFoundError: No module named 'cython_bbox'
这个问题解决了么？亲。
我也遇到了这个问题，你是怎么解决的？

**Comment by chenjianqu** [comment]
> > ModuleNotFoundError: No module named 'cython_bbox'
> > 这个问题解决了么？亲。
> > 我也遇到了这个问题，你是怎么解决的？

就是有些依赖（不太记得是什么依赖了 好像是cpython）用conda装不上，后来使用Pip安装架就好了。

**Comment by volkov-maxim** [comment]
Hi! I had a similar error, but with opencv-python, because opencv-contrib-python already was installed.
Script setup.py interrupted when any error is raised and consequently cython_bbox and some other libraries not installed.
After uninstalling opencv-contrib-python I have installed opencv-python and run setup.py one more time. After that setup.py executed without any errors. Double-check execution log.
