### ISSUE TITLE
why is  LIFOqueue used in dataloader_webcam.py (pytorch branch)?

### ISSUE THREAD

**Issue by athulvingt** [MVIG-SJTU/AlphaPose#720]
we need to process the first frame in the queue, but LIFO queue take the last frame in the queue, right? I am no expert in data structure, could you pleases explain why LIFOqueue is used in dataloader_webcam.py.

**Comment by Fang-Haoshu** [comment]
Hi, we need to process the latest frame in the queue, thus we use LIFO
Latest means that the image is always the newest.

**Comment by athulvingt** [comment]
so when running on webcam ( real time) do we skip the earlier frames and process only the latest frames?
