### ISSUE TITLE
Generating JSON in sequence of file name (based on names or  inverse of last modified time stamp)

### ISSUE THREAD

**Issue by SutirthaChakraborty** [MVIG-SJTU/AlphaPose#721]
I have my folder with images with file names sequentially.  But when I am reading the json, they are not in sequence.   How can I sort them in order ? like 1.jpg,2.jpg..... so on..
![image](https://user-images.githubusercontent.com/47362033/97782784-68f19900-1b8b-11eb-82bb-288b7638a94c.png)

The output I get on reading the json file. 
![image](https://user-images.githubusercontent.com/47362033/97782810-9e968200-1b8b-11eb-8ce3-d09b642bcaa6.png)

**Comment by Fang-Haoshu** [comment]
Hi, the json result should be in order. Is it due to the pandas library?

**Comment by Fang-Haoshu** [comment]
Input img are sorted here:https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/demo_inference.py#L136

**Comment by SutirthaChakraborty** [comment]
What should be the ideal version of pandas ?

**Comment by Fang-Haoshu** [comment]
Not use pandas. Open the json with json.load(open(....json))
