### ISSUE TITLE
Weird result : one person but two estimated poses

### ISSUE THREAD

**Issue by wwdok** [MVIG-SJTU/AlphaPose#723]
Look at below output result:
Why will it happen and how to avoid ?
![image](https://user-images.githubusercontent.com/43233772/98082945-8f2d7680-1eb4-11eb-8c28-2452f7613cac.png)

**Comment by Fang-Haoshu** [comment]
Hi, you can use higher detection conf in detector/yolo_cfg.py, like 0.4
Then it will detect fewer people and eliminate redandunt boxes

**Comment by wwdok** [comment]
> Hi, you can use higher detection conf in detector/yolo_cfg.py, like 0.4
> Then it will detect fewer people and eliminate redandunt boxes

You mean these two pose were caused by two bbox ? but from the image, i can only see one bbox
