### ISSUE TITLE
It is difficult to embed this program into other programs

### ISSUE THREAD

**Issue by CrystalSixone** [MVIG-SJTU/AlphaPose#726]
hi! Thank you for your awesome work! However, i find it difficult to embed this program into other programs. If you can open an interface, whose input is an image, and the output is the detected pose information, it will be much more conducive to the secondary development of engineering :D

**Comment by Fang-Haoshu** [comment]
Oh I see. Perhaps you mean something like this file? https://github.com/MVIG-SJTU/AlphaPose/blob/570d467d03ea77ec37e6966fae399ea1bfb668cf/scripts/demo.py
We will merge this branch later. You may copy this file if needed

**Comment by CrystalSixone** [comment]
THX a lot! This is exactly what I want. But I also need to change the code to adapt to python 2.7.. If you can release more python version please let me know :+1:

**Comment by Fang-Haoshu** [comment]
Sure

**Comment by assafge** [comment]
@Fang-Haoshu, It is still hard to use it from another location besides the script's folder. the "installed" library in the interpreter includes only small subset of functionality, and this project cannot be integrated in another project. 
interfaces like _detector/api.py_ 'get_detector' function.
