### ISSUE TITLE
处理较大视频时进程总是被杀死？

### ISSUE THREAD

**Issue by ZHANGGUANGLONG327** [MVIG-SJTU/AlphaPose#727]
numpy==1.14.5
scipy==1.1.0
opencv_python==3.4.2.16
opencv_contrib_python==3.4.2.16
matplotlib==2.2.2
tqdm==4.23.4
Image==1.5.25
Pillow==5.3.0
munkres==1.0.12
显卡是gtx1660ti
能否单纯用cpu？

**Comment by ZHANGGUANGLONG327** [comment]
视频有什么限制么  比如多少分辨率， 或者mp4和avi那个更好 显存是6G  CUDA==10.1 torch ==1.4.0

**Comment by ZHANGGUANGLONG327** [comment]
nur@nur:~/桌面/AlphaPose$ python3 scripts/demo_inference.py --cfg /home/nur/桌面/AlphaPose/configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --video examples/demo/4.mp4 --outdir /home/nur/桌面/AlphaPose/examples/results --save_vide
Loading pose model from pretrained_models/halpe26_fast_res50_256x192.pth...
Loading YOLO model..
  0%|                                                  | 0/1334 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found
Try to use other video encoders...
 14%|█████▋                                  | 189/1334 [00:31<03:12,  5.94it/s]已杀死

**Comment by ZHANGGUANGLONG327** [comment]
Loading YOLO model..
Loading pose model from pretrained_models/halpe26_fast_res50_256x192.pth...
  0%|                                                  | 0/1449 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found
Try to use other video encoders...
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
  0%|▏                                         | 5/1449 [00:07<37:08,  1.54s/it]
或者就卡这不动了

**Comment by Fang-Haoshu** [comment]
试试-qsize 100

**Comment by ZHANGGUANGLONG327** [comment]
> 试试-qsize 100

非常感谢，已经可以运行了🙏🏼
