### ISSUE TITLE
SPPE的框架

### ISSUE THREAD

**Issue by HongChow** [MVIG-SJTU/AlphaPose#732]
非常感谢AlphaPose的工作和开源. 
现在我看master分支上的代码,SPPE的框架似乎也不是Stacked Hourglass,翻看了之前的Issues知道是用了其他新的框架.
想问两个问题:
(1) 这样的框架如果在前置摄像头数据上是否可以提高性能,或有没有比较好的数据集(特别是Upper Body)可以供finetune训练?
(2)如果希望用进一步指导做human segmentation 有没有好的思路, 除了pose2seg这样的.
非常感谢,期待回复

**Comment by Fang-Haoshu** [comment]
可以提高性能
segmentation框架都可以处理human segmentation
