### ISSUE TITLE
Colab with --tracking --pose_track?

### ISSUE THREAD

**Issue by rschmaelzle** [MVIG-SJTU/AlphaPose#735]
Hello,
thanks for a fantastic project  - it was the most accurate & easiest of all posetracking projects that I could get to run! 
I used the Colab notebook provided https://github.com/tugstugi/dl-colab-notebooks/blob/master/notebooks/AlphaPose.ipynb and it worked pretty much out of the box (I ran into issues with a local GPU though). However, this notebook installs from the pytorch-subbranch of the repository, which is older.
I tried to install the master, but failed. In particular, I would like to obtain tracking results about person identity so that I can track multiple persons. However, the options --tracking or --pose_track are not working (it complains that the module 'detector' is missing  - that seems to be only present in master). 
Does anyone have suggestions for how to get the master branch to work on colab? I tried to using the instructions, but didn't succeed (the old pytorch branch had a requirements-file -- the setup/build isn't working as smoothly).
Thank you very much
R

**Comment by Fang-Haoshu** [comment]
https://colab.research.google.com/drive/14Zgotr2_F0LfvcpRi03uQdMvUbLQSgok?usp=sharing
Can you try if it works?

**Comment by rschmaelzle** [comment]
Dear Fang/Fred Haoshu!,
thank you very much. I had to make minor changes to the original notebook, but got it to work! I am digging in deeper as I am still struggling with two issues: 
I) the tracked people sometimes swap identities (this has been noted before and if I run without --viz_fast it works mostly - if people stay in position). 
II) one thing I ran into is what seem to be memory limits. With the googleColab, I get 12 GB RAM, but if I run the code on youtube videos that are longer than 15 sec, it crashes. I am now trying to see if I can get it to run on a local GPU, or upgrade Colab. Do you have a tip on the memory that is needed?
Again many thanks Ralf.

**Comment by Fang-Haoshu** [comment]
--qsize 100 can lower the memory usage

**Comment by rschmaelzle** [comment]
thank you. that seemed to work and is a great suggestion I will keep in mind! 
- I tried to find out what what were meaningful values for --qsize (e.g does using '50' lower memory even more?)
- I still struggle running this on videos longer than 30 sec, such as 5 minute clip (which I what I need), and starting with a minute or so, it gets prohibitively long. I don't quite get why it is so slow, since many lower-quality tools (e.g. posenet for Javascript) work in realtime, and although the --pose_track understandably takes longer, it shouldn't be so slow (meanwhile I am working on ColabPro)
- the --viz-fast option causes the bounding boxes of the identified persons to be way off 
If these issues are meaningful, it would help me a lot to hear suggestions (and if not, the issue can be closed since my basic question has been answered - Thank you!)

**Comment by Fang-Haoshu** [comment]
Hi, if you want to run faster, you can set the conf in detector/yolo_cfg.py to 0.4 or higher.

**Comment by Fang-Haoshu** [comment]
--qsize 50 indeed lower the memory.
"--viz-fast option causes the bounding boxes of the identified persons to be way off"
Can you show how does it look like? Thanks

**Comment by rschmaelzle** [comment]
thanks a lot 
- setting the yolo_cfg.py to 0.4 
- and using size 50 worked as well
- Here is a [screenshot](https://drive.google.com/file/d/11keWTwGzxsRIbZ_DnINCFTHAk--vhRjY/view?usp=sharing) of the issue with --vis_fast , and [here](https://drive.google.com/file/d/1-VGieNezl4oA5eavrDJVmFuojvzhxCC-/view?usp=sharing) is a longer video.

**Comment by Fang-Haoshu** [comment]
Oh I see, it is indeed a bug. Let me fix it.

**Comment by Fang-Haoshu** [comment]
Should be fixed.

**Comment by qhdqhd** [comment]
I meet same problem in colab,  the options --tracking or --pose_track are not working ,too?  can you tell me why?

**Comment by qhdqhd** [comment]
@rschmaelzle

**Comment by qhdqhd** [comment]
thanks bro,  @rschmaelzle

**Comment by qhdqhd** [comment]
well i know.  just add --vis works fine,which may be a bug, can not tracking without visualization

**Comment by dekathomas** [comment]
Hello @rschmaelzle, how can you visualize the bounding box?
