### ISSUE TITLE
What's inps and cropped_boxes?

### ISSUE THREAD

**Issue by cbsudux** [MVIG-SJTU/AlphaPose#736]
I'm trying to feed my own image input and bounding boxes and not use the yolo queue based system you created. This seems to be harder than it looks. What are  inps and cropped_boxes in line https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/demo_inference.py#L226?

**Comment by Fang-Haoshu** [comment]
It is already implemented. You can use --det_file. Please refer the docs for usage
