### ISSUE TITLE
setup.py build develop error

### ISSUE THREAD

**Issue by ElisonSherton** [MVIG-SJTU/AlphaPose#740]
Hello guys!

I have tried to install alphapose using [this official documentation](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md#code-installation). I have cuda installed and running on my system which has a nvidia GTX 1060 6GB graphics. Here's the error log

```
running build_ext
building 'detector.nms.soft_nms_cpu' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/detector
creating build/temp.linux-x86_64-3.6/detector/nms
creating build/temp.linux-x86_64-3.6/detector/nms/src
gcc -pthread -B /home/vinayak/anaconda3/envs/alphapose/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/vinayak/anaconda3/envs/alphapose/lib/python3.6/site-packages/numpy/core/include -I/home/vinayak/anaconda3/envs/alphapose/include/python3.6m -c detector/nms/src/soft_nms_cpu.cpp -o build/temp.linux-x86_64-3.6/detector/nms/src/soft_nms_cpu.o -Wno-unused-function -Wno-write-strings -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=soft_nms_cpu -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1
```

Before that I have installed pytorch 1.4 and torchvision 0.5 in this alphapose environment. These are my nvidia GPU details
```
Fri Nov 20 11:26:23 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   56C    P8     9W /  N/A |    607MiB /  6070MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2471      G   /usr/lib/xorg/Xorg                 18MiB |
|    0   N/A  N/A      2822      G   /usr/bin/gnome-shell               47MiB |
|    0   N/A  N/A      3240      G   /usr/lib/xorg/Xorg                204MiB |
|    0   N/A  N/A      3384      G   /usr/bin/gnome-shell              166MiB |
|    0   N/A  N/A      3816      G   ...token=5922960996717256212       60MiB |
|    0   N/A  N/A      4126      G   ...AAAAAAAAA= --shared-files      104MiB |
+-----------------------------------------------------------------------------+
```

Also, the versions of gcc and g++ are as follows
![sn](https://user-images.githubusercontent.com/45599762/99780685-d1a1b500-2b3c-11eb-9216-ce0c79dcc33a.png)

Can someone help me figure out where am I going wrong? Appreciate a prompt reply...

**Comment by yyyyojiro** [comment]
have you solved this problem? I have the same problem as you

**Comment by ElisonSherton** [comment]
> have you solved this problem? I have the same problem as you

No, I couldn't solve it but I found an implementation of alphapose on Google Colab [here](https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/AlphaPose.ipynb). Using a pretrained model from the model zoo was sufficient for my application so I didn't have to pretrain anything and only needed to infer keypoint details and this notebook helped me with the same.

Hope this helps...

**Comment by yyyyojiro** [comment]
thank you very much! this reply helped me a lot! thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MVIG-SJTU/AlphaPose"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月1日(星期五) 晚上7:53
收件人:&nbsp;"MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;;
抄送:&nbsp;"only_Yojiro"<2402068371@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] setup.py build develop error (#740)





  
have you solved this problem? I have the same problem as you
  
No, I couldn't solve it but I found an implementation of alphapose on Google Colab here. Using a pretrained model from the model zoo was sufficient for my application so I didn't have to pretrain anything and only needed to infer keypoint details and this notebook helped me with the same.
 
Hope this helps...

**Comment by ElisonSherton** [comment]
> thank you very much! this reply helped me a lot! thanks!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MVIG-SJTU/AlphaPose" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月1日(星期五) 晚上7:53 收件人:&nbsp;"MVIG-SJTU/AlphaPose"<AlphaPose@noreply.github.com&gt;; 抄送:&nbsp;"only_Yojiro"<2402068371@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] setup.py build develop error (#740) have you solved this problem? I have the same problem as you No, I couldn't solve it but I found an implementation of alphapose on Google Colab here. Using a pretrained model from the model zoo was sufficient for my application so I didn't have to pretrain anything and only needed to infer keypoint details and this notebook helped me with the same. Hope this helps... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Welcome :+1:
