### ISSUE TITLE
Where is 'frame_preprocess' function?

### ISSUE THREAD

**Issue by paul-shuvo** [MVIG-SJTU/AlphaPose#746]
I'm trying to use `scripts/demo_api.py` and it returns `None` on `img = self.detector.frame_preprocess(image)` (`line 108`). Here the detector in use is `YOLODetector` and I couldn't find any `frame_preprocess` method. Should it be `image_preprocess`?

**Comment by Fang-Haoshu** [comment]
Oh you are right, thanks for the remind! Just fix it.
