### ISSUE TITLE
I'm trying to use scripts/demo_api.py with tracking option

### ISSUE THREAD

**Issue by yone-moto** [MVIG-SJTU/AlphaPose#747]
I'm trying to use scripts/demo_api.py with tracking options

`python scripts/demo_api.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --vis --image examples/demo/1.jpg --pose_track`

I get the following error 

```
alphapose/utils/vis.py", line 281, in vis_frame
color = get_color_fast(int(abs(human['idx'])))
TypeError: bad operand type for abs(): 'list'
```

So I modified the program and it ran.
alphapose/utils/vis.py", line 281, in vis_frame
`color = get_color_fast(int(abs(human['idx'])))　→　color = get_color_fast(int(abs(human['idx'][0])))`

But the people in the image were all in the same color posture, and when I checked the json file, all the "idx": [0.0].
How do I fix it so I can run the tracking options?

**Comment by Fang-Haoshu** [comment]
You should use the scripts/demo_inference.py 
What's more, the pose track is not included in the api file, as single image cannot be tracking.

**Comment by yone-moto** [comment]
Thank you for your reply.

I would like to run AlphaPose with tracking options in ROS on video .

Should I run scripts/demo_inference.py in such a case?

**Comment by hsauod** [comment]
@yone-moto hi Moto,   
I also want to use API in tracking. How did you work with it?
Could you please give me some ideas? 
Thank you very much

**Comment by yone-moto** [comment]
@hsauod hi hsauod
Thanks for asking.

I have improved the API code and was able to implement the tracking in ROS.
However, there are a lot of imperfections in the code, so I have a lot to improve.
I will upload my code in a few days, but please forgive me if it is not perfect.

Regards,
YONEMOTO

**Comment by adithyashankar-97** [comment]
@yone-moto Hi moto, if possible can you share your code? I am facing similar issues
