### ISSUE TITLE
Perhaps consider adding more comments to the pytorch branch

### ISSUE THREAD

**Issue by 326623** [MVIG-SJTU/AlphaPose#75]
It's very hard to read through the source codes...
Like what does this function do etc(function parameter and return type)

Can you guys look into the` box_coder` of `SSD512`. It seems to forget about resizing the detected box size, causing some confusing pose detection results.

And sometime when no box is detected, and the code would call something like `torch.cat(boxes, 0)`, which cause python interpreter to complain about calling the function with a list object and then crash

**Comment by Jeff-sjtu** [comment]
1. We will elaborate the comments of `sppe` in new version.
2. In our new model code, we use `fpnssd` instead of `ssd512`, it seems you doesn't renew your code.
3. Refer to 2.

**Comment by 326623** [comment]
1. Thanks, appreciate it.
2. In demo_faster.py, it seems to use the coder from SSD (namely **SSDBoxCoder**).
3. In demo_fast.py, I would encounter something like this

```
RuntimeError: Error(s) in loading state_dict for FPNSSD512:
	Missing key(s) in state_dict: "fpn.conv1.weight", "fpn.bn1.weight", "fpn.bn1.bias", "fpn.bn1.running_mean", "fpn.bn1.running_var", "fpn.layer1.0.conv1.weight", "fpn.layer1.0.bn1.weight", "fpn.layer1.0.bn1.bias", "fpn.layer1.0.bn1.running_mean", "fpn.layer1.0.bn1.running_var", "fpn.layer1.0.conv2.weight", "fpn.layer1.0.bn2.weight", "fpn.layer1.0.bn2.bias", "fpn.layer1.0.bn2.running_mean", "fpn.layer1.0.bn2.running_var", "fpn.layer1.0.conv3.weight", "fpn.layer1.0.bn3.weight", "fpn.layer1.0.bn3.bias", "fpn.layer1.0.bn3.running_mean", "fpn.layer1.0.bn3.running_var", "fpn.layer1.0.downsample.0.weight", "fpn.layer1.0.downsample.1.weight", "fpn.layer1.0.downsample.1.bias",
```

The list goes on...
Therefore I switch back to the old code. 

Maybe there are some inconsistent with the new fpnssd box coder and the model. I get this:

`RuntimeError: The size of tensor a (24564) must match the size of tensor b (49149) at non-singleton dimension 0`

Now I use the SSD coder and old code of fpnssd to get the system to work.

4. If no person is detected, then during the decode phase` torch.cat() `would try to concatenate a list, which would report as runtime error.

**Comment by 326623** [comment]
Could you guys provide some response? Looking forward to them. @Jeff-sjtu @Fang-Haoshu 
Sorry for bothering you guys.

**Comment by Jeff-sjtu** [comment]
Hi, please try the new version of code(27dd18d8a3d711a409d1513a8303427aec3e6ba1). Hope can fix your problem.

**Comment by 326623** [comment]
Thanks, I will try. Great work!
