### ISSUE TITLE
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

### ISSUE THREAD

**Issue by rirri93** [MVIG-SJTU/AlphaPose#752]
With this command:  
`/scripts/inference.sh ./configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml ./pretrained_models/fast_421_res152_256x192.pth ./examples/demo/apart.avi ./output --pose_track`

I obtain this: 

++ CONFIG=./configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml
++ CKPT=./pretrained_models/fast_421_res152_256x192.pth
++ VIDEO=./examples/demo/apart.avi
++ OUTDIR=./output
++ python scripts/demo_inference.py --cfg ./configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml --checkpoint ./pretrained_models/fast_421_res152_256x192.pth --video ./examples/demo/apart.avi --outdir ./output --detector yolo --save_img --save_video
Load SE Resnet...
Loading YOLO model..
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Loading pose model from ./pretrained_models/fast_421_res152_256x192.pth...
  0%|                                                                                                                                                                                | 0/87 [00:00<?, ?it/s]
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 87/87 [00:02<00:00, 38.62it/s]
===========================> Finish Model Running.
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
===========================> Rendering remaining 73 images in the queue...
===========================> Rendering remaining 68 images in the queue...
===========================> Rendering remaining 62 images in the queue...
===========================> Rendering remaining 57 images in the queue...
===========================> Rendering remaining 51 images in the queue...
===========================> Rendering remaining 46 images in the queue...
===========================> Rendering remaining 41 images in the queue...
===========================> Rendering remaining 35 images in the queue...
===========================> Rendering remaining 30 images in the queue...
===========================> Rendering remaining 25 images in the queue...
===========================> Rendering remaining 19 images in the queue...
===========================> Rendering remaining 14 images in the queue...
===========================> Rendering remaining 8 images in the queue...
===========================> Rendering remaining 2 images in the queue...
===========================> Rendering remaining 0 images in the queue...
Results have been written to json.

This is my configuration: 
torch==1.1.0
CUDA 10.0 (I tried with 10.2 too)

**Comment by Fang-Haoshu** [comment]
Hi, it seems the program finished. Do you get the correct output?
