### ISSUE TITLE
Halpe 136 model doesn't work correctly 

### ISSUE THREAD

**Issue by YomnaGamal** [MVIG-SJTU/AlphaPose#753]
Hi,
I use Halpe_136 model here: 
https://drive.google.com/file/d/1NyOuVLb5oIYP4LZmp9BSAQdbGjEk--gv/view?usp=sharing
and cfg file here: 
https://drive.google.com/file/d/1d9BSHnIXS3OVGNa4lc1de4qTsybY-N9_/view?usp=sharing
and changed all occurrences of coco_wholebody to Halpe_136 in cfg file and modified num_joints from 133 to 136, but it didn't get all points, it gets a few of them.
It was said that it is not the final model but I couldn't find neither anyone else released after that "from September" nor any issue to help.

Are there any other pre-trained models for Haple 136? or when will be the final model released?

**Comment by Fang-Haoshu** [comment]
Hi, sorry for the confusion. I updated the code and models.
You can pull the latest code and download the new models in  MODEL ZOO: https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md

Script for running is also available.
