### ISSUE TITLE
Detection takes long time when inference one img?

### ISSUE THREAD

**Issue by Stephenfang51** [MVIG-SJTU/AlphaPose#756]
Hi Sir
Thanks for the great work

I just wonder if it's normal to take about 500ms when testing on one image?
when I test a list of image, it takes around average 100ms.

How could I speed up for one image inference?

and what speed can reach using webcam stream ?

Thanks !

**Comment by Fang-Haoshu** [comment]
Hi, you mean the need to load models for each time of one image?

**Comment by Fang-Haoshu** [comment]
webcam is also much faster than that.

**Comment by Stephenfang51** [comment]
@Fang-Haoshu I tried to modify your `demo_api.py` since it did load model each time for just one pic, and now can reach 50ms without multi-processes or threads.

**Comment by YomnaGamal** [comment]
@Stephenfang51  Can you tell me what did you modify in demo_api.py to reduce time?
Thanks in advance.

**Comment by Stephenfang51** [comment]
> @Stephenfang51 Can you tell me what did you modify in demo_api.py to reduce time?
> Thanks in advance.

emm.. just move loading model outside the main function, make sure that only need to load each model once (detection and pose model)

**Comment by Stephenfang51** [comment]
@Fang-Haoshu 
Hi, I modified the vis_frame a bit which causes me should put --sp to run demo_inference.py, otherwise it would shows rendering remaining 0 images in queue and cannot play output mp4 sucessfully. Could you please tell me why it can affect the multi threads or multi processes ?

**Comment by Fang-Haoshu** [comment]
Cool @Stephenfang51
