### ISSUE TITLE
Is there a way to import alphapose as a function and get json as return results in python?

### ISSUE THREAD

**Issue by Unicorndy** [MVIG-SJTU/AlphaPose#757]
Hi Alphapose Team,
First of all, I must thank you for open-sourcing this wonderful model, it has been most helpful in many applications.
However, I have a question regarding integrating into other program. Currently we hope to run the inference and get the json results only, is there an api or function that we can import into our python script instead of getting result using demo_inference.py with arguments?

**Comment by Fang-Haoshu** [comment]
Hi, you can see the demo_api.py

**Comment by Unicorndy** [comment]
Thank you!
