### ISSUE TITLE
How can i use yolov3-tiny.cfg and weights for detection.

### ISSUE THREAD

**Issue by laomaup** [MVIG-SJTU/AlphaPose#759]
I want use  yolov3-tiny.cfg and yolov3-tiny.weights for human detection, so replace the code
self.det_model = Darknet("yolo/cfg/yolov3-tiny.cfg")
self.det_model.load_weights('models/yolo/yolov3-tiny.weights')

error message:
Traceback (most recent call last):
  File "/home/pkg/new_py/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/pkg/new_py/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/data/AlphaPose/dataloader_webcam.py", line 157, in update
    prediction = self.det_model(img, CUDA=True)
  File "/home/pkg/new_py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data/AlphaPose/yolo/darknet.py", line 353, in forward
    x = torch.cat((map1, map2), 1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 16 and 14 (The offending index is 0)

**Comment by 13281306705** [comment]
> 我想使用yolov3-tiny.cfg和yolov3-tiny.weights进行人体检测，因此替换代码
> self.det_model = Darknet（“ yolo / cfg / yolov3-tiny.cfg”）
> self.det_model.load_weights（'models / yolo /yolov3-tiny.weights'）
> 
> 错误消息：
> 追溯（最近一次调用最近）：
> 文件“ /home/pkg/new_py/lib/python3.6/threading.py”，行916，位于_bootstrap_inner
> self.run（）
> 文件中，文件“ / home / pkg / new_py / lib / python3.6 / threading.py”，行864，在运行
> self._target（* self._args，** self._kwargs）
> 文件“ /home/data/AlphaPose/dataloader_webcam.py”，行157，在更新中
> 预测= self.det_model（img，CUDA = True）
> 文件“ /home/pkg/new_py/lib/python3.6/site-packages/torch/nn/modules/module.py”，第722行，位于_call_impl中，
> 结果= self .forward（* input，** kwargs）
> File“ /home/data/AlphaPose/yolo/darknet.py”，第353行，正向
> x = torch.cat（（map1，map2），1）
> RuntimeError：张量的大小必须匹配，但尺寸2除外。得到16和14（有问题的索引为0）

老哥，请问你的yolov3-tiny放好了吗

**Comment by laomaup** [comment]
没有用tiny，可能只修改模型不行，需要修改代码。



在 2021-05-17 22:23:18，"13281306705" ***@***.***> 写道：

我想使用yolov3-tiny.cfg和yolov3-tiny.weights进行人体检测，因此替换代码
self.det_model = Darknet（“ yolo / cfg / yolov3-tiny.cfg”）
self.det_model.load_weights（'models / yolo /yolov3-tiny.weights'）

错误消息：
追溯（最近一次调用最近）：
文件“ /home/pkg/new_py/lib/python3.6/threading.py”，行916，位于_bootstrap_inner
self.run（）
文件中，文件“ / home / pkg / new_py / lib / python3.6 / threading.py”，行864，在运行
self._target（* self._args，** self._kwargs）
文件“ /home/data/AlphaPose/dataloader_webcam.py”，行157，在更新中
预测= self.det_model（img，CUDA = True）
文件“ /home/pkg/new_py/lib/python3.6/site-packages/torch/nn/modules/module.py”，第722行，位于_call_impl中，
结果= self .forward（* input，** kwargs）
File“ /home/data/AlphaPose/yolo/darknet.py”，第353行，正向
x = torch.cat（（map1，map2），1）
RuntimeError：张量的大小必须匹配，但尺寸2除外。得到16和14（有问题的索引为0）

老哥，请问你的yolov3-tiny放好了吗

**Comment by 13281306705** [comment]
> 没有用tiny，可能只修改模型不行，需要修改代码。 在 2021-05-17 22:23:18，"13281306705" ***@***.***> 写道： 我想使用yolov3-tiny.cfg和yolov3-tiny.weights进行人体检测，因此替换代码 self.det_model = Darknet（“ yolo / cfg / yolov3-tiny.cfg”） self.det_model.load_weights（'models / yolo /yolov3-tiny.weights'） 错误消息： 追溯（最近一次调用最近）： 文件“ /home/pkg/new_py/lib/python3.6/threading.py”，行916，位于_bootstrap_inner self.run（） 文件中，文件“ / home / pkg / new_py / lib / python3.6 / threading.py”，行864，在运行 self._target（* self._args，** self._kwargs） 文件“ /home/data/AlphaPose/dataloader_webcam.py”，行157，在更新中 预测= self.det_model（img，CUDA = True） 文件“ /home/pkg/new_py/lib/python3.6/site-packages/torch/nn/modules/module.py”，第722行，位于_call_impl中， 结果= self .forward（* input，** kwargs） File“ /home/data/AlphaPose/yolo/darknet.py”，第353行，正向 x = torch.cat（（map1，map2），1） RuntimeError：张量的大小必须匹配，但尺寸2除外。得到16和14（有问题的索引为0） 老哥，请问你的yolov3-tiny放好了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，老哥的回答
