### ISSUE TITLE
json result file

### ISSUE THREAD

**Issue by adel6666** [MVIG-SJTU/AlphaPose#761]
Hello,

I get this json structure results:
{'image_id': '0.jpg',
 'category_id': 1,
 'keypoints': [54.21041488647461,
  42.75874328613281,
  0.9267162084579468,
  ...
  68.84831237792969,
  36.179542541503906,
  0.9536290764808655],
 'score': 2.472965717315674,
 'idx': [[0.0], [0.0]]}
I didn't understand what 'idx' mean? Can you help me :)

**Comment by Fang-Haoshu** [comment]
tracking idx, no use if no tracking is enabled.
