### ISSUE TITLE
python setup.py build develop error

### ISSUE THREAD

**Issue by 13517592731** [MVIG-SJTU/AlphaPose#762]
My operating environment: cuda11.1, cudnn8.0.5, pytorch1.7.1, python3.6, gcc7.5.0
When I run the install command, An error occurred in the program:
**running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.6/alphapose
running build_ext
building 'detector.nms.soft_nms_cpu' extension
Emitting ninja build file /home/machine/project/python/deep-learn/AlphaPose/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -shared -B /home/machine/application/anaconda3/envs/alphapose/compiler_compat -L/home/machine/application/anaconda3/envs/alphapose/lib -Wl,-rpath=/home/machine/application/anaconda3/envs/alphapose/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/machine/project/python/deep-learn/AlphaPose/build/temp.linux-x86_64-3.6/detector/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.6/detector/nms/soft_nms_cpu.cpython-36m-x86_64-linux-gnu.so
g++: error: /home/machine/project/python/deep-learn/AlphaPose/build/temp.linux-x86_64-3.6/detector/nms/src/soft_nms_cpu.o: No such file or directory
error: command 'g++' failed with exit status 1**
Is my version of Python too high ？ What should I do to compile this module？

**Comment by Fang-Haoshu** [comment]
pytorch version too high, you need to merge pull request that supports pytorch1.5

**Comment by Fang-Haoshu** [comment]
You can check the new install instruction for that.

**Comment by wwdok** [comment]
Hello@Fang-Haoshu, how to merge pull request that supports pytorch1.5, just run `git pull origin pull/592/head` ? is there other steps ?
