### ISSUE TITLE
Ubuntu18 cannot install alphapose

### ISSUE THREAD

**Issue by Deep-learning999** [MVIG-SJTU/AlphaPose#766]
Can alphase provide high-level GCC compilation? For example, gcc8 and gcc7 restrict the use of alphase because they use versions before gcc6, because the current Ubuntu 18 and Ubuntu 20 do not have gcc5. Local compilation is also very slow and easy to eat mistakes

**Comment by Fang-Haoshu** [comment]
Seems the gcc is not a restriction. I installed alphapose on Ubuntu 18 yesterday.
