### ISSUE TITLE
Human-ReID based tracking

### ISSUE THREAD

**Issue by zgs731** [MVIG-SJTU/AlphaPose#768]
hi!
You said that you want to publish the paper of Human-ReID based tracking. It’s been a few months. Is it published now?

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your interest. It is not yet published. I would say it is coming soon.

**Comment by Fang-Haoshu** [comment]
Hi, the paper is public at http://arxiv.org/abs/2211.03375
Thanks for your interest! @maarten0912
