### ISSUE TITLE
AlphaPose killed

### ISSUE THREAD

**Issue by velastin** [MVIG-SJTU/AlphaPose#769]
Hello. I am building a large public dataset from a set of RGB videos of people walking in public spaces.
To install alphapose I did the following:
mkvirtualenv --system-site-packages -p python3 pytorch
pip install opencv-python
pip install opencv-contrib-python
pip install torch==0.4.0
pip install torchvision==0.4.0    # this updates pytorch to 1.2.0
pip install visdom
pip install nibabel
pip install pandas
pip install tqdm
pip install matplotlib

# Alphapose
git clone -b pytorch https://github.com/MVIG-SJTU/AlphaPose.git
git checkout pytorch

Download the models manually: duc_se.pth (2018/08/30) (Google Drive | Baidu pan), yolov3-spp.weights(Google Drive | Baidu pan). Place them into ./models/sppe and ./models/yolo respectively.
*************
I converted my video (mp4) to individual jpg files using ffmpeg
I then created a sorted list of my jpg files into Image.lst
Then
python demo.py --list Image.lst --outdir examples/res --save_img --sp

is starts computing skeletons but at some point the process is Killed.
The problem is that it is not always the same point (that is why I sorted the list to check this).
I have also tried different --posebatch values. No effect.
The same occurs when using the original video with video-demo.py
And the same happens when running on a different GPU with more memory (11GB)

I am using Ubuntu 18.x
The problem does not occur on some other videos of similar level of human activity.
As I will batching the processing of a large number of videos, I need to find a solution to this.

Many thanks

**Comment by velastin** [comment]
Solved. The problem is that when cudnn is enabled, cpu memory keeps on increasing until the process is killed.
Please see https://github.com/pytorch/pytorch/issues/3665
Solution is to add: torch.backends.cudnn.enabled = False at the start of the main python code (e.g. demo.py)

**Comment by hdnh2006** [comment]
It is not enough with `torch.backends.cudnn.enabled = False` you fitted the parameters as following: "--qsize 128 --detbatch 1 --posebatch 30"

**Comment by samymdihi** [comment]
@velastin  using your command reduces the use of CPU but it only uses CPU and takes longer to compute. Do you have any idea on how to use the gpu with your method ?
