### ISSUE TITLE
Is the pretrained models trained from FPN50?

### ISSUE THREAD

**Issue by zhengpengpeng** [MVIG-SJTU/AlphaPose#77]
Hi, I tried your code currently. Everything works well until I got this error loading the model.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FPNSSD512:

Missing key(s) in state_dict: "fpn.conv1.weight", "fpn.bn1.weight", "fpn.bn1.running_var", "fpn.bn1.bias", "fpn.bn1.running_mean", "fpn.layer1.0.conv1.weight", "fpn.layer1.0.bn1.weight", "fpn.layer1.0.bn1.running_var", "fpn.layer1.0.bn1.bias", "fpn.layer1.0.bn1.running_mean", "fpn.layer1.0.conv2.weight", "fpn.layer1.0.bn2.weight", "fpn.layer1.0.bn2.running_var", "fpn.layer1.0.bn2.bias", "fpn.layer1.0.bn2.running_mean", "fpn.layer1.0.conv3.weight", "fpn.layer1.0.bn3.weight", "fpn.layer1.0.bn3.running_var", "fpn.layer1.0.bn3.bias", "fpn.layer1.0.bn3.running_mean", "fpn.layer1.0.downsample.0.weight", "fpn.layer1.0.downsample.1.weight", "fpn.layer1.0.downsample.1.running_var", "fpn.layer1.0.downsample.1.bias", "fpn.layer1.0.downsample.1.running_mean", "fpn.layer1.1.conv1.weight", "fpn.layer1.1.bn1.weight", "fpn.layer1.1.bn1.running_var", "fpn.layer1.1.bn1.bias", "fpn.layer1.1.bn1.running_mean", "fpn.layer1.1.conv2.weight", "fpn.layer1.1.bn2.weight", "fpn.layer1.1.bn2.running_var", "fpn.layer1.1.bn2.bias", "fpn.layer1.1.bn2.running_mean", "fpn.layer1.1.conv3.weight", "fpn.layer1.1.bn3.weight", "fpn.layer1.1.bn3.running_var", "fpn.layer1.1.bn3.bias", "fpn.layer1.1.bn3.running_mean", "fpn.layer1.2.conv1.weight", "fpn.layer1.2.bn1.weight", "fpn.layer1.2.bn1.running_var", "fpn.layer1.2.bn1.bias", "fpn.layer1.2.bn1.running_mean", "fpn.layer1.2.conv2.weight", "fpn.layer1.2.bn2.weight", "fpn.layer1.2.bn2.running_var", "fpn.layer1.2.bn2.bias", "fpn.layer1.2.bn2.running_mean", "fpn.layer1.2.conv3.weight", "fpn.layer1.2.bn3.weight", "fpn.layer1.2.bn3.running_var", "fpn.layer1.2.bn3.bias", "fpn.layer1.2.bn3.running_mean", "fpn.layer2.0.conv1.weight", "fpn.layer2.0.bn1.weight", "fpn.layer2.0.bn1.running_var", "fpn.layer2.0.bn1.bias", "fpn.layer2.0.bn1.running_mean", "fpn.layer2.0.conv2.weight", "fpn.layer2.0.bn2.weight", "fpn.layer2.0.bn2.running_var", "fpn.layer2.0.bn2.bias", "fpn.layer2.0.bn2.running_mean", "fpn.layer2.0.conv3.weight", "fpn.layer2.0.bn3.weight", "fpn.layer2.0.bn3.running_var", "fpn.layer2.0.bn3.bias", "fpn.layer2.0.bn3.running_mean", "fpn.layer2.0.downsample.0.weight", "fpn.layer2.0.downsample.1.weight", "fpn.layer2.0.downsample.1.running_var", "fpn.layer2.0.downsample.1.bias", "fpn.layer2.0.downsample.1.running_mean", "fpn.layer2.1.conv1.weight", "fpn.layer2.1.bn1.weight", "fpn.layer2.1.bn1.running_var", "fpn.layer2.1.bn1.bias", "fpn.layer2.1.bn1.running_mean", "fpn.layer2.1.conv2.weight", "fpn.layer2.1.bn2.weight", "fpn.layer2.1.bn2.running_var", "fpn.layer2.1.bn2.bias", "fpn.layer2.1.bn2.running_mean", "fpn.layer2.1.conv3.weight", "fpn.layer2.1.bn3.weight", "fpn.layer2.1.bn3.running_var", "fpn.layer2.1.bn3.bias", "fpn.layer2.1.bn3.running_mean", "fpn.layer2.2.conv1.weight", "fpn.layer2.2.bn1.weight", "fpn.layer2.2.bn1.running_var", "fpn.layer2.2.bn1.bias", "fpn.layer2.2.bn1.running_mean", "fpn.layer2.2.conv2.weight", "fpn.layer2.2.bn2.weight", "fpn.layer2.2.bn2.running_var", "fpn.layer2.2.bn2.bias", "fpn.layer2.2.bn2.running_mean", "fpn.layer2.2.conv3.weight", "fpn.layer2.2.bn3.weight", "fpn.layer2.2.bn3.running_var", "fpn.layer2.2.bn3.bias", "fpn.layer2.2.bn3.running_mean", "fpn.layer2.3.conv1.weight", "fpn.layer2.3.bn1.weight", "fpn.layer2.3.bn1.running_var", "fpn.layer2.3.bn1.bias", "fpn.layer2.3.bn1.running_mean", "fpn.layer2.3.conv2.weight", "fpn.layer2.3.bn2.weight", "fpn.layer2.3.bn2.running_var", "fpn.layer2.3.bn2.bias", "fpn.layer2.3.bn2.running_mean", "fpn.layer2.3.conv3.weight", "fpn.layer2.3.bn3.weight", "fpn.layer2.3.bn3.running_var", "fpn.layer2.3.bn3.bias", "fpn.layer2.3.bn3.running_mean", "fpn.layer3.0.conv1.weight", "fpn.layer3.0.bn1.weight", "fpn.layer3.0.bn1.running_var", "fpn.layer3.0.bn1.bias", "fpn.layer3.0.bn1.running_mean", "fpn.layer3.0.conv2.weight", "fpn.layer3.0.bn2.weight", "fpn.layer3.0.bn2.running_var", "fpn.layer3.0.bn2.bias", "fpn.layer3.0.bn2.running_mean", "fpn.layer3.0.conv3.weight", "fpn.layer3.0.bn3.weight", "fpn.layer3.0.bn3.running_var", "fpn.layer3.0.bn3.bias", "fpn.layer3.0.bn3.running_mean", "fpn.layer3.0.downsample.0.weight", "fpn.layer3.0.downsample.1.weight", "fpn.layer3.0.downsample.1.running_var", "fpn.layer3.0.downsample.1.bias", "fpn.layer3.0.downsample.1.running_mean", "fpn.layer3.1.conv1.weight", "fpn.layer3.1.bn1.weight", "fpn.layer3.1.bn1.running_var", "fpn.layer3.1.bn1.bias", "fpn.layer3.1.bn1.running_mean", "fpn.layer3.1.conv2.weight", "fpn.layer3.1.bn2.weight", "fpn.layer3.1.bn2.running_var", "fpn.layer3.1.bn2.bias", "fpn.layer3.1.bn2.running_mean", "fpn.layer3.1.conv3.weight", "fpn.layer3.1.bn3.weight", "fpn.layer3.1.bn3.running_var", "fpn.layer3.1.bn3.bias", "fpn.layer3.1.bn3.running_mean", "fpn.layer3.2.conv1.weight", "fpn.layer3.2.bn1.weight", "fpn.layer3.2.bn1.running_var", "fpn.layer3.2.bn1.bias", "fpn.layer3.2.bn1.running_mean", "fpn.layer3.2.conv2.weight", "fpn.layer3.2.bn2.weight", "fpn.layer3.2.bn2.running_var", "fpn.layer3.2.bn2.bias", "fpn.layer3.2.bn2.running_mean", "fpn.layer3.2.conv3.weight", "fpn.layer3.2.bn3.weight", "fpn.layer3.2.bn3.running_var", "fpn.layer3.2.bn3.bias", "fpn.layer3.2.bn3.running_mean", "fpn.layer3.3.conv1.weight", "fpn.layer3.3.bn1.weight", "fpn.layer3.3.bn1.running_var", "fpn.layer3.3.bn1.bias", "fpn.layer3.3.bn1.running_mean", "fpn.layer3.3.conv2.weight", "fpn.layer3.3.bn2.weight", "fpn.layer3.3.bn2.running_var", "fpn.layer3.3.bn2.bias", "fpn.layer3.3.bn2.running_mean", "fpn.layer3.3.conv3.weight", "fpn.layer3.3.bn3.weight", "fpn.layer3.3.bn3.running_var", "fpn.layer3.3.bn3.bias", "fpn.layer3.3.bn3.running_mean", "fpn.layer3.4.conv1.weight", "fpn.layer3.4.bn1.weight", "fpn.layer3.4.bn1.running_var", "fpn.layer3.4.bn1.bias", "fpn.layer3.4.bn1.running_mean", "fpn.layer3.4.conv2.weight", "fpn.layer3.4.bn2.weight", "fpn.layer3.4.bn2.running_var", "fpn.layer3.4.bn2.bias", "fpn.layer3.4.bn2.running_mean", "fpn.layer3.4.conv3.weight", "fpn.layer3.4.bn3.weight", "fpn.layer3.4.bn3.running_var", "fpn.layer3.4.bn3.bias", "fpn.layer3.4.bn3.running_mean", "fpn.layer3.5.conv1.weight", "fpn.layer3.5.bn1.weight", "fpn.layer3.5.bn1.running_var", "fpn.layer3.5.bn1.bias", "fpn.layer3.5.bn1.running_mean", "fpn.layer3.5.conv2.weight", "fpn.layer3.5.bn2.weight", "fpn.layer3.5.bn2.running_var", "fpn.layer3.5.bn2.bias", "fpn.layer3.5.bn2.running_mean", "fpn.layer3.5.conv3.weight", "fpn.layer3.5.bn3.weight", "fpn.layer3.5.bn3.running_var", "fpn.layer3.5.bn3.bias", "fpn.layer3.5.bn3.running_mean", "fpn.layer4.0.conv1.weight", "fpn.layer4.0.bn1.weight", "fpn.layer4.0.bn1.running_var", "fpn.layer4.0.bn1.bias", "fpn.layer4.0.bn1.running_mean", "fpn.layer4.0.conv2.weight", "fpn.layer4.0.bn2.weight", "fpn.layer4.0.bn2.running_var", "fpn.layer4.0.bn2.bias", "fpn.layer4.0.bn2.running_mean", "fpn.layer4.0.conv3.weight", "fpn.layer4.0.bn3.weight", "fpn.layer4.0.bn3.running_var", "fpn.layer4.0.bn3.bias", "fpn.layer4.0.bn3.running_mean", "fpn.layer4.0.downsample.0.weight", "fpn.layer4.0.downsample.1.weight", "fpn.layer4.0.downsample.1.running_var", "fpn.layer4.0.downsample.1.bias", "fpn.layer4.0.downsample.1.running_mean", "fpn.layer4.1.conv1.weight", "fpn.layer4.1.bn1.weight", "fpn.layer4.1.bn1.running_var", "fpn.layer4.1.bn1.bias", "fpn.layer4.1.bn1.running_mean", "fpn.layer4.1.conv2.weight", "fpn.layer4.1.bn2.weight", "fpn.layer4.1.bn2.running_var", "fpn.layer4.1.bn2.bias", "fpn.layer4.1.bn2.running_mean", "fpn.layer4.1.conv3.weight", "fpn.layer4.1.bn3.weight", "fpn.layer4.1.bn3.running_var", "fpn.layer4.1.bn3.bias", "fpn.layer4.1.bn3.running_mean", "fpn.layer4.2.conv1.weight", "fpn.layer4.2.bn1.weight", "fpn.layer4.2.bn1.running_var", "fpn.layer4.2.bn1.bias", "fpn.layer4.2.bn1.running_mean", "fpn.layer4.2.conv2.weight", "fpn.layer4.2.bn2.weight", "fpn.layer4.2.bn2.running_var", "fpn.layer4.2.bn2.bias", "fpn.layer4.2.bn2.running_mean", "fpn.layer4.2.conv3.weight", "fpn.layer4.2.bn3.weight", "fpn.layer4.2.bn3.running_var", "fpn.layer4.2.bn3.bias", "fpn.layer4.2.bn3.running_mean", "fpn.conv6.weight", "fpn.conv6.bias", "fpn.conv7.weight", "fpn.conv7.bias", "fpn.conv8.weight", "fpn.conv8.bias", "fpn.conv9.weight", "fpn.conv9.bias", "fpn.toplayer.weight", "fpn.toplayer.bias", "fpn.latlayer1.weight", "fpn.latlayer1.bias", "fpn.latlayer2.weight", "fpn.latlayer2.bias", "fpn.smooth1.weight", "fpn.smooth1.bias", "fpn.smooth2.weight", "fpn.smooth2.bias", "loc_head.0.weight", "loc_head.0.bias", "loc_head.2.weight", "loc_head.2.bias", "loc_head.4.weight", "loc_head.4.bias", "loc_head.6.weight", "loc_head.6.bias", "loc_head.8.weight", "loc_head.8.bias", "cls_head.0.weight", "cls_head.0.bias", "cls_head.2.weight", "cls_head.2.bias", "cls_head.4.weight", "cls_head.4.bias", "cls_head.6.weight", "cls_head.6.bias", "cls_head.8.weight", "cls_head.8.bias".
        Unexpected key(s) in state_dict: "extractor.conv1.weight", "extractor.bn1.weight", "extractor.bn1.bias", "extractor.bn1.running_mean", "extractor.bn1.running_var", "extractor.layer1.0.conv1.weight", "extractor.layer1.0.bn1.weight", "extractor.layer1.0.bn1.bias", "extractor.layer1.0.bn1.running_mean", "extractor.layer1.0.bn1.running_var", "extractor.layer1.0.conv2.weight", "extractor.layer1.0.bn2.weight", "extractor.layer1.0.bn2.bias", "extractor.layer1.0.bn2.running_mean", "extractor.layer1.0.bn2.running_var", "extractor.layer1.0.conv3.weight", "extractor.layer1.0.bn3.weight", "extractor.layer1.0.bn3.bias", "extractor.layer1.0.bn3.running_mean", "extractor.layer1.0.bn3.running_var", "extractor.layer1.0.downsample.0.weight", "extractor.layer1.0.downsample.1.weight", "extractor.layer1.0.downsample.1.bias", "extractor.layer1.0.downsample.1.running_mean", "extractor.layer1.0.downsample.1.running_var", "extractor.layer1.1.conv1.weight", "extractor.layer1.1.bn1.weight", "extractor.layer1.1.bn1.bias", "extractor.layer1.1.bn1.running_mean", "extractor.layer1.1.bn1.running_var", "extractor.layer1.1.conv2.weight", "extractor.layer1.1.bn2.weight", "extractor.layer1.1.bn2.bias", "extractor.layer1.1.bn2.running_mean", "extractor.layer1.1.bn2.running_var", "extractor.layer1.1.conv3.weight", "extractor.layer1.1.bn3.weight", "extractor.layer1.1.bn3.bias", "extractor.layer1.1.bn3.running_mean", "extractor.layer1.1.bn3.running_var", "extractor.layer1.2.conv1.weight", "extractor.layer1.2.bn1.weight", "extractor.layer1.2.bn1.bias", "extractor.layer1.2.bn1.running_mean", "extractor.layer1.2.bn1.running_var", "extractor.layer1.2.conv2.weight", "extractor.layer1.2.bn2.weight", "extractor.layer1.2.bn2.bias", "extractor.layer1.2.bn2.running_mean", "extractor.layer1.2.bn2.running_var", "extractor.layer1.2.conv3.weight", "extractor.layer1.2.bn3.weight", "extractor.layer1.2.bn3.bias", "extractor.layer1.2.bn3.running_mean", "extractor.layer1.2.bn3.running_var", "extractor.layer2.0.conv1.weight", "extractor.layer2.0.bn1.weight", "extractor.layer2.0.bn1.bias", "extractor.layer2.0.bn1.running_mean", "extractor.layer2.0.bn1.running_var", "extractor.layer2.0.conv2.weight", "extractor.layer2.0.bn2.weight", "extractor.layer2.0.bn2.bias", "extractor.layer2.0.bn2.running_mean", "extractor.layer2.0.bn2.running_var", "extractor.layer2.0.conv3.weight", "extractor.layer2.0.bn3.weight", "extractor.layer2.0.bn3.bias", "extractor.layer2.0.bn3.running_mean", "extractor.layer2.0.bn3.running_var", "extractor.layer2.0.downsample.0.weight", "extractor.layer2.0.downsample.1.weight", "extractor.layer2.0.downsample.1.bias", "extractor.layer2.0.downsample.1.running_mean", "extractor.layer2.0.downsample.1.running_var", "extractor.layer2.1.conv1.weight", "extractor.layer2.1.bn1.weight", "extractor.layer2.1.bn1.bias", "extractor.layer2.1.bn1.running_mean", "extractor.layer2.1.bn1.running_var", "extractor.layer2.1.conv2.weight", "extractor.layer2.1.bn2.weight", "extractor.layer2.1.bn2.bias", "extractor.layer2.1.bn2.running_mean", "extractor.layer2.1.bn2.running_var", "extractor.layer2.1.conv3.weight", "extractor.layer2.1.bn3.weight", "extractor.layer2.1.bn3.bias", "extractor.layer2.1.bn3.running_mean", "extractor.layer2.1.bn3.running_var", "extractor.layer2.2.conv1.weight", "extractor.layer2.2.bn1.weight", "extractor.layer2.2.bn1.bias", "extractor.layer2.2.bn1.running_mean", "extractor.layer2.2.bn1.running_var", "extractor.layer2.2.conv2.weight", "extractor.layer2.2.bn2.weight", "extractor.layer2.2.bn2.bias", "extractor.layer2.2.bn2.running_mean", "extractor.layer2.2.bn2.running_var", "extractor.layer2.2.conv3.weight", "extractor.layer2.2.bn3.weight", "extractor.layer2.2.bn3.bias", "extractor.layer2.2.bn3.running_mean", "extractor.layer2.2.bn3.running_var", "extractor.layer2.3.conv1.weight", "extractor.layer2.3.bn1.weight", "extractor.layer2.3.bn1.bias", "extractor.layer2.3.bn1.running_mean", "extractor.layer2.3.bn1.running_var", "extractor.layer2.3.conv2.weight", "extractor.layer2.3.bn2.weight", "extractor.layer2.3.bn2.bias", "extractor.layer2.3.bn2.running_mean", "extractor.layer2.3.bn2.running_var", "extractor.layer2.3.conv3.weight", "extractor.layer2.3.bn3.weight", "extractor.layer2.3.bn3.bias", "extractor.layer2.3.bn3.running_mean", "extractor.layer2.3.bn3.running_var", "extractor.layer3.0.conv1.weight", "extractor.layer3.0.bn1.weight", "extractor.layer3.0.bn1.bias", "extractor.layer3.0.bn1.running_mean", "extractor.layer3.0.bn1.running_var", "extractor.layer3.0.conv2.weight", "extractor.layer3.0.bn2.weight", "extractor.layer3.0.bn2.bias", "extractor.layer3.0.bn2.running_mean", "extractor.layer3.0.bn2.running_var", "extractor.layer3.0.conv3.weight", "extractor.layer3.0.bn3.weight", "extractor.layer3.0.bn3.bias", "extractor.layer3.0.bn3.running_mean", "extractor.layer3.0.bn3.running_var", "extractor.layer3.0.downsample.0.weight", "extractor.layer3.0.downsample.1.weight", "extractor.layer3.0.downsample.1.bias", "extractor.layer3.0.downsample.1.running_mean", "extractor.layer3.0.downsample.1.running_var", "extractor.layer3.1.conv1.weight", "extractor.layer3.1.bn1.weight", "extractor.layer3.1.bn1.bias", "extractor.layer3.1.bn1.running_mean", "extractor.layer3.1.bn1.running_var", "extractor.layer3.1.conv2.weight", "extractor.layer3.1.bn2.weight", "extractor.layer3.1.bn2.bias", "extractor.layer3.1.bn2.running_mean", "extractor.layer3.1.bn2.running_var", "extractor.layer3.1.conv3.weight", "extractor.layer3.1.bn3.weight", "extractor.layer3.1.bn3.bias", "extractor.layer3.1.bn3.running_mean", "extractor.layer3.1.bn3.running_var", "extractor.layer3.2.conv1.weight", "extractor.layer3.2.bn1.weight", "extractor.layer3.2.bn1.bias", "extractor.layer3.2.bn1.running_mean", "extractor.layer3.2.bn1.running_var", "extractor.layer3.2.conv2.weight", "extractor.layer3.2.bn2.weight", "extractor.layer3.2.bn2.bias", "extractor.layer3.2.bn2.running_mean", "extractor.layer3.2.bn2.running_var", "extractor.layer3.2.conv3.weight", "extractor.layer3.2.bn3.weight", "extractor.layer3.2.bn3.bias", "extractor.layer3.2.bn3.running_mean", "extractor.layer3.2.bn3.running_var", "extractor.layer3.3.conv1.weight", "extractor.layer3.3.bn1.weight", "extractor.layer3.3.bn1.bias", "extractor.layer3.3.bn1.running_mean", "extractor.layer3.3.bn1.running_var", "extractor.layer3.3.conv2.weight", "extractor.layer3.3.bn2.weight", "extractor.layer3.3.bn2.bias", "extractor.layer3.3.bn2.running_mean", "extractor.layer3.3.bn2.running_var", "extractor.layer3.3.conv3.weight", "extractor.layer3.3.bn3.weight", "extractor.layer3.3.bn3.bias", "extractor.layer3.3.bn3.running_mean", "extractor.layer3.3.bn3.running_var", "extractor.layer3.4.conv1.weight", "extractor.layer3.4.bn1.weight", "extractor.layer3.4.bn1.bias", "extractor.layer3.4.bn1.running_mean", "extractor.layer3.4.bn1.running_var", "extractor.layer3.4.conv2.weight", "extractor.layer3.4.bn2.weight", "extractor.layer3.4.bn2.bias", "extractor.layer3.4.bn2.running_mean", "extractor.layer3.4.bn2.running_var", "extractor.layer3.4.conv3.weight", "extractor.layer3.4.bn3.weight", "extractor.layer3.4.bn3.bias", "extractor.layer3.4.bn3.running_mean", "extractor.layer3.4.bn3.running_var", "extractor.layer3.5.conv1.weight", "extractor.layer3.5.bn1.weight", "extractor.layer3.5.bn1.bias", "extractor.layer3.5.bn1.running_mean", "extractor.layer3.5.bn1.running_var", "extractor.layer3.5.conv2.weight", "extractor.layer3.5.bn2.weight", "extractor.layer3.5.bn2.bias", "extractor.layer3.5.bn2.running_mean", "extractor.layer3.5.bn2.running_var", "extractor.layer3.5.conv3.weight", "extractor.layer3.5.bn3.weight", "extractor.layer3.5.bn3.bias", "extractor.layer3.5.bn3.running_mean", "extractor.layer3.5.bn3.running_var", "extractor.layer4.0.conv1.weight", "extractor.layer4.0.bn1.weight", "extractor.layer4.0.bn1.bias", "extractor.layer4.0.bn1.running_mean", "extractor.layer4.0.bn1.running_var", "extractor.layer4.0.conv2.weight", "extractor.layer4.0.bn2.weight", "extractor.layer4.0.bn2.bias", "extractor.layer4.0.bn2.running_mean", "extractor.layer4.0.bn2.running_var", "extractor.layer4.0.conv3.weight", "extractor.layer4.0.bn3.weight", "extractor.layer4.0.bn3.bias", "extractor.layer4.0.bn3.running_mean", "extractor.layer4.0.bn3.running_var", "extractor.layer4.0.downsample.0.weight", "extractor.layer4.0.downsample.1.weight", "extractor.layer4.0.downsample.1.bias", "extractor.layer4.0.downsample.1.running_mean", "extractor.layer4.0.downsample.1.running_var", "extractor.layer4.1.conv1.weight", "extractor.layer4.1.bn1.weight", "extractor.layer4.1.bn1.bias", "extractor.layer4.1.bn1.running_mean", "extractor.layer4.1.bn1.running_var", "extractor.layer4.1.conv2.weight", "extractor.layer4.1.bn2.weight", "extractor.layer4.1.bn2.bias", "extractor.layer4.1.bn2.running_mean", "extractor.layer4.1.bn2.running_var", "extractor.layer4.1.conv3.weight", "extractor.layer4.1.bn3.weight", "extractor.layer4.1.bn3.bias", "extractor.layer4.1.bn3.running_mean", "extractor.layer4.1.bn3.running_var", "extractor.layer4.2.conv1.weight", "extractor.layer4.2.bn1.weight", "extractor.layer4.2.bn1.bias", "extractor.layer4.2.bn1.running_mean", "extractor.layer4.2.bn1.running_var", "extractor.layer4.2.conv2.weight", "extractor.layer4.2.bn2.weight", "extractor.layer4.2.bn2.bias", "extractor.layer4.2.bn2.running_mean", "extractor.layer4.2.bn2.running_var", "extractor.layer4.2.conv3.weight", "extractor.layer4.2.bn3.weight", "extractor.layer4.2.bn3.bias", "extractor.layer4.2.bn3.running_mean", "extractor.layer4.2.bn3.running_var", "extractor.conv6.weight", "extractor.conv6.bias", "extractor.conv7.weight", "extractor.conv7.bias", "extractor.conv8.weight", "extractor.conv8.bias", "extractor.conv9.weight", "extractor.conv9.bias", "extractor.toplayer.weight", "extractor.toplayer.bias", "extractor.latlayer1.weight", "extractor.latlayer1.bias", "extractor.latlayer2.weight", "extractor.latlayer2.bias", "extractor.smooth1.weight", "extractor.smooth1.bias", "extractor.smooth2.weight", "extractor.smooth2.bias", "loc_layers.0.weight", "loc_layers.0.bias", "loc_layers.1.weight", "loc_layers.1.bias", "loc_layers.2.weight", "loc_layers.2.bias", "loc_layers.3.weight", "loc_layers.3.bias", "loc_layers.4.weight", "loc_layers.4.bias", "loc_layers.5.weight", "loc_layers.5.bias", "loc_layers.6.weight", "loc_layers.6.bias", "cls_layers.0.weight", "cls_layers.0.bias", "cls_layers.1.weight", "cls_layers.1.bias", "cls_layers.2.weight", "cls_layers.2.bias", "cls_layers.3.weight", "cls_layers.3.bias", "cls_layers.4.weight", "cls_layers.4.bias", "cls_layers.5.weight", "cls_layers.5.bias", "cls_layers.6.weight", "cls_layers.6.bias".

It seems that the pretrained model provided is not right? I am not familiar with pytorch. So please tell 
me if I make any mistakes. Thanks for your great work.

**Comment by zhengpengpeng** [comment]
By the way, I was running the pytorch branch.

**Comment by zhengpengpeng** [comment]
Here is the code: 
python3 demo_faster.py --inputlist ./examples/img-list.txt --imgpath ./examples/demo  --outputpath ./coco-minival

/home/dl/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loading SSD model..
Traceback (most recent call last):
  File "demo_faster.py", line 34, in <module>
    det_model.load_state_dict(torch.load('./models/ssd/fpnssd512_20_trained.pth'))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FPNSSD512:
 Missing key(s) in state_dict: "fpn.conv1.weight", "fpn.bn1.weight", "fpn.bn1.bias", "fpn.bn1.running_var", "fpn.bn1.running_mean", "fpn.layer1.0.conv1.weight", "fpn.layer1.0.bn1.weight", "fpn.layer1.0.bn1.bias", "fpn.layer1.0.bn1.running_var", "fpn.layer1.0.bn1...............

**Comment by zhengpengpeng** [comment]
thx...It works.

**Comment by Jeff-sjtu** [comment]
Hi, new model is released (27dd18d8a3d711a409d1513a8303427aec3e6ba1). It should fix your problem.

**Comment by zhengpengpeng** [comment]
Thx...  demo_fast.py works. By the way, demo_faster.py still no works..

**Comment by Jeff-sjtu** [comment]
`demo_faster.py` is useless now. In `demo_fast.py`, we set `--fast_inference True`.
I forgot to delete it. Sorry.
