### ISSUE TITLE
Any paper introduce the fast pose method?

### ISSUE THREAD

**Issue by deep-practice** [MVIG-SJTU/AlphaPose#770]

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your interest, they are still on the way...

**Comment by shelly-xue** [comment]
@Fang-Haoshu Have your team release the paper about FastPose? Thanks a lot!

**Comment by Fang-Haoshu** [comment]
Hi, the paper is public at http://arxiv.org/abs/2211.03375
Thanks for your interest! @deep-practice @shelly-xue
