### ISSUE TITLE
Some results are minus

### ISSUE THREAD

**Issue by zephms** [MVIG-SJTU/AlphaPose#772]
When I use the Alphapose,I found some keypoints in the json file are minus

I thought the keypoint number are the position of pixels,but where comes the minus?

![image](https://user-images.githubusercontent.com/55483184/103356266-6f4cb480-4aeb-11eb-8478-540e19729e8c.png)

**Comment by Fang-Haoshu** [comment]
Perhaps some results are invalid. Just ignore results <0. It doesn't affect other things.

**Comment by zephms** [comment]
the points are in order
the total count is 51,and if you ignore ,that means the algorithm has the unpreditable result

**Comment by zephms** [comment]
> Perhaps some results are invalid. Just ignore results <0. It doesn't affect other things.
the points are in order
the total count is 51,and if you ignore ,that means the algorithm has the unpreditable result

**Comment by 13185742215** [comment]
Also the bbox value is， I am very curious.
