### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yyyyojiro** [MVIG-SJTU/AlphaPose#773]
when I run the command "python setup.py build develop --user" , I meet error that 
/home/dell-03/anaconda3/envs/alphapose/compiler_compat/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

my enviroment setting is 
python=3.6
torch=1.1.0
torchvision=0.3.0
ubuntu=16.04
gcc= 5.5

how can I solve it? Has anyone encountered the same problem? thanks!!

**Comment by suoych** [comment]
Hi, did you solve the problem? It would be so nice if you could share how you deal with it. Thanks a lot.

**Comment by yyyyojiro** [comment]
> Hi, did you solve the problem? It would be so nice if you could share how you deal with it. Thanks a lot.

sorry, I forgot it, It has been a long time since I read this code... Maybe you can check your cuda version? or change your gcc and g++ version that matches your cuda version
