### ISSUE TITLE
 validation set the same as the test set

### ISSUE THREAD

**Issue by shelly-xue** [MVIG-SJTU/AlphaPose#779]
Hi,Is the validation set the same as the test set? It's all val2017.And test_gt_kpt.json and test_kpt.json are according to the val2017 datasets.Is that correct？Excuse me.
thank you very much!

**Comment by Fang-Haoshu** [comment]
Hi, what dataset are you mentioning

**Comment by shelly-xue** [comment]
Hi, I mean Mscoco dataset

**Comment by Fang-Haoshu** [comment]
mscoco has val2017 and test2017

**Comment by shelly-xue** [comment]
ok but i see in 256x192_res50_lr1e-3_1x.yaml  ANN is person_keypoints_val2017.json.
  TEST:
    TYPE: 'Mscoco_det'
    ROOT: './data/coco/'
    IMG_PREFIX: 'val2017'
    DET_FILE: './exp/json/test_det_yolo.json'
    ANN: 'annotations/person_keypoints_val2017.json'
