### ISSUE TITLE
Pytorch version. Visualize the results

### ISSUE THREAD

**Issue by jgallegov** [MVIG-SJTU/AlphaPose#78]
Hello, 
I am using the pythorch version, and I can't see any option to visualize the results. Please, can you tell me how to proceed with demo_fast.py?

Thank you

**Comment by 326623** [comment]
I only find a vis_image.py in the code, which visualize the bounding box. Though, I have to do some hacking for it to work.

**Comment by jgallegov** [comment]
Hello, 
then there is not any args to allow visualization¿?

**Comment by Fang-Haoshu** [comment]
Hi, we will add that soon

**Comment by Jeff-sjtu** [comment]
You can visualize the result now!
``` shell
python demo_fast.py \
--inputlist ./list-coco-minival500.txt \
--imgpath ${img_directory} \
--outputpath ./coco-minival \
--vis_res True
```
The visualization results will be saved in `outputpath`.

**Comment by jgallegov** [comment]
Hello,

I've got this error:

Loading SSD model..
Traceback (most recent call last):
  File "demo_fast.py", line 33, in <module>
    det_model.load_state_dict(torch.load('./models/ssd/ssd_coco.pth'))
  File "C:\Users\jaume\Anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 706, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FPNSSD512:
        Missing key(s) in state_dict: "fpn.bn1.num_batches_tracked", "fpn.layer1.0.bn1.num_batches_tracked", "fpn.layer1.0.bn2.num_batches_tracked", "fpn.layer1.0.bn3.num_batches_tracked", "fpn.layer1.0.downsample.1.num_batches_tracked", "fpn.layer1.1.bn1.num_batches_tracked", "fpn.layer1.1.bn2.num_batches_tracked", "fpn.layer1.1.bn3.num_batches_tracked", "fpn.layer1.2.bn1.num_batches_tracked", "fpn.layer1.2.bn2.num_batches_tracked", "fpn.layer1.2.bn3.num_batches_tracked", "fpn.layer2.0.bn1.num_batches_tracked", "fpn.layer2.0.bn2.num_batches_tracked", "fpn.layer2.0.bn3.num_batches_tracked", "fpn.layer2.0.downsample.1.num_batches_tracked", "fpn.layer2.1.bn1.num_batches_tracked", "fpn.layer2.1.bn2.num_batches_tracked", "fpn.layer2.1.bn3.num_batches_tracked", "fpn.layer2.2.bn1.num_batches_tracked", "fpn.layer2.2.bn2.num_batches_tracked", "fpn.layer2.2.bn3.num_batches_tracked", "fpn.layer2.3.bn1.num_batches_tracked", "fpn.layer2.3.bn2.num_batches_tracked", "fpn.layer2.3.bn3.num_batches_tracked", "fpn.layer3.0.bn1.num_batches_tracked", "fpn.layer3.0.bn2.num_batches_tracked", "fpn.layer3.0.bn3.num_batches_tracked", "fpn.layer3.0.downsample.1.num_batches_tracked", "fpn.layer3.1.bn1.num_batches_tracked", "fpn.layer3.1.bn2.num_batches_tracked", "fpn.layer3.1.bn3.num_batches_tracked", "fpn.layer3.2.bn1.num_batches_tracked", "fpn.layer3.2.bn2.num_batches_tracked", "fpn.layer3.2.bn3.num_batches_tracked", "fpn.layer3.3.bn1.num_batches_tracked", "fpn.layer3.3.bn2.num_batches_tracked", "fpn.layer3.3.bn3.num_batches_tracked", "fpn.layer3.4.bn1.num_batches_tracked", "fpn.layer3.4.bn2.num_batches_tracked", "fpn.layer3.4.bn3.num_batches_tracked", "fpn.layer3.5.bn1.num_batches_tracked", "fpn.layer3.5.bn2.num_batches_tracked", "fpn.layer3.5.bn3.num_batches_tracked", "fpn.layer4.0.bn1.num_batches_tracked", "fpn.layer4.0.bn2.num_batches_tracked", "fpn.layer4.0.bn3.num_batches_tracked", "fpn.layer4.0.downsample.1.num_batches_tracked", "fpn.layer4.1.bn1.num_batches_tracked", "fpn.layer4.1.bn2.num_batches_tracked", "fpn.layer4.1.bn3.num_batches_tracked", "fpn.layer4.2.bn1.num_batches_tracked", "fpn.layer4.2.bn2.num_batches_tracked", "fpn.layer4.2.bn3.num_batches_tracked".


Any idea about?

Thanks

**Comment by Jeff-sjtu** [comment]
Hi, @huangzhenjie. We will consider video-input or camera-input in future.

**Comment by Jeff-sjtu** [comment]
@jgallegov Did you use the latest code?

**Comment by Hansoluo** [comment]
@jgallegov it seems like a pytorch version problem. you can see more info in [Unexpected key(s) in state_dict](https://discuss.pytorch.org/t/solved-unexpected-key-s-in-state-dict-batches-tracked/23884)
