### ISSUE TITLE
Where can I find "validate_gt_kpt.json"?

### ISSUE THREAD

**Issue by ArchNew** [MVIG-SJTU/AlphaPose#780]
Without this file, I can't validate the model you offered. And I can't seem to find this file. Is this the same file with "instances_val2017.json" in the COCO dataset? or just the human part of the file? or you have your own version?

**Comment by shelly-xue** [comment]
Hi,have you solved this problem? I meet the same problem as you. @ArchNew

**Comment by ArchNew** [comment]
> Hi,have you solved this problem? I meet the same problem as you. @ArchNew

Yes, I solved this problem. All files in that folder are generated by Alphapose codes. We do not need to offer such a file.

**Comment by shelly-xue** [comment]
Thank you.   @@@I see... but when i use validate.py to predict my model,it still occur an error : FileNotFoundError:[Errno 2]No such file or directory: './exp/json/validate_gt_kpt.json'.
Can you tell me how to solve this? thank you very much.  @ArchNew

**Comment by ArchNew** [comment]
> Thank you. @@@i see... but when i use validate.py to predict my model,it still occur an error : FileNotFoundError:[Errno 2]No such file or directory: './exp/json/validate_gt_kpt.json'.
> Can you tell me how to solve this? thank you very much. @ArchNew

can you show the complete error information? I need to know where your error started. In theory, such an error shouldn't happen.

**Comment by shelly-xue** [comment]
hi,this is the error:
Traceback (most recent call last):
  File "./scripts/validate.py", line 233, in <module>
    gt_AP = validate_gt(m, cfg, heatmap_to_coord, opt.batch)
  File "./scripts/validate.py", line 217, in validate_gt
    with open('/exp/json/validate_gt_kpt.json', 'w') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/exp/json/validate_gt_kpt.json'

**Comment by ArchNew** [comment]
> hi,this is the error:
> Traceback (most recent call last):
> File "./scripts/validate.py", line 233, in
> gt_AP = validate_gt(m, cfg, heatmap_to_coord, opt.batch)
> File "./scripts/validate.py", line 217, in validate_gt
> with open('/exp/json/validate_gt_kpt.json', 'w') as fid:
> FileNotFoundError: [Errno 2] No such file or directory: '/exp/json/validate_gt_kpt.json'

I got it. You need to create the directory exp/json under the alphapose directory. The open operation in write mode can't create new folder or directory.

**Comment by shelly-xue** [comment]
ok, but when i run train.py, the directory exp/json has already been created. this error occurs in validate.py.

**Comment by ArchNew** [comment]
> ok, but when i run train.py, the directory exp/json has already been created. this error occurs in validate.py.

I thought you ran the validate.sh. if you run the train.py, the error message should be able to give you some clue. It should be able to trace back to the inital call.

**Comment by shelly-xue** [comment]
hi, Do you know the result of 73.3 in this code is on the test2017 dataset? if it is, how can i download the annotations of test2017?  thank you very much.

**Comment by shelly-xue** [comment]
hi, Do you know the result of 73.3 in this code is on the test2017 dataset? if it is, how can i download the annotations of test2017? thank you very much. @ArchNew
