### ISSUE TITLE
error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by yeonchae** [MVIG-SJTU/AlphaPose#781]
Hi guys, 
first, thanks so much for visiting this issue, and thanks for sharing this useful git. 
I've just set the environment through server computer, and already converted the PATH. 
Finally, with command: 
$ python setup.py build

I've got the errors as follows. 

running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.6/alphapose
running build_ext
building 'detector.nms.soft_nms_cpu' extension
Emitting ninja build file /home/yeonchae/anaconda3/envs/alphapose/AlphaPose/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/yeonchae/anaconda3/envs/alphapose/compiler_compat -L/home/yeonchae/anaconda3/envs/alphapose/lib -Wl,-rpath=/home/yeonchae/anaconda3/envs/alphapose/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/yeonchae/anaconda3/envs/alphapose/AlphaPose/build/temp.linux-x86_64-3.6/detector/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.6/detector/nms/soft_nms_cpu.cpython-36m-x86_64-linux-gnu.so

collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
compilation terminated.
error: command 'g++' failed with exit status 1

-------
Actually, I have no idea with the g++ error, since gcc version and cuda seems ok.

(alphapose) yeonchae@snucem:~/anaconda3/envs/alphapose/AlphaPose$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by connor-john** [comment]
What version of Linux, Cuda and Pytorch?

This might be similar to my issue #782

**Comment by yeonchae** [comment]
> What version of Linux, Cuda and Pytorch?
> 
> This might be similar to my issue #782


thanks a lot ! After changing CUDA version to 9,0 and fit all version compatible, 
all works!

Thanks a lot.

**Comment by Fang-Haoshu** [comment]
cool
