### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x01'.

### ISSUE THREAD

**Issue by yeonchae** [MVIG-SJTU/AlphaPose#783]
Hello, 
I've got the problem as below:
I'm on the stage of modeling process, and finally run demo_inference.py
The model I used is fast_res50_256x192.pth and I've already downloaded yolo files.
I've got the error with pickle and full text of error is as below. 

Any help would be greatly appreciated

(base) yeonchae@snucem:~/anaconda3/envs/alphapose/AlphaPose$ python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --save_img
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 13, in <module>
    from detector.apis import get_detector
ModuleNotFoundError: No module named 'detector'
(base) yeonchae@snucem:~/anaconda3/envs/alphapose/AlphaPose$ conda activate alphapose
(alphapose) yeonchae@snucem:~/anaconda3/envs/alphapose/AlphaPose$ python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --save_img
Loading YOLO model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
Process Process-2:
Traceback (most recent call last):
  File "/home/yeonchae/anaconda3/envs/alphapose/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yeonchae/anaconda3/envs/alphapose/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yeonchae/anaconda3/envs/AlphaPose/alphapose/utils/detector.py", line 223, in image_detection
    dets = self.detector.images_detection(imgs, im_dim_list)
  File "/home/yeonchae/anaconda3/envs/AlphaPose/detector/yolo_api.py", line 91, in images_detection
    self.load_model()
  File "/home/yeonchae/anaconda3/envs/AlphaPose/detector/yolo_api.py", line 49, in load_model
    self.model.load_weights(self.model_weights)
  File "/home/yeonchae/anaconda3/envs/AlphaPose/detector/yolo/darknet.py", line 488, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: shape '[255, 256, 1, 1]' is invalid for input of size 64796
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 182, in <module>
    pose_model.load_state_dict(torch.load(args.checkpoint, map_location=args.device))
  File "/home/yeonchae/anaconda3/envs/alphapose/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/yeonchae/anaconda3/envs/alphapose/lib/python3.7/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
_pickle.UnpicklingError: invalid load key, '\x01'.

**Comment by hongsukchoi** [comment]
may be there's session files for the model checkpoint which have dot or underbar in front of file names.
You can check them in linux directory by typing ls -la. Erase them and try again

**Comment by yeonchae** [comment]
Thanks a lot for your comment. 

Referring to your comment, I've checked directories and here's the list below. 

(alphapose) yeonchae@snucem:~/anaconda3/envs/alphapose/AlphaPose$ ls -la
total 116
drwxrwxr-x 14 yeonchae yeonchae  4096 Jan 14 15:11 .
drwxrwxr-x 11 yeonchae yeonchae  4096 Jan 14 15:10 ..
drwxrwxr-x  3 yeonchae yeonchae  4096 Jan 14 15:10 .eggs
drwxrwxr-x  8 yeonchae yeonchae  4096 Jan 14 15:09 .git
-rw-rw-r--  1 yeonchae yeonchae  1394 Jan 14 15:09 .gitignore
-rw-rw-r--  1 yeonchae yeonchae 34192 Jan 14 15:09 LICENSE
-rw-rw-r--  1 yeonchae yeonchae  7117 Jan 14 15:09 README.md
drwxrwxr-x  6 yeonchae yeonchae  4096 Jan 14 15:35 alphapose
drwxrwxr-x  2 yeonchae yeonchae  4096 Jan 14 15:25 alphapose.egg-info
drwxrwxr-x  4 yeonchae yeonchae  4096 Jan 14 15:10 build
drwxrwxr-x  6 yeonchae yeonchae  4096 Jan 14 15:09 configs
drwxrwxr-x  7 yeonchae yeonchae  4096 Jan 14 15:35 detector
drwxrwxr-x  3 yeonchae yeonchae  4096 Jan 14 15:09 docs
drwxrwxr-x  4 yeonchae yeonchae  4096 Jan 14 15:35 examples
drwxrwxr-x  2 yeonchae yeonchae  4096 Jan 14 15:52 pretrained_models
drwxrwxr-x  2 yeonchae yeonchae  4096 Jan 14 15:09 scripts
-rw-rw-r--  1 yeonchae yeonchae    66 Jan 14 15:09 setup.cfg
-rw-rw-r--  1 yeonchae yeonchae  7088 Jan 14 15:09 setup.py
drwxrwxr-x  7 yeonchae yeonchae  4096 Jan 14 15:35 trackers


Actually I have no idea what's the problem,

Thanks a lot again.

**Comment by Fang-Haoshu** [comment]
try redownload the file

**Comment by Fang-Haoshu** [comment]
I guess the pth file is corrupted during download.

**Comment by KGgggggggggwp** [comment]
bro have u ever solved this problem?
Now i am facing a problem just like you,i get a folder ,and all the files are .pt ,when i try to open them,they will shou me an error just like you show,UnpicklingError: invalid load key, '\x01'.
i really want to know how to solve the problem , it make me so puzzle!
