### ISSUE TITLE
Getting Broken pipe error when testing the videos

### ISSUE THREAD

**Issue by akshaykadam771** [MVIG-SJTU/AlphaPose#787]
I am getting broken pipe error when i testing with videos.as @Fang-Haoshu suggested to set --qsize=128 , i did that but again i am getting same issue.

**Comment by Fang-Haoshu** [comment]
Hi, what is your PC configuration

**Comment by akshaykadam771** [comment]
I was using colab. I have just add one parameter  "--sp" & now it's working fine

**Comment by akshaykadam771** [comment]
I am getting one more error. if in images/video if there is no human present then it is giving error   " write_image() missing 1 positional argument 'im_name' "   & it will stuck there.

**Comment by Fang-Haoshu** [comment]
Can you provide the details of the error?

**Comment by akshaykadam771** [comment]
This error i was getting when i am testing with videos, after this everything will stuck

![alphapose_error_missing_imname](https://user-images.githubusercontent.com/62059604/107383850-694ce900-6b17-11eb-87d0-73923fd2aba9.png)

**Comment by Fang-Haoshu** [comment]
Hi, for the latest code, the line 99 in writer.py is not the line in this error. Did you modify the code? Or are you using an older version? You can update to the latest code by `git pull origin master`

**Comment by akshaykadam771** [comment]
Yes, i have little bit modified the writer.py code hence it is showing on line 99 otherwise in official code it was on line no.94.  but i didn't made any changes which can affect this function on line 94

**Comment by akshaykadam771** [comment]
Actually i am using Alphapose for Suspicious-Activity-Detection. this is the project which i did https://github.com/akshaykadam771/Suspicious-Activity-Detection-Using-Pose-Estimation    It is working fine as long as person is available in image/frame but when there is no person available in image/frame then it shoots  above error.

**Comment by Fang-Haoshu** [comment]
Hi, you modified the write_image() function:https://github.com/akshaykadam771/Suspicious-Activity-Detection-Using-Pose-Estimation/blob/main/alphapose/utils/writer.py#L163
So you miss an argument. You need to pad it
