### ISSUE TITLE
FastPose paper

### ISSUE THREAD

**Issue by wawaa** [MVIG-SJTU/AlphaPose#788]
Hi~Very thanks for your open source. Have your team release the paper about FastPose? Thanks a lot!

**Comment by Fang-Haoshu** [comment]
Hi, still not yet😂 We are still working on that.

**Comment by Fang-Haoshu** [comment]
Hi, still not yet😂 We are still working on that.

**Comment by wawaa** [comment]
> Hi, still not yet😂 We are still working on that.

OK~

**Comment by Fang-Haoshu** [comment]
Hi, the paper is public at http://arxiv.org/abs/2211.03375
Thanks for your interest! @wawaa

**Comment by wawaa** [comment]
Got it. Very great job. Thx!

**Comment by wawaa** [comment]
> Hi, the paper is public at http://arxiv.org/abs/2211.03375 Thanks for your interest! @wawaa


Got it. Very great job. Thx!
