### ISSUE TITLE
Error when I run the pose_track demo.

### ISSUE THREAD

**Issue by Abalizzw** [MVIG-SJTU/AlphaPose#789]
My compiling env is Ubuntu16.04 on the server.
I tried both PyTorch version 1.1 and 1.5+, but when I run the pose tracking demo, still occurs this error.

  File "scripts/demo_inference.py", line 181
    print(f'Loading pose model from {args.checkpoint}...')
                                                        ^
SyntaxError: invalid syntax

I am looking forward to someone's reply, thank you.

**Comment by Fang-Haoshu** [comment]
python version is low. You can also delete that line by yourself

**Comment by Fang-Haoshu** [comment]
fixed
