### ISSUE TITLE
Calling Alphapose from a custom script

### ISSUE THREAD

**Issue by rirri93** [MVIG-SJTU/AlphaPose#790]
Hi!
I created a run.py script inside the root of AlphaPose. Now I imported demo_inference.py as ap using this script: 
`def import_module_by_path(path):
    name = os.path.splitext(os.path.basename(path))[0]
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod`

Then, in demo_inference.py I substituted `if __name__ == "__main__":` with `def startAlphapose():` and in run.py I wrote `ap.StartAlphapose()`.

Now I got this error: 

`File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory` 

What does it mean?

**Comment by Fang-Haoshu** [comment]
Sorry, I am not sure. You can use demo_api.py for calling, but it does not support multi-processing.
