### ISSUE TITLE
Output ID-Track mistake

### ISSUE THREAD

**Issue by hsauod** [MVIG-SJTU/AlphaPose#795]
Hi MVIG_SJTU team, thank you for your great work!

There are 2 people in my video, but in the JSON file, the idx is always 0.(The output video is OK)
 I'm using this command:
./scripts/inference.sh ${CONFIG} ${CHECKPOINT} ${VIDEO_NAME} ${OUTPUT_DIR}  --pose_track
How can I solve this problem?
Thank you very much.

**Comment by Fang-Haoshu** [comment]
Hi, according to here: https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/writer.py#L148
The output video is rendered according to the final result. Thus the json should be correct. Can you check it again?

**Comment by hsauod** [comment]
@Fang-Haoshu Hi Fang, thank you for your prompt response. I will check it again.
