### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sid0407** [MVIG-SJTU/AlphaPose#799]

**Comment by mishamishra** [comment]
You need to make a few changes to the cocoeval.py file. I successfully trained and ran validate.py for coco_wholebody, but we can't run demo_inferece.py on the trained model as the demo file uses DATASET.TRAIN and the train annotation file is following the COCO format [see link](https://github.com/jin-s13/COCO-WholeBody/blob/master/data_format.md). 
According to this repo code, len(keypoints) should be 133 in the annotation file, but COCO has divided these 133 keypoints into different types (see the above link). So when I run the demo_inference file, I get only 17 body key points on the person labeled as "keypoints" in the COCO annotation file.
