### ISSUE TITLE
No module named tqdm

### ISSUE THREAD

**Issue by 91Eric** [MVIG-SJTU/AlphaPose#8]
when i run the cmd `./run.sh --indir examples/demo/ --outdir examples/results/ --vis`, I got error 
`
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 30, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm
`
But I have installed tqdm,I don't know what's wrong i did   Thanks

**Comment by Fang-Haoshu** [comment]
maybe you want to try pip2 install tqdm if you are using python 2.7, and pip3 for python3

**Comment by YuliangXiu** [comment]
tqdm is a python module to display processbar in terminal, you can find the installation in https://pypi.python.org/pypi/tqdm
