### ISSUE TITLE
Type problem

### ISSUE THREAD

**Issue by divastar** [MVIG-SJTU/AlphaPose#800]
Hi . I am using a newest pytorch version .
And I am having this typing problem did not managed to solve yet.
Someone can help?
File "C:\pose estimation\AlphaPose\fn.py", line 214, in vis_frame
    polygon = cv2.ellipse2Poly((int(mX),int(mY)), (int(length/2), stickwidth), int(angle), 0, 360, 1)TypeError: only integer tensors of a single element can be converted to an index

thank you

**Comment by divastar** [comment]
I tried np.int64( casting :
mX = np.int64(np.mean(X))
                mY = np.int64(np.mean(Y))
                length = np.int64(np.int64(((Y[0] - Y[1]) ** 2 + (X[0] - X[1]) ** 2) ** 0.5))
                angle = np.int64(math.degrees(math.atan2(Y[0] - Y[1], X[0] - X[1]))/2)
                stickwidth = np.int64((kp_scores[start_p] + kp_scores[end_p]) + 1)
                # polygon = cv2.ellipse2Poly((int(mX),int(mY)), (int(length/2), stickwidth), int(angle), 0, 360, 1)
                polygon = cv2.ellipse2Poly((mX,mY), (length, stickwidth), int(angle), 0, 360, 1)


doesn't help

**Comment by Fang-Haoshu** [comment]
Hi, did you mange to solve it?

**Comment by divastar** [comment]
No. But it is still works without..

**Comment by Fang-Haoshu** [comment]
It is weird... You can use the --vis_fast flag to use simple drawing, so you wont meet this problem
