### ISSUE TITLE
shape problem when i convert it to onnx format

### ISSUE THREAD

**Issue by wwdok** [MVIG-SJTU/AlphaPose#803]
Hi MVIG-SJTU, i have converted the fast_res50_256x192.pth to onnx format, but i found i problem, that is the input and output shape contain the size of person number : torch.Size([n, 3, 256, 192]), n is the num of persons in one image. You know, in real world, the number of person is varying, we can not fix number.
Could you give me some inspiration to deal with this problem ? thanks !
Following screenshot show the two results with n = 1 and n =5 :
![image](https://user-images.githubusercontent.com/43233772/106874331-6c5b6a00-6710-11eb-8925-2973cbdbef48.png)
![image](https://user-images.githubusercontent.com/43233772/106874053-18e91c00-6710-11eb-9e3c-d965c0730e21.png)

**Comment by wwdok** [comment]
Now i use a workaround, that is fixed n to 1, then use for loop to traverse all persons in python script

**Comment by Fang-Haoshu** [comment]
I guess fix it to a number and then use padding or looping at outside is a solution.
