### ISSUE TITLE
In training pose estimation, why don't you use half-body augmentation?

### ISSUE THREAD

**Issue by ArchNew** [MVIG-SJTU/AlphaPose#804]
I noticed that you used most of the data augmentation strategies that HRNet used. I'm curious that why don't use half-body augmentation in training? Based on experiments I did on Simple Baselines and HRNet, it can bring a 0.7~1 percent increase on the COCO dataset. 

Is it because fastpose-based models do not have noticeable gain with this strategy?

**Comment by Fang-Haoshu** [comment]
Hi, we also used in. In the cfg file, the prob is set to 0.3
