### ISSUE TITLE
关于输出的关键点信息

### ISSUE THREAD

**Issue by lijinyong0618** [MVIG-SJTU/AlphaPose#808]
从论文中得知输出的关键点信息应该是18个，但是我运行demo的结果只有17个关键点，请问是为什么？
这些数据的含义是什么？最后score的含义是什么

- [{"image_id": "img_directory\\1.png", "category_id": 1,
  "keypoints":
  [119.63655090332031, 57.98761749267578, 0.7912510633468628,
    123.6702880859375, 49.920127868652344, 0.7652539014816284,
    113.58592224121094, 51.9370002746582, 0.8315414190292358,
    133.75465393066406, 47.903255462646484, 0.7568730115890503,
    105.5184326171875, 53.9538688659668, 0.49982956051826477,
    151.90650939941406, 72.10572814941406, 0.8309847116470337,
    103.50157165527344, 80.1732177734375, 0.7395451664924622,
    186.19334411621094, 92.27445220947266, 0.8389726877212524,
    73.24847412109375, 108.40943145751953, 0.8772179484367371,
    182.1595916748047, 126.56128692626953, 0.8335634469985962,
    95.43408203125, 136.64564514160156, 0.8256604671478271,
    155.94024658203125, 144.71315002441406, 0.660769522190094,
    123.6702880859375, 146.73001098632812, 0.6661599278450012,
    166.0246124267578, 201.18556213378906, 0.7439570426940918,
    133.75465393066406, 205.2193145751953, 0.7625607252120972,
    182.1595916748047, 253.624267578125, 0.7337401509284973,
    151.90650939941406, 255.64112854003906, 0.7526907324790955], "score": 2.8521335124969482} ]

**Comment by Fang-Haoshu** [comment]
please refer to the format.md page in our doc/
