### ISSUE TITLE
run ./install.sh error

### ISSUE THREAD

**Issue by zjbabylove** [MVIG-SJTU/AlphaPose#81]
when I run ./install.sh , I encounter an error: 
Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
-- you may want to run as a privileged user or use your local tree with --local.

if I run ./install.sh like this:   sudo ./install.sh, then I encounter another error:
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip'
Installing https://rocks.moonscript.org/hdf5-2.0.0-1.src.rock...
Using https://rocks.moonscript.org/hdf5-2.0.0-1.src.rock... switching to 'build' mode
Warning: variable CFLAGS was not passed in build_variables
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-4423/lua-hdf5/gcc-lua'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-4423/lua-hdf5/gcc-lua/gcc'
gcclua-config.h:1:24: fatal error: gcc-plugin.h: 没有那个文件或目录
compilation terminated.
gcc -c -o gcclua.o -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include -fPIC  -O2 -Wall -Wformat-security -I/usr/include/lua5.1 gcclua.c
gcclua.c:7:24: fatal error: gcc-plugin.h: 没有那个文件或目录
compilation terminated.
Makefile:29: recipe for target 'gcclua.o' failed
make[2]: *** [gcclua.o] Error 1

**Comment by Fang-Haoshu** [comment]
no response, close.

**Comment by whitelok** [comment]
It is ok for me after running: `apt install gcc-6-plugin-dev`

**Comment by Fang-Haoshu** [comment]
Thanks! @whitelok
