### ISSUE TITLE
File `transform.json` not provided

### ISSUE THREAD

**Issue by lizuoyue** [MVIG-SJTU/AlphaPose#82]
Dear MVIG@SJTU,

Recently I want to train a human detector based on your code. However, I cannot manage to run the training stripts provided. The error comes from a not provided `transform.json` file.

Details:
In file `/AlphaPose/human-detection/lib/datasets/coco.py`, line 49-51, the code is shown as below.
```
import json
f=open('/SSD3/crh/tf-faster-rcnn/data/coco/annotations/transform.json','r')
self.transform=json.load(f)
```
It seems like reading an absolute-path file `transform.json`, and I cannot find any information about this file. The variable `self.transform` is also used in line 92-108.
```
def image_path_from_index(self, index):
    """
    Construct an image path from the image's "index" identifier.
    """
    # Example image path for index=119993:
    #   images/train2014/COCO_train2014_000000119993.jpg
    if index>1000000:
        file_name=self.transform[str(index)]+'.jpg'
    else:
        file_name = ('COCO_' + self._data_name + '_' +
                    str(index).zfill(12) + '.jpg')
    
    image_path = osp.join(self._data_path, 'images',
                            self._data_name, file_name)
    assert osp.exists(image_path), \
        'Path does not exist: {}'.format(image_path)
    return image_path
```
I guess the file `transform.json` stores paths of some other images but I am not really sure. Could you explain a bit more about this file and how is it working during training?

Thank you very much!

Regards,
Zuoyue

**Comment by Fang-Haoshu** [comment]
Hi, for the training pipeline, you can refer to the original repo here https://github.com/endernewton/tf-faster-rcnn

**Comment by lizuoyue** [comment]
Hi, the original repo does not use Soft NMS and we want to reproduce the performance of AlphaPose. Could you explain a bit more about the `transform.json` file? It does help to our reproduction.

**Comment by lizuoyue** [comment]
@Fang-Haoshu Hello, is it possible to explain a bit more?

**Comment by Fang-Haoshu** [comment]
Hi, the soft NMS is just a post-processing and needs no training. You can add it to the original repo. To reproduce the performance of AlphaPose, retrain the human detector does not help to that. We did not train the human detector.
But if you hope to train it,  I guess @crh19970307 can help you.
