### ISSUE TITLE
validate_gt and validate use the same ann_file

### ISSUE THREAD

**Issue by shelly-xue** [MVIG-SJTU/AlphaPose#822]
您好，我在train.py文件中发现，函数validate和validate_gt在计算res时，函数evaluate_mAP的参数ann_file传的值是相同的，都是.../VAL.ANN。但是validate所用的数据集是测试集，对应的ann_file不应该是.../test.ann吗？期待您的回复。

**Comment by Fang-Haoshu** [comment]
没有 这两个都是validation集，一个是gt box一个是detection box
