### ISSUE TITLE
Setup Issue: Sandbox Violation

### ISSUE THREAD

**Issue by NiccoloCavagnero** [MVIG-SJTU/AlphaPose#825]
########

error: Setup script exited with error: SandboxViolation: mkdir('/Users/neikos/Library/Caches/com.apple.python/private/var/folders/8m/s5gth4hn7nb0pwq6bt015b3w0000gn/T/easy_install-cugtmvt1', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand. Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

########

I'm trying to run setup.py but I get this error, how can I solve it?

**Comment by czkyx** [comment]
me,too 
`error: Setup script exited with error: SandboxViolation: mkdir('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\easy_install-pzhrecod\\easydict-1.9\\build', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.`

**Comment by czkyx** [comment]
me,too 
`error: Setup script exited with error: SandboxViolation: mkdir('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\easy_install-pzhrecod\\easydict-1.9\\build', 511) {}
The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.
This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.`
