### ISSUE TITLE
codec id 27: Encoder not found

### ISSUE THREAD

**Issue by JosePeeterson** [MVIG-SJTU/AlphaPose#826]
Hi, 
       This error was encountered before but the solutions suggested is not working for me. 

command to run video of 256x192 resolution of length 15 seconds. (I also tried to add --sp flag below but I get the error, "Illegal instruction (core dumped)" )

`(alphapose) peeterson@ashutosh:~/Desktop/AlphaPose$ python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --video examples/in_vid/Hospital-15fps.mp4 --outdir examples/out_vid --save_video --qsize 100
`

It gets stuck below and does not move.
`Loading YOLO model..
Loading pose model from pretrained_models/halpe26_fast_res50_256x192.pth...
  0%|                                                                                                                        | 0/230 [00:00<?, ?it/s]Could not find encoder for codec id 27: Encoder not found
Try to use other video encoders...
`

My environment setup is

`
_libgcc_mutex             0.1                        main  
alphapose                 0.3.0+ff22ba9             dev_0    <develop>
blas                      1.0                         mkl  
ca-certificates           2021.1.19            h06a4308_1  
certifi                   2020.12.5        py36h06a4308_0  
cffi                      1.14.5           py36h261ae71_0  
chardet                   4.0.0                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cycler                    0.10.0                   py36_0  
cython                    0.29.22                  pypi_0    pypi
cython-bbox               0.1.3                    pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
easydict                  1.9                      pypi_0    pypi
expat                     2.2.10               he6710b0_2  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.67.4               h36276a3_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
intel-openmp              2020.2                      254  
jpeg                      9b                   h024ee3a_2  
jsonpatch                 1.31                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
kiwisolver                1.3.1            py36h2531618_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.3                h2531618_0  
matplotlib                3.3.4            py36h06a4308_0  
matplotlib-base           3.3.4            py36h62a2d02_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.3.0            py36h54f3939_0  
mkl_random                1.1.1            py36h0573a6f_0  
munkres                   1.1.4                    pypi_0    pypi
natsort                   7.1.1              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2           py36hff7bd54_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
openssl                   1.1.1j               h27cfd23_0  
pcre                      8.44                 he6710b0_0  
pillow                    8.1.2            py36he98fc37_0  
pip                       21.0.1           py36h06a4308_0  
protobuf                  3.15.5                   pypi_0    pypi
pyaml                     20.4.0                   pypi_0    pypi
pycocotools               2.0.0                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py36h05f1152_2  
python                    3.6.13               hdb3f193_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
pytorch                   1.1.0           cuda100py36he554f03_0  
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                52.0.0           py36h06a4308_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0           py36h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tensorboardx              2.1                      pypi_0    pypi
terminaltables            3.1.0                    pypi_0    pypi
timm                      0.1.20                   pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.3.0           cuda100py36h72fc40a_0  
tornado                   6.1              py36h27cfd23_0  
tqdm                      4.59.0                   pypi_0    pypi
urllib3                   1.26.3                   pypi_0    pypi
visdom                    0.1.8.9                  pypi_0    pypi
websocket-client          0.58.0                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  

`

I am using cuda toolkit 11.2 

`(alphapose) peeterson@ashutosh:~/Desktop/AlphaPose$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
`

GPU

`
(alphapose) peeterson@ashutosh:~/Desktop/AlphaPose$ nvidia-smi
Wed Mar 10 12:46:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0 Off |                  N/A |
| 36%   33C    P8    22W / 175W |    233MiB /  7982MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1385      G   /usr/lib/xorg/Xorg                155MiB |
|    0   N/A  N/A      1768      G   /usr/bin/gnome-shell               34MiB |
|    0   N/A  N/A      1770      G   ...mviewer/tv_bin/TeamViewer        1MiB |
|    0   N/A  N/A      5487      G   ...gAAAAAAAAA --shared-files       38MiB |
+-----------------------------------------------------------------------------+
`

Thanks.

**Comment by JosePeeterson** [comment]
`python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --video examples/in_vid/Hospital_15fps.m4v --outdir examples/out_vid --save_video --qsize 100 --vis_fast
`

I am able to run the above code using .m4v file instead of .mp4 file. So you might have to convert first. I am also able to use video size bigger than 256 x 192. I am using a video size of 1920x1080. 

It is taking about 4 mins to process 15sec video running at 15 fps even after I used --vis_fast. 

Any suggestion to speed it up? I want real-time detection of video of this resolution. 

Thanks.

**Comment by Fang-Haoshu** [comment]
Hi. Encoder not found is not a bug, but a warning.
If you want to speed up, disable visualization by not using save_video or save_img. Rendering takes a lot of time
