### ISSUE TITLE
Question about the pre-trained models

### ISSUE THREAD

**Issue by taotaoorange** [MVIG-SJTU/AlphaPose#83]
Hi, Thanks for sharing the code and pre-trained models. Would you please give a bit more information about how the pre-trained models were trained? Like what data were used for training etc?

**Comment by Jeff-sjtu** [comment]
Detection model is the official `yolo_v3` model. Pose model training follows the pipeline from [RMPE](https://arxiv.org/abs/1612.00137), with `coco` + `mpii` data.
