### ISSUE TITLE
加了DPG_MILESTONE后，loss上升

### ISSUE THREAD

**Issue by shelly-xue** [MVIG-SJTU/AlphaPose#831]
你好，训练时，我在准确率达到90后，加入DPG，发现loss上升一下，然后开始下降；准确率也相应降低，然后升高，最终准确率稳定值也没有降低那会的准确率值大。请问这是什么原因呢？我用的自己的数据集。如果不加DPG，对模型影响大吗？希望能帮忙解答一下。谢谢

**Comment by Fang-Haoshu** [comment]
你好，这个是data augmentation，可以使网络更适应现实情况下的使用与detector的噪声，总体使用效果会更好。
