### ISSUE TITLE
Problem in visualization.

### ISSUE THREAD

**Issue by YuQi9797** [MVIG-SJTU/AlphaPose#835]
作者您好，请问是否有提供骨架可视化的代码? 
同时，想请教作者一下，若我给的图像所见区域，不包含关键点的部位。 那么是如何进行可视化，使得不存在的点不打出来。 只可视化模型检测出的点。 （我看很多论文输出，既是关节点个数。但有些关节点其实图上并看不见的）

**Comment by Fang-Haoshu** [comment]
只可视化骨架，你可以修改alphapose/utils/vis.py的代码
