### ISSUE TITLE
 Using different detectors to train the model

### ISSUE THREAD

**Issue by 13281306705** [MVIG-SJTU/AlphaPose#837]
Hello, how should I call the target detection model in the detector file (such as Yolo, effdet) and use different detectors to train the model.
Looking forward to your reply

**Comment by fresh382227905** [comment]
have you solved this problem?

**Comment by 13281306705** [comment]
> have you solved this problem?

Sorry I have not sovle it

**Comment by Fang-Haoshu** [comment]
Hi, in fact it does not affect the performance. Our framework is robust to detector variance since we used strong data augmentation. So you can directly train the model with our training script.

**Comment by dekathomas** [comment]
Is alphapose training pipeline use yolo for human detector? What I know from the code is it only use ResNet for receiving the input image and do some transformations. But I don't really know the full pipeline. What magic is done on its pipeline.

Really need enlightment from you guys @Fang-Haoshu @Jeff-sjtu 🙏🙏🙏
