### ISSUE TITLE
How to evaluate the model on MPII and COCO?

### ISSUE THREAD

**Issue by taotaoorange** [MVIG-SJTU/AlphaPose#84]
Hi,

Please how can I evaluate the (pre-trained) models on MPII and COCO? And how to get the final mAP? Thanks.

**Comment by Fang-Haoshu** [comment]
Hi, for MPII evaluation, please refer to https://github.com/MVIG-SJTU/RMPE, for COCO, please refer to the COCO website

**Comment by GloryyrolG** [comment]
Hi @Fang-Haoshu , thx. May I ask if you have any MPII mAP/PCKh evaluation pytorch code?
