### ISSUE TITLE
storage has wrong size: expected 0 got 65536

### ISSUE THREAD

**Issue by Json0926** [MVIG-SJTU/AlphaPose#844]
when I run'
python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x-dcn.yaml --checkpoint pretrained_models/fast_dcn_res50_256x192.pth --indir examples/demo/'
I got this 'RuntimeError: storage has wrong size: expected 0 got 17' error
anybody know why?

**Comment by Fang-Haoshu** [comment]
Not sure what's the problem. Perhaps you can re-download the models and see if the problem occurs again
