### ISSUE TITLE
imght and imgwidth in coco_det.py

### ISSUE THREAD

**Issue by shelly-xue** [MVIG-SJTU/AlphaPose#845]
hi, when i debug in coco_det.py which load image, I see image's shape is [1080.1920,3]. So if the code 
imght, imgwidth = image.shape[1],image.shape[2] 
and imght is 1920, imgwidth is 3.That is right? Because I think the code should be 
imght, imgwidth = image.shape[0],image.shape[1] .
Thank you!

**Comment by Fang-Haoshu** [comment]
Hi, you are right. I will correct it.
Luckily it seems the ht and width is not used yet.

**Comment by samymdihi** [comment]
@shelly-xue Did you notice a performance improve with this modification ?
