### ISSUE TITLE
使用pycharm无法生成视频

### ISSUE THREAD

**Issue by Stig-Huang** [MVIG-SJTU/AlphaPose#851]
将args.save_video = True放置在video_demo文件中后运行
显示如下错误
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
  1%|          | 1/97 [00:00<01:00,  1.59it/s]Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\anaconda\envs\Ap\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\anaconda\envs\Ap\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Ap\AlphaPose\dataloader.py", line 675, in update
    img = vis_frame(orig_img, result)
  File "D:\Ap\AlphaPose\fn.py", line 213, in vis_frame
    polygon = cv2.ellipse2Poly((int(mX),int(mY)), (int(length/2), stickwidth), int(angle), 0, 360, 1)
TypeError: only integer tensors of a single element can be converted to an index
 92%|█████████▏| 89/97 [00:10<00:00,  8.18it/s]
Process finished with exit code -1

json文件正常导出但视频文件输出后仅几kb且时长几乎为0
望解答谢谢

**Comment by Fang-Haoshu** [comment]
可以使用vis_fast的flag避免该问题

**Comment by Stig-Huang** [comment]
已开启vis_fast的flag后，仍然产生此问题

**Comment by Stig-Huang** [comment]
> 可以使用vis_fast的flag避免该问题

开启flag后仍然显示此问题

**Comment by Stig-Huang** [comment]
TypeError: Can't parse 'axes'. Sequence item with index 1 has a wrong type
更换编译器后报出此错误
仍然只输出json文件，无法输出视频

**Comment by tomisalready** [comment]
modify to this：polygon = cv2.ellipse2Poly((int(mX),int(mY)), (int(length/2), int(stickwidth)), int(angle), 0, 360, 1)

add int convert to stickwidth.
