### ISSUE TITLE
training

### ISSUE THREAD

**Issue by RCpengnan** [MVIG-SJTU/AlphaPose#852]
Hello, sorry to bother you, I want to retrain the 26 key points, I want to ask how to generate the following files, thank you!
![image](https://user-images.githubusercontent.com/74439931/117267443-d8bd4500-ae88-11eb-8418-352864a5b026.png)

**Comment by xiaochenwise** [comment]
Hello, I met the same problem, have you solved it now?

**Comment by RCpengnan** [comment]
> Hello, I met the same problem, have you solved it now?

I used the coco2017 datasets and json files.  pth file will be generated by training

**Comment by xiaochenwise** [comment]
So how did you get the map of the 26 key points? PycocoTools can only find maps of 17 key points

**Comment by RCpengnan** [comment]
> So how did you get the map of the 26 key points? PycocoTools can only find maps of 17 key points



> So how did you get the map of the 26 key points? PycocoTools can only find maps of 17 key points

I only need 19 points, so I modified Coco's JSON file to add the coordinates of the two points.
