### ISSUE TITLE
Cuda version

### ISSUE THREAD

**Issue by divastar** [MVIG-SJTU/AlphaPose#869]
Hi . thank you for your code.
Should I only work with cuda 10.1? or cuda 11 will work too?
thank you

**Comment by samymdihi** [comment]
cuda 11.3 works. I tried it on windows with the latest versions of pytorch etc. You just need to use the branch that was made for pytorch >=1.5

**Comment by Fang-Haoshu** [comment]
Hi, cuda version is not specified, as long as it compatible with your pytorch.
