### ISSUE TITLE
Problem in the use of gpu/cpu

### ISSUE THREAD

**Issue by samymdihi** [MVIG-SJTU/AlphaPose#870]
I have a problem regarding the use of cpu/gpu. I have really good cpu/gpu but when I run demo_inference I reach 100% of the CPU all the time during the process and only 12% of the gpu is used. Do you know how I could increase the use of the gpu ? Is anyone facing the same issue ? 

I am using the "support for pytorch 1.5.0" #592 branch, with cuda 11.3, python 3.9, pytorch 1.8.1, torchvision 0.9.1

**Comment by fortminors** [comment]
Same here. Have you managed to solve it?

**Comment by Fang-Haoshu** [comment]
Hi, seems it currently consumes a lot of CPU in order to speed up. We haven't found a good way to solve it yet.
