### ISSUE TITLE
为什么大量的bbox预测值输出是负的？代表什么意思？输出文件json中的bbox各位数值代表什么意思？

### ISSUE THREAD

**Issue by 13185742215** [MVIG-SJTU/AlphaPose#872]
为什么大量的bbox预测值输出是负的？代表什么意思？输出文件json中的bbox各位数值代表什么意思？

**Comment by hongyaohongyao** [comment]
> 为什么大量的bbox预测值输出是负的？代表什么意思？输出文件json中的bbox各位数值代表什么意思？

据我观察，目标检测结果超出边界框是可能的，手动限制一下把

**Comment by Fang-Haoshu** [comment]
是的，@hongyaohongyao是对的
