### ISSUE TITLE
Training MPII data 

### ISSUE THREAD

**Issue by asluborski** [MVIG-SJTU/AlphaPose#881]
Hello,

I am trying to just train the MPII data. Once it get pasts the first 2 epochs, I get an error
```
Mpii object does not have attribute: EVAL_JOINTS
```

How to fix this?

**Comment by Vbird-ML** [comment]
how to train model with mpii?  
KeyError: 'mpii is not in the dataset registry'

**Comment by Vbird-ML** [comment]
how you solve it?I met same problem
