### ISSUE TITLE
can't download install_requires: matplotlib

### ISSUE THREAD

**Issue by liuyu6u** [MVIG-SJTU/AlphaPose#883]
![image](https://user-images.githubusercontent.com/18735001/121513495-7b835900-ca1d-11eb-9244-5eb9643ed8ee.png)
stuck here... is there another way to install this?

**Comment by liuyu6u** [comment]
tsing source seems not stable, try to comment index_url of setup.cfg.

**Comment by anas-zafar** [comment]
@lewis-gb were you able to solve this?
