### ISSUE TITLE
C++ library implemented for Windows (Open Library)

### ISSUE THREAD

**Issue by samylee** [MVIG-SJTU/AlphaPose#884]
hello guys, go and find c++ library: https://github.com/samylee/SamyleePoseApi-OpenLibrary

**Comment by samymdihi** [comment]
Hello @samylee thanks a lot for your work ! Do you have a detailed readme on how to use your algorithm ?

**Comment by maxmahe1** [comment]
Hey @samylee thanks for the help! Do you have a more detailed explanation on how to implement your code ?
Cheers!

**Comment by samylee** [comment]
@samymdihi hi, yes, of course, please check "SamyleePoseApi.h".

**Comment by Fang-Haoshu** [comment]
Thanks for your contribution. This issue will be closed as it is not an issue.
