### ISSUE TITLE
Restarting training from backup point

### ISSUE THREAD

**Issue by asluborski** [MVIG-SJTU/AlphaPose#885]
Hello my computer disconnected during training, is there some sort of backup that I can use?

**Comment by Fang-Haoshu** [comment]
Hi, yes, you can always find the 'TRY_LOAD' in your cfg like :https://github.com/MVIG-SJTU/AlphaPose/blob/master/configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml#L38
You can specify the model path here and modify the training iteration if you don't want to train too long.
