### ISSUE TITLE
--pose_flow cann't output video，and always rendering，can we use _pose_flow?

### ISSUE THREAD

**Issue by songsonggithub** [MVIG-SJTU/AlphaPose#887]
![image](https://user-images.githubusercontent.com/31984963/122409306-9f164880-cfb5-11eb-9ba6-b6cd1bbc4162.png)

**Comment by Fang-Haoshu** [comment]
There is an error that stop the program. You need to solve it. But --pose_flow is not recommended as it may be a bit slow currently.
