### ISSUE TITLE
how to get "mu" and "std"?

### ISSUE THREAD

**Issue by YoungZiyu** [MVIG-SJTU/AlphaPose#89]
Hi,
I have some questions about PGPG module. In the paper, there is "For different atomic poses, we have different Gaussian mixture parameters.", but in training code I can't find code about generating "mu" and "std", can you tell me how you get "mu" and "std"?
thanks!

**Comment by Fang-Haoshu** [comment]
https://github.com/Fang-Haoshu/multi-human-pose/blob/master/train/src/util/pose.lua#L97
