### ISSUE TITLE
What is the format for the detfile argument ?

### ISSUE THREAD

**Issue by samymdihi** [MVIG-SJTU/AlphaPose#890]
What should the detfile look like ? 
Shoudl it look like this : 
[{"frame15000.png", "category_id": 1, "bbox": [258.15, 41.29, 348.26, 243.78], "score": 0.236}] ?

**Comment by samymdihi** [comment]
This format is working

**Comment by TUT103** [comment]
@samymdihi
Could you place more specific json file format? For example, a sample of your json file.
