### ISSUE TITLE
Slow speed and high CPU usage

### ISSUE THREAD

**Issue by fortminors** [MVIG-SJTU/AlphaPose#895]
Hello

I am currently trying out the alphapose solution on a web camera, and the best I could get is 16 fps with tweaking parameters and 95% cpu usage no matter what parameters I used (~30% gpu usage).

So I went down to analyse the code and it turned out that in `webcam_detector.py`, this line of code:

`dets = self.detector.images_detection(img, im_dim_list)`

literally consumes 30-50 milliseconds. And as far as I understood, it is the YOLO detection algorithm. The question is, how can this be possible if the real YOLO runs in ~ 4 ms? Have you changed the algorithm in any way? What are you doing differently?

I am looking forward to your replies.

**Comment by Fang-Haoshu** [comment]
Hi, we are using yolo v3 and you might set the resolution of the input image.
However, the whole AlphaPose run in a multi-process manner, thus the speed of each module might be affected.

**Comment by GitHubjinliu** [comment]
请问您是怎么计算的FPS？
