### ISSUE TITLE
'duc_se.pth' pose model missing

### ISSUE THREAD

**Issue by shrubb** [MVIG-SJTU/AlphaPose#90]
Hi and thanks a lot for your research. Just wondering if you forgot to include a pose model download link in the README?

```
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
...
FileNotFoundError: [Errno 2] No such file or directory: './models/sppe/duc_se.pth'
```

**Comment by Jeff-sjtu** [comment]
Thanks, we will update the README.

**Comment by my-hello-world** [comment]
Hi and thanks a lot for your research. Just wondering if you forgot to include a pose model download link with baidu pan?  it was uinvalid

**Comment by Jeff-sjtu** [comment]
Sorry, baidupan-link was fixed now.

**Comment by my-hello-world** [comment]
Thanks!

**Comment by godcr** [comment]
Hi and thanks a lot for your research. Now broken download link 'duc_se.pth'. plz fix download link.
