### ISSUE TITLE
what mean of  --filp in demo_inference.py?

### ISSUE THREAD

**Issue by jaffe-fly** [MVIG-SJTU/AlphaPose#901]
`parser.add_argument('--flip', default=False, action='store_true',
                    help='enable flip testing')`

`    if args.flip:
        batchSize = int(batchSize / 2)`

can explain in detail?

**Comment by Fang-Haoshu** [comment]
Hi，if means enabling flip testing which can have higher accuracy.
We smaller batch size to avoid possible out of memory issue.
