### ISSUE TITLE
如何修改输出的json文件

### ISSUE THREAD

**Issue by cyy-1102** [MVIG-SJTU/AlphaPose#902]
您好，我想问一下，我想改变输出的.json文件的内容：把置信度分数去掉，格式变成[x1,y1,...xk,yk]。可以这样做吗？如果可以我要怎么修改呢？谢谢您。

**Comment by Fang-Haoshu** [comment]
可以，修改writer.py里的函数即可

**Comment by cyy-1102** [comment]
> 可以，修改writer.py里的函数即可

谢谢您~
