### ISSUE TITLE
How to get skeleton 17 keypoints from the video?

### ISSUE THREAD

**Issue by ITKirito** [MVIG-SJTU/AlphaPose#905]
Hi guys I want to ask how to get  17 keypoints of skeleton from the video? This is because the result i get is 50 keypoints after i convert it to csv.file.

**Comment by Fang-Haoshu** [comment]
It is not 50 keypoints. Should be (x,y,confidence) for each point

**Comment by ITKirito** [comment]
oh..oh I see  thx
