### ISSUE TITLE
关于生成json文件数据顺序问题

### ISSUE THREAD

**Issue by wssxsfz** [MVIG-SJTU/AlphaPose#915]
在生成的json格式的文件中，每一帧中的keypoints数据都不是以人的位置从左到右的顺序出现的，我想知道在写json数据的时候是以什么样的规则写的数据，还有如何确定哪一条数据对应的是哪一个人。

**Comment by Fang-Haoshu** [comment]
是按每个人的检测分数。你可以自己写规则把json以人的位置从左到右的顺序出现
