### ISSUE TITLE
运行Webcam只能用单GPU吗？

### ISSUE THREAD

**Issue by YX-003** [MVIG-SJTU/AlphaPose#916]
我有两个3080 但使用--gpu 0,1这个参数时候报错
![image](https://user-images.githubusercontent.com/40412282/133729999-1873f6ee-90c4-477c-8b23-9654d07e7ee2.png)
单GPU跑的很慢只有10FPS左右

**Comment by Fang-Haoshu** [comment]
你好，运行webcam目前只支持单GPU
你可以使用--vis_fast的flag或者关闭可视化来加速，可视化耗时较多
