### ISSUE TITLE
Output Score Calculation

### ISSUE THREAD

**Issue by kbvatral** [MVIG-SJTU/AlphaPose#921]
I was wondering where I could find more information about the calculation of the `score` parameter in the JSON output. In the `docs/output.md` document, it says 

> score is the confidence score for the whole person, computed by our parametric pose NMS

 However, I have been unable to find any more information than this, as the papers do not seem to contain any reference to overall score in the sections on parametric pose NMS, only distance calculations. Is there a specific equation that is documented somewhere for this score calculation?

**Comment by kbvatral** [comment]
Digging through the codebase, I found this line in `scripts/demo_api.py`

> 'proposal_score': torch.mean(preds_scores[k]) + scores[k] + 1.25 * max(preds_scores[k]),

Does this mean that the final score parameter is the mean of the individual joint scores + the bounding box score from the object detector + 1.25 * the maximum of the individual joint scores?

**Comment by HaoyiZhu** [comment]
Yes, you can also refer to here: https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/writer.py#L154. And about the score calculation in pPose_nms, you can refer to here: https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/pPose_nms.py#L569
