### ISSUE TITLE
Live Run?! (PyTorch)

### ISSUE THREAD

**Issue by fire17** [MVIG-SJTU/AlphaPose#93]
Hi there,
Since I've had issues installing, I moved to the PyTorch version
**I LOVE IT!**
_it was quick and simple install, and it works great!!_

I'm having difficulty understanding how to loop this code for a continues run, on new live incoming pictures

I have a webcam, I'd like the detection to run on one snap, and when it finishes, I download a new snapshot and rerun the detection.

Now, AlphaPose tells me that it takes it 0.06 seconds to fully process 1 img,
`det time: 0.001 | pose time: 0.06 | post processing: 0.0000:  78%|▊| 7/9 [00:00<00:00, 15.33it/s]`
but...
The issue is that the **Loading times** for YOLO and the Pose Model take around **13 seconds**

and to my surprise, the loading of the detection, has the image list already
```
   # Load input images
    dataset = Image_loader(im_names, format='yolo')

   # Load detection loader
    print('Loading YOLO model..')
    test_loader = DetectionLoader(dataset).start()
```
Does that mean that for everytime that I want to make a run on a new pic I have to reLOAD the models
**and wait another 13 seconds????**

I'm pretty sure thats not right, so...
Please help understand how to do this
Hope you understood what I mean
Thank you very much!
Tami

**Comment by fire17** [comment]
Thank you... but Im not asking for webcam support,
Im downloading the images myself
Im asking how to Load once, and rerun detection for each image separately

**Comment by Fang-Haoshu** [comment]
Hi, check out the webcam_demo.py and I guess it can help you.
