### ISSUE TITLE
How Can I use rtsp server address as webcam source?

### ISSUE THREAD

**Issue by RI-SMJ** [MVIG-SJTU/AlphaPose#933]
Dear AlphaPose team.
Thank you so much for providing good data.
While I was testing AlphaPose, I had some problems.
I want to get real-time AlphaPose results using rtsp server IP camera as an input source.
I tried to modify the check_input() part of demo_inference.py and webcam_detector.py part, but failed repeatedly.
Is there any way to receive and use a string-type rtsp server address, not just an integer value on --webcam?
I should be very grateful to you if you might help me.
Thank you.

**Comment by Fang-Haoshu** [comment]
Hi, I hope to help but we dont know too much about  rtsp. But it is a good start point to modify the  webcam_detector.py  and change your data source.

**Comment by melgabay** [comment]
Is there any update? @RI-SMJ @Fang-Haoshu
