### ISSUE TITLE
references and documentation for fast pose DUC and DCN?

### ISSUE THREAD

**Issue by HansHorak** [MVIG-SJTU/AlphaPose#941]
Hi, thank you for this wonderful repo, very user friendly and useful. I use it in my research, so i want to properly cite particularly the fastpose DUC and DCN. Do you have a paper for these or some official documentation? Or are these (exactly) same models present in the "simple baselines.." paper? if so which ones?

**Comment by Fang-Haoshu** [comment]
Hi, the paper is public at http://arxiv.org/abs/2211.03375
Thanks for your interest!
