### ISSUE TITLE
Use custom yolov3/yolov5 detector?

### ISSUE THREAD

**Issue by Hiltona99** [MVIG-SJTU/AlphaPose#949]
I am trying to estimate pose on hockey players and the detection of them is not as good as it could be ( I am running scripts/demo_inference.py) . I have a custom yolov3 detector to detect these players almost perfectly but I get errors when I try to replace the existing yolo weights at the location `/content/AlphaPose/detector/yolo/data/yolov3-spp.weights`. The error I get is the following, 

`File "/content/AlphaPose/detector/yolo/darknet.py", line 488, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 718025`

Is there a way to either pass the detections from my existing model to alphapose or find a way to insert my custom yolov3 into the network?

**Comment by GitHubjinliu** [comment]
你是yolov3.pt 还是 yolov3.weights

**Comment by Hiltona99** [comment]
yolov3.pt, does it need to be a .weights?

**Comment by GitHubjinliu** [comment]
> @GitHubjinliu I am using yolov3.pt, does it need to be a .weights?

Yes! .pt 和 .weights 的加载方式不同。
