### ISSUE TITLE
Incorrect nms

### ISSUE THREAD

**Issue by github-pengge** [MVIG-SJTU/AlphaPose#95]
Hi, I love this project very much, thanks for your sharing.
Besides, I found a bug in [yolo/utils.py](https://github.com/MVIG-SJTU/AlphaPose/blob/a6319db7e511ebcea87813e8b978eea26a504b41/yolo/util.py#L181), which leads to multiple detections for a single person. Another implementation can be found here: [eriklindernoren/PyTorch-YOLOv3/utils/utils.py](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/959e0ff43f5b82bdacef87f4240bae8415eac45b/utils/utils.py#L128). After checking by experiments, I think it's correct. Would you please have a look?

**Comment by Fang-Haoshu** [comment]
Hi, thanks for the suggestion! Can you please tell us where the bug is and how to reproduce it?

**Comment by Fang-Haoshu** [comment]
fixed
