### ISSUE TITLE
no pull/592/head branch

### ISSUE THREAD

**Issue by arctanx999** [MVIG-SJTU/AlphaPose#950]
git pull origin pull/592/head   failed, its implies that no "fatal: Couldn't find remote ref pull/592/head"
and no such branch can be found in https://github.com/pytorch/pytorch/branches/all?query=pull

**Comment by koalaaaaaaaaa** [comment]
you should run"git clone https://github.com/MVIG-SJTU/AlphaPose.git" first, then
"git pull origin pull/592/head"

**Comment by arctanx999** [comment]
> 

thx, bro!!!!!

**Comment by arctanx999** [comment]
> you should run"git clone https://github.com/MVIG-SJTU/AlphaPose.git" first, then "git pull origin pull/592/head"

it works
