### ISSUE TITLE
Module 'torch.jit' has no attribute '_script_if_tracing'

### ISSUE THREAD

**Issue by dekathomas** [MVIG-SJTU/AlphaPose#951]
Hello guys, can you help me with this problem? When I try to run inference.sh based on [README.md](https://github.com/MVIG-SJTU/AlphaPose#quick-start)
![image](https://user-images.githubusercontent.com/33560350/141483153-9af91e24-886a-47ea-89bb-2a2c83f138d7.png)

Thank you

**Comment by Fang-Haoshu** [comment]
Hi, it is not an issue related to AlphaPose. I google the title and found this answer: https://github.com/pytorch/pytorch/issues/42078
Perhaps it can help.
