### ISSUE TITLE
The halpe26 model cannot output results in openpose format

### ISSUE THREAD

**Issue by sulei1998** [MVIG-SJTU/AlphaPose#952]
Thanks for your great work! When i test your demo, I find that I can not get the 26 keypoints in openpose format when using the halpe26 model. The output 2d keypoints is (18, 3). This is a bug?
Here is my command:
```sh
CUDA_VISIBLE_DEVICES=2 /root/miniconda3/envs/alphapose/bin/python /root/Workspace/AlphaPose/scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --indir /root/Source/SL_projects/dataset3/9_13_gyt1/After_Process/images/r1_ir1  --outdir  /root/Source/SL_projects/dataset3/9_13_gyt1/After_Process/AlphaPose/r1_ir1 --format open
```

**Comment by Fang-Haoshu** [comment]
Hi, it is not a bug, the openpose has only 18 keypoints. If you want to use the halpe26 model, you need to use our original format.

**Comment by sulei1998** [comment]
Thanks for your reply!
