### ISSUE TITLE
When I reduce the detbatch and posebatch, does it affect the performance?

### ISSUE THREAD

**Issue by RI-SMJ** [MVIG-SJTU/AlphaPose#954]
Dear, AlphaPose team.
First of all, I really appreciate to you for providing a good source code.
Due to the cuda out of memory problem, the source code could be executed normally by reducing the posbatch and detbatch. But I was curious about this. If I reduce the batch size, does it affect the performance? There are questions about poor performance or increased runtime.
Once again, thank you for providing a good code, and I would appreciate it if you could answer.

**Comment by Fang-Haoshu** [comment]
Hi, it does not affect the performance. But it slows down the speed.
