### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by dekathomas** [MVIG-SJTU/AlphaPose#956]
Hello I have pytorch 1.1.0 and torchvision 0.3.0 and cudatoolkit 10.0. I install that using `conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch` from the [pytorch webpage](https://pytorch.org/get-started/previous-versions/).
And when I run this command `python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --video videos/testing.mp4 --outdir example/video --save_video` (the video path is correct) I got this error.
```
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 17, in <module>
    from alphapose.models import builder
  File "d:\skripsi-repository\alphapose\alphapose\alphapose\models\__init__.py", line 2, in <module>
    from .fastpose_duc import FastPose_DUC
  File "d:\skripsi-repository\alphapose\alphapose\alphapose\models\fastpose_duc.py", line 11, in <module>
    from .layers.ShuffleResnet import ShuffleResnet
  File "d:\skripsi-repository\alphapose\alphapose\alphapose\models\layers\ShuffleResnet.py", line 9, in <module>
    from .dcn import DCN
  File "d:\skripsi-repository\alphapose\alphapose\alphapose\models\layers\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "d:\skripsi-repository\alphapose\alphapose\alphapose\models\layers\dcn\deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: DLL load failed: The specified module could not be found.
```

Could anyone help me please? My cuda verson in my pc is 11.5 and Nvidia GeForce 940MX btw. I try to downgrade and install cuda 10.0 by the software from Nvidia and it can't be installed.

**Comment by Fang-Haoshu** [comment]
Hi, did you install the dcn module? If you run `python setup.py install` it should be installed. If you are using windows PC, you cannot run models with '_dcn'.

**Comment by Fang-Haoshu** [comment]
Seems you are running dcn model. I just fix a bug that may cause this error. Can you update the code to see if it works now?

**Comment by dekathomas** [comment]
Hello @Fang-Haoshu, I use windows and I run `python setup.py build develop` based on this [INSTALL.md](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md#recommended-install-with-conda).

Okay I will try the updated code.

**Comment by dekathomas** [comment]
Hello @Fang-Haoshu your solution is works for me. Thank you for you help.
Can we visual the keypoints to the video demo?

**Comment by Fang-Haoshu** [comment]
Cool. You can visualize by use the flag --vis.
Check more flags here: https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/run.md#flags

**Comment by dekathomas** [comment]
The visualization I mean is print the keypoints number to each keypoint in the video each frames.
