### ISSUE TITLE
GPU with 2GB

### ISSUE THREAD

**Issue by fire17** [MVIG-SJTU/AlphaPose#96]
Hi there!
I'm interested in running this (pytorch version) on a 2 GB GPU, has anyone managed to do this?

or at least, will you please release a version where this is possible?

Thank you! :)
Tami

**Comment by fire17** [comment]
Confirmed!
I'm running on GTX 1050 OC 2GB

note: I'm running on one picture at a time, since I'm downloading images live from ip camera.
One thread of Alphapose Detection gets me to about 1600mb usage of GPU memory, 2 threads of Detection gets me to about 1950mb of GPU memory usage...
Have fun :)

**Comment by Fang-Haoshu** [comment]
Cool! Can you tell us how to do that?

**Comment by fire17** [comment]
I'll do some code cleanup and upload it for you :)

**Comment by Fang-Haoshu** [comment]
Thanks!
