### ISSUE TITLE
dcn

### ISSUE THREAD

**Issue by shelly-xue** [MVIG-SJTU/AlphaPose#960]
Hi, thank you for this wonderful repo, very user friendly and useful. I use it in my research, so i want to properly cite particularly the fastpose DUC and DCN. Do you have a paper for these or some official documentation? Or are these (exactly) same models present in the "simple baselines.." paper? if so which ones?

**Comment by Fang-Haoshu** [comment]
Hi, they are in fact only implemented in AlphaPose. But our paper for AlphaPose is not ready yet😂 You can cite it like "we used the FastPose-DUC and FastPose-DCN proposed in AlphaPose[1,2]"
[1] {RMPE}: Regional Multi-person Pose Estimation
[2] CrowdPose: Efficient Crowded Scenes Pose Estimation and A New Benchmark
