### ISSUE TITLE
Does anyone know where the generated code for the atomic pose is?有哥们知道原子姿态是在代码中的哪部分进行聚类得到的吗？

### ISSUE THREAD

**Issue by lingfengqiu** [MVIG-SJTU/AlphaPose#962]
Hello author, the PGPG module in the paper mentioned that different BBOX parameter offsets are obtained according to different atomic poses. You use K-means to cluster the poses of the data set to obtain the atomic pose, but I am not sure about atomic The specific implementation code of pose, so I want to ask you for help, thank you very much!

作者您好，论文中的PGPG模块提到的是根据不同的atomic pose得到不同的BBOX参数偏移的，您使用的-means对数据集姿态进行聚类得到的atomic pose，但是我不太清楚atomic pose的具体实现代码，所以想向您请求帮助，非常感谢！

**Comment by Fang-Haoshu** [comment]
您好，这部分代码不在这个代码库里哈。我印象里这部分没有开源
