### ISSUE TITLE
What does "gt mAP", "rcnn mAP", " gt box" and "det box" means?

### ISSUE THREAD

**Issue by thisimyusername** [MVIG-SJTU/AlphaPose#967]
I have tried train some models(hrnet,fastpose and simeplepose) using custom datasets, and obtain many models.When training it print:  Epoch 153 | gt mAP: 0.6215162432424949 | rcnn mAP: 0.6274187838001606
and when run validate.py with "model_153.pth",  It print: gt box: 0.6333331405098032 mAP | det box: 0.595698565478996 mAP.
I have much confusion with "gt mAP", "rcnn mAP", " gt box" and "det box".

**Comment by dekathomas** [comment]
Hello, sorry maybe I can't answer your question, but I have the problem when I try train using FastPose model and I use Google Colab when doing training [I have you have time, please check my issue](https://github.com/MVIG-SJTU/AlphaPose/issues/974). I need your help I you want to help me.

Thanks in advance!

**Comment by HaoyiZhu** [comment]
Alphapose uses top-down methods which will first detect human bboxes and then detect human keypoints. So the gt mAP and the gt box means using groundtruth bboxes, while rcnn mAP and det box means using bboxes generated by detectors (default is yolo v3).

**Comment by dekathomas** [comment]
Hello @thisimyusername, where is the place you can change the model used by training algorithm?

**Comment by HaoyiZhu** [comment]
@dekathomas Hi, if you want to use a custom model, you can check alphapose/models/. We use FastPose by default.

**Comment by dekathomas** [comment]
owh sorry @HaoyiZhu I mean the base network (hrnet,fastpose and simeplepose), because by default alphapose use resnet right? i want to try mobilenet for speed

**Comment by HaoyiZhu** [comment]
@dekathomas Ah, I think you can find it under alphapose/models/layers/

**Comment by dekathomas** [comment]
sorry for late reply @HaoyiZhu, I wanna try mobilenet, but I don't find mobilenet in `layers` folder. And if I look at the pytorch documentation, torchvision 0.3.0 doesn't support mobilenet. Do you have any suggestions for me to be able to use mobilenet?

**Comment by HaoyiZhu** [comment]
I see. Actually we do not support mobilenet yet. Maybe you can implement it by yourself, or you can update yout pytorch version. I think higher version of pytorch can support higher version of torchvision？ @dekathomas

**Comment by dekathomas** [comment]
Hmm oke I will try it later. Thanks for your information.

**Comment by dekathomas** [comment]
by the way @HaoyiZhu why you give the name rcnn mAP if the validation is by yolo bounding box?

**Comment by HaoyiZhu** [comment]
I think it is a history remain? @Fang-Haoshu
