### ISSUE TITLE
yolov3-spp.weights这权重在哪下载

### ISSUE THREAD

**Issue by dugudongfangshuo** [MVIG-SJTU/AlphaPose#976]
你好 
yolov3-spp.weights这权重在哪下载

**Comment by HaoyiZhu** [comment]
这里的Models部分有写：https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md

**Comment by yzbx** [comment]
> 你好 yolov3-spp.weights这权重在哪下载

直接从darknet/yolo 官网上下载也是一样的，https://pjreddie.com/media/files/yolov3-spp.weights
