### ISSUE TITLE
Make Human Re-ID tracking model available on Drive 

### ISSUE THREAD

**Issue by jayantsharma** [MVIG-SJTU/AlphaPose#979]
Can the authors make the pretrained human re-id model available on Google Drive? It's nearly impossible to download it from Baidu for me.

Much appreciated.

**Comment by Fang-Haoshu** [comment]
Hi, in fact the original link includes the Mega drive. Here is the link: https://mega.nz/#!YTZFnSJY!wlbo_5oa2TpDAGyWCTKTX1hh4d6DvJhh_RUA2z6i_so

I make the readme a bit clearer.
