### ISSUE TITLE
您好，运行阶段出现渲染图片一直不成功的问题

### ISSUE THREAD

**Issue by seven1995** [MVIG-SJTU/AlphaPose#984]
运行命令如下
python scripts/demo_inference.py --cfg F:\AlphaPose-master\configs\coco\resnet\256x192_res50_lr1e-3_1x.yaml  --checkpoint pretrained_models/fast_res50
_256x192.pth --video F:\test\1.mp4 --outdir F:\test --save_video 

出现如下问题
![image](https://user-images.githubusercontent.com/61695631/154220187-af325005-cff8-44f4-a634-056b9d0dcdd3.png)

===========================> Rendering remaining 695 images in the queue...一直保持不动

请问一下有可能的原因是什么？

**Comment by Fang-Haoshu** [comment]
您好，请问您有对代码做过什么改动吗

**Comment by Fang-Haoshu** [comment]
您好，我们刚刚发现一个bug，fix了一下，您拉一下最新的commit看看还会不会

**Comment by seven1995** [comment]
> 您好，请问您有对代码做过什么改动吗



> 您好，我们刚刚发现一个bug，fix了一下，您拉一下最新的commit看看还会不会

好的 我试试

**Comment by seven1995** [comment]
> 您好，请问您有对代码做过什么改动吗

改动就是在detector文件夹下面加了一个__init__.py；不然import找不到这个模块
然后在demo_inference.py中的from detector.apis import get_detector语句前面加了一句sys.path.append('F:\\alphapose-master')
把项目的绝对路径加进去了
别的代码逻辑改动没有

**Comment by seven1995** [comment]
> > 您好，请问您有对代码做过什么改动吗
> 
> 改动就是在detector文件夹下面加了一个__init__.py；不然import找不到这个模块 然后在demo_inference.py中的from detector.apis import get_detector语句前面加了一句sys.path.append('F:\alphapose-master') 把项目的绝对路径加进去了 别的代码逻辑改动没有

最新的commit我也试了一下 还是不行 这次没有任何改动

**Comment by seven1995** [comment]
![9c82a8284f71bbb84d698f0bada4b16](https://user-images.githubusercontent.com/61695631/154448074-3237ef2d-c125-4476-b654-4164425f5d35.png)
![3387336ea45c5cf6a0b42828262e05c](https://user-images.githubusercontent.com/61695631/154448102-41998031-7d05-43c2-8563-29eb758c660a.png)
![d92d8eb3f9d1d953026d0aba5e8aa0a](https://user-images.githubusercontent.com/61695631/154448151-2f6bba09-c6e1-4dbd-acf5-310e35666743.png)
![e5a7b5b5b5ce72fe0e029dac6e23d4e](https://user-images.githubusercontent.com/61695631/154448187-8e806fe5-68d0-4b9b-98fb-5369f44a4619.png)
这是我安装的包

**Comment by seven1995** [comment]
> 环境没有问题，应该是能fix的呀，您的alphapose/utils/vis.py的418行和目前网上的一样吗： https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/vis.py#L418

您好，是一样的，有可能是那个openh264-1.8.0-win64.dll动态库没有加载成功，我找找应该放在哪

**Comment by seven1995** [comment]
![image](https://user-images.githubusercontent.com/61695631/154879819-ad7cf179-a2c9-4486-9eba-1fc44fa0145e.png)
您好，请问一下内存不够了，可以改哪些地方？

**Comment by seven1995** [comment]
您好，请问一下在gpu显存不够的情况下 如何用cpu运行，我把setup.py的211行注释了 依然显示如上的内容

**Comment by Fang-Haoshu** [comment]
不要用cpu运行，很慢
你可以看我们文档https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/GETTING_STARTED.md
里面有写OOM问题怎么处理
