### ISSUE TITLE
Clean COCO Dataset

### ISSUE THREAD

**Issue by dekathomas** [MVIG-SJTU/AlphaPose#986]
Hello @Fang-Haoshu, I look at your [MODEL_ZOO.md](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md) to train your model, you said `All models are trained on keypoint train 2017 images which contains at least one human with keypoint annotations (64115 images).`

Do you mean you choose the images one by one and alter file `person_keypoints_train2017.json` provided by COCO dataset?

**Comment by dekathomas** [comment]
btw @Fang-Haoshu how long you train AlphaPose using COCO train 2017 dataset?

**Comment by Fang-Haoshu** [comment]
You can simply load the COCO dataset and filter those images with human by code.

**Comment by Fang-Haoshu** [comment]
About one or two days?

**Comment by dekathomas** [comment]
How about the annotations file? Did you direct use the file or you edit it?
