### ISSUE TITLE
demo_api  TypeError: vis_frame() missing 1 required positional argument: 'vis_thres'

### ISSUE THREAD

**Issue by zhengqun** [MVIG-SJTU/AlphaPose#992]
TypeError: vis_frame() missing 1 required positional argument: 'vis_thres'

**Comment by HaoyiZhu** [comment]
Hi, we have fixed it. Could you please pull the latest code and try again?

**Comment by zhengqun** [comment]
Yes, I do.


| |
郑群
|
|
***@***.***
|
签名由网易邮箱大师定制


On 03/4/2022 17:35，Haoyi ***@***.***> wrote：

Hi, we have fixed it. Could you please pull the latest code and try again?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
